### ISSUE TITLE
Event Listing - Filter option- Throbber is availabel more time on the screen

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1001]
When I move the next page using pagination option then throbber is availabel more time on the screen.

Recored is taking more time to load. 

![image](https://user-images.githubusercontent.com/75515088/160380961-cfe9313c-c020-4a89-a945-a5296d12b05a.png)

**Comment by tamanna-ahuja** [comment]
Checked on Staging , It isn't much time in case needed will improve in future .

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja - This is not taking much time to load . It is properly working.

If It will needed then improve in the future.

So I closed the issue.
