### ISSUE TITLE
Event is not search

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1002]
Event is not search .

When I have created few events and location name as assigned -"Ahmedabad".

Now go to Event listing page.

In the location text box type name as - "Ahmedabad" then events are search .

But when I type location nanme as - ""Ahmedabad,Gujarat,India" then events is not search.

https://user-images.githubusercontent.com/75515088/160550110-bc996426-f35c-4f56-a55d-d1b02aaa8d8f.mp4

**Comment by tamanna-ahuja** [comment]
Check if online event field is set to no and if not set , set it to know and search again.

**Comment by mistry-jignesh** [comment]
Now I have verified the issue. Event search is working properly.

 Ahmedabad .
 Ahmedabad, Gujarat,India.

Here events are search . So I closed the issue.
