### ISSUE TITLE
Single Event -  In the preview page few details are missing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1004]
**Elementor**

Using single event option - Try to view the event details page. Here few details are missing on the page.

Without  Elementor - The event details page is as below .

![image](https://user-images.githubusercontent.com/75515088/160989436-c95761cb-16be-4bec-b45a-744d5f8dec05.png)

With Elementor - The event details page is as below .

![image](https://user-images.githubusercontent.com/75515088/160989670-fae86762-bc62-4247-a997-8f926f290d34.png)

Also event location map is not display.

![image](https://user-images.githubusercontent.com/75515088/163531681-150b7a47-2fd9-4bca-89dd-30e77c76f33a.png)

**Comment by yukta05** [comment]
**Without elementor**, when i try to duplicate an event and preview.
here some details are missed :- 
organizer, venue, location, registration end date.

**Comment by vijayrathod245** [comment]
Now, It working fine.

**Comment by mistry-jignesh** [comment]
Verified issue . Now with elementor & without elementor details are display on the single event page.

So I closed the issue.
