### ISSUE TITLE
Google structured data issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1007]
Google  Structured Data issue.

URL - https://search.google.com/test/rich-results

https://staging-myeventplatform.kinsta.cloud/event/test-ticket/

![Rich Results Test – Google Search Console](https://user-images.githubusercontent.com/75515088/161202236-8cc427de-f7ba-4926-8388-e1db98052e3b.png)

**Comment by ritakikani** [comment]
Now, looks like

https://search.google.com/test/rich-results/result?id=gnuU22r-RLbUFhDFJCZHVQ

**Comment by mistry-jignesh** [comment]
Verified this issue.Now data are properly and working fine .
So I closed the issue.
