### ISSUE TITLE
 Past Event listing with pagination option is visible on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1008]
Past Event listing -

 I have not use the show_pagination="true" option . After that event listing  pagination option is display on the page.

 [past_events per_page="10" orderby="title" order="DESC"]

![image](https://user-images.githubusercontent.com/75515088/161234267-2b825782-bcf4-4ef4-b0b5-1d1731755fed.png)

**Comment by tamanna-ahuja** [comment]
Past event by default show pagination for hiding pagination you can use show_pagination="false"

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja - Past event by default show pagination. If hinding pagination then need to add show_pagination="false".

So I closed the issue.
