### ISSUE TITLE
Elementor - Do not display single event field Component until Event  Componenet draged

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1009]
Do not display single event field Component until Event  Componenet draged.

**Comment by ritakikani** [comment]
This is elementor default behavior that if you want to use any widget either it is of event manager or elementor itself, must need to drag-drop.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  : This is elementor default behavior that if you want to use any widget either it is of event manager or elementor itself, must need to drag-drop.

So I closed the issue.
