### ISSUE TITLE
Event Dashboard - Location - ASC/DESC filter is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1019]
Event end date- ASC/DESC filter is not working.

![image](https://user-images.githubusercontent.com/75515088/163529608-5b901a19-86af-46e4-834a-2c6a1f4a7d6a.png)

Same issue is face in the  Event location -ASC/DESC filter is not working.

![image](https://user-images.githubusercontent.com/75515088/163530261-c3980515-8cd5-4aab-a722-de5314ff1b7f.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is facing in the **Event location -ASC/DESC** filter is not working.

![image](https://user-images.githubusercontent.com/75515088/180154312-b90dcf32-22c2-46b0-b5db-5174c7109050.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Location with DESC option is not working.
First online  events are display on the page.


![image](https://user-images.githubusercontent.com/75515088/189278643-690fda52-309a-47c2-90fb-d1cb19f45649.png)

**Comment by ritakikani** [comment]
working fine on staging and local so please test again.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine. DESC options working properly.
So I closed the issue.
