### ISSUE TITLE
Venues only appear on the front end for the author that created them.

### ISSUE THREAD

**Issue by RayHollister** [wpeventmanager/wp-event-manager#1021]
We are having trouble using the venues. We have added 20 venues to WP event manager, but they are only appearing on the front end for the user that created them. Any other user cannot see them. We have multiple users adding events to the calendar for multiple venues. 

Here's a screen capture video showing the issue we are experiencing...
https://youtu.be/viF8lLx_soE

**Comment by krinaydhanani** [comment]
@yukta05 Please check this issue and reproduce it.

**Comment by RayHollister** [comment]
Priya provided this feedback in the Wordpress Plugin support pages. I added the snippet to our child theme. It's not a perfect solution, but it works.

https://wordpress.org/support/topic/venues-only-appear-on-the-front-end-for-the-user-that-created-them/#post-15570294

**Comment by Priya-Goenka** [comment]
Hi @RayHollister 

Can you please help me tell what would be ideal perfect solution, We will develop the code for the same.

**Comment by Priya-Goenka** [comment]
Hi @RayHollister 

This is the following code for organizers, You can add for Venues by customizing it. 
Add this in the functions.php at theme side. 

add_filter( 'get_all_event_organizer_args', 'wpem_all_event_organizer_args', 10 );
function wpem_all_event_organizer_args($args)
{
	if(isset($args['author']))
		unset($args['author']);

    return $args;
}

**Comment by mistry-jignesh** [comment]
Need to add this code to the knowledge base. @Prachetshi1991

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1r4pDM4iIwtqaoAfjoowJ6rZIjDRG2MLBcSH4seq09is/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Code is available on the KB page in the venue shortcode page.
So I closed the issue.
