### ISSUE TITLE
Event was not sorting by date and time

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1025]
We added a patch to the plugin to "hardcode the sort" we want because it doesn't offer a filter between loading the data and displaying it.  

Event was not sorting by date and time.

usort($events->posts, function($a, $b) {
                return(get_post_meta($a->ID, "_event_start_date", false)[0]>get_post_meta($b->ID, "_event_start_date", false)[0]);
                });

**Comment by yukta05** [comment]
According to @tamanna-ahuja this issue is already covered. so i close this issue.
