### ISSUE TITLE
Warning message with Ocean wp theme

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1030]
![image](https://user-images.githubusercontent.com/86232676/164441156-b45174f4-5e72-48b5-9b98-4d5b92d80330.png)

This issue facing with Ocean wp theme. With Event listing theme it's perfectly working. 
Here i duplicated the event from the event dashboard and added an organizer and venue-related details.
during preview time I faced this issue.

**Comment by ritakikani** [comment]
In version 3.1.32, this issue is not occure, so please take latest version and check.

**Comment by mistry-jignesh** [comment]
I have verfied issue with Ocean wp theme. This error message issue is not reproduced.

So I closed the issue.
