### ISSUE TITLE
Show_filters="false" code not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1033]
1.    [events per_page="10" show_filters="false"] 

    When use above code and  I click on the Load more event button then loading message is present on the screen.
   
2 .[events per_page="10" show_filters="true" orderby="title" show_tags="false/true"]

 When use **show_tags="false/true** .This shortcode not working.

**Comment by AHDOnline** [comment]
can confirm on 6 sites, removing the show_filters it will display.  With show filters on it shows 
There are currently no events.

**Comment by mistry-jignesh** [comment]
I have verified issue .

 I have checked below two shortcode and both are working fine.

[events show_filters="true"]
[events show_filters="false"]

Video file.

https://user-images.githubusercontent.com/75515088/165221571-b36715b1-4bb0-4696-8d77-a2d89d73821c.mp4

**Comment by mistry-jignesh** [comment]
Need to fixed issue no 2 

[events per_page="10" show_filters="true" orderby="title" show_tags="false/true"]

**Comment by mistry-jignesh** [comment]
Verified this issue no2 

[events per_page="10" show_filters="true" orderby="title" show_tags="false/true"]

Now this is working fine.
