### ISSUE TITLE
Added extra fields, not showing at venue details page. 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1042]
![image](https://user-images.githubusercontent.com/86232676/165732507-ba3921f4-f86e-4048-811f-50f41f0c08c1.png)

Added extra fields from the Form field, but not showing those details on the venue details page.

**Comment by ritakikani** [comment]
We does not need to provide or any extra code for custom fields added for venue field editor because we already given hooks so using that user can show their custom fields or he has other way to show is template override. By overriding the template files of venue, they can show there extra fields.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.

An extra field is displayed on the venue details page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/71ea5fa4-54c2-46fb-bd9f-a6e1cd499a41)

So I closed the issue.
