### ISSUE TITLE
Both layout type are display on the page with [upcoming_events] shortcode

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1046]
Both layout type are display on the page with [[upcoming_events] shortcode.

[upcoming_events layout_type="list"]

It should be display on the list view becuase in the shortcode  layout_type="list".

![image](https://user-images.githubusercontent.com/75515088/165899357-f5b1975b-6246-44f9-b19f-2e476dc42fac.png)

**Same issue face in the elemetor & elementor shortcode.**

**Comment by ritakikani** [comment]
@mistry-jignesh  , we do not have this type of any attribute for upcoming event shortcode.

**Comment by ritakikani** [comment]
I will add this feature for layout type.

**Comment by mistry-jignesh** [comment]
I have verified this issue using below shortcode.

1. [past_events layout_type="list"]

2. [ upcoming_events layout_type="list"]

Here layout attribute use "list" type but both view are available on the page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/11dff16f-cd3c-48c3-86b9-c755ab954b8e)

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is working fine.

[past_events layout_type="list"]

[ upcoming_events layout_type="list"]

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/5bf3b65f-bb11-49bd-b97c-ce248fdc7c40)


So I closed the issue.
