### ISSUE TITLE
Elementor -Using elementor created one template and use single event field

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1049]
Verified issue with latest core plugin. Created custom field in the event form fields.
Now using elementor created one template and use single event field.
Here in the preview displaying the custom field values.
This issue is reproduced . HTML  code is display  

![image](https://user-images.githubusercontent.com/75515088/166897959-7cabf516-7abc-47dc-b982-4e85bf5a6a92.png)

**Comment by yukta05** [comment]
I verified this issue. issue is resolved, so i going to close this issue.
