### ISSUE TITLE
Separator "|A|B|C" is change into " ： | A : A | B : B | C : C" in field

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1054]
hen users are making new event, they cannot select blank on drop-down field.
So I have overridden the template in my child-theme like below, always show having hidden attribute as "not selected",
addnew-view
but in admin panel, no template but core file that in ./admin/wp-event-manager-writepanels.php includes this part.
I have changed this file as below, and can choose blank in submit view and admin view.
./admin/wp-event-manager-writepanels.php
But when you update this plugin, I have to change everytime.
I think this feature is need to many users using drop-down field.
I hope it is included officially.
In addition, when I set "|" separator at first character in field-list, it work well only the first time but when I save next time it do not work.
"|A|B|C" is change into " ： | A : A | B : B | C : C".
2-bites colon
At next time it changed into " ： : ： | A : A | B : B | C : C".
2-1-2 colons
It seems a blank is changed into 2-bite colon, and next time the 2-bite colon is translated to 2-1-2-bites colons separated with 1-bite space.
In this case, users can select the 2-bites colon as value at any drop-down fields.

**Comment by mistry-jignesh** [comment]
I verified this issue. I have created a new field like multiselect.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/4fae4f1d-cb64-4fd9-9ee2-b94d22e3b486)

Added values like as mention issue. It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ff6b5471-47f6-46cc-ab07-cd545a637936)

So I closed the issue.
