### ISSUE TITLE
Show pagination attribute not working in Past event listing module.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1059]
Show pagination attributes not working in Past event listing module 

![image](https://user-images.githubusercontent.com/35419531/128156100-eadfc05e-881e-4e37-a698-7164fe9579cf.png)

![image](https://user-images.githubusercontent.com/35419531/128156234-38e0aae9-370b-4907-91d1-6acedaf8fdfe.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Pagination is not working with past event listing module.

![image](https://user-images.githubusercontent.com/75515088/173530685-c8cb8c65-2e70-4634-941c-6cbe6c8bc2e9.png)

So I have reopend the issue.

**Comment by ritakikani** [comment]
@mistry-jignesh , pagination is working fine past event page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/b116e235-b822-43fd-81fb-010b269e866f)

**Comment by mistry-jignesh** [comment]
Verified this issue. Pagination option is working fine with the past event listings.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7086e308-0c25-445f-9c27-35fd4c72abb6)

This issue is fixed .So I closed the issue.
