### ISSUE TITLE
Term multiselect is disbling the event category and type in block editor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1062]
Term multiselect is diabling the event category and type in block editor

**Comment by live-aamir** [comment]
@mistry-jignesh Reopen it as its not fixed and creating error.

**Comment by tamanna-ahuja** [comment]
We already had documented about this issue 

https://wp-eventmanager.com/knowledge-base/duplicate-event-type-meta-box/

**Comment by mistry-jignesh** [comment]
Verified this issue using above document steps.

Now this issue is fixed and working fine. 

Term multiselect is working properly with event category and type in block editor.

So I closed the issue.
