### ISSUE TITLE
Event Dashboard setting - Event per page 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1063]
When I have set event per page option as "3" then more than 3 events are display on the page.

![image](https://user-images.githubusercontent.com/75515088/146713905-dd7289c3-9743-41a8-9c9e-8935f7d098e9.png)

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is not working.

When I have set event per page option as "3" then more than 3 events are display on the page.

So I reopen the issue.

**Comment by kinjal6810** [comment]
Now properly work.

**Comment by mistry-jignesh** [comment]
Now this issue is working fine. 

When I have set event per page option as "3" then  3 events are display on the page.

So I closed the issue.
