### ISSUE TITLE
Field editor - The checkbox is displaying 1 or 0

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1064]
Go to backend 

Event Manager > Field editor

Create new field like - Check box and type is select - Checkbox.

![image](https://user-images.githubusercontent.com/75515088/172097906-8fbe6ff6-63bb-42e1-92b4-2f24923d5368.png)

Edit event and checkmark on the checkbox field.

Now save the data.

Now view form at the front end .

![image](https://user-images.githubusercontent.com/75515088/172098967-78ed16ea-41c4-4683-8306-143e4e4f96ea.png)

Here Additional details section

When I checkmarked then values 1 display. So insted of the 1 It should be display like Yes

And if not checkmarked then No label should be availabe.

**Comment by kinjal6810** [comment]
Solved this support Ticket by Roshani

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

When I checkmarked then values is display - Yes . So insted of the 1 It  is display like Yes.

So I closed the issue.
