### ISSUE TITLE
Elementor Compatibility with wp event manager plugin. 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1066]
https://user-images.githubusercontent.com/86232676/168973276-96e93c8b-d480-440e-80bd-73f2b186f593.png

facing issue in goggle map while using elementor.
this issue is also available in core plugin.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed and working.

Error message is fixed.

So I closed the issue.
