### ISSUE TITLE
Banner not showing

### ISSUE THREAD

**Issue by EIASBrussels** [wpeventmanager/wp-event-manager#1067]
When I go to the future events widget I am unable to add a display banner and the site is displaying the below image.
<img width="475" alt="Screenshot 2022-06-09 120136" src="https://user-images.githubusercontent.com/107183870/172821510-fbda28b1-77ec-4538-bd00-85456987b9a0.png">

**Comment by EIASBrussels** [comment]
Option to add event banner is not availabl
<img width="692" alt="Screenshot 2022-06-09 132149" src="https://user-images.githubusercontent.com/107183870/172835564-3dae89d9-2de1-49f3-a9b4-e92457189843.png">
e

**Comment by jrsarath** [comment]
Hello there,
seems like somehow the Event banner field been removed/erased from the field editor which can be found under Event Manager/Field Editor.
I would suggest that if you haven't made any to the field editor then you can just reset it from the same page, or if you have made changes to the default field editor let us know we will guide you though how to add Event Banner field back to your website.

**Comment by EIASBrussels** [comment]
Thank you so much!
