### ISSUE TITLE
Unable to see the event banner image in linkedin post

### ISSUE THREAD

**Issue by subramanyamsri** [wpeventmanager/wp-event-manager#1068]
Hi Team,

I have been trying to post my event page in my linkedin. Event page banner image is not shown on the post. Instead of my event page banner image it shows as the attached..

![image](https://user-images.githubusercontent.com/10936336/173067420-cb0f4d81-e11d-4503-b53d-2df49c77bd9a.png)

Best Regards.

**Comment by subramanyamsri** [comment]
Hi Team,

I found its a cache issue. so clearing cache worked for me like a charm.

Best Regards.

**Comment by jrsarath** [comment]
Hi @subramanyamsri 
Glad to hear that you found a solution.
Closing the issue as its been reported as fixed
