### ISSUE TITLE
shortcode expire event

### ISSUE THREAD

**Issue by onopko81** [wpeventmanager/wp-event-manager#1069]
how display a loop of expire events? there is a shortcode? thanks

**Comment by ritakikani** [comment]
Hello @onopko81 ,

Sorry for the late reply. Yes, there is a shortcode to show expire events list, that is [past_events].

You can get brief explanation in this documentation : https://wp-eventmanager.com/knowledge-base/past-events/

Thank you.

**Comment by mistry-jignesh** [comment]
I have verified past shortcode with different attributes.
It is working fine. So I closed .
