### ISSUE TITLE
Save/Update event will goes in infinite

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#107]
This problem is occurs in two situation :

1) If Event type is enable and user will add or update the event at admin side, then it will goes in infinite loop.

2) If the status of event is change at the time of update then also will goes in infinite loop.

In short whenever "post" is update, then it will create infinite loop.(it's "post" not "post_meta")

**Comment by hiteshmakvana** [comment]
No need to update slug while saving. If user wants they can apply via filter.
