### ISSUE TITLE
Backend - Draft event is create when edit event at front end side

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1072]
First click on edit event button at frontend.

Now click on the Save Changes button.

Here at backend  draft event is create when edit event at front end side.

![image](https://user-images.githubusercontent.com/75515088/173329216-d97809ec-05e3-4469-b96b-1edc8939da33.png)

**Comment by tamanna-ahuja** [comment]
@mistry-jignesh  - Confirm funcationality with @krinaydhanani after event edit at frontend side it should moved to draft only to get the event approved by admin

**Comment by tamanna-ahuja** [comment]
Sorry , Got it wrong , Its done Solved by @aamir-ayub

**Comment by mistry-jignesh** [comment]
This issue is verified . Now this issue is fixed.

So I closed the issue.
