### ISSUE TITLE
Space required in between the google map and box view events

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1073]
Space required in between the google map and box view events.

![image](https://user-images.githubusercontent.com/75515088/173338055-7196dbe1-9c11-4b5a-85d3-3001da17f56c.png)

Like as below images

![image](https://user-images.githubusercontent.com/75515088/173338261-35aa8383-03fe-48b0-88b2-fd6b4670f37e.png)

**Comment by kaushikpokal** [comment]
issue already fixed on new version in google map

**Comment by mistry-jignesh** [comment]
Verified issue with new version. Now this issue is fixed  .

So I closed the issue.
