### ISSUE TITLE
Making Organizer Field compoulsary

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1074]
Please add the following code in the functions.php file at theme side:

// Add your own function to filter the fields
add_filter( 'submit_event_form_fields', 'custom_submit_event_form_fields' );
 
function custom_submit_event_form_fields( $fields ) {
 
   
    $fields['organizer']['event_organizer_ids']['required'] = true;
$fields['venue']['event_venue_ids']['required'] = true;
 
    // And return the modified fields
    return $fields;
}

**Comment by tamanna-ahuja** [comment]
@Priya-Goenka  - What needs to be done here.

**Comment by ashokdudhat** [comment]
@krinaydhanani this is solution for how to customise organize filed mandatory... so please put in document and assign to writer.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1w4z7PmBY4CLU8VzNQOHh3Xc5PeWctaDmT99wahqM9rU/edit
already there on the page 
https://wp-eventmanager.com/knowledge-base/event-submission-form-field/

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
It is available on the KB page in the " Editing Event Submission Form Fields" section.
So I closed the issue.
