### ISSUE TITLE
Function to change email address for sender.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1076]
// Function to change email address
function wpb_sender_email( $original_email_address ) {
return '[miracle@yoursite.com](mailto:miracle@yoursite.com)';
}

// Function to change sender name
function wpb_sender_name( $original_email_from ) {
return 'A miracle worker';
}

// Hooking up our functions to WordPress filters
add_filter( 'wp_mail_from', 'wpb_sender_email' );
add_filter( 'wp_mail_from_name', 'wpb_sender_name' );

**Comment by ashokdudhat** [comment]
This is tutorial part for the documentation. so please assign to writer.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this code has been added to the tutorial section.
This issue is fixed. So I closed the issue.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1LDrOb-cCOJrCEK4jDeit5t_f_dOlnb8ciLbL30k4KKo/edit
