### ISSUE TITLE
WP Event Manager Backend

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#108]
All the links are showing under "Support the Ongoing Development of this Plugin" should open in new window on clicking mode instead of same window and "Contribute code or report a bug" is redirecting me to 404 error page. Please check it.

![Unbenannt](https://user-images.githubusercontent.com/49863477/60384417-a452f380-9a7d-11e9-9201-415146410da6.PNG)

**Comment by hiteshmakvana** [comment]
It will be improved with new design.

**Comment by hiteshmakvana** [comment]
All the links are updated with target attributes.
