### ISSUE TITLE
WordPress org : Security Issues

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1080]
There are still places you're missing proper escaping:

wp-event-manager/templates/form-fields/term-checklist-field.php:68:<?php if (!empty($field['description'])) : <small class="description"><?php echo $field['description']; </small><?php endif; 

wp-event-manager/templates/form-fields/number-field.php:4:<?php if (!empty($field['description'])) : <small class="description"><?php echo $field['description']; </small><?php endif; 

wp-event-manager/templates/form-fields/radio-field.php:50:<?php if ( ! empty( $field['description'] ) ) : <small class="description"><?php echo $field['description']; </small><?php endif; 

wp-event-manager/templates/form-fields/textarea-field.php:4:<?php if (!empty($field['description'])) : <small class="description"><?php echo $field['description']; </small><?php endif; 

wp-event-manager/templates/venue/event-venues.php:40:                echo '<div class="venue-letters-list"><a id="' . $letter . '" href="#' . $letter . '">' . $letter . '</a></div>';

wp-event-manager/templates/venue/event-venues.php:44:                echo '<div class="venue-letters-list"><a id="' . $letter . '" href="#' . $letter . '">' . $letter . '</a></div>';

**Comment by mistry-jignesh** [comment]
1. When edit venue at front end section then  error message is display
![image](https://user-images.githubusercontent.com/75515088/174005664-4f02f702-2723-4241-99ad-4ee0da509ff3.png)

2.When edit event at backend then white page is display.

![image](https://user-images.githubusercontent.com/75515088/174005928-63ffef7d-6022-4deb-b863-c509261439d4.png)

3.Backend- Field editor - Error message is display  & Field editor page desing is change.

![image](https://user-images.githubusercontent.com/75515088/174006134-821ef111-03ee-4833-9a57-9e9f306d37f2.png)

**Comment by mistry-jignesh** [comment]
**Above error fixed but other error found at front end side.**

1. Edit organizer at front end.
  
![image](https://user-images.githubusercontent.com/75515088/174013477-3245b74d-2c4c-4651-b816-4ed892edabaa.png)

2.Create new event at front end section .

Warning: exif_read_data(alyce.jpg): Incorrect APP1 Exif Identifier Code in D:\xampp\htdocs\eventlisting\wp-admin\includes\image.php on line 846

3.Edit venue at front end then error message is display.

![image](https://user-images.githubusercontent.com/75515088/174013780-9d9239ab-a963-41ae-80ec-bf3dacd079b3.png)


4.Edit event at front end setiocn the error messsage is dispplay.

![image](https://user-images.githubusercontent.com/75515088/174014093-5fcfbb27-9a53-4ccf-b927-a8c8a67940ab.png)

5. Duplicated venue and organizer then display fatal error .

![image](https://user-images.githubusercontent.com/75515088/174014435-36e5b659-88bf-4d82-8581-a94f2a4fda76.png)

6. Duplicate event then front then error message is display.

![image](https://user-images.githubusercontent.com/75515088/174014640-cffa7421-a0d3-4289-a6d2-9e2fe6ee0e06.png)

**Comment by mistry-jignesh** [comment]
Verified issue . Warning error message issues is fixed.

So I closed the issue.

**Comment by ashokdudhat** [comment]
There are still issues, so we are extending the time for your review by 2 weeks as you have been actively working on it.

As long as keep us in the loop, telling us when you've made updates or asking for an extension, we will keep your plugin open. If you fail to reply to this email, and in 2 weeks we find more issues, your plugin will be closed.

The privilege of having your plugin stay open in these cases is only granted to developers who uphold their side. Failing to properly follow directions will result in revocation of that privilege, and it will extend to all plugins you work on.

## Including Libraries Already In Core

Your plugin has included a copy of a library that WordPress already includes.

WordPress includes a number of useful libraries, such as jQuery, Atom Lib, SimplePie, PHPMailer, PHPass, and more. For security and stability reasons, plugins may not include those libraries in their own code, but instead must use the versions of those libraries packaged with WordPress.

You can see the list of jQuery Libraries here:

https://developer.wordpress.org/reference/functions/wp_enqueue_script/#default-scripts-and-js-libraries-included-and-registered-by-wordpress

While we do not YET have a decent public facing page to list all these libraries, we do have a list here:

https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/core/credits/wp-59.php#L739

It’s fine to locally include add-ons not in core, but please ONLY add those additional files. For example, you do not need the entire jquery UI library for one file. If your code doesn't work with the built-in versions of jQuery, it's most likely a noConflict issue.

Example(s) from your plugin:

wp-event-manager/assets/js/jquery-ui/jquery-ui.js
wp-event-manager/assets/js/jquery-ui/jquery-ui.min.js

## You cannot translate $-variables or defines

It is impossible to use the WordPress translation system on dynamic code. A correct, ready to translate, example would be this:

__( 'This string needs to be translated.', 'my-plugin-permalink' )

By using 'my-plugin-permalink' and having it match the actual permalink of a plugin, you tell the system which plugin is translating and what it's translating.

However if you try to do this, it won't work:

__( $string_to_translate, 'my-plugin-permalink' )

The system doesn't know how to look back for $string_to_translate which means your plugin simply will not be translated properly.

Example(s) from your plugin:

wp-event-manager/templates/form-fields/group-field.php:40: <label for="<?php esc_attr_e($subkey); "><?php echo __($subfield['label'], 'wp-event-manager') . apply_filters('submit_event_form_required_label', $subfield['required'] ? '<span>*</span>' : ' <small>' . __('(optional)', 'wp-event-manager') . '</small>', $subfield); </label>

This will never work:

echo __($subfield['label'], 'wp-event-manager')

And it's not escaped.

wp-event-manager/templates/event-submit.php:26: <label for="<?php esc_attr_e($key); "><?php echo __($field['label'], 'wp-event-manager') . apply_filters('submit_event_form_required_label', $field['required'] ? '<span>*</span>' : ' <small>' . __('(optional)', 'wp-event-manager') . '</small>', $field); </label>

**Comment by mistry-jignesh** [comment]
After update plugin . Field editor page is not looking properly .

Event form field, organizer and venue form field details are missing.

![image](https://user-images.githubusercontent.com/75515088/185129685-21bcfee1-c045-42b7-875c-09c12d0704b6.png)

**Comment by mistry-jignesh** [comment]
When create new event at front end then Fatal error message is display .
Here create one organizer & venue using "Here" option.

![image](https://user-images.githubusercontent.com/75515088/185143275-f40864f6-8f0b-4fb9-b146-740ef7cd7427.png)

**Comment by mistry-jignesh** [comment]
When I have added repeated field at backend from field editor then front end section display the error message .

![image](https://user-images.githubusercontent.com/75515088/185310135-8e65275a-fd25-4769-82d8-86766c03baf2.png)

**Comment by ashokdudhat** [comment]
You still have issues we pointed out before.

You did not remove your copy of jQuery like we said to:

wp-event-manager/assets/js/jquery-ui/jquery-ui.min.js
wp-event-manager/assets/js/jquery-ui/jquery-ui.js

You still have non-sanitized code:

wp-event-manager/admin/wp-event-manager-writepanels.php:1108: $date = $_POST[$key];
wp-event-manager/admin/wp-event-manager-writepanels.php:1109: $datetime = explode(' ', $_POST[$key]);

You're still trying to translate $-variables (using numbers would be okay, but not words, which appears to be what you're doing):

wp-event-manager/admin/wp-event-manager-cpt.php:401: 5 => isset($_GET['revision']) ? sprintf(__('%1$s restored to revision from %2$s', 'wp-event-manager'), $wp_post_types['event_listing']->labels->singular_name, wp_post_revision_title((int) $_GET['revision'], false)) : false,

wp-event-manager/admin/wp-event-manager-settings.php:828:												echo wp_kses_post(' <p class="description">' . sprintf(__('%s', 'wp-event-manager'), $option['desc']) . '</p>');

wp-event-manager/admin/wp-event-manager-settings.php:848:												echo wp_kses_post(' <p class="description">' . sprintf(__('%s', 'wp-event-manager'), $option['desc']) . '</p>');

**Comment by mistry-jignesh** [comment]
Wrong label is availabel at venue & organizer list.

![image](https://user-images.githubusercontent.com/75515088/186886676-ac2bc6f0-37bc-4812-b81d-330e90e02def.png)

![image](https://user-images.githubusercontent.com/75515088/186886764-fd5b4c2f-2440-450d-91e6-f445f3749036.png)

**Comment by mistry-jignesh** [comment]
Need to remove from space form event listing page.

Space issue page.

![image](https://user-images.githubusercontent.com/75515088/186890538-f661d406-0a30-4f98-b36f-4c498854329a.png)

Correct event listing page.

![image](https://user-images.githubusercontent.com/75515088/186890736-9f9e73e3-257b-4f6c-8242-74e302a4288f.png)

**Comment by mistry-jignesh** [comment]
Need to add correct description - Expo networking tab

Need to update description.

![image](https://user-images.githubusercontent.com/75515088/186908642-5bd8d753-5eb1-4faa-841b-7b8b65fa92d1.png)

Correct desctiption.

![image](https://user-images.githubusercontent.com/75515088/186908848-b03a61ea-9a62-49ba-a5ad-bb3afc817d47.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/186909634-38f286a9-adee-456c-93c6-7716d18cad5d.png)
Proper display from my side

**Comment by mistry-jignesh** [comment]
Fatal error message is display on the page.

**Comment by mistry-jignesh** [comment]
When I have not fill up Attendee details then validation message is display wrong. 

![image](https://user-images.githubusercontent.com/75515088/187138304-b4f85ea4-cfb5-4a3e-9c58-5c446fb2e55e.png)

Correct message as below.

![image](https://user-images.githubusercontent.com/75515088/187138844-436f4620-c8c3-4c22-b065-e8fb24f4153c.png)
Attendee Information to collect is a required field.

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/187141314-d6c42500-b0ac-4ebe-800e-21505ff82532.png)

**Comment by mistry-jignesh** [comment]
Click on the reset to default button 2 times then priority values is display like 1,2,3,4,5 etc.

Priority values start from the wrong values.

https://user-images.githubusercontent.com/75515088/187349971-35d83838-8774-49f2-8341-bbe822108c92.mp4

Check video.

**Comment by ashokdudhat** [comment]
You still have issues we pointed out before.

You did not remove your copy of jQuery like we said to:

wp-event-manager/assets/js/jquery-ui/jquery-ui.min.js
wp-event-manager/assets/js/jquery-ui/jquery-ui.js

You still have non-sanitized code:

wp-event-manager/admin/wp-event-manager-writepanels.php:1108: $date = $_POST[$key];
wp-event-manager/admin/wp-event-manager-writepanels.php:1109: $datetime = explode(' ', $_POST[$key]);

You're still trying to translate $-variables (using numbers would be okay, but not words, which appears to be what you're doing):

wp-event-manager/admin/wp-event-manager-cpt.php:401: 5 => isset($_GET['revision']) ? sprintf(__('%1$s restored to revision from %2$s', 'wp-event-manager'), $wp_post_types['event_listing']->labels->singular_name, wp_post_revision_title((int) $_GET['revision'], false)) : false,

wp-event-manager/admin/wp-event-manager-settings.php:828:												echo wp_kses_post(' <p class="description">' . sprintf(__('%s', 'wp-event-manager'), $option['desc']) . '</p>');

wp-event-manager/admin/wp-event-manager-settings.php:848:												echo wp_kses_post(' <p class="description">' . sprintf(__('%s', 'wp-event-manager'), $option['desc']) . '</p>');

**Comment by krinaydhanani** [comment]
Now this issue was fixed as per the WordPress Org guidance. I am going to close this issue.
