### ISSUE TITLE
Field editor- Time zone type is display blank

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1095]
Add custom Field editor.

Time zone type is display blank.

![image](https://user-images.githubusercontent.com/75515088/174799976-608edff0-089d-4c00-b659-b21cbc3c9c33.png)

![image](https://user-images.githubusercontent.com/75515088/174800323-609c169f-cf86-4119-aeec-1c8567909c02.png)

**Comment by mistry-jignesh** [comment]
When I have select below time zone .

![image](https://user-images.githubusercontent.com/75515088/175020787-d4f2881c-bea4-46c3-bff7-ca1ecb02e847.png)

At event detail or listing page below value is display then it is not proper.

![image](https://user-images.githubusercontent.com/75515088/175021164-103e2f97-c6c5-4a0a-bbb0-f616fe2860b1.png)

**Comment by tamanna-ahuja** [comment]
@mistry-jignesh - Above is correct only we can show it in either way

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja - At event detail page time is display correctly . 

So I closed the issue.
