### ISSUE TITLE
3.1.29

### ISSUE THREAD

**Issue by tamanna-ahuja** [wpeventmanager/wp-event-manager#1100]
= 3.1.29 [ June 22nd, 2022 ] =

Fixed - Add/Edit Event bug fixes
Fixed - Security fixes
Fixed - Event shortcode details missing bug fixes

**Comment by tamanna-ahuja** [comment]
Read me file created

**Comment by tamanna-ahuja** [comment]
This for readme file

**Comment by mistry-jignesh** [comment]
This issue is created for readme file.

So now closed this issue.
