### ISSUE TITLE
Location field displaying on event detail page.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1103]
https://user-images.githubusercontent.com/86232676/175256906-132b9bd6-370b-4c1b-91ca-5673037508b0.mp4
 online event selected , but on event details page location  field showing. 
![image](https://user-images.githubusercontent.com/86232676/175257766-007746c9-74c5-4bab-b567-f0e14795140c.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .

Online event is selected , Here event details page location field is showing as "Online Event".

So I closed the issue.
