### ISSUE TITLE
Add new Event - Venue/Organizer- Second time selected logo file is not visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1106]
Open the post an event page.

For create new venue/organizer .
Click on the -"Here" link button.

First create new venue/organizer .Here selected logo is visible .

Second time Click on the -"Here" link button.

Fill up details and selected logo for venue/organizer.

Here selected logo file is not visible.

![image](https://user-images.githubusercontent.com/75515088/175270642-71e03420-7d40-453a-8914-61b1e1a0338c.png)
![image](https://user-images.githubusercontent.com/75515088/175270867-779292ae-0411-46d9-bc19-81182bb478f7.png)

**Comment by kinjal6810** [comment]
cover this issue bug No #1137

**Comment by kinjal6810** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/104058202/179486137-b015c5a1-1297-4b0a-be88-a28b87d9619b.jpg)  

![Screenshot_44](https://user-images.githubusercontent.com/104058202/179486167-b9cd3de4-7805-44c6-abc9-ddb0bfd0ff63.jpg)

![image](https://user-images.githubusercontent.com/104058202/179486197-5e18c957-5fd1-4e2d-8ffb-df9389e095cd.png)

 When I comment above file. it works fine but only displays file names as shown above screenshot.
we can improve UI next version.

**Comment by mistry-jignesh** [comment]
Verified this issue.This issue is fixed.

When Second time Click on the -"Here" link button.

Fill up details and selected logo for venue/organizer.

Here selected logo file is not visible but  only displays file names .

As per @kinjal6810 - Comment above file. it works fine but only displays file names as shown above screenshot.
we can improve UI next version.
