### ISSUE TITLE
Problem after update with sell ticket display

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1109]
![image](https://user-images.githubusercontent.com/65893994/175465927-aaa0a83b-a936-4f9f-818e-e2658eb2e128.png)

**Comment by Priya-Goenka** [comment]
Please check the layout on phone as well.

**Comment by mistry-jignesh** [comment]
This issue is open in the sell ticket. Issue id is - https://github.com/wpeventmanager/wp-event-manager-sell-tickets/issues/286

Here I closed the issue.
