### ISSUE TITLE
Post meta changes to incorrect value

### ISSUE THREAD

**Issue by dtraintrain** [wpeventmanager/wp-event-manager#1111]
When some books for an event directly through the purchase tickets process the post meta field "**_event_registered_for**" is set correctly.

However if you -

1 - Update the registration status to any status and press save it sets this meta field as the Post Title

2 - If you create a registration directly from the WordPress dashboard and not through the ticket sales process it sets this post meta field to the Post Title

**Comment by Priya-Goenka** [comment]
https://user-images.githubusercontent.com/65893994/177287817-0b981b6f-f1f6-463a-9364-ed436026361a.mp4

https://user-images.githubusercontent.com/65893994/177287822-000326a1-3808-496d-a023-8a4227dd767f.mp4

**Comment by ritakikani** [comment]
This issue is from registration addon so here i am closing this issue.
