### ISSUE TITLE
Warning message on post an event page.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1113]
![image](https://user-images.githubusercontent.com/86232676/176680750-bbfd2de9-cee3-49ce-8340-c82e0a6fe632.png)
steps:- post an event page
fill up all the details
preview the page. warning message showing.

**Comment by kinjal6810** [comment]
We have not use such function. this issue Wordpress core.

**Comment by yukta05** [comment]
As per @tamanna-ahuja this issue of WordPress. So I close this issue.
