### ISSUE TITLE
Calendar design issue with  core plugin 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#1114]
![image](https://user-images.githubusercontent.com/86232676/176840193-675baf55-e27c-4b0b-bdcd-839998515018.png)
 
  On event page, a calendar design issue occurred.

**Comment by kaushikpokal** [comment]
![image](https://user-images.githubusercontent.com/83581741/178981895-95ea82a4-26d3-40eb-8bd2-16b642d78fde.png)
 @yukta05 Can you please re-produce this issue ?

**Comment by mistry-jignesh** [comment]
This issue is coming from the core plugin. Now this issue is fixed & working fine.

Calendar layout is looking proper.

So I closed the issue.
