### ISSUE TITLE
 Past events does not find any events 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1117]
Using the shortcode [past_events] does not find any events even though there are many.

[past_events show_filters="false" selected_datetime="2022-01-01,today"]

**Comment by ritakikani** [comment]
Please first check which attribute is used in this [past_events] shortcode.

 show_filters="false"  this is not an attribute of this shortcode please verify from this doc : https://wp-eventmanager.com/knowledge-base/past-events/

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/d9959fd9-8a09-43b6-8612-7ac85203db94)


Now, for selected_datetime attributes, today/tomorrow/yesterday will be worked.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.
[past_events selected_datetime="2023-04-01,today"]
Shortcode is working .
So I closed the issue
