### ISSUE TITLE
Adsense not working. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1121]
https://wordpress.org/support/topic/adsense-and-single-event-page/

**Comment by ritakikani** [comment]
Reference forum link : 
https://stackoverflow.com/questions/36024303/google-adsense-advertisements-not-displaying

**Comment by ritakikani** [comment]
Adsense is working perfect on event listing page.

![image](https://user-images.githubusercontent.com/25837982/189338797-c4e0e02e-6c0e-4f84-8cd7-eda1fb708b4f.png)

**Comment by ritakikani** [comment]
Adsense also working fine on single event page.

![image](https://user-images.githubusercontent.com/25837982/189364423-d4f9ac0e-91bb-441d-8d77-d619ebb3e2cb.png)

**Comment by mistry-jignesh** [comment]
As per @ritakikani . Now this issue is working fine.

Adsense is working fine on single event page.
