### ISSUE TITLE
Speed Time Checking

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1129]
The processing time to provide a screen display is many seconds when using the selected_datetime filter

This is using an event database of about 500 events

How can this be improved?

Ref: https://wordpress.org/support/topic/wp_eventmanager-very-slow-using-selected_datetime/

**Comment by mistry-jignesh** [comment]
This issue is fixed and working fine.
Verified this issue with 150+ events. 
Processing time is less when using  selected_datetime filter option
So I closed the issue.
