### ISSUE TITLE
Import events date issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1130]
If I import US date (m/d/Y} then the detail of the event has the correct date. 

However the Event Manager->All Events has the incorrect date.

If Import AUS date (d/ m/Y) then the detail of the evevnts has the INcorrect date.

However the Event Manager >All events has the correct date.

**Comment by live-aamir** [comment]
@mistry-jignesh Not find any error after exporting and importing to other installation.

**Comment by mistry-jignesh** [comment]
Verified this issue . After other installation import  events. Here Event Manager->All Events has the correct date.

This issue is working fine.

So I closed the issue
