### ISSUE TITLE
Elementor - Deprecated error message is availabel

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1134]
In the elementor when drag and drop below plugin then deprecated error message is availabel.

- Event Alert
- Event past registration
- Event Sell ticket

![image](https://user-images.githubusercontent.com/75515088/177982353-f6126311-1a25-4dbf-b519-ba10b86b8b90.png)

**Comment by kinjal6810** [comment]
Request to You transfer to above addons

**Comment by mistry-jignesh** [comment]
Created new issue in the releated pluign.

Event Alert
Event past registration
Event Sell ticket

https://github.com/wpeventmanager/wp-event-manager-sell-tickets/issues/283
https://github.com/wpeventmanager/wp-event-manager-registrations/issues/236
https://github.com/wpeventmanager/wp-event-manager-alerts/issues/37

So I closed the issue.
