### ISSUE TITLE
Backend - Setting - Expo Networking- Text description is different

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1138]
Expo Networking- Text description.

![image](https://user-images.githubusercontent.com/75515088/178945870-d1b56190-57e6-4216-8534-4b5803184c8b.png)

**Should be text descriotion as below.**

![image](https://user-images.githubusercontent.com/75515088/178946367-24c7b641-3438-4172-86f6-bd5085ac7a58.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/178957305-20fd77ed-1465-4f65-ad62-e23bc0cfd6bf.png)
working properly from my side.
