### ISSUE TITLE
load throbber is missing in the listview option

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1144]
load throbber is missing in the listview option.

![image](https://user-images.githubusercontent.com/75515088/179724064-bb1f2e8e-579c-4707-9f18-1746adad646c.png)

**Comment by ritakikani** [comment]
This is working fine in current version.

**Comment by mistry-jignesh** [comment]
Now this issue is working fine currently version.

So I closed the issue.
