### ISSUE TITLE
Please check this issue reported by client. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1145]
![image](https://user-images.githubusercontent.com/65893994/179789992-b6549e1c-30d3-4f66-bb37-2ad1dfe4f322.png)

the plugin is affecting our server image below, i made a few changes in one event in this crash site.
We are considering buy the plugin but the latest issues make us consider that.
There a new release to be publish soon, with corrections?
This problem doesn´t affect anyone?

![image](https://user-images.githubusercontent.com/65893994/179790140-83eb4e50-7b31-4784-a2b2-519c35a992dc.png)

**Comment by mistry-jignesh** [comment]
This issue is not reproduced. So I am closing the issue.
