### ISSUE TITLE
Fields dissappear when a error occurs

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1148]
If you enter a non-numeric field in a numeric field, an error message will be displayed after submitting the form and the values ​​in all fields will disappear.

If the email address is not in the correct format, an error message will be displayed after submitting the form and the values ​​in all fields will disappear.

Can you understand the error you are experiencing?
This is an error message prepared by the plugin, so you can probably understand it.

While subbitting a event form, if there is any error in respect to non entered field or wrong entry of field, The details vanishes, rather it should stay.

**Comment by mistry-jignesh** [comment]
Verified this issue. In the numeric field if try enter non-numeric values here unable to type any values .

Also  verified email address is not in the correct format then validation is not check. This should be check if enter invalid values.
 
After submitting the form and the values ​​in all fields will disappear issue is not reproduced.

The details page is not  vanishes.
