### ISSUE TITLE
Fatal Errors arising.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1150]
[@Krinay Dhanani]

https://pastebin.com/mVNwMmg9
The WP Event Manager is showing multiple PHP Fatal errors.
Please check this before release.
I tried downgrading from PHP 8.0 to 7.4 but that didn't fix the issue.

**Comment by kinjal6810** [comment]
Do you have any other cache plugin installed or caching enabled on the server? If yes can you please disable it temporarily and check if you still see these errors in the error logs?

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed & working.

This issue is not reproduced . So I closed the issue.
