### ISSUE TITLE
Post an event page dropdown is not availabel- Organizer & attendee infomration field 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1151]
Post an event page dropdown is not availabel - Organizer & attendee infomration field .

![image](https://user-images.githubusercontent.com/75515088/180140193-feb26131-d2ce-4550-9594-40e403b06ec3.png)

**Comment by kinjal6810** [comment]
I checked but working properly from my side

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is not reproduced & working fine.

So I closed the issue.

**Comment by mistry-jignesh** [comment]
Verified this issue .

Now this issue is not reproduced & working fine.

So I closed the issue.

**Comment by mistry-jignesh** [comment]
This issue still availabel on local server. So reopen the issue.

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is fixed & working fine.
