### ISSUE TITLE
Email id field - Validation is not check

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1154]
Post an event page. 

**Email id field-**  

If enter invalid values mail id then validation message is not check.

![image](https://user-images.githubusercontent.com/75515088/180205333-d6d4a27d-caf0-4cc0-a74f-602f1d44768c.png)

**Comment by ritakikani** [comment]
In "Registration Email/URL", user can add either email address or URL. so, we cannot restrict that field with email validation cause if user wants to add URL then he cannot add.

Need to discuss more regarding this validation.

**Comment by ritakikani** [comment]
After discussion with @krinaydhanani , we decide that there is no need to validate email/url , just validation for blank field is ok for now. So we can close this issue.

**Comment by mistry-jignesh** [comment]
After discussion with @krinaydhanani , we decide that there is no need to validate email/url , just validation for blank field is ok for now. 

So we can close this issue.
