### ISSUE TITLE
Borders and class on listing page. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1156]
I updated recent version of EventManager.
In listing page, it seems that the borders in each event are incorrect.

![image](https://user-images.githubusercontent.com/65893994/180806916-65022e88-4ede-4ddc-a7b8-7a9736ce96dc.png)
 
And, maybe the function that event_listing_class() in wp-event-manager/wp-event-manager-template.php doesn't work.
No class has output into html even though the event is cancelled.
![image](https://user-images.githubusercontent.com/65893994/180807003-86556c46-e98a-4ef8-bb4d-eced3d3f6788.png)

 
Has the event_listing_class() function been changed something?
Please fix this issue as soon as you can.

**Comment by ritakikani** [comment]
@Priya-Goenka  I need client site link and credential for testing.

**Comment by ritakikani** [comment]
I had checked for this issue but not found this type of any issue in our latest version.

**Comment by Priya-Goenka** [comment]
resolved, It was in map addon

**Comment by mistry-jignesh** [comment]
As per @Priya-Goenka - Now this issue is resolved.

 So I closed the issue.
