### ISSUE TITLE
 Elementor custom field ticket link showing as html markup

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1159]
Elementor custom field ticket link showing as html markup

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed and working fine.

Html markup code issue is fixed.

![image](https://user-images.githubusercontent.com/75515088/183083396-57f91ff9-2310-4766-919e-f74b3a2f5220.png)

So I closed the issue.
