### ISSUE TITLE
Online event field with field editor compatiblity 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#116]
Online event field with field editor compatiblity.

Also there is some conflict with default value of all radio,checkbox and select box.

Need to improve field editor.

**Comment by hiteshmakvana** [comment]
By default, all radio button default value must have to stay selected if you save or reset fields in field editor.
Need to test with each and every possible case with a custom filter,GUI save and addon compatibility

**Comment by hiteshmakvana** [comment]
Key of the option must have to store without translation and with trim so it won't add more _ in after and before.
Value of the option is translated with i18n functions.
Now select will work with key and value separated by : and option separated by |

**Comment by ritakikani** [comment]
working fine
