### ISSUE TITLE
Multiselect field (country)not display properly

### ISSUE THREAD

**Issue by kinjal6810** [wpeventmanager/wp-event-manager#1161]
![183079368-35368bfc-b271-49b7-bd5e-301c19a5b017](https://user-images.githubusercontent.com/104058202/183364185-d4ffee8b-2b7b-4fd9-a0be-fba648151362.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed & working fine.

In the dropdown values are availabel properly.

![image](https://user-images.githubusercontent.com/75515088/183412590-a4a186f5-6aa2-44eb-b6cf-feb806e1775e.png)
