### ISSUE TITLE
Custom Field editor - Type update issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1164]
First I have added custom field as Date Type.

In the event I have added value for date type.

 Event details page (Date) value is display.

Now change type as time .

Edit event and try select time but here time is unable to select.

Here last select value is display.

**Comment by ritakikani** [comment]
I had followed the step mention above, but didnot produce issue.So, as per me there is no issue with field date/time type.so, please check again with above steps.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.

Currently this issue is not reproduced .
So I closed the issue.
