### ISSUE TITLE
Updated steps for add-on License Key Activation

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1165]
URL - https://wp-eventmanager.com/knowledge-base/install-wp-event-manager/

Now we have added option **License**  for adding license key.

![image](https://user-images.githubusercontent.com/75515088/184613584-44684b58-6483-416c-a363-bebf7d1aef09.png)

![image](https://user-images.githubusercontent.com/75515088/184614086-a455dae8-b951-4c5c-bbcf-406bdcfb8014.png)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1JaRyskisgNBgvzvyjBpQp5OoZkbDy3TGUzEwdythyTw/edit

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.
It is working fine. So I closed the issue.
