### ISSUE TITLE
Event Listing shortcode issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1168]
Verified below shortcode are not working.

[events orderby="name/modified/parent" per_page="15"]

[events orderby="featured" per_page="15" order="ASC/DESC"]

[events per_page="10" show_filters="false" ticket_prices="paid"]

[events per_page="5" event_types="attraction,appearance-or-signing" show_event_types="true" show_filters="true" orderby="title" order="DESC/ASC" layout_type="list" show_more="true"]

**Name wise events are ordering with elementor.**

**Comment by ritakikani** [comment]
[events orderby="name/modified/parent" per_page="15"]

here, "modified" working fine.
"name" is similar to title so need to remove it from documentation.
Need to discuss with @krinaydhanani  regarding "parent".

**Comment by ritakikani** [comment]
[events orderby="featured" per_page="15" order="ASC/DESC"] is working fine currently but we can provide more flexible "featured" orderby in next version.

**Comment by ritakikani** [comment]
[events per_page="5" event_types="attraction,appearance-or-signing" show_event_types="true" show_filters="true" orderby="title" order="DESC/ASC" layout_type="list" show_more="true"]

in above shortcode, if event_types attribute is there then show_event_types will not work as per the code.
other attribute is working fine.

**Comment by ritakikani** [comment]
[events per_page="10" show_filters="false" ticket_prices="paid"] this is not working so i will resolve the issue.

**Comment by mistry-jignesh** [comment]
![image](https://user-images.githubusercontent.com/75515088/189295320-2564df0e-a19f-4d7d-a0b7-33ad11f5be73.png)

Verified this issue. Still free ticket events are display on the page.
Please check it.

**Comment by mistry-jignesh** [comment]
Verified this issue.Now this issue is fixed.
Events are display with matching code..
So I closed the issue.
