### ISSUE TITLE
Event Dashbaord page is taking more time to load

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1169]
Event Dashbaord page is taking more time to load.

Use below shortcode in the event dashboard page.

[event_dashboard posts_per_page="25"] 

https://user-images.githubusercontent.com/75515088/185054448-cc83ef48-245c-4171-a347-00569aebc2a4.mp4

**Comment by ritakikani** [comment]
Speed issue on dashboard is not because of our core plugin.
Try to check after deactivate other addons of wp event manager plugin, you will get dashboard data in 1-2 seconds.
It may be because of add other addons menu in our dashboard page

**Comment by mistry-jignesh** [comment]
Verified this issue . After deactivate other addons of wp event manager plugin .
Now event dashboard page is not taking more time to load. It may be because of add other addons menu in our dashboard page.
So I closed the issue.
