### ISSUE TITLE
Event Organizer short code is not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1172]
Event Organizer short code is not working .

When I write below shortcode . Try to view of this page then blank is display.

[event_organizer id=82]

![image](https://user-images.githubusercontent.com/75515088/185095738-f0d6b30a-e6e1-45e0-87fc-e4806be749d9.png)

**Comment by ritakikani** [comment]
This is working fine i had test on local and staging.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine . 

So I closed it
