### ISSUE TITLE
Event summary - limit attribute is not working as per setting

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1173]
I have added below code in the page.

[event_summary id="" width="150px" align="right" featured="false" limit="5"]

Now preview the page .Here only the four events summry are display on the page.

If increase the limit then here not effect on the view page.

![image](https://user-images.githubusercontent.com/75515088/185101731-e53ef547-f465-443f-a336-afaad9641131.png)

**Comment by ritakikani** [comment]
This feature "limit" is working fine in version 3.0.32 so please take latest and test again with version 3.0.32.

**Comment by mistry-jignesh** [comment]
This issue is present in the  in version 3.0.32. 

So I closed the issue.

**Comment by mistry-jignesh** [comment]
Verified this issue . Limit is workig fine.

Here issue with  featured="false" attribute . This attribute is not working.

For that create new issue.So I closed the issue.
