### ISSUE TITLE
Backend - Settings - Event submission tab - Need to update option list

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1177]
URL -https://wp-eventmanager.com/knowledge-base/event-submission-page-settings/

1. **Need to update option list in the documention.**

Currently in the event submission option below option are availabel .

![image](https://user-images.githubusercontent.com/75515088/185859361-3d0a148e-e366-43e8-813e-6ce3c23c58d7.png)

2.**In the documention old option and containt are display.**

![image](https://user-images.githubusercontent.com/75515088/185859917-7e1378a3-10c7-4d46-9135-c12d2bf536a4.png)

**Comment by kaushikpokal** [comment]
1. Multi-select Event types for event Submission
2. Multi-select Event Category for event Submission

this 2 section currently not showing this settings

**Comment by mistry-jignesh** [comment]
Multi-select Event types for Event Submission
Multi-select Event Category for Event Submission

For above issue . I have created a new issue.
Issue Id is #1377

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1eQQtofw7jO-kFxvu313QlFSu3IUAh2H2g3pndEV7vgc/edit#heading=h.6ieqjsu5nil2

**Comment by mistry-jignesh** [comment]
This issue is fixed. So I closed the issue.
