### ISSUE TITLE
Go to  word is repeated two times in the sentence

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1184]
URL -  https://wp-eventmanager.com/knowledge-base/backend-event-dashboard/

Go to  **How to delete the submitted event?** section 

Here first steps need to remove **Go to** word from the sentence .

**Go to** word is repeated two times.

![image](https://user-images.githubusercontent.com/75515088/186073507-b109a91c-3827-472c-a01d-4fb5c75ed645.png)

**Comment by Prachetshi1991** [comment]
i am not the right person for this

**Comment by mistry-jignesh** [comment]
This issue is fixed on the live site. 
So I closed the issue.
