### ISSUE TITLE
Remove link from  "WP" word .It should be display like other steps 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1185]
URL  -https://wp-eventmanager.com/knowledge-base/event-fields/

**How to delete the event field?** **section**

Remove link from  "WP" word .It should be display like other steps .

![image](https://user-images.githubusercontent.com/75515088/186079131-8f3f80e9-014a-4969-a63b-21375b94cffc.png)

**Same issue face in the other page.**

URL - https://wp-eventmanager.com/knowledge-base/organizer-fields/

**How to edit the organizer field? Section**

Remove link from  "WP" word .It should be display like other steps .

![image](https://user-images.githubusercontent.com/75515088/186081476-d26bb2bf-1291-4b78-9c5a-5773cf2730ab.png)

**Same issue face in the other page.**

URL - https://wp-eventmanager.com/knowledge-base/add-a-new-event-category/

**How to edit & delete the event category? section** 

Remove link from  "WP" word .It should be display like other steps .

![image](https://user-images.githubusercontent.com/75515088/186085035-9cd2aec3-2dd3-4a07-8776-a0f79f01a743.png)

**Comment by Prachetshi1991** [comment]
I think Shoyeb will be the right person to solve this issue.

**Comment by Prachetshi1991** [comment]
i am not the right person for this assignment

**Comment by mistry-jignesh** [comment]
Here above all screenshots in the "WP" word available the link.
So is correct? OR

Need to make it simple text. @krinaydhanani

**Comment by mistry-jignesh** [comment]
I have verified this issue. Remove the link from the "WP" word.
Now it is made of simple text like other pages. Now it is similar to another page.
This issue is fixed. So I closed the issue.
