### ISSUE TITLE
Instead of category need to add categories spelling in the step

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1186]
URL - https://wp-eventmanager.com/knowledge-base/add-a-new-event-category/

Instead of category need to add categories spelling in the step.

![image](https://user-images.githubusercontent.com/75515088/186086164-d08e4c47-0159-4753-9fb4-267dc167a023.png)

**Comment by Prachetshi1991** [comment]
I am not the right for this assignment. @mistry-jignesh please take care of it

**Comment by mistry-jignesh** [comment]
This issue is fixed on the live site.
 So I closed the issue.
