### ISSUE TITLE
Elementor custom post type template compatibility

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#119]
Elementor custom post type template compatibility.
Elementor template not showing events post type due to has_archive 
Need to make events post type compatible with elementor.

**Comment by krinaydhanani** [comment]
![image](https://user-images.githubusercontent.com/35419531/90628423-34806900-e23b-11ea-9c40-2ea6e258c4c4.png)

**Comment by krinaydhanani** [comment]
It's working fine only for Event.

**Comment by mistry-jignesh** [comment]
I have verified this bug. Now it is working properly.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
