### ISSUE TITLE
WordPress Org : JS File issue

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1190]
You still have issues we pointed out before.

You did not remove your copy of jQuery like we said to:  Please make sure that below file removed or not.

wp-event-manager/assets/js/jquery-ui/jquery-ui.min.js
wp-event-manager/assets/js/jquery-ui/jquery-ui.js

**Comment by ritakikani** [comment]
These files deleted from version 3.0.32.

**Comment by mistry-jignesh** [comment]
Now files are deleted in the version 3.0.32

So I closed the issue.
