### ISSUE TITLE
 Create Event Details Page issue with Elementor

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1191]
Using elementor option I am try to create event details page.

Below Details added from the event field.
- Event title
- Event Banner
- Start date,time
- End date,time
- Event description.

**Check other option also** 

![image](https://user-images.githubusercontent.com/75515088/187615949-c57c4d3a-4e54-4847-b516-264778a30890.png)

![image](https://user-images.githubusercontent.com/75515088/186413419-88d7bd4c-85f5-4dec-95a9-6841e52fe403.png)

Added details but details is not availabel properly on the page.

Details are display two times on the page.

![Single Event – beta](https://user-images.githubusercontent.com/75515088/186413628-998f5baf-4f8a-4439-9718-3f6fe34165f3.png)

For more refernce check video - https://www.youtube.com/watch?v=VolTLINnBak&t=754s

**Comment by kinjal6810** [comment]
plz check the using template elementor

**Comment by ritakikani** [comment]
It is working fine after solving issue #1204 and #1205 .

**Comment by mistry-jignesh** [comment]
Need to discuss desing issue @krinaydhanani

**Comment by ritakikani** [comment]
When single event template is create with elementor, that time some sections, div and other html tags added by elemntor, so we can't do any changes in elementor default design. There is no any conflict or bug from our plugin.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - When single event template is create with elementor, that time some sections, div and other html tags added by elemntor, so we can't do any changes in elementor default design. There is no any conflict or bug from our plugin.

So I closed the issue.
