### ISSUE TITLE
Problem with add ons menu

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1192]
Problem with add ons menu inside admin.

<img width="1720" alt="Screenshot 2022-08-24 at 23 47 03" src="https://user-images.githubusercontent.com/15089059/186610018-f2da0593-383d-4e05-8102-5d0876923e92.png">

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/188132404-18cc7cc0-caf5-4f58-86ea-8adbbd758313.png)
already solved this issue

**Comment by mistry-jignesh** [comment]
This issue is verified and closed it.
