### ISSUE TITLE
Addons menu in WP Event Manager plugin details are not availabel properly

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1196]
Addons menu in WP Event Manager plugin details are not availabel properly.

![image](https://user-images.githubusercontent.com/75515088/186841965-18043e7e-9353-4c28-98d0-acee0c07b9db.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/186885153-39827660-c150-443e-85a4-dc0219ecf872.png)

**Comment by mistry-jignesh** [comment]
![WP-Event-Manager-Add-ons](https://user-images.githubusercontent.com/75515088/186911390-7d8b16e5-2fb0-4314-8fc1-ca0a19aead1e.png)


**Verified this issue . Now desing issue is fixed.**

But some plugin are still missing . For that open new issue.

Now this is fixed .So I closed the issue.
