### ISSUE TITLE
Speed loading. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1199]
People are time and again reporting speed issues. 
Its taking real time to load the events pages.

**Comment by ashokdudhat** [comment]
We have two loading time problems on the event overview site.
Sometimes the event overview take over 10 seconds to load. It seems that the Xhr Call takes so long to load.

* Is there a way to speed up the loading time of the event overview from the plugin?

1. Event overview/filtering
the loading time of the events is up to 5-12 seconds.

2. Load more Events (Button)
the loading time when loading more events is up to 4-10 seconds

Installed Plugins:
Event Manager – v.3.1.31
If further information is needed please just ask.

Ref: https://wordpress.org/support/topic/event-overview-increase-loading-time/

**Comment by ritakikani** [comment]
In our current version 3.1.32, event filtering and load more button take 1-2 seconds times to get data through xhr

**Comment by mistry-jignesh** [comment]
- Event overview/filtering
- The loading time of the events is up to 5-12 seconds.
- **Now loading time of events is reducing on filtering page.**

![image](https://user-images.githubusercontent.com/75515088/189581441-e27e7cd4-4cb9-4911-b7c1-c32fd53e263b.png)


- Load more Events (Button)
- The loading time when loading more events is up to 4-10 seconds
- **When loading more events on the page . Now this time is also reducing .**

![image](https://user-images.githubusercontent.com/75515088/189581236-20c5c63e-1f85-42a0-bb0d-a0d3753ae551.png)
