### ISSUE TITLE
Elementor - Event listing - In the preview click on any event then page is display blank.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1202]
Event listing - In the preview click on any event then page is display blank.

Here event detisl is not display on the page. Should display details on the page.

![image](https://user-images.githubusercontent.com/75515088/187412207-2e12e59e-9c33-45b9-8a97-0c7a309c97a9.png)

![image](https://user-images.githubusercontent.com/75515088/187412701-11edb9b0-bcae-4f90-b9f0-8fe541e6a1ff.png)

**Comment by kinjal6810** [comment]
elementor template all data delete after checking event listing

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is working fine after template all data delete.

So I closed the issue.
