### ISSUE TITLE
Facing issue with past shortcode 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1203]
Below shortcode not working with  attribute.

[past_events orderby="id"] - **Id wise not display events.**
[past_events orderby="title"] - **By default Descending order display.**
[past_events orderby="event_start_date"]- **By default Descending order display**
[past_events orderby="name"] -  **Name wise events are not display.**
[past_events orderby="parent"]-  **All past events are display.**
[past_events orderby="modified"] -  **As per modified time event are not display.**

**Comment by ritakikani** [comment]
This atts of Orderby is working fine. 

We are giving default order "DESC", you must need to set order atts in shortcode to set order "ASC/DESC".

"name" is not working and also not important because we are already giving title wise sorting functionality.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - We are giving default order "DESC"
.Here events default order is display "DESC".
"Name" is not working and also not important because we are already giving title wise sorting functionality.

So I closed the issue
