### ISSUE TITLE
Elemetor -Template - Single event venue - Preview is display the blank

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1205]
First create new template using add new template option.
Select option as single event venue .
Set condtion.
Click on the preview button.
Click on the event link button.
Now click on the any events.
Here preview is display the blank.

![image](https://user-images.githubusercontent.com/75515088/187420311-883f037d-b0e0-44e8-b464-73ac74d9df21.png)

**Comment by kinjal6810** [comment]
#1202

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is fixed and working fine.

Now venue details is display on the page.

So I closed the issue.
