### ISSUE TITLE
Venue/Organizer- Display warning error message - Trying add invalid image format like webp

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1206]
**Venue/Organizer** 

Display warning error message - Trying add invalid image format like webp

![image](https://user-images.githubusercontent.com/75515088/187604505-6b3dd6d0-a7c3-409e-9a9f-320b05e18b5f.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/188079503-6cfada94-6985-420b-842c-ba2da02ace95.png)

![image](https://user-images.githubusercontent.com/104058202/188079362-0c45888f-5d8e-4011-8f2d-edd85737f998.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.Warning error message is fixed.

Validation message is display trying add invalid image format like webp.

So I closed the issue.
