### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1208]
We have noticed that when someone searches for events by a date range it takes about 40 seconds to get information back from the ajax call. Do you know why it takes so long? Is there any way to resolve this issue? Thanks for your help with this.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now searches for events by a date range it is taking less time as prevuosly taking .
This issue is working fine. 

@Priya-Goenka - Please verify this issue at your end.

**Comment by Priya-Goenka** [comment]
ok, sol,ved

**Comment by kinjal6810** [comment]
this issue is fixed so i close this issue
