### ISSUE TITLE
Printed jquery

### ISSUE THREAD

**Issue by ClareO** [wpeventmanager/wp-event-manager#121]
Hi,

I have this printed on my single event page since updating to latest version

![print-jquery](https://user-images.githubusercontent.com/13809372/63008516-0f685600-be83-11e9-9ee3-0bcea8c3c009.jpg)

Can you please fix?

**Comment by hiteshmakvana** [comment]
Hi @ClareO,
Can you please confirm that you have overridden template file to your theme side? Script tag is added on the above jQuery. I have verified it is not working on any instance.

Can you please provide the link of your site?

**Comment by ClareO** [comment]
I did indeed have this particular file overriden, so I deleted the override to see the new file and that is when I saw the printed code.
So I put my override back for the moment and I don't have the problem (so you won't see it on the website)

**Comment by hiteshmakvana** [comment]
Hi @ClareO,
It looks like your issue is fixed. 
Thank you so much for providing all the details.
