### ISSUE TITLE
Organizer Dashboard -  Details are not display properly

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1210]
Organizer Dashboard - Click on the any organizer.

 Details are not display properly.

![image](https://user-images.githubusercontent.com/75515088/188070883-b511567a-0df0-40ed-a75f-c3b685499e9c.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/188071213-39550e59-a162-47ef-b665-45c11e74a622.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.
Details are properly display on the organizer detaila page.
So I closed the issue.
