### ISSUE TITLE
featured=false shortcode is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1212]
featured=false shortcode is not working.
[event_summary id="" width="150px" align="right" featured="false"]

**Comment by ritakikani** [comment]
[event_summary limit="10" featured="false" width="150px" align="right"]

this shortcode is working fine on my local and also on staging .

https://staging-appwpeventmanager.kinsta.cloud/wp-admin/post.php?post=7263&action=edit

https://staging-appwpeventmanager.kinsta.cloud/test/

**Comment by mistry-jignesh** [comment]
Please check this issue again with

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.

So I closed the issue.
