### ISSUE TITLE
Featured search issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1214]
Select orderby as "featured "option.

If there is not featured date events then events are not display in order.
https://prnt.sc/1bqa1aw

2.I have select orderby as "featured "option.

If there is featured date events then events are not display in order.

https://prnt.sc/1bqhqgb

3.I have select orderby as "Event start date "option.

There are 3 events .All events start on same date and time(07/7/2021) and 2 events are finished on same date(31/8/2021).
one event finished on (31/7/2021)

Here one event finished on 31/7/2021 and this event is display second position.

This event should be display first.

https://prnt.sc/1bpm0ae

**Comment by ritakikani** [comment]
1-2 issues are already resolve in previous issue.so, please check with latest version.

In 3rd query, you choose orderby "event start date" then will correctly sorting with start date.This will not sort your end date.so this is not issue.Is you choose start date then will only sort start date at a time.

**Comment by mistry-jignesh** [comment]
1st  and 3rd  point are working fine.

Need to verify 2nd point.

I have select orderby as "featured "option.

If there is featured date events then Featured events are not display first. 

![image](https://user-images.githubusercontent.com/75515088/189338417-d8f6198e-7bfd-4dc8-8e51-2bfadd09a049.png)


![image](https://user-images.githubusercontent.com/75515088/189337762-f2a8c89b-7731-4b24-9f92-ad05c473357b.png)

**Comment by mistry-jignesh** [comment]
Verified this issue and it is working fine.
So I closed the issue.
