### ISSUE TITLE
Add ons menu has still problem

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1223]
add ons menu has still problem, it show html comment

<img width="1727" alt="Screenshot 2022-09-13 at 10 59 17" src="https://user-images.githubusercontent.com/15089059/189859080-0da4ebe6-6602-4ae6-9abd-93f617c239d9.png">

**Comment by mistry-jignesh** [comment]
This issue is working fine.

**Comment by ritakikani** [comment]
For remaining addon, need to set specific id or different class on https://wp-eventmanager.com/plugins/ so we can get all addon list.
