### ISSUE TITLE
Backend - Venue/Organizer - Logo update issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1225]
Created venue & orgnaizer from backend with logo details .

Now go to frontend .

Edit Venue/Organizer from frontend side.

Remove old logo . 

Added new logo for  Venue/Organizer.

After added new logo. Now old logo is  display for organizer and venue .

Now I have to mauallly remove logo from backend admin section(Venue/organizer.)

Agian add new logo then new logo is display in the Venue/Organizer.

**Comment by ritakikani** [comment]
As per our current code, when admin can create organizer/venue that time organizer/venue logo will set as thumbnail, while from front side user create organizer/venue that time logo will not set as a thumbnail but upload as a banner, and when open dashboard that time we first check for thumbnail for organizer/venue logo if not set then we check for banner.

![image](https://user-images.githubusercontent.com/25837982/196161503-984fcce3-a9fb-46f5-9206-737bf36f6626.png)

**Comment by kinjal6810** [comment]
As per @ritakikani.
I close it.
