### ISSUE TITLE
Duplicate events on listing page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1226]
Duplicate events on listing page.

 More than 100 events are availabel & Same event date repeat more than 15 times.

[events per_page="12" orderby="event_start_date" order="ASC" show_more="true" categories="Palermo" show_filters="false" selected_datetime="2022-01-01,2022-12-31"]

https://www.youtube.com/watch?v=-nEW8MTBDSM

**Comment by ritakikani** [comment]
We had verify that this issue not recognize by our team or any other client.

**Comment by kinjal6810** [comment]
Verified this issue but not recognized by me so I close this issue.
