### ISSUE TITLE
html tags in multi select checkbox list

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1227]
If i select field type "term checklist" then design issue at front side post event form.

![image](https://user-images.githubusercontent.com/25837982/190115341-9c55c192-6ee6-4fc8-8469-fdc678a70ff5.png)

![image](https://user-images.githubusercontent.com/25837982/190115098-d05e15af-d2af-4719-a3cc-941489118aeb.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now post event form page desing issue is fixed.

Error message issue is fixed 

So I closed the issue.
