### ISSUE TITLE
Field editor - Type select as Teram checklist issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1229]
From field editor added Term checklist field type.

Now in the event selected checking list.

Here event details page checklist is not display & click on edit event then selected check list is not save.

![image](https://user-images.githubusercontent.com/75515088/190402411-39b566a4-b0a7-444b-a2f3-7856a9b9063a.png)

**Comment by ritakikani** [comment]
This issue is occur for event tags.

**Comment by ritakikani** [comment]
I am open this issue in event tags addon.

**Comment by mistry-jignesh** [comment]
This issue is from event tags addon . So Here I closed the issue.

Open issue in the tags addon.

https://github.com/wpeventmanager/wp-event-manager-event-tags/issues/30
