### ISSUE TITLE
paid or free tickets not decrease in ticket from frontend

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1231]
#304 
Reduce paid or free tickets not decrease in ticket from frontend.

When we will make it zero from frontend then it must show sold out in frontend but it not work..

When we do from only admin then it work.

 #299
Ticket disappearing when quantity changes to zero from frontend

https://wordpress.org/support/topic/ticket-disappear-from-event_submit_form/

steps of bug reproduce :
    add a event from frontend
    add the ticket
    approve on backend
    edit the event from frontend
    change the ticket qty to 0
    the ticket in details on backend and frontend dissapears.
    whereas it shows on event detail page.

**Comment by mistry-jignesh** [comment]
Verified this issue . 

Ticket disappearing when quantity changes to zero from frontend/backend issue is fixed and working fine.

So I closed the issue.
