### ISSUE TITLE
Please check this function. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1233]
Hi,
it's a custom theme.
I make a function with the same name in functions.php file.
But for each update, a fatal error appears because the function can't appear 2 times.
the only solution is :

![image](https://user-images.githubusercontent.com/65893994/190585761-d9d23cff-903e-4f36-86bf-1f35e8c3dc18.png)

**Comment by ritakikani** [comment]
Hi @Priya-Goenka ,

Please ask user to use below filter for achieve the  custom functionality he/she wants to.

![image](https://user-images.githubusercontent.com/25837982/196092176-09b76ffc-d73d-49ec-b2f3-7653bfb7119e.png)

**Comment by mistry-jignesh** [comment]
As per @ritakikani :  Use below filter for achieve the custom functionality.

![image](https://user-images.githubusercontent.com/75515088/198583691-34cc19f8-1192-4fe0-a0b3-c85c8fd47cb6.png)


So I closed the issue .
