### ISSUE TITLE
Elementor - Single event organizer /venue issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1236]
From the elementor select option as single event organizer /venue.

![image](https://user-images.githubusercontent.com/75515088/190625954-2a6ade91-efb4-478e-be84-43c8f73ec743.png)

![image](https://user-images.githubusercontent.com/75515088/190626078-364c9129-abdf-4795-8b9c-d78d41cb2fb3.png)

Page is display the blank.

**Comment by ritakikani** [comment]
this is working fine on my end.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine. Not able reproduced again.

So i closed the issue.
