### ISSUE TITLE
selected_datetime says "There are currently no events".

### ISSUE THREAD

**Issue by yesroom657** [wpeventmanager/wp-event-manager#1238]
I am using a short code to display upcoming events on a site and it is returning 0 events if I add any datetime filters.  The code I am using is below:

[events show_filters="false" orderby="event_start_date" layout_type="List" featured="true" selected_datetime="today,1/01/2100"]

This functionality was working several days ago, but I noticed this happening after the latest update was released a week ago.  I did not add any addons or make any changes to the site other than add events.  I verified that the date format was consistent.

**Comment by mistry-jignesh** [comment]
I have verified this issue using below shortcode . This issue is working fine at staging & local server.

![image](https://user-images.githubusercontent.com/75515088/191173939-b27af466-a623-4f6d-b9e7-51fe23a40bdd.png)

First need to set date & time below format.

![image](https://user-images.githubusercontent.com/75515088/191174031-ca18918d-d6fa-47cf-aa66-4bc4903ba537.png)

Event detaila page display the featured events.

![image](https://user-images.githubusercontent.com/75515088/191174184-85d28b73-3a24-49bc-95ce-bec3eb9b944e.png)

**Comment by yesroom657** [comment]
I verify the settings on the site:
![image](https://user-images.githubusercontent.com/38575162/191264377-750c7f24-2cdf-45ac-bcf5-828c9dc01e8e.png)

![image](https://user-images.githubusercontent.com/38575162/191264731-b22cd3b7-c321-4189-953b-27bdf72b5ce6.png)
 However I am still getting the message that there are no events listed.

Is there any way I can debug this error further?  

I even get this result when I try to filter on any date range:

![image](https://user-images.githubusercontent.com/38575162/191265611-0de2ad68-24c3-4200-983e-fed454be995c.png)

**Comment by ritakikani** [comment]
@yesroom657  we solved this issue so you can take latest update from here.

**Comment by yesroom657** [comment]
I uploaded the v3.1.33 and I am still not returning any results when filtering by date.

**Comment by ritakikani** [comment]
@yesroom657  hi,

did you test with below shortcode?becuase this is working fine on our all testing server after update the code.
did you take above update ?
https://github.com/wpeventmanager/wp-event-manager/commit/714f83c97fbf46d29553948daf36250b7164a9c5



`[events show_filters="true" orderby="event_start_date" layout_type="List" featured="true" selected_datetime="today,01/01/2100"]`

**Comment by mistry-jignesh** [comment]
I have verified this issue with 3 diffeerent setup . Using below code.

[events show_filters="false" orderby="event_start_date" layout_type="List" featured="true" selected_datetime="today,1/01/2100"]
Now this issue is working fine .

**Comment by mistry-jignesh** [comment]
This issue is working fine. 

So I closed the issue.

**Comment by ritakikani** [comment]
Hi @yesroom657 ,

We had solved the issue which you faced, and soon we will release new version 3.1.33 of our plugin.

Thank you.
