### ISSUE TITLE
Issue in widget title

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1245]
I have one widget - past event widget.
I don't have any past event so on frontend it will show me blank box in place of past event widget.
It should be hide or with title "Past Event" and with content "there is no past events".

![image](https://user-images.githubusercontent.com/25837982/192208798-7149ccf7-cbae-424a-b494-bab28f8257fa.png)

![image](https://user-images.githubusercontent.com/25837982/192208848-43eecdb4-99a5-45b7-abfe-0c4f1f86c0b4.png)

**Comment by kinjal6810** [comment]
verified this issue. it is hiding a blank box in place of the past event widget so I close it.
