### ISSUE TITLE
A Bug in the code, please check

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1248]
Maybe this issue is caused by handling of 2-byte character, I think.

It seems that at the function in the file wp-event-manager/wp-event-manager-template.php, in case that users select the event type includes 2-byte character, this function doesn't work.

![image](https://user-images.githubusercontent.com/75515088/193993252-c6cad1e9-1147-490c-a5c1-dc82bd74ea2f.png)

Till 3.1.27, it works well with escaped letter. But from 3.1.28, something was changed, I think.

with event type letter

Now I commented it out like below. It works well, its class without event category name.

/**

get_event_listing_class function.

@access public

@return array
*/
function get_event_listing_class($class = '', $post_id = null)
{

$post = get_post($post_id);

if ($post->post_type !== 'event_listing') {
return array();
}

$classes = array();

if (empty($post)) {
return $classes;
}

$classes[] = 'event_listing';

// if ($event_type = get_event_type()) {
//
// if ($event_type && !empty($event_type)) {
// foreach ($event_type as $type) {
// $classes[] = 'event-type-' . sanitize_title($type->name);
// }
// }
// }

if (is_event_cancelled($post)) {

	$classes[] = 'event_cancelled';
}

if (is_event_featured($post)) {

	$classes[] = 'event_featured';
}

if (!empty($class)) {

	if (!is_array($class)) {
		$class = preg_split('#\s+#', $class);
	}

	$classes = array_merge($classes, $class);
}

return get_post_class($classes, $post->ID);

![image](https://user-images.githubusercontent.com/75515088/193993294-28d32ad5-4106-4d08-b404-548955c0ac72.png)

without event type letter

Hoping that will fix in near future

**Comment by ritakikani** [comment]
I can't reproduce the above mention bug, so please provide me bug reproduce steps so i can verify and resolve this issue.

**Comment by mistry-jignesh** [comment]
@Priya-Goenka - Please provide steps for this issue. So developer can solve the issue.

**Comment by mistry-jignesh** [comment]
Now this issue is no more available. So I closed the issue.
