### ISSUE TITLE
GUI Single Event page

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#125]
User can manage single event listing page from admin panel or from custom template must have t o be generated from plugin.

**Comment by krinaydhanani** [comment]
Please put proper comment with screen shots so tester can easily understand and test it well.

**Comment by siddharthgotawala** [comment]
@krinaydhanani Please provide more details

**Comment by krinaydhanani** [comment]
We already have an improved design so we do not need to implement more.
