### ISSUE TITLE
Events with duration of multiple days not showing with daterange selection

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1250]
When I update the plugin from version 3.1.30 to 3.1.32 (WP v 6.0.2) the events overview does not show any events with duration of multiple days (with an end-date that is different from the startdate) when a daterange selection is made in the filters (the range starts today and ends after the end dates, the start dates of the events are before today).

- When the daterange is set to start before the start dates of the events and ends after the end dates of the events they do show up.
- When the daterange is set to start before the start dates of the events and ends before the end dates of the events they do show up.
- When the daterange is set to start after the start dates of the events and ends before the end dates of the events they do not show up.

When I roll back to v. 3.1.30 the events show up in all of the 3 dateranges above.

**Comment by ritakikani** [comment]
The above 1, 2nd options is working fine as per plugin functionality.
But the 3rd one is new feature, for this please read this https://github.com/wpeventmanager/wp-event-manager/issues/792

**Comment by ritakikani** [comment]
This functionality of 3rd option as mention above is added now in version 3.1.33.

https://github.com/wpeventmanager/wp-event-manager/issues/1265
