### ISSUE TITLE
Location donot considering the english symbols

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1252]
I would like to inform you that that when there is a location that contanins an accent (‘) like Xi’an, the result of the event list will be null with no event.

Example:
[events per_page=”10″ location=”xi’an”]

The list will generate zero events because your tool does not take into consideration these accents: Xi’an VS Xian

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/196361686-34063cfb-c46f-406c-add6-709f1cc70f60.png)

![image](https://user-images.githubusercontent.com/104058202/196361556-ca67580c-2f68-4962-afcd-aa22333c1f26.png)
when there is a location that contanins an accent (‘) like Xi’an, the result of the event list will be null with no event.

**Comment by ritakikani** [comment]
This is working fine.

**Comment by kinjal6810** [comment]
Verified this issue. working fine so I close it.
