### ISSUE TITLE
Bulk action issue

### ISSUE THREAD

**Issue by shb1899** [wpeventmanager/wp-event-manager#1253]
Bulk action doesn't work except trash. 

Approve events:

1. Create two events from the front end. They will remain unapproved as long as you don't approve them from the back end. 
2. Go to the backend. Choose approve events from the bulk action. 
3. After clicking on apply, the page will refresh but the events will remain unapproved. 

Edit:  Choose Edit option from Bulk actions. Click on apply. Nothing happens. 

Expire Events: Doesn't work as well.

**Comment by kinjal6810** [comment]
Verified this issue. Bulk action is properly working so I close it.
