### ISSUE TITLE
Date conversion must have to verify before showing curren date

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#126]
Currently if date is empty it will show current day which is not correct. Just hide them if it is empty.

**Comment by ritakikani** [comment]
I had added some conditions for blank date check in my branch.

**Comment by hiteshmakvana** [comment]
Date conversion needs to verify from DB and in Date and time class functions.

**Comment by krinaydhanani** [comment]
It's working fine.
