### ISSUE TITLE
Backend side - Attendee Information to collect field is reset

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1260]
This issue is duplicate of https://github.com/wpeventmanager/wp-event-manager-attendee-information/issues/28

Need to activated Attendee information plugin.

Go to backend .

From the attendee information field remove selected field like attendee name ,attendee email.

Click on the update buttton .

Here attendee information field deleted field are agian visible.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Attendee information fields deleted are not visible.

This issue is working . So I closed the issue.
