### ISSUE TITLE
If there is no organizer then need to display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1262]
If there is no organizer then need to display.

![image](https://user-images.githubusercontent.com/75515088/198560331-1bd0fc48-9f24-4f53-81e0-5f16f5ded53a.png)

Click on the above screenshot link then error message is not display.

Should be display proper message. Like ad venue.

![image](https://user-images.githubusercontent.com/75515088/198560740-4abce892-8baf-4ec8-9878-ab587d36e300.png)

**Comment by ritakikani** [comment]
I had test but not found this type of issue on updated version so Please provide bug reproduce steps

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue working.

Message is display :  If there is no organizer.

So I closed the issue.
