### ISSUE TITLE
Instead of Watch button should display the video URL

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1264]
Instead of Watch button should display the video URL.

![image](https://user-images.githubusercontent.com/75515088/199216557-0c0f4709-cd1a-453c-94da-3b923590376e.png)

**Comment by live-aamir** [comment]
@mistry-jignesh I have discussed with @krinaydhanani the settings for video is fine. If user wants to create any link, the user can create a link field in field editor, which will be showing dynamically in single event field widget. So close this issue.

**Comment by mistry-jignesh** [comment]
As per @live-aamir- If user wants to create any link, the user can create a link field in field editor, which will be showing dynamically in single event field widget.

So I closed the issue.
