### ISSUE TITLE
Filtering by datetime not working correctly

### ISSUE THREAD

**Issue by freeze2404** [wpeventmanager/wp-event-manager#1265]
When using the datetime filter I get only events which have an end date.
Events which have only a start date are not shown.

Furthmore, when looking into the wp-event-manager-functions.php, the if-then-else structure starting at line 175 always jumps into the else (line 301) - at least for my configuration (datepicker date format: 15.01.2022).
And if we have a look into the code in this else structure we see:

	else
	{

		$dates = json_decode($args['search_datetimes'][0], true);
		//get date and time setting defined in admin panel Event listing -> Settings -> Date & Time formatting
		$datepicker_date_format 	= WP_Event_Manager_Date_Time::get_datepicker_format();

		//covert datepicker format  into php date() function date format
		$php_date_format 		= WP_Event_Manager_Date_Time::get_view_date_format_from_datepicker_date_format($datepicker_date_format);
		if (
			!empty($dates)
		) {
		$dates['start'] = WP_Event_Manager_Date_Time::date_parse_from_format($php_date_format, $dates['start']);
		$dates['end'] = WP_Event_Manager_Date_Time::date_parse_from_format($php_date_format, $dates['end']);
		$date_search['relation'] = 'AND';
		$date_search1[] = array(
			'key'     => '_event_start_date',
			'value'   =>  $dates['end'],
			'compare' => '<=',
			'type'    => 'date'
		);
		$date_search1[] = array(
			'key'     => '_event_start_date',
			'value'   => $dates['start'],
			'compare' => '>=',
			'type'    => 'date'
		);
		$date_search1['relation'] = 'AND';
		$date_search[] = $date_search1;
		$date_search2[] = array(
			'key'     => '_event_end_date',
			'value'   => $dates['start'],
			'compare' => '>=',
			'type'    => 'date'
		);
		$date_search2[] = array(
			'key'     => '_event_start_date',
			'value'   => $dates['end'],
			'compare' => '<=',
			'type'    => 'date'
		);
		$date_search2['relation'] = 'AND';
		$date_search[] = $date_search2;
	}

In my opinion the "$date_search['relation'] = 'AND';" in line 315 is wrong.
It should be 'OR' and not 'AND', because we want to get all events which have the start date inside the given range OR the end date inside the given range. And that's also why we only get results for events that have an end date set.

And.. furthermore the second $date_search2[] array member is wrong im my opinion.
The first query ($date_search1[]) looks good: "'_event_start_date' <= $dates['end'] AND '_event_start_date' >= $dates['start']".
But the second search query ($date_search2[]) is "'_event_end_date' >= $dates['start'] and '_event_start_date' <= $dates['end']".
This makes no sense in my opinion?
Shouldn't this be "'_event_end_date' >= $dates['start'] and '_event_end_date' <= $dates['end']" together with "$date_search['relation'] = 'OR';" at the beginning?

**Comment by ritakikani** [comment]
Hi @freeze2404 ,

We’re very thankful that you write your opinion and post here regarding the issue which you are facing with detail description( +code issue from our side ).

We had update code regarding above issue and we will release new version very soon.

Thanks for once again supporting and choosing us!

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.

Events which have only a start date are display.

Facing other issue . For the date & Time format select at backend.

So open new issue for that.
