### ISSUE TITLE
Backend : Date & Time format - Few event are not diaply

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1267]
Backend perform below setting.

![image](https://user-images.githubusercontent.com/75515088/199700756-29ec0170-700e-4171-a366-e4698d3df63b.png)

Date&Timeformat   Dateformat  

01-15-2022 -->     d-m-Y  -      2 event are display. - Which events has no end date.
01.15.2022  -->      d-m-Y -       2 event are display. - Which events has no end date.

Test Event4  -location - Online events - 28-10-2022 & **No End date**
Test Event5  -location - Ahemdabad -     28-10-2022 & **No End date**
Test Event1 - Location - Ahemdabad -    28-10-2022 & 28-02-2023
Test Event2 - location -  Surat     -    30-10-2022 & 30-11-2022
Test Event3A -location-  Online events - 28-10-2022 & 30-11-2022  
Test Event3 - location - Online events - 01-11-2022 & 30-11-2022

![image](https://user-images.githubusercontent.com/75515088/199700674-92758d0b-ae14-496d-83c4-be659a903fd7.png)

There are six events availabel in the application.

**Comment by ritakikani** [comment]
this functionality is working fine so please take latest version then test.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working.

Unable to reproduced this issue again.

So I closed the issue.
