### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1273]
- Just updated the latest version of coreplugin.
- When using Chinese characters as one of the category.
- This category is use in the event.
- The entire web page breaks at backend.

**Error Message :**

PHP Fatal error: Uncaught ArgumentCountError: 7 arguments are required, 1 given in /…/wp-content/plugins/wp-event-manager/wp-event-manager-functions.php:1280

![image](https://user-images.githubusercontent.com/75515088/200761844-c3ada74f-3f5f-4916-afda-b9e32232814e.png)

**Comment by ritakikani** [comment]
https://wordpress.stackexchange.com/questions/51498/wordpress-slug-issue-with-non-latin-characters

**Comment by ritakikani** [comment]
https://core.trac.wordpress.org/ticket/9591

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed and working fine.

PHP Fatal error: Uncaught ArgumentCountError: 7 issue is fixed.

So I closed the issue.
