### ISSUE TITLE
 Event Expire after 12PM 

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1274]
Event start date, end date and expire date will same then event will not view at front end.It will show as event is expired.

duplicate from https://github.com/wpeventmanager/wp-event-manager-recurring-events/issues/82

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Event start date, end date and expire date will same then event is view at front end.

It is show as event is Active.

So I closed the issue.

**Comment by mistry-jignesh** [comment]
Event is expired automatically .So Please check it.

**Comment by ritakikani** [comment]
I had test and verify on my local. this is working fine. so, please take latest code and test again.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Event start date, end date and expire date will same then event is view at front end.

It is show as event is Active . Right is working fine.

So I closed the issue.
