### ISSUE TITLE
Create documention for without locotranslate

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1276]
Create documention for without locotranslate.

**Comment by Prachetshi1991** [comment]
without locotranslate means?

**Comment by ritakikani** [comment]
@Prachetshi1991  you just need to create documentation for translate language for our plugin.

For say, If you want to translate your site language in hindi then please see the below video for steps and generate doc for this.

https://www.awesomescreenshot.com/video/17644971?key=2404425b62cce00c91d417cc59c9be14

If client want to add his own .po/.mo fie after changes in translation files, then see in below video for steps.

https://www.awesomescreenshot.com/video/17645084?key=dcbe031013720a63fcc59a7920a24def

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1Z2JjxAMByzSK5CJzz41C6F-FWOUHHVhHczYp7vM3U8A/edit

**Comment by krinaydhanani** [comment]
We can not put this type of video link on documentation.

**Comment by mistry-jignesh** [comment]
I have checked the YouTube videos section. Here this topic is not available.
So I have created a topic for this in the click up.
