### ISSUE TITLE
Event thumbnail is missing in event listing page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1277]
Some time event banner is set in database but thumbnail is not there then on listing page event thumbnail will not seen so at that time we must need to show event banner in place of event thumbnail.

This is happens when we list events which is comes from migration.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .

Event thumbnail is availabe in the event listing page.

Issue verified after events import to new setup. This is working fine.

So this issue is closed.

**Comment by mistry-jignesh** [comment]
Taken new version of migration plugin. After code cleanup again same issue is facing.

So here I reopen the issue. Need to check it.

![image](https://user-images.githubusercontent.com/75515088/205842759-254cd496-cfa2-4a6d-b78c-e3ce1d1d120e.png)

**Comment by ritakikani** [comment]
This is working fine now. please take latest and check again.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Taken new version of migration plugin. Import organizer.venue and events.

In the event details page event thumnnail is working fine. 

So I closed the issue.
