### ISSUE TITLE
Data cleanup

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1278]
Data cleanup and finding error 

https://plugintests.com/plugins/wporg/wp-event-manager/latest

you can find if any options missed when plugin delete .. then deleting all options from database.

**you can find from above ur and section :  Options wp_options**

Options wp_options 51
enable_event_organizer
enable_event_venue
event_listing_category_children
event_listing_type_children
event_manager_category_filter_type
event_manager_date_time_format_separator
event_manager_datepicker_format
event_manager_delete_data_on_uninstall
event_manager_delete_events_after_finished
event_manager_delete_expired_events
event_manager_enable_categories
event_manager_enable_default_category_multiselect
event_manager_enable_default_event_type_multiselect
event_manager_enable_event_ticket_prices
event_manager_enable_event_types
event_manager_enable_registration
event_manager_event_dashboard_page_id
event_manager_event_type_filter_type
event_manager_events_page_id
event_manager_generate_username_from_email
event_manager_google_maps_api_key
event_manager_hide_cancelled_events
event_manager_hide_expired
event_manager_hide_expired_content
event_manager_installed_terms
event_manager_login_page_url
event_manager_organizer_dashboard_page_id
event_manager_per_page
event_manager_rating_showcase_admin_notices_dismiss
event_manager_registration_role
event_manager_submission_duration
event_manager_submission_expire_options
event_manager_submission_requires_approval
event_manager_submit_event_form_page_id
event_manager_submit_organizer_form_page_id
event_manager_submit_venue_form_page_id
event_manager_timepicker_format
event_manager_timepicker_step
event_manager_timezone_setting
event_manager_use_standard_password_setup_email
event_manager_user_can_add_multiple_banner
event_manager_user_can_edit_pending_submissions
event_manager_user_requires_account
event_manager_venue_dashboard_page_id
event_manager_view_date_format
widget_widget_featured_events
widget_widget_past_events
widget_widget_recent_events
widget_widget_upcoming_events
wp_event_manager_db_version
wp_event_manager_version

**Comment by krinaydhanani** [comment]
This issue was fixed so I am going to close this issue.
