### ISSUE TITLE
in single event view some strings are still not translated

### ISSUE THREAD

**Issue by Michele64** [wpeventmanager/wp-event-manager#1281]
![image](https://user-images.githubusercontent.com/65893994/127625628-a57ab7e2-d94c-4780-a6c5-f13db609e4b0.png)

_Originally posted by @Priya-Goenka in https://github.com/wpeventmanager/wp-event-manager/issues/874#issuecomment-889733891_

**Comment by Michele64** [comment]
still not translated even if the correct strings are present in po files... 
![Köln-–-online-–-Pyar](https://user-images.githubusercontent.com/13287876/203859061-0841ebd0-966c-4273-9725-66e78e20e760.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed .

Date and time &  To key word is translated properly.

![image](https://user-images.githubusercontent.com/75515088/209517483-df8e6947-2e93-4c25-a8bd-6cb0c39a1f67.png)

This issue is working fine .
