### ISSUE TITLE
Events 404 error when profile language different to site language

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1282]
by @grandeljay
https://github.com/wpeventmanager/wp-event-manager-google-maps/issues/125

I have set the site language to German and my Profile language to English.

The event I created has an English slug /event/ yet the shortcode is linking to the translated slug /veranstaltungen/. This is causing a 404 error.

In order to work around this I had to change my wp profile language settings to "Site Default" and re-save the event for it to get the translated event slug too.

Oh I am a plugin dev too, if you want me to look at something I can give it a go and see if I can submit a working PR.

**Comment by ritakikani** [comment]
Hi @grandeljay,

We had resolve the above issue which you were faced in our org version.You just need to take latest version from here git repository and then you need to set your site default language as "german" and profile language to "Site default Language" then reset the permalink from the settings then again you need to change your profile language to "English" then again you need to save the permalink from the settings and go to your event listing page and then select any event from them.Your issue will be resolve and you can see your event content.

Thank you.

**Comment by mistry-jignesh** [comment]
Verified this issue. When I set language like site language to German and my Profile language to English.
Now issue 404 is fixed . Events are listing fine. So I closed the issue.
