### ISSUE TITLE
Event titile is use apostrophe " 's "

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1283]
Like if I have created event title name with Test Jerry Event's .

When edit alert and updated alert message . 

Face this issue  apostrophe " 's " issue. Here blackslash is added automatically .

![image](https://user-images.githubusercontent.com/75515088/205624702-22306ed9-11f1-4817-8823-10adeeae20b1.png)

**Comment by ritakikani** [comment]
this is issue of alert addon so i am transferring issue in alert addon.

**Comment by mistry-jignesh** [comment]
This issue is from the alert addpn.

Now this isue is moved in alert addon.

So I closed the issue here.
