### ISSUE TITLE
In the event title use  “&”  then "& amp;" is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1285]
Here in the event title name use "&" symbol .
In the backend and Frontend event title name is display properly.

**_Only I edit the event from the backend then in the title text box "& amp;" is display._**

![image](https://user-images.githubusercontent.com/75515088/208046441-c9f759c3-ba13-4ffd-b42c-2cbf4a571a56.png)

**Comment by ritakikani** [comment]
This is the issue from classic editor.Classic editor is not decode special characters like '&'.

https://wordpress.org/support/?post_type=topic&p=16309269

**Comment by ritakikani** [comment]
This is the behavior of wordpress which cannot be changed by us.Please look into this forum for answer .

https://wordpress.org/support/topic/html-special-character-issue/

**Comment by mistry-jignesh** [comment]
As per @ritakikani - This is the behavior of wordpress which cannot be changed by us.Please look into this forum for answer .

https://wordpress.org/support/topic/html-special-character-issue/

So I closed the issue.
