### ISSUE TITLE
Sell ticket dependacy on single event and event listing page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1286]
Sell ticket dependacy on single event and event listing page.

Ex.
If i have sell ticket addon activates and for the event have 2 types of ticket 1.paid 2. free so on event listing and single event page will show me ticket "Paid/Free" for that event.

then i will deactivate the sell ticket addon then their must not seen that both ticket because from core plugin i didnot select any ticket.
inshort we have to manage ticket options at event listing and single event page with and without sell ticket to show tickets.

![image](https://user-images.githubusercontent.com/25837982/208828965-f37bf347-c36b-4181-bca2-565068467fef.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed .

If deactivated sell ticket then ticket label is not visible on the single event and event listing page.

This issue is working fine. 

So I closed the issue.
