### ISSUE TITLE
Event overview – increase loading time

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1287]
https://wordpress.org/support/topic/event-overview-increase-loading-time/

https://wordpress.org/support/topic/event-overview-too-high-loading-time/

**Comment by ritakikani** [comment]
this issue is already resolve in previous version.

**Comment by mistry-jignesh** [comment]
This issue is fixed and working fine.
Verified this issue with 150+ events.
Processing time is less when using selected_datetime filter option
So I closed the issue.
