### ISSUE TITLE
Price  and ticket icon should be display horizontal line

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1289]
Price  and ticket icon should be display horizontal line.

![image](https://user-images.githubusercontent.com/75515088/209510989-fffed8f0-a2fc-45db-8ab4-e68b07fa4805.png)

**Comment by mistry-jignesh** [comment]
![image](https://user-images.githubusercontent.com/75515088/216765177-758e954f-4986-40e0-9ec5-096105b39600.png)

Ticket label and Price, ticket icon should display horizontal line.

**Comment by kaushikpokal** [comment]
This issue has been resolved.

**Comment by mistry-jignesh** [comment]
This issue is working fine.

Ticket label and Price, ticket icon should display horizontal line.

So I closed the issue.
