### ISSUE TITLE
incorrect time on event detail page

### ISSUE THREAD

**Issue by junaidajmal** [wpeventmanager/wp-event-manager#1296]
Hi, the in time is showing correctly in event page but when you open its detail it is incorrect. I have give website as well as some screenshot so you can get the idea. Any help with this? Thanks.
https://jewishflorida.news/events/

![Screenshot 2023-01-10 203242](https://user-images.githubusercontent.com/5518175/211594969-40aaf0c5-cc01-4191-9510-a419c9bc8e84.jpg)
![Screenshot 2023-01-10 203227](https://user-images.githubusercontent.com/5518175/211594051-1e1e2b2b-4159-4c1b-ba68-21171dafe7fe.jpg)

**Comment by junaidajmal** [comment]
When will be this issue solved, it's causing problem on my website. Is there any solution?

**Comment by vijayrathod245** [comment]
I have checked as per your issue with our staging server and it's working fine.
Can you please provide your website login details so I can check it and let you know.

**Comment by junaidajmal** [comment]
https://jewishflorida.news/wp-admin
user: JFN9900
pass: JfN@15082004

**Comment by vijayrathod245** [comment]
I have checked as per your issue but it's not our issue, It's your theme issue.
I have checked your website with current theme so it's not working but I use other different theme so it's working fine.
So can you please check from your side with different theme.

**Comment by vijayrathod245** [comment]
@junaidajmal Any update ??

**Comment by junaidajmal** [comment]
Yes, It is working fine with different theme. Thanks!

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed .
It wroking fine. 
Client has informed that  working fine with different theme.
So I closed issue.
