### ISSUE TITLE
Post an event page - Dropdown box is not display properly

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1299]
Verified this issue in the version  3.1.33
In the mobile view.
Theme : wpem-charity, event listing

Post an event page - Dropdown box is not display properly.

![image](https://user-images.githubusercontent.com/75515088/211732744-40eebd8d-48b7-4028-9bf8-f52fd8b265a9.png)

**Comment by mistry-jignesh** [comment]
As per @ritakikani - This issue is related to design . 
So I have assigned to @kaushikpokal.

**Comment by kaushikpokal** [comment]
When you open **Device Toolbar** inside **Inspect Element** then show this error. So not a designer issue.
@mistry-jignesh You can ask developer if can be fix issue or not.

**Comment by mistry-jignesh** [comment]
As per @kaushikpokal: When you open Device Toolbar inside Inspect Element then show this error.
