### ISSUE TITLE
Thumbnails on event listing page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#130]
As you can see in attached screenshot, thumbnail images are getting cut. It should not cut the image. It should display full image in thumbnail.

![thumbnail](https://user-images.githubusercontent.com/49863477/63455472-25f74a00-c44d-11e9-9994-dfca91dacf18.png)

**Comment by ritakikani** [comment]
That image is not thumbnail but it is banner image so it is cut cause it will not fit in square box.

**Comment by hiteshmakvana** [comment]
I would like to test with thumbnail. Let's see

**Comment by siddharthgotawala** [comment]
We have added thumbnail feature in the addon now user can set images according to their website's image ratio.

**Comment by sapnadudhat03** [comment]
@krinaydhanani Can you please test this?

**Comment by krinaydhanani** [comment]
I have tested it. It is working fine but the user has to use thumbnail according to their website's image ratio.
