### ISSUE TITLE
Edit Event - Warning message is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1301]
Edit Event - Warning message is display on the page.

This issue is facing on the Demo server site :   https://demo.wp-eventmanager.com/

![image](https://user-images.githubusercontent.com/75515088/212609343-0c8e4266-245a-417b-8ef8-db119e833b09.png)

**Comment by ritakikani** [comment]
this is not issue of core plugin but it clearly seen that warning message from third party plugin.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.
Now this error message is not available on the demo server.
So I closed the issue.
