### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1302]
As the subject says, I am writing due to slow performance of the plugin when loading events. Currently, it takes on average 30 seconds to load the events in the website.

We have tested loading events in three different hostings and, in all of them, takes the above mentioned time (or even more).

From our investigation, the query retrieving the events is:
SELECT SQL_CALC_FOUND_ROWS  vyu_posts.ID
FROM vyu_posts 
INNER JOIN vyu_postmeta ON ( vyu_posts.ID = vyu_postmeta.post_id )  
INNER JOIN vyu_postmeta AS mt1 ON ( vyu_posts.ID = mt1.post_id )  
INNER JOIN vyu_postmeta AS mt2 ON ( vyu_posts.ID = mt2.post_id )  
INNER JOIN vyu_postmeta AS mt3 ON ( vyu_posts.ID = mt3.post_id )  
INNER JOIN vyu_postmeta AS mt4 ON ( vyu_posts.ID = mt4.post_id )
WHERE 1=1  AND ( 
  vyu_postmeta.meta_key = '_event_start_date' 
  AND 
  ( 
    ( 
      ( 
        ( mt1.meta_key = '_event_start_date' AND CAST(mt1.meta_value AS DATE) <= '2023-01-15' ) 
        AND 
        ( mt2.meta_key = '_event_start_date' AND CAST(mt2.meta_value AS DATE) >= '2022-11-01' )
      ) 
      OR 
      ( 
        ( mt3.meta_key = '_event_end_date' AND CAST(mt3.meta_value AS DATE) >= '2022-11-01' ) 
        AND 
        ( mt4.meta_key = '_event_start_date' AND CAST(mt4.meta_value AS DATE) <= '2023-01-15' )
      )
    )
  )
) AND vyu_posts.post_type = 'event_listing' AND ((vyu_posts.post_status = 'publish' OR vyu_posts.post_status = 'expired'))
					GROUP BY vyu_posts.ID 
					LIMIT 0, 10

This is an example of query to retrieve 10 events on specific dates.

Could you please advise on how we can improve the loading time?
Do you have an updated version where the query to retrieve results performs faster?
Do you have any recommendations or changes we can apply to improve the result?

**Comment by ritakikani** [comment]
I need shortcode of this

**Comment by krinaydhanani** [comment]
Right now we are not facing this issue so I am going to close this issue.
