### ISSUE TITLE
Need to add date range in the Week and month option

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1304]
Need to add date range in the Week and month option.
Right now for week & month date range is not selected.

![image](https://user-images.githubusercontent.com/75515088/213409952-3e5aabf3-3ae4-4b96-b12a-14543e7b3ea1.png)

**Comment by ritakikani** [comment]
This feature already we have in our plugin.so, please  check it.

**Comment by mistry-jignesh** [comment]
This option is working fine with option.
So I closed the issue.
