### ISSUE TITLE
Very long titles break design and event dashboard

### ISSUE THREAD

**Issue by Puetz** [wpeventmanager/wp-event-manager#1306]
Hello,

I just tested what happens if you enter a really long event title. Multiple issues came up.
On the event dashboard, you are no longer able to see the buttons for editing, cancelling, deleting, etc.
Also on the details page the text just overflows and you can scroll horizontally in for browser.

Is there any way to add a max length property to the text fields?
I checked the Field Editor and Settings but was not able to find this option.

Thanks for your help.
Kind regards,
Thomas

**Comment by Puetz** [comment]
Here is a screenshot showing that the buttons get pushed outside the view when entering a really long title:
![image](https://user-images.githubusercontent.com/34755160/213721064-3c8baeba-c7fe-454b-9404-965c18098b9a.png)

It would be really great to set a maximum length to every text input fields.

**Comment by ritakikani** [comment]
Hi @Puetz ,

I really appreciate for the query you posted after testing.We will resolve this issue in our next release.

Thank you.

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is fixed.
It is working fine. Event Dashboard is looking fine.
So I closed the issue.
