### ISSUE TITLE
German keyboard characters not supported for location search

### ISSUE THREAD

**Issue by Puetz** [wpeventmanager/wp-event-manager#1309]
Hello,

I'm on the event listings page and try to filter for German locations. Those can contain the letters ä, ö, ü.
If a location contains those letters, the search field does not show any results. If I use the general keyword search field it works.
Munich is called "München" in German, so it would be a problem it I can't search for locations in such a big city.

![image](https://user-images.githubusercontent.com/34755160/213728474-444f8781-7ced-4d57-9250-b22b17a84407.png)

Those characters also don't work for the registraion email/url field when creating a new event.

![image](https://user-images.githubusercontent.com/34755160/213729256-0b1c3f62-2452-4803-8ad3-fc440f566cb2.png)

Is there any way to disable those checks?

Thanks and kind regards,
Thomas

**Comment by ritakikani** [comment]
Hello @Puetz ,

We had resolve issue which you found and we will release updated version soon.

**Comment by mistry-jignesh** [comment]
I verified this issue. Now location search is working properly.
This issue is fixed.

For the second issue, gmail is not able to create an email address using letters ä, ö, ü.
So not able to disable it.
