### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1313]
<img width="1204" alt="Screenshot 2023-01-30 at 12 44 57" src="https://user-images.githubusercontent.com/15089059/215468301-e4e19ca4-d05e-43a0-a8c3-ce5f051b677e.png">

**Comment by ritakikani** [comment]
already compitible with php 8.1.0

**Comment by mistry-jignesh** [comment]
As per @ritakikani - Already compitible with php 8.1.0 .

I have verified this issue in the below version . Here this issue is not faced.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7ebb3139-9355-4dba-ad67-fcba9507cb24)

So I closed the issue.
