### ISSUE TITLE
Demo listing site not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1315]
Demo listing site not working .

Display error message on the page.

![image](https://user-images.githubusercontent.com/75515088/215965862-276b74ba-6b7e-4ebe-a2dc-8985efdd27b0.png)

![image](https://user-images.githubusercontent.com/75515088/215966166-527cfea8-7725-4737-a964-d854f5f2a9a2.png)

**Comment by ritakikani** [comment]
This is demo site issue so please open in related directory.

**Comment by mistry-jignesh** [comment]
Now this error message issue is fixed in the new demo server.
So I closed the issue.
