### ISSUE TITLE
Event Status Decision

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#132]
Decide how event submissions are handled You can choose whether events should be automatically published, or should await admin approval before it goes live. The form settings allow you to designate the desired ‘status’ of a submitted event.

- Require Admin Approval
- Publish Automatically
- Sava as draft

**Comment by ritakikani** [comment]
This feature is already inside settings of event submission with label "Moderate New Listings". so please verify it that any changes required in already given feature ?

**Comment by mistry-jignesh** [comment]
I have verified bug  . When I have published new events here before it goes to live their is require admin approval and after event is  published .

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
