### ISSUE TITLE
Demo server - Seminar site is now working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1320]
Demo server - Seminar site is now working.

Display error message on the page.

![image](https://user-images.githubusercontent.com/75515088/217999884-de1fbf07-9318-4519-b241-6f9aab513c45.png)

**Comment by ritakikani** [comment]
This is not issue of core plugin so please open bug in related directory.

**Comment by mistry-jignesh** [comment]
In the new demo server, this site is removed from the list.
It is working fine. So I closed the issue.
