### ISSUE TITLE
Need to update text category to type

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1321]
URL : https://wp-eventmanager.com/knowledge-base/add-a-new-event-type/
![image](https://user-images.githubusercontent.com/75515088/218002171-581dd18e-6cee-47e8-92ba-a86b17729044.png)

**Comment by Prachetshi1991** [comment]
i am not the right person for this,, i can not make changes in the webpage. i can only do this in the doc.

**Comment by mistry-jignesh** [comment]
This issue is fixed on the live site.
So I closed the issue.
