### ISSUE TITLE
Setup step2 page description text should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1322]
![image](https://user-images.githubusercontent.com/121149500/218002290-1d5ae684-5f79-4895-a89e-dbaacaf06f6d.png)

Current text :- post event
Should be :- Add Event

In setup step 2 the text should be proper

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.
Text is changed in step 2.
So I closed the issue.
