### ISSUE TITLE
Wrong information text showing in second line at Introduction page

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1323]
We are not creating event management pages.

Current text :- This setup wizard will help you get started by creating various pages for event submission, event management, and listing your events, along with setting up organizers and venues pages.

![image](https://user-images.githubusercontent.com/121149500/218002866-b55ffbe1-3543-40c4-91c9-4998e6c45d13.png)

**Comment by Prachetshi1991** [comment]
The Setup wizard helps you create various pages for event submission, event listings, handing events along with organizers and venue pages.
if you want to avoid the Setup wizard and want to creates pages manually, you can refer to the documentation for support.

**Comment by mistry-jignesh** [comment]
I have verified this issue. In step one update content is missing.

![image](https://user-images.githubusercontent.com/75515088/235587099-679867b3-dd9d-4efb-aef7-76b7b39b5c3b.png)

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
Now the description is updated.
It is working fine. So I close the issue.
