### ISSUE TITLE
Wrong notice text showing in event listing page.

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1325]
![image](https://user-images.githubusercontent.com/121149500/218004905-03931a25-d2ed-42a5-a1ef-4d3e6f94ba77.png)

Right now there is no any event was added in event manager addon and the notice like There are no events matching your search.

Show this notice when user search something using filter but there is no any result found.

When there is no event in the event listing please show like "There is no event added in event manager add some event for the listing"

**Comment by mistry-jignesh** [comment]
I verified this issue. Now the display message is changing.
It is working fine.
So I closed the issue.
