### ISSUE TITLE
Organizer message UI should be proper in responsive mode

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1326]
![image](https://user-images.githubusercontent.com/121149500/218006555-7dbe80f3-8135-4ff9-b7a2-1e605f8fc36e.png)

Organizer message UI should be proper in responsive mode

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is available.

Plz check it.

![image](https://user-images.githubusercontent.com/75515088/234207030-1389a7b7-137d-4a61-89c9-310e8ed1aee9.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is working fine.
So I closed the issue.
