### ISSUE TITLE
Add event page organizer and venue popup validation not proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1332]
![image](https://user-images.githubusercontent.com/121149500/218008627-430ab8ae-4e5a-4539-9095-919d249b9993.png)
![image](https://user-images.githubusercontent.com/121149500/218008687-7cdd14e7-b724-4d34-9ea7-f3b437400258.png)

On add event page in the venue and organizer popup the validation is displaying by default... If we do not enter and click on submit button then it should display validation message

**Comment by mistry-jignesh** [comment]
Verified this issue. 
Post an event page Organizer & Venue section.
Click on the "here" .
Not added details and click on the Add button. Here validation message is displayed.
Now closed the form.
Again open the same form.
Observed that by default validation message is display in the organizer & venue page.
Here issue is available.

![image](https://user-images.githubusercontent.com/75515088/234501056-6232445c-2f7e-43c3-b91c-ee2c222661c6.png)

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
It is working fine. Again open the same form then the validation message is not displayed.
So I closed.
