### ISSUE TITLE
Field editor displaying extra field when we edit or add 

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1333]
The field editor is displaying extra fields once we add them.

Steps
1. add a field without entering the name 
2. Enter a name in the title
3. Click on create a field and save changes it will display two fields one is blank and one is with a name with duplicate data like priority, type, etc.
![image](https://user-images.githubusercontent.com/121149500/218009157-b99886c8-2148-4321-a6c8-8dc46c5cca99.png)

**Comment by mistry-jignesh** [comment]
I verified this issue with mentioned steps.
If not add a field without entering the name and click on the save changes button.
Here validation message is displayed on the page. So here the issue is fixed.
So I closed the issue.
