### ISSUE TITLE
Settings all option field title should be capitalize

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1335]
In settings all field title's first letter should be capital

![image](https://user-images.githubusercontent.com/121149500/218009765-f1355bd8-8a57-4593-8a7a-09df481cd21b.png)
![image](https://user-images.githubusercontent.com/121149500/218009872-309cf8a0-fee0-4b87-9544-717c168c44d8.png)
![image](https://user-images.githubusercontent.com/121149500/218010262-597bf296-6368-4f91-8836-90a0a22aced1.png)

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
2nd & 3rd screenshot issues are fixed.
It is working fine. So I closed the issue.
