### ISSUE TITLE
Event listing Multi select category and type should display result

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1337]
![image](https://user-images.githubusercontent.com/121149500/218051388-03a6000b-f66b-43b4-aea8-4171f87401e2.png)
![image](https://user-images.githubusercontent.com/121149500/218051429-49fcedca-9a10-4f0d-bf99-9d0d83940b5d.png)

Event listing multi-select category and type should display the result .

**Comment by mistry-jignesh** [comment]
As per @ritakikani -It will verify for all selected categories and types, if the event has all categories and types both then only will list the event.So, this is working fine.

So I closed the issue.
