### ISSUE TITLE
Pending event unable to edit from dashboard

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1339]
![image](https://user-images.githubusercontent.com/121149500/219267889-fb4be307-abdd-4f72-98a4-f3296476d09e.png)

If an event is in a pending approval state then it is unable to edit.

**Comment by ritakikani** [comment]
This is not an issue cause we already have this setting to on/off.

![image](https://user-images.githubusercontent.com/25837982/233566307-ee360021-a01a-4dc4-a749-1fcf42a36241.png)

**Comment by mistry-jignesh** [comment]
After enabling the above option. This issue is working fine.
So I closed the issue.
