### ISSUE TITLE
Event summary page desing not proper 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1342]
Event summary page desing not proper .

User below shortcode.
[event_summary limit="5" featured="false" width="150px" align="right"]

![image](https://user-images.githubusercontent.com/75515088/219286764-fcf56fc5-0a35-451f-a68f-be3cb3db0199.png)

**Comment by kaushikpokal** [comment]
This is not a issue.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  - This issue will solve from theme side only.

So please check it @kaushikpokal .

**Comment by kaushikpokal** [comment]
This is not a issue 
because you can check you have add width in shortcode 150px so event box will be manager 150px width
and we will not set fixed height on event.
