### ISSUE TITLE
Shortcodes menu

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1346]
Shortcodes menu will shown up with following options

- Available shot codes (list of all shot code show)

**Comment by ritakikani** [comment]
This enhancement will reflect in all other addons which has shortcode.

**Comment by ritakikani** [comment]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/f43ed803-4404-4f1f-84d1-0e986248541f)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Right now below list are available in the shortcode menu.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/eeb4effa-d887-4cd5-9967-387725cb8e09)

As per @ritakikani - Once details are available for other addons then it will add. 
So I closed the issue.
