### ISSUE TITLE
Widgets in List

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1349]
Widgets should also be available in list format

**Comment by Priya-Goenka** [comment]
The event listing in the widgets should be available in the List Format.

**Comment by ritakikani** [comment]
This is added for widgets :

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/0fe562f8-6c92-494b-9a90-7064527d2248)


Design will look like this : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/e764e425-83f9-48cb-b189-457a76f39fe2)

**Comment by mistry-jignesh** [comment]
Now List view option is available in the  Widget.

It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/3894f3f8-129e-4589-b238-e091bae9a33d)

So I closed the issue.
