### ISSUE TITLE
Shop and Cart pages of woocommerce

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#135]
When there is no item in cart, it is showing button of "Return to shop"  and clicking on that button is redirecting us on shop page which is totally unneccessory.

https://staging-wpeventmanagerdemo.kinsta.cloud/shop/

![cart1](https://user-images.githubusercontent.com/49863477/63753223-f1ebb100-c8b2-11e9-8ccd-441974dabbbb.png)

![shop](https://user-images.githubusercontent.com/49863477/63753228-f7e19200-c8b2-11e9-9d04-2e78b556deba.png)

**Comment by ritakikani** [comment]
This issue is related to sell ticket addon.
