### ISSUE TITLE
 Single Organizer’s Details shortcode not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1351]
Single Organizer’s Details shortcode not working.

[event_single_organizer organizer_name="BHF" per_page=5 show_pagination=true]

![image](https://user-images.githubusercontent.com/75515088/220553513-8cd15eb4-0867-4ed5-8815-d3b030683df2.png)

**Comment by ritakikani** [comment]
@mistry-jignesh  this shortcode is not exist any where in plugin.This is wrong shortcode please inform to doc team to correct this mistake, The right shortcode is 'single_event_organizer'

**Comment by mistry-jignesh** [comment]
I have check this issue with the below shortcode.

[single_event_organizer  organizer_name="BHF" per_page=5  show_pagination=true]

But this shortcode is not working.

**Comment by ritakikani** [comment]
@mistry-jignesh , we do not have any attributes like per_page, organizer_name etc in single_event_organizer shortcode.

The right one has only one parameter in shortcode is "id" of event.

[single_event_organizer id="event_id"]

ex.[single_event_organizer id="370"]

**Comment by mistry-jignesh** [comment]
I verified this issue. This issue is working fine.
Need to use the below shortcode.
[single_event_organizer id="118"] 

Need an update in the documentation.

**Comment by mistry-jignesh** [comment]
Add the correct shortcode in the document. This issue is fixed.

https://wp-eventmanager.com/knowledge-base/organizers/

So I closed the issue.
