### ISSUE TITLE
Update screenshot for : Frontend Event Dashboard for Admin

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1352]
URL : https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

Update screenshot for : Frontend Event Dashboard for Admin

**Old Screenshot** 

![image](https://user-images.githubusercontent.com/75515088/220593730-57fcd460-7345-43c9-9bb6-3db4e5a105bd.png)

**New screenshot**  

![image](https://user-images.githubusercontent.com/75515088/220594068-e1d177a0-a8a2-4b95-87dc-5684d691924c.png)

URL :https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

**Frontend Event Dashboard for Organizer**

**Same for  :  How to edit the submitted event?**

**Comment by Prachetshi1991** [comment]
Content done 
https://docs.google.com/document/d/14r-k9Vz8sw0Fq6ewqz07D7YS6jQ7iLHk0Hg5jmXPimM/edit#

**Comment by mistry-jignesh** [comment]
I verified this issue. At Frontend Event Dashboard for Admin screenshots are updated.
It is working fine. So I closed the issue.
