### ISSUE TITLE
Update screenshot for  : How to edit the submitted event?

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1353]
URL  :  https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

**Old Screenshot** : 

![image](https://user-images.githubusercontent.com/75515088/220596209-86ef4352-be68-4755-84aa-25e59ffc9a9c.png)

**New screenshot**

![image](https://user-images.githubusercontent.com/75515088/220596565-c6398e02-63ce-4eb2-8161-edac5538a96e.png)

**Same issue with below page  :  How to delete the submitted event?**

**Comment by Prachetshi1991** [comment]
Content is done 
https://docs.google.com/document/d/1oUSbRVkps5DYdbIsZHVIKulc9aJAa39y2OWs727412o/edit#

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is fixed. 
So I closed the issue.
