### ISSUE TITLE
Recent Events Widget : Online event is display if added location

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1355]
Recent Events Widget : Online event is display if added location.

![image](https://user-images.githubusercontent.com/75515088/220608328-bb8a4b71-e291-4549-90b6-d5927b8605fe.png)

![image](https://user-images.githubusercontent.com/75515088/220608866-cbe3779f-e167-4a1d-8eb9-703306973688.png)

**Comment by ritakikani** [comment]
This issue resolve in previous issue please take latest and verify.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.
Now online event is not displayed.
It is working fine. So I closed the issue.
