### ISSUE TITLE
Setting - Event submission - Allow Pending Edits - If not enable option after that submission event is editing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1361]
Setting - Event submission - Allow Pending Edits -

 If not enable option after that submission event is editing.

![image](https://user-images.githubusercontent.com/75515088/221139960-8116a160-3355-4b26-ba5f-4718bf2ae2dd.png)

**Comment by ritakikani** [comment]
This is not an issue in latest version :

![image](https://user-images.githubusercontent.com/25837982/231374745-446caa63-7321-422f-9814-ab3b7ab6f2c8.png)


![image](https://user-images.githubusercontent.com/25837982/231374809-2fad841a-8eef-43a5-8cb3-4c73a92a78c9.png)

**Comment by mistry-jignesh** [comment]
I verified this issue. If not enable allow pending edit option then event is not editable.
 This option is working fine. So I closed the issue.
