### ISSUE TITLE
Some part not translated and if event location not added then it not show in event location section 

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1363]
**Some part not translated into German** and if event location not added then it not show in event location section 

https://www.kreativekurse.de/kurse/haut-und-substanz/

<img width="869" alt="Screenshot 2023-02-27 at 13 33 02" src="https://user-images.githubusercontent.com/15089059/221564977-555516cd-de05-444d-824e-82608d3891ad.png">

**Comment by ashokdudhat** [comment]
Also no translated in below filter.

<img width="1483" alt="Screenshot 2023-02-27 at 17 48 02" src="https://user-images.githubusercontent.com/15089059/221627111-c0c5f0b3-d44e-4328-bc22-0b89633ec330.png">

**Comment by ashokdudhat** [comment]
Watch Video

<img width="1332" alt="Screenshot 2023-02-27 at 19 06 44" src="https://user-images.githubusercontent.com/15089059/221646983-1f9532da-1615-4c0c-85be-eba77a829429.png">

**Comment by ritakikani** [comment]
@ashokdudhat sir, For the event filter, translation working fine with latest version.


![image](https://user-images.githubusercontent.com/25837982/226532270-e7b2d3aa-909c-4d16-9747-5cc4139b7d37.png)

**Comment by ritakikani** [comment]
For the rest of the text like Event Location and Event Tags, then this is not core plugin part, so we can raise the issue in particular addon for solve.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Here Event tag issue is open in the Event tag plugin addon.
Verified this issue is working fine.
