### ISSUE TITLE
Demo Server : A critical error on this website.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1368]
Demo Server : A critical error on this website.

Click on the any organizer then  page is not display &  critical error is display on the page.

![image](https://user-images.githubusercontent.com/75515088/226618746-28973983-6f37-4df9-ac79-b2ae0d614bfb.png)

**Comment by ritakikani** [comment]
Please open core related bug only in this directory.

**Comment by mistry-jignesh** [comment]
Now this issue is fixed in the new version. It is working fine.
Once plugin will release then available on the Demo server.
So I have closed the issue.
