### ISSUE TITLE
Demo server : Location text is display on the event detail page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1370]
Demo server : Location text is display on the event detail page.
First event is created with location details.
Now edit event &  event is selected online event option.
Here location text is display on the event detail page

![image](https://user-images.githubusercontent.com/75515088/226909363-351adb94-eef7-46ab-b3b3-c5799a1f1001.png)

**Comment by ritakikani** [comment]
This issue already resolve in version 3.1.34, please take latest and verify it again.

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
Location field proper data is displayed.
It is working fine. So I closed the issue.
