### ISSUE TITLE
Backend : Organizer section is not display proper 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1371]
Backend : Organizer section is not display proper .
![image](https://user-images.githubusercontent.com/75515088/228433091-13e03680-eb52-4e15-976d-5719dd210c75.png)

**Comment by kaushikpokal** [comment]
@ritakikani please add css for backend 

@media screen and (min-width: 783px){
    .post-type-event_organizer .widefat .column-_is_salesforce_crm_sync,
    .post-type-event_organizer .widefat .column-_is_hubspot_crm_syncm,
    .post-type-event_organizer .widefat .column-_is_constant_contact_sync,
    .post-type-event_organizer .widefat .column-_is_activecampaign_sync,
    .post-type-event_organizer .widefat .column-_is_sendinblue_sync,
    .post-type-event_organizer .widefat .column-is_mailchimp_sync{
        width: inherit;
    }
}

**Comment by mistry-jignesh** [comment]
Verified this issue at backend organizer side. Now it is display proper.

![image](https://user-images.githubusercontent.com/75515088/228437354-5d55c21d-b1b7-4469-a786-a529914716c0.png)

So I closed the issue.
