### ISSUE TITLE
Error on saving post while using classic editor

### ISSUE THREAD

**Issue by gawins** [wpeventmanager/wp-event-manager#1372]
WP Event Manager causes an error when not using gutenberg editor on saving event posts

Warning: Undefined variable $event_online in /home/httpd/vhosts/folder/folder/wp-content/plugins/wp-event-manager/admin/wp-event-manager-writepanels.php on line 1137
Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/folder/folder/wp-content/plugins/wp-event-manager/admin/wp-event-manager-writepanels.php:1137)

**Comment by ritakikani** [comment]
Hi @gawins ,  

we are sorry for the inconvenient, but this issue is already resolve for our next version 3.1.34.
