### ISSUE TITLE
Addons menu in WP Event Manager plugin image are not display properly

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1373]
Addons menu in WP Event Manager plugin image are not display properly

**Comment by ritakikani** [comment]
This issue resolve because of some changes of other bug.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.
Plugins images are displayed properly.
It is working fine. So I closed the issue.
