### ISSUE TITLE
How to select Multiple types/Category for event submission

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1377]
https://wp-eventmanager.com/knowledge-base/event-fields/

Now this functionality is available at Event Manager > Field editor selection > Event Form fields.

![image](https://user-images.githubusercontent.com/75515088/234182931-5a95f409-642c-4e1c-9743-08cb0ca8ae90.png)

Using WP Event Manager, you can add multiple categories to event submission form. By performing the below steps, each event can be classified into multiple categories.

- Go to Event Manager >>  Field editor selection > Event Form fields

- Select Term Multi-select option from the dropdown box,

- Click on the save changes button.

--------------------------------------------------------------------------------------------------------------------------------------------

Using WP Event Manager, you can add multiple types to event submission form. By performing the below steps, each event can be classified into multiple Types.

- Go to Event Manager >>  Field editor selection > Event Form fields

- Select Term Multi-select option from the dropdown box,

- Click on the save changes button.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1kpIibVGxB6X66RQNaw7zAmB6H5S5piBILMrxc0LX8BY/edit#

**Comment by wpemmarketing** [comment]
Content uploaded from my side
