### ISSUE TITLE
Shortcode issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1379]
I checked the below shortcode not working.

[events selected_ticket_price="paid"]
[events selected_ticket_price="free"]
[events per_page="12" show_ticket_prices="false"]
[events per_page="12" show_ticket_prices="true"]
[events ticket_prices="ticket_price_paid"]
[events ticket_prices="ticket_price_free"]

**Comment by ritakikani** [comment]
one setting is added for ticket price in event listing page.

![image](https://user-images.githubusercontent.com/25837982/234495503-231dfe88-5750-4851-ae7d-5acb0afbaf48.png)


If it will be disable then the ticket price filter and options related to ticket price in shortcode for [events] will not work else it will work either sell ticket installed or not.

**Comment by mistry-jignesh** [comment]
[events selected_ticket_price="paid"]
[events selected_ticket_price="free"]
