### ISSUE TITLE
If create one event then edit time event numbering is not proper

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1380]
https://user-images.githubusercontent.com/121149500/219553400-52fd807d-80e6-4124-93b5-11e72ac7c410.png

https://github.com/wpeventmanager/wp-event-manager-sell-tickets/issues/374

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
Ticket numbering is available properly. 
So I closed the issue.
