### ISSUE TITLE
 Unable to remove ticket from edit page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1384]
When I have click on the below icon then nothing is work .

Also for user information provide add tooltip .

https://user-images.githubusercontent.com/75515088/139068613-42833596-a2d9-4f27-b3d2-e0e2694e4336.png

https://github.com/wpeventmanager/wp-event-manager-sell-tickets/issues/229

**Comment by mistry-jignesh** [comment]
I verified this issue. Added ticket unable to delete.
So added a tooltip for user notifications.
Here I closed the issue.
