### ISSUE TITLE
Load more button not visible in the List/box layout when calendar addon installed

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1392]
Add below shortcode to the event listing page.

[events per_page="5" show_filters="false" orderby="title"]

Go to front end event listing page.

Click on the Calendar layout. Events are displayed in the calendar layout.

Click on the either List or box layout . Here Load more button is not visible.

Again refresh page then you can see the "Load more" button.

https://github.com/wpeventmanager/wp-event-manager-calendar/issues/134

**Comment by ritakikani** [comment]
Need to take calendar addon also to test this issue.

**Comment by mistry-jignesh** [comment]
I have taken core plugin version -3.1.35 with new calendar new version.
Load More button is available in the List/box properly.
This shortcode is working fine [events per_page="3" show_filters="false" orderby="title"].
So I closed the issue.
