### ISSUE TITLE
Need to update content and screenshot in knowlendgebage

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1393]
On this page : https://wp-eventmanager.com/knowledge-base/settings/

current SS in doc :  
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/795e30c5-f3b2-48e5-896d-f2f794db195a)

Actual SS as per latest plugin :  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/b6e71b52-d6ce-4af2-8e33-98255d346cb7)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/e3859ba4-1fb4-4542-ac1d-553d0a0739de)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/ef450bc4-4352-4232-9267-3a156ed435fd)

**Comment by ritakikani** [comment]
There is no brief explanation of all settings in knowledge base, Need to add description for all settings of core plugin.

General Setting tab :

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/292bd282-0db1-445d-a771-b7c412d46557)


Event listing Tab: 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/63a9383c-cf17-49a0-aba2-1b75133c564e)


Event submission Tab:

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/4f9e9b28-22fa-4dd7-85ce-247d311391b6)

Pages Tab:

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/f6b1e3b0-34c8-431b-a80d-6847fe7dc21f)

Date & Time Tab:

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/98ff23e2-5558-456f-bccc-8650677cc756)

**Comment by ritakikani** [comment]
Please remove "my registration" shortcode from shortcode list, because this is not core plugin shortcode, this is registration addon shortcode.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/78c65872-520d-4ed7-8bf4-70fcb1159d79)

**Comment by ritakikani** [comment]
Need to add shortcodes for organizer on this page : https://wp-eventmanager.com/knowledge-base/organizer-shortcode/

[single_event_organizer id="<event_id>"]

Please highlight this shortcode with screenshot same like other above shortcode:

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/ea27df99-2057-4869-bc90-4d0b6b434ebd)

**Comment by ritakikani** [comment]
Need to add venue shortcodes same like oragnizer shortcodes on this page : https://wp-eventmanager.com/knowledge-base/

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/cdeba704-0769-4cdc-821d-d3fbb550b10d)

**Comment by ritakikani** [comment]
Need to add below in page :  https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

Please remove below tab from all Screenshot in above page, because this is not a part of core plugin :   

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/c225e429-ee17-4879-9c34-4bd47d19f997)


Also mention below default organizer dashboard section which is on event dashboard page :    

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/15e50d3c-7c67-4b24-b92d-100bbf3e9833)

Also mention below default venue dashboard section which is on event dashboard page : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/4732efc6-6fe9-4f4a-96a3-a061441ada48)

**Comment by ritakikani** [comment]
Mention about event organizer and venue tab in this page : https://wp-eventmanager.com/knowledge-base/backend-event-dashboard/

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/e15ea38b-1957-43b5-8ed3-d6115ef4bd2c)

**Comment by ritakikani** [comment]
On this page need to change default page value :  https://wp-eventmanager.com/knowledge-base/the-event-dashboard/
default value for the page is 10 not 25.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/eb581ccb-26ee-4f49-a9d8-7d3ca880f691)

**Comment by ritakikani** [comment]
Need to update on this page :  https://wp-eventmanager.com/knowledge-base/past-events/

default value of 'order' attribute is "DESC" not "ASC"

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/6db5d608-64f8-4757-8bbf-fc437b35aa70)

**Comment by ritakikani** [comment]
Need to add below shortcode which is not listed for core plugin shortcode list :   

1. [event_register id="event_id"]
This will return registration form of selected event.

ex. 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/0693f184-6599-4134-9dcc-f274cbc59fb1)

result:
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/e84b8b39-9830-4605-8a89-f777c1c4fb9a)


2. [upcoming_events]

attributes : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/071b52a9-1388-4f36-a122-ed7ff9d2d277)

**Comment by ritakikani** [comment]
on this page need to change some content : https://wp-eventmanager.com/knowledge-base/the-single-event-listing/

please correct text, remove bold font.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/cb26e4af-8261-482a-9b59-c56e8394d6da)

**Comment by ritakikani** [comment]
Please update some attributes and value for page : https://wp-eventmanager.com/knowledge-base/the-event-listings/

**Comment by ritakikani** [comment]
Please also mention some where that user can also add organizer/venue at the time of event posting as shown in below screenshot.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/b6f7296a-9f0d-4df3-a8f5-3d5fa49f47b8)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/15eaa61e-a5c3-4f90-9580-3d0e61fe4256)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1eQQtofw7jO-kFxvu313QlFSu3IUAh2H2g3pndEV7vgc/edit#

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1xr6cIx9oYt6Qhu8PABX82nzpXETbXdY0Wi3C-cGhf1E/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1xr6cIx9oYt6Qhu8PABX82nzpXETbXdY0Wi3C-cGhf1E/edit#

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1uYidkI79qqO6U6MbM0OO6Wyf7nCvfgBkD2hKiv9WeK4/edit#

**Comment by ritakikani** [comment]
@Prachetshi1991 ,
Please read above all document, I found some changes and mark as red text to remove and green text to add.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1r4pDM4iIwtqaoAfjoowJ6rZIjDRG2MLBcSH4seq09is/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1HjG_sq7Dc5zAYT7ADN3yyYBXYslNgzZ6kaM304YMvjU/edit#

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1HjG_sq7Dc5zAYT7ADN3yyYBXYslNgzZ6kaM304YMvjU/edit#

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1HjG_sq7Dc5zAYT7ADN3yyYBXYslNgzZ6kaM304YMvjU/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1B56pGB6q6qOJZmygKX9oVBBl1JDt8afzxZlF05GOWj0/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1P7eyIKCGgReNMjoVyxM3LKIyBk0Kf_B4QswZOuvulAY/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1WZPn45yfyLAnazP39SDMloQ0S8JuTBK23kkYk_6T5Bg/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1RsVIHtFBwwFfUL20XObE2hf9B-0TgPNuY9Z6qVAztGQ/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1RsVIHtFBwwFfUL20XObE2hf9B-0TgPNuY9Z6qVAztGQ/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1-CPJVSA7e-wo2qkxurWcQ2MMjRJUavRy0RCvAmiDsR4/edit

**Comment by kaushikpokal** [comment]
**Venue Field**
https://docs.google.com/document/d/1GHQiAK_tNWiMiPgCfhfbF6by-I7yt-RQDb8wCJW_7JU/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
The screenshot and content are available on the live site.
So I closed the issue.
