### ISSUE TITLE
Field editor page is blank on admin side

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1399]
If there is disable option of organizer from "General Settings" "Enable Organizer" then field editor page is display blank at admin side.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

If disable organizer option from general setting then page is not displayed blank on admin side.
Also, disable both options from general setting then page is not displayed blank on admin side.

So I closed the issue.
