### ISSUE TITLE
Submitting listings requires an account

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#140]
When I clicked on "sign in" button displaying on submit event form, im getting redirected on woocommerce account page instead of login or registration form.

Please see these attached screenshots:

![submit1](https://user-images.githubusercontent.com/49863477/64819127-dddfc900-d5ad-11e9-8e92-60abc0a56993.png)
![submit2](https://user-images.githubusercontent.com/49863477/64819141-e2a47d00-d5ad-11e9-94b9-46b6904cd1be.png)
![submit3](https://user-images.githubusercontent.com/49863477/64819152-e932f480-d5ad-11e9-960a-55dfb59494b6.png)

**Comment by ritakikani** [comment]
Hi @sapnadudhat03 ,

You need to set login page url from admin side, Event Listings -> Settings -> Pages -> Login Page URL.
If login page url not set from admin side, then it will redirect on default wordpress login page.
