### ISSUE TITLE
Language Translation issue 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1400]
Language Translation issue in the core plugin.

**Comment by ritakikani** [comment]
Please provide screenshot.

**Comment by mistry-jignesh** [comment]
1. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/e8112bfa-90f2-4479-ae72-e72d1a07c018)

2. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/0dbbda32-6a88-40f7-81b3-942c99b96579)

3. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/b72cc688-0b5e-4f4a-bc3c-2764c69d13c0) 

4.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ad0b3916-ef8e-4991-bf66-a33ffd4ad979) 


5. 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d42ba6b2-38d9-4821-98a4-693d3abd6de8)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now it is working fine.
So I closed the issue.
