### ISSUE TITLE
Updated code in the documention

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1402]
For this knowledgebase article - https://wp-eventmanager.com/knowledge-base/fields-on-single-event-page/

I got this to work but line 17 is misleading .The line would be much clearer if it was: 

$event_FIELD_NAME=$post->_event_YOUR_CUSTOM_FIELD_NAME;For example, this line would be $event_country=$post->_event_country not $event_country=$post->_country

**Comment by Prachetshi1991** [comment]
This is not my job actually... i have not worked on the coding part.

**Comment by mistry-jignesh** [comment]
In the documentation what should I add . This code is available.
Please provide details about this code. @Priya-Goenka 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/87269b97-1b50-4e94-b57d-20e3a159ad6e)

**Comment by Priya-Goenka** [comment]
@mistry-jignesh 
Please Ask Rita for same.

**Comment by mistry-jignesh** [comment]
As per @Priya-Goenka : Aks about code for Rita.

**Comment by mistry-jignesh** [comment]
This code is available in the documentation .So I closed the issue.
