### ISSUE TITLE
In database registration email/URL title should be proper

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1403]
In database registration email/URL title should be proper.

like _event_registration_URL.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/772d8b43-1133-4a44-8ad6-31b6dc4f3fab)

**Comment by mistry-jignesh** [comment]
Same for other fields also.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ad8bdeae-b155-4f9b-abf9-3370a31e1f26)

**Comment by ritakikani** [comment]
New meta key : 
1. _registration = _event_registration_email
2. _submitting_key = _wpem_unique_key
3. _cancelled = _event_cancelled
4. _featured = _event_featured

For this version we will add these new key for safety purpose.Once this will be success then in next update we will remove the older meta keys.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now new meta key is added.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/c6c0fc15-5c16-4ff7-a430-ef6f626a2a15)

As per @ritakikani - This will be a success then in the next update we will remove the older meta keys.

So I closed the issue.
