### ISSUE TITLE
wp_posts table : Venue and organizer data are availavel in the table

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1405]
I have completed deleted WP Event Manager plugin from the enable backend setting.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7cb21492-1113-4045-ad6d-39870f8ca273)

Venue and organizer data are available in the wp_posts table.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/a83e3cbe-8a07-4136-a76e-081bd9af827d)

**Comment by mistry-jignesh** [comment]
wp_postmeta table :   Venue and organizer file URL is are available.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/14ee4fca-1099-41fb-acd4-e97fd4284aab)

**Comment by ritakikani** [comment]
@mistry-jignesh  I had test, there is no any data available in media library as well in data base after delete the plugin.
