### ISSUE TITLE
Expiry Date not working

### ISSUE THREAD

**Issue by Eff16** [wpeventmanager/wp-event-manager#1407]
If I set the expiry date to the end date of the event, the event won´t show up on the date the event is actually happening.
If I set the expiry date to the day after the event is happening, the event will be shown the whole day after the event is finished.

I just created a blank Site with a default wordpress theme, installed only the WP Event Manager Plugin and created one event.
As soon as I check ‘Hide expired listings in event archive/search’ in the plugin options, the event – that is happening and expiring today – is gone.

When I select the option ‘Listing expire on specific days below’ and set days to 1, I got the same problem.
FYI: I am adding events only through the backend and I set the expiry date to the same day the event is happing as you suggested in other posts.

My goal is that the event is not shown anymore after the day it is happing. Throughout the whole day the event is happing, it has to be shown in the event list.
This is not possible for me at the moment.

**Comment by ritakikani** [comment]
Hi @Eff16 , 

Please take v.3.1.35 from github and then you need to add below code in your theme functions.php file so, your event will be expire exact after event date and time.

`add_filter('wpem_expire_date_time', 'wpem_change_expire_date_time', 10, 2);
function wpem_change_expire_date_time($expire_date, $event){
	//this will return event expire date and time
	return get_event_end_date($event);
}`

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is fixed.
Adding above code event will be expire exact after event date and time.
So I closed the issue.
