### ISSUE TITLE
Past Event widget - Events display issue with orderby

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1412]
When I have selected order by as Title then events are not display title name wise.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d15357ba-3667-48d7-9154-b1c0a4d47325)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/4122ae22-6d11-4ab7-8146-54238a023b6a)

**Comment by ritakikani** [comment]
This is not an issue. Please first see that the first event named "Event -B" and second event named "Event-A" see the difference between this titles.If your event title are "Event-B" and "Event-A" then it will must order like "Event-A" and then "Event-B". But, your event title  is "Event -B", you added 1 space between "t" and "B".

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Order by option is working fine. 
So I closed the issue.
