### ISSUE TITLE
DIVI theme issue from customer

### ISSUE THREAD

**Issue by shb1899** [wpeventmanager/wp-event-manager#1413]
![2023-06-22 14_03_56-Divi Theme and WPEM doesn’t work _ WordPress org](https://github.com/wpeventmanager/wp-event-manager/assets/112388130/f59426bf-ff9e-48d1-bb63-439e82fade8d)

Please check into this and let me know if there are any updates regarding this.

https://wordpress.org/support/topic/divi-theme-and-wpem-doesnt-work-2/

**Comment by ritakikani** [comment]
@shb1899 , please explain that what is the issue?

**Comment by ritakikani** [comment]
@mistry-jignesh  this is not an issue of our plugin, head part always been used from the activated theme, he needs to customize or hide that head , caption from theme.
