### ISSUE TITLE
Need to add setting for email header

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1416]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/b6d4af20-48eb-421a-a232-c64835749853)

This will used for Registrations and Email addon to set header from name and email address for sender.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/c6b278a1-a09e-4731-a290-9a718251f1fc)

**Comment by mistry-jignesh** [comment]
Verified this issue. As below new setting is added for the email header.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/965c8835-791d-4178-9fa1-e81d162349b1)

So I closed the issue.
