### ISSUE TITLE
Bug when filtering using search_datetimes

### ISSUE THREAD

**Issue by ThomasRambaud** [wpeventmanager/wp-event-manager#1418]
Hello,

When using search_datetimes with values such as datetime_today, datetime_tomorrow etc. Filtering is ignored (meta_query is never given a value) because you have a code indentation issue starting line 122 in wp-event-manager-functions.php.

I made a PR a few months ago but you somehow ignored it :)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/1260302/7ecd2e4a-891a-4bea-83d1-bdbdf0ed924c)
should be 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/1260302/e302feb4-b0bb-4f71-9018-4d1ac71ecc5e)

**Comment by ritakikani** [comment]
Hello @ThomasRambaud , 

We improved code in our latest version, please verify for it.

**Comment by ThomasRambaud** [comment]
> Hello @ThomasRambaud ,
> 
> We improved code in our latest version, please verify for it.

Thank you @ritakikani, sounds solved
