### ISSUE TITLE
Events not showing up in Upcoming Event

### ISSUE THREAD

**Issue by echoots1** [wpeventmanager/wp-event-manager#1420]
After an update on 6/28/2023 version 3.1.34 to 3.1.34 my events are no longer showing up on our events page despite having some scheduled. My site https://calvarybcug.com/events

**Comment by ritakikani** [comment]
Hi @echoots1 , 

please open support ticket regarding this issue with your site temporary credential.

**Comment by ritakikani** [comment]
Hi @echoots1  , We release version 3.1.36, so please download and verify.We hope your issue would be resolve with new version.

**Comment by echoots1** [comment]
Yes this resolved the issue. Thank you!!

Sincerely,
Evan Hoots
________________________________

**Comment by mistry-jignesh** [comment]
I verified this issue with version 3.1.36. Events are showing up in upcoming events.
It is working fine .So I closed the issue.
