### ISSUE TITLE
Events not showing

### ISSUE THREAD

**Issue by szinserBSO** [wpeventmanager/wp-event-manager#1421]
My events are not showing using a shortcode on my homepage here: [https://www.bsomusic.org/](https://www.bsomusic.org/)

they should appear immediately below my featured slider and I have many events scheduled on the backend that were showing before yesterday, when updates were run

**Comment by ritakikani** [comment]
Hi @szinserBSO ,

please open support ticket regarding this issue with your site temporary credential.

**Comment by szinserBSO** [comment]
@ritakikani Thank you for the information.  I have tried to open a ticket but have no access, no username is found and I have no credentials in the system, the plugin predates my time at this org so Im not sure if our credential expired

**Comment by ritakikani** [comment]
Hi @szinserBSO ,  We release version 3.1.36, so please download and verify.We hope your issue would be resolve with new version.

**Comment by mistry-jignesh** [comment]
Our Dev team has provided an update for this issue. But still, there is no reply from the client.
Now I closed the issue.
