### ISSUE TITLE
Need to write documentation for below new feature

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1422]
1. Widgets are now available in the list format.
 We have to update in documentation that User would be able to set widget design as per they required like box-view or line-layout.
They can change it from Appearance -> Widget -> choose event widget

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/4c7d1834-6221-4aba-83d5-f57426ab46fe)

2. Shortcodes of each addon can now be displayed in a list form.
User can get all shortcodes of WP Event Manager plugin and it's addon from their own site:
Go to admin dashboard -> Event Manager -> Shortcodes

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/2d3b3280-dd05-4c26-8ff4-db5bfda21e6e)

3. Email field type added in the field editor.
New field type is added for form-field editor, so user can set input email type in their form.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/a0b86291-83a9-46b2-bd7c-f2ad9739f4eb)

4. Added setting for email header in the general tab.
This would be used in email sending for WP Event Manager to set header of email.
Email Name and Email Address field is added in Event Manager -> Settings -> General

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/d5c8843f-17e9-4596-bc40-323b5befb708)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/105Zpdp8ZAJXJrI2MLthIjQ0FEiiutybEuVr67DxTRjw/edit

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/11YV_pc0IkHOLoi8VvSZukT9UYj3Pr-MIhCmLmXUHoIo/edit

**Comment by mistry-jignesh** [comment]
This issue is fixed. 
Content is available on the KB pages.
So I closed the issue.
