### ISSUE TITLE
Need to prepare documention for event will expire exact after the event date and time

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1423]
Need to prepare documentation for the expiry event on time.

For that need to add below code in your theme functions.php file so, your event will expire exact after the event date and time.

add_filter('wpem_expire_date_time', 'wpem_change_expire_date_time', 10, 2);
function wpem_change_expire_date_time($expire_date, $event){
//this will return event expire date and time
return get_event_end_date($event);
}

add_filter('wpem_set_current_expire_time', 'get_current_date_time', 10, 2);
function get_current_date_time($expire_date, $event){
//this will return your current date and time
// pass your timezone string here
date_default_timezone_set('America/Los_Angeles');
return date("Y-m-d H:i:s");
}

**Comment by ritakikani** [comment]
duplicate of this : https://github.com/wpeventmanager/wp-event-manager/issues/1449

**Comment by mistry-jignesh** [comment]
This issue is duplicated with #1449.
So I closed this issue.
