### ISSUE TITLE
Need to improve grammatical errors in general settings tab.

### ISSUE THREAD

**Issue by kaushikpokal** [wpeventmanager/wp-event-manager#1428]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/83581741/f868fcc8-3b37-42ce-adbd-c16b09720405)

**Comment by Prachetshi1991** [comment]
Google API key: If you are using Google Maps for your events then you will need the API key to retrieve the location details for your event listings. You can obtain the Google API key from the Google Maps API developer site. 

From (name): If you are handling registrations and emails then the sender's name will appear in the outgoing WP Event Manager emails. 
From (address): If you are handling registrations and emails then the sender's email address will appear in the outgoing WP Event Manager emails.

**Comment by kaushikpokal** [comment]
@mistry-jignesh  Rita says above screenshot content already proper we had taken in woocommerce. please do not change this content and close this issue.

**Comment by Prachetshi1991** [comment]
The screen shot content has multiple grammatical errors... there is nothing called sender name it should be sender's name..  i have not made any technical changes. i would still suggest the changes as i have kept the meaning intact.

**Comment by krinaydhanani** [comment]
If you are going to deal with event registrations or emails then you need the sender's name will appear in outgoing WP Event Manager emails.

**Comment by Prachetshi1991** [comment]
Google API key: If you are using Google Maps for your events then you will need the API key to retrieve the location details for your event listings. You can obtain the Google API key from the Google Maps API developer site.

From (name): If you are going to deal with registrations and emails then the sender's name usually appears in the outgoing WP Event Manager emails. You can type the sender's name here. 
From (address): If you are going to deal with registrations and emails then the sender's email address usually appears in the outgoing WP Event Manager emails. You can type the sender's email address here. 

Please take the above text as it is verified by Jignesh bhai @kaushikpokal

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/11YV_pc0IkHOLoi8VvSZukT9UYj3Pr-MIhCmLmXUHoIo/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Google map API key option old content is display.
Need to correct it.
