### ISSUE TITLE
Event Listings for users

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#143]
It is not displaying the **total number of event posts/listings** submitted by specific users in users list as u can see in below-attached screenshot. There are many posts for those users (sapna, sapna123, sapnapatel361991) added in user list.

![posts](https://user-images.githubusercontent.com/49863477/64851091-fc2ddf00-d616-11e9-827b-4187d6d2afa1.png)

**Comment by ritakikani** [comment]
Hi,

To display events on user page, need to add filters in functions.php file of theme : 

` 
/*
* Add Event Column 
*/
function users_events_column( $cols ) {
	$cols['user_events'] = 'Events';   
	return $cols;
}
add_filter( 'manage_users_columns', 'users_events_column' );

/*
* Print Event Column Value  
*/ 
function user_events_column_value( $value, $column_name, $id ) {
	if( $column_name == 'user_events' ) {
	  global $wpdb;
	  $count = (int) $wpdb->get_var( $wpdb->prepare(
		"SELECT COUNT(ID) FROM $wpdb->posts WHERE 
		 post_type = 'event_listing' AND post_status = 'publish' AND post_author = %d",
		 $id
	  ) );
	  if($count>0)
		$count = '<a href="edit.php?post_type=event_listing&author='.$id.'" >'.$count.'</a>';
	  return $count;
	}
}
add_filter( 'manage_users_custom_column', 'user_events_column_value', 10, 3 );
`
