### ISSUE TITLE
Description field disappearing when completing other fields on Checkout (Loom Video Link)

### ISSUE THREAD

**Issue by genowales** [wpeventmanager/wp-event-manager#1433]
https://www.loom.com/share/920aa414c798453b90647e44f6f4a33e?sid=c2e2a01e-6b63-4968-8a51-e9dfc185cba7

**Comment by ritakikani** [comment]
Hello @genowales ,
 
I had seen the video, this is issue from registration addon, so will check and resolve this in registration addon. So I am transferring this issue in registration addon.

**Comment by genowales** [comment]
Thank you Rita

**Comment by ritakikani** [comment]
@genowales , your issue is fixed in sell ticket plugin, we will release it soon. But, if you want to resolve it in your site then you need to add below css in your "wp-content\plugins\wp-event-manager-sell-tickets\assets\css\frontend.css" and "wp-content\plugins\wp-event-manager-sell-tickets\assets\css\frontend.min.css" at the end of the both file.

`.description {
  display: contents !important;
}`

**Comment by genowales** [comment]
This worked perfectly - thank you



 <https://www.creative-services.ltd.uk/>	
Gene Thompson
Managing Director | Creative Services Limited
 
M 07949 331763 | P 029 2115 0013
E ***@***.*** ***@***.***>
 
65 Regent Street | Treorchy | CF42 6PN
www.creative-services.ltd.uk <http://www.creative-services.ltd.uk/>	
 <https://www.facebook.com/creativeserviceslimited>	
 
 <https://www.linkedin.com/in/creativeservicesltd/>
 <https://www.creative-services.ltd.uk/low-cost-website-solutions-for-business/>
All e-mails are checked for known viruses by our anti-virus system and Creative Services accepts no responsibility once e-mails and attachments leave our PCs. If this transmission reaches you in error, please inform us and delete it from your system. It may contain confidential or privileged information, and any recipients other than those to whom it is addressed must not copy, distribute or take action in reliance on it. Any of the statements or comments made in transmissions should be regarded as personal and not necessarily those of Creative Services, any constituent part or connected body.

**Comment by mistry-jignesh** [comment]
A client has informed that this issue is working fine.
Also, I have verified this issue. This issue is fixed.
So I closed the issue.
