### ISSUE TITLE
ticket selection not showing up

### ISSUE THREAD

**Issue by lrichards31** [wpeventmanager/wp-event-manager#1436]
the ticket selection is not showing up for customers to select their ticket option.

**Comment by ritakikani** [comment]
Hi @lrichards31 , 

Could you please explain in brief that where you want to show ticket option in submit event form? and are you talking about only org plugin ticket feature or you are talking about sell ticket addon ticket option?

Thank you.

**Comment by mistry-jignesh** [comment]
Still, a client has not provided an update on this issue. 
So I closed this issue.
