### ISSUE TITLE
rest api features not appearing

### ISSUE THREAD

**Issue by lrichards31** [wpeventmanager/wp-event-manager#1437]
I just downloaded rest api 1.0.2 then upgraded to 1.0.3.  The rest API function does not appear anywhere on my settings for me to access it.

**Comment by ritakikani** [comment]
Hi @lrichards31 ,

First I would like to inform you that if you want to use our Rest Api plugin, you must need our core plugin "WP Event Manager" latest version on your wordpress installation. 
You will get rest api menu as shown in below screenshot : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/244743db-6d72-4e2a-a73a-f9aef56f0e65)

If you have still issue, then please open support ticket, our support team will guide you and resolve your issue.

You can create ticket from here  if you are paid user : https://support.wp-eventmanager.com/portal/en/signin

Thank you.

**Comment by mistry-jignesh** [comment]
This issue is related to Rest API. So Here I closed the issue.
Open this issue in the Rest API.
