### ISSUE TITLE
QR Code not appearing on ticket: Image not found or type unknown error

### ISSUE THREAD

**Issue by databell** [wpeventmanager/wp-event-manager#1439]
Not sure if I just made an error but I've got my ticket PDF created but the image where the QR code is supposed to appear is broken. Getting an "Image not found or type unknown error" in it's place. Is there a bug here?

**Comment by ritakikani** [comment]
Hi @databell , this is issue from sell ticket so please open ticket on our support portal : https://support.wp-eventmanager.com/portal/en/signin

We had tested our plugin, we didnot found any issue which you mention, so our support team will help you and resolve you issue once you create ticket.

Thank you.

**Comment by databell** [comment]
I can't create a support ticket. My login no longer works even though I never changed it.

**Comment by mistry-jignesh** [comment]
@databell , you can chat with support team for this issue and provide required detail to them.They will help you.

Thank you.

**Comment by mistry-jignesh** [comment]
This issue is related to sell ticket. So I closed the issue here.
