### ISSUE TITLE
Ticket Options : Paid/Free

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#144]
In the backend add event form:

There is an option of "**Ticket Options : Yes / No**" in backend add event form. The **price** field is visible for **free** ticket option too. 

**Price field should be visible if I select Paid ticket option only.** 

![ticketoptions](https://user-images.githubusercontent.com/49863477/64851846-8296f080-d618-11e9-90b9-00d9de4336ff.png)

**Comment by krinaydhanani** [comment]
It's working fine.
