### ISSUE TITLE
Duplicate event change start & end date then expired date is not set

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1440]
Duplicate event change start & end date then an expired date is not set.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/fd0a5ad2-7e91-4363-8c31-e078af4770f6)

**Comment by ritakikani** [comment]
@mistry-jignesh , 

I does not found any issue, you mention above, in current version. Please see the below screenshot.

![Screenshot](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/f6a95187-95d8-4a25-b337-3845bf340efb)

NOTE : 
 If you have event expiry date in main event or not, but once you duplicate the event, then the expire date for the duplicated event will be the same as the event end date.

**Comment by mistry-jignesh** [comment]
I have verified this issue on the staging server. 
Duplicate event change start & end date then an expired date is set properly.
It is working fine. So I closed the issue.
