### ISSUE TITLE
Field editor : Change placeholder values then post an event page value not change

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1441]
Field editor: Field name: Online Event

Change the value in the placeholder From Yes | No to Y | N.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/845a2cbd-0b9a-4263-9893-d2f5c13542ee)

Now go to front end. 

Post an event page

Click on the Y or N check box then nothing is work.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/94ac88f0-986c-467a-aa87-b763e0d052cd)

**Comment by ritakikani** [comment]
This is not an issue, because if you change the value of any option then that new value will saved in your database post meta_key, and for the settings of online/offline event, that condition is based on the default value added by our plugin only.
