### ISSUE TITLE
Field editor : Change date type to text type then text box should be clear

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1442]
Field editor : Change the date type to text type then text box should be clear.

1. First type of field is added Date.
2. Post an event page add a date value.
3. Details page also display date value.
4. Now change date type to text type .
5. Observed that post an event page display the date value.
6. Here text box should be display clear.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/f5577109-bf1c-4f39-9f3e-7780d12066fb)

**Comment by ritakikani** [comment]
This should not be clear because you already enter value as date.This is not a bug.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  : This should not be clear because you already enter the value as a date. Because you are changing field type only not post meta_key.
So I closed the issue.
