### ISSUE TITLE
add filter to change image alt-text

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1443]
add filter to change image alt-text for event banner

**Comment by ritakikani** [comment]
@mistry-jignesh , this is the function which need to write in theme functions.php file to change the single event banner alt text : 

`add_filter('display_event_alt_text', 'set_event_alt_text', 10, 2);
function set_event_alt_text($alt_text, $post){
	return 'YOUR_ALT_TEXT';
}`

**Comment by mistry-jignesh** [comment]
I verified this issue . Now this issue is fixed.

alt-text is available.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d386ad63-0410-4601-a551-c62267813192)

So I closed the issue.
