### ISSUE TITLE
en-gb.po has incorrect language

### ISSUE THREAD

**Issue by alexfurr** [wpeventmanager/wp-event-manager#1444]
en-gb.po file seems to be wrong. Should be English, but multiple other languages have crept in.

Example:
msgstr on Lines 127, 132, 137
They are in French, Spanish and Chinese respectively.

Can you check with your language team and fix please thanks!

**Comment by ritakikani** [comment]
Hi @alexfurr ,

For the version 3.1.36, you can use these attached files for translation. If you are using other version then please let us know so I can provide you for that.
These are machine translated files, so if you found any wrong translation then please update in .po file and provide us that, We will give you .mo file based on that file.

 If you have other query then please let us know we will help you to resolve your issue.

Thank you.

[wp-event-manager-en_GB.zip](https://github.com/wpeventmanager/wp-event-manager/files/12076189/wp-event-manager-en_GB.zip)

**Comment by mistry-jignesh** [comment]
Our Dev team has provided steps for the issue,
Please follow the instruction, So this issue will fix. 
So now  I closed the issue.
