### ISSUE TITLE
Function get_venue_description() returns plain text instead of formatted html

### ISSUE THREAD

**Issue by peteger** [wpeventmanager/wp-event-manager#1446]
We found out that when using get_venue_description() in the theme file, it returns plain text instead of formatted html.

This happens when new content to the Venue description is added or changed. It works fine for old content saved with an older version of WP Event Manager.

Tested with the latest 3.1.36 and 3.1.37 (from Git Hub) and also with version 3.1.34.

Steps to reproduce:

1) Add content-single-event_venue.php into theme/wp-event-manager/venue folder
2) Add the following line: `<div><?php printf(__('%s', 'wp-event-manager'), get_venue_description($venue)); ?></div>`
3) Add a new Venue and add formatted text to the Venue description
4) Display the venue on the front end - the description text is returned as plain text not as formatted text

**Comment by ritakikani** [comment]
Hi @peteger ,

This is the wordpress functionality that if you simply print any post content, then will display like simple text(without formatting).
To print text with format you need use 'wpem_the_content' filter for our plugin. Please look on below code : 

Either ,

`<?php $content = apply_filters('wpem_the_content',$venue->post_content);
                        echo wp_kses_post( $content );?>`

Or 

`<div><?php
$content = apply_filters('wpem_the_content', get_venue_description($venue);
 printf(__('%s', 'wp-event-manager'), $content); ?></div>`

Please try one of above code.

Thank you.

**Comment by peteger** [comment]
Thank you, @ritakikani, I can confirm it works fine with the first code option. 

Thanks for your help, much appreciated.
