### ISSUE TITLE
change action name due to conflict with google recaptcha plugin

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1447]
Remove recaptcha from Organizer page

I would like to remove the recaptcha from the event organizer pages. There is no form so I am not sure why it is there. I know that in Settings there is a way to remove it from the organizer page. However, that also removes it from the form that appears when Contact Organizer is clicked. 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/f7a89de5-4431-4918-bac3-7433eb24b927)

https://wordpress.org/support/topic/remove-recaptcha-from-organizer-page/

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
Recaptcha is not available on the event organizer pages.
It is working properly. So I closed the issue.
