### ISSUE TITLE
wp_editor field not showing default placeholder

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1448]
Hello,

The wp_editor field doesn't return any default placeholder on the frontend when it has a value.
I guess you should modify the line 23 of the wp-editor.php file, under /template/form-fields/, to add the placeholder value when it is not empty. :)

**Comment by ritakikani** [comment]
Hi @designboxcom ,

First I would like to thank you for the suggestion given by you. For editor, we can add value in editor but we can not add placeholder. But, after discussion with team, realize that All users have different perspective for the default value and If we provide default value then it would be added in database for event_desciption (default text) if any one forget to add description.

But, if you want to add the default value as placeholder then you can override the template file "wp-editor-field.php" at your theme side and change into that file according to your way.

For override template file, you need to copy the file from "wp-content\plugins\wp-event-manager\templates\form-fields" with the file "wp-editor-field.php" and paste it in your "themes\<YOUR_THEME_FOLDER>\wp-event-manager\form-fields".

You can also read documentation for template file override from here : 
https://wp-eventmanager.com/knowledge-base/how-override-archive-template/

**Comment by mistry-jignesh** [comment]
As per the above steps, this issue will fix. 
So Now  I closed the issue

**Comment by designboxcom** [comment]
Well, thank you. THis is not really fixing the "issue" to customize the child theme to add a function that should be core into your plugin. It is possible to define a default placeholder for almost all other fields directly in the field editor but not foe the wp-editor itself.

You only have to modify the wp-editor-field.php file, under templates/form-fields/, and anyhow add the $field['placeholder'] in the function on the line 23.

Shouldn't have been that difficult and would have taken less time than writing the long answer on July 31 to explain me why it wasn't possible. Or do I miss something ?
