### ISSUE TITLE
New Suggestion: For Featured Events

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#145]
Currently, Featured events are not displaying at top of the page on event listings. 

**Featured events** submitted on the site should be displayed **at top** of the page (before non-featured events) on event listings. Otherwise, what is the meaning of the featured event? 

Featured means - event with highlighted background and displayed at the top.

**Comment by wpem-kishan** [comment]
add this shortcode and all featured event is comming in top of  the list.
[events orderby="featured" order="ASC"]

**Comment by sapnadudhat03** [comment]
@Priya-Goenka Can you please check once on test site for this using the shortcode given by Kishan and if it is working fine then make a new doc of this.

**Comment by krinaydhanani** [comment]
It's working fine after adding a short code.

**Comment by sapnadudhat03** [comment]
@Priya-Goenka You can make a doc of this or add this shortcode in related doc.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/the-event-listings/#articleTOC_2

**Comment by sapnadudhat03** [comment]
Done.
