### ISSUE TITLE
Org thread issue : Event with startdate before startdate of range in shortcode not displayed

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1450]
https://wordpress.org/support/topic/event-with-startdate-before-startdate-of-range-in-shortcode-not-displayed/

I noticed that events (multiple days) that have a start date set on for example the 19th of july and an enddate of the 23th of july will not appear in this shortcode date selection: “selected_datetime=”20-07-2023,31-12-2023″

I know this worked a while ago.

When the start date is the 20th or later it does show up but the moment I set the date to an earlier date as the start of the selected datetime range it is excluded from the results.

**Comment by mistry-jignesh** [comment]
I have verified this below shortcode. It is working fine.


![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ab8baa0b-0681-4fa2-bc0f-afe70aa727fb)

[events per_page="3"  selected_datetime="08-07-2023,31-08-2023"]


![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/71aa7aa9-ee37-41cc-b3ea-975e748875df)
