### ISSUE TITLE
Customize permalink

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1451]
If I want to change the permalink structure of single event page or category or type slug, then there should be a filter through which I can edit the permalink for it. Definitely I can edit it from permalink settings of wordpress but if I want to leave it blank for event page then by default it will take "event" in single event page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/6968cdb2-8a57-4ba2-98f3-b58fad6c71cf)

https://wordpress.org/support/topic/how-can-i-remove-permalink/

**Comment by ritakikani** [comment]
We need to add below filter in theme functions.php file to set default custom permalink for event single page :

`add_filter('wpem_set_event_permalinks', 'wpem_set_event_permalink');
function wpem_set_event_permalink($permalinks){
	$permalinks['event_rewrite_slug'] = 'DEFAULT_VALUE';
	return $permalinks;
}`

**Comment by ritakikani** [comment]
To reset the permalink with the blank (remove "event" from single event page slug), we need to add below code in our theme functions.php file to achieve the functionality which user wants to do.

We need to add below filter in functions.php to remove the slug from the permalink:

add_filter( 'post_type_link', 'wpem_remove_slug_event_listing_slug', 10, 3 );
function wpem_remove_slug_event_listing_slug( $post_link, $post, $leavename ) {
    if ( 'event_listing' != $post->post_type || 'publish' != $post->post_status ) {
        return $post_link;
    }
    $post_link = str_replace( '/' . $post->post_type . '/', '/', $post_link );
    return $post_link;
}

Just removing the slug isn't enough. Because after applying above filter, we'll get a 404 page because WordPress only expects posts and pages to behave this way. So, we'll also need to add below action in our functions.php file :

function wpem_parse_request( $query ) {
    if ( ! $query->is_main_query() || 2 != count( $query->query ) || ! isset( $query->query['page'] ) ) {
        return;
    }
    if ( ! empty( $query->query['name'] ) ) {
        $query->set( 'post_type', array( 'post', 'event_listing', 'page' ) );
    }
}
add_action( 'pre_get_posts', 'wpem_parse_request' );

Now, we have to  refresh your permalinks from our wordpress backend Settings tab.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine
Now change the permalink structure to is working fine.
So I closed the issue.
