### ISSUE TITLE
Need to add new attribute for shortcode

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1455]
One new attribute is added for below shortcodes to change the title of the event list.

title = "Title_String"

ex. [events title="Event List"]  (Note : Default value would be "Events")
[past_events title="Past Event List"] (Note : Default value would be "Past Events")
[upcoming_event title="Upcoming Event List"] (Note : Default value would be "Upcoming Events")

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/0835de09-d23b-41d7-998b-2217cc73a89e)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1P7eyIKCGgReNMjoVyxM3LKIyBk0Kf_B4QswZOuvulAY/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed. 
New attribute are available on the KB page in the Event listing page.
So I closed the issue.
