### ISSUE TITLE
Can’t change Registration email/URL

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1457]
After updating the WP Event Manager Plugin, all my registration links defaulted to my email address instead of the registration link on all my events. I had to do a temporary fix of adding my own button within the content of the event.

When I go into the “Event Data” section and try to change “Registration email/URL:” it will not save. It just goes back to showing my email address.

https://wordpress.org/support/topic/i-cant-change-registration-email-url/

**Comment by mistry-jignesh** [comment]
verified this issue. When I updated field Registration email/URL then Here added value is save .
But Event detail page not display Registration email/URL field value.
