### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1460]
URL :  https://wp-eventmanager.com/knowledge-base/install-wp-event-manager/

Title :  Installing the core plugin manually from the Backend 

**Old screenshot**  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/0f28652c-a778-47b1-9b05-0fa6b5b6592a)

**New Screenshot**

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/2424db2d-c27b-4b3e-a0e1-66cb98217bd1)

**Comment by ashokdudhat** [comment]
please do not show our compettitor inside image

**Comment by ashokdudhat** [comment]
new screenshot is still not correct.. bcz of our competitor show @kaushikpokal

**Comment by mistry-jignesh** [comment]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ab18b184-ca8b-4e87-971c-543a937ac9c3)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now the screenshot is updated.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/38aec36c-ff19-411e-8f58-7d6548d7d5c5)

This issue is fixed. So I closed the issue.
