### ISSUE TITLE
Need to add steps wise screenshot for install Premium Add-ons

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1461]
URL: https://wp-eventmanager.com/knowledge-base/install-wp-event-manager/

Need to add a steps-wise screenshot for the install addon.
 
Here only 2 images are available for the installation process.

So Add images steps-wise. So users can get an idea of how to install a plugin.

Old Screenshot :  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/6caf14c6-98b8-41ee-a96e-d5af11ff1559)

**Comment by kaushikpokal** [comment]
@mistry-jignesh  This is not an issue because other all steps are very basic so no need to add images.

**Comment by mistry-jignesh** [comment]
@kaushikpokal : This is not an issue because other all steps are very basic.So no need to add images.
Now I closed the issue.
