### ISSUE TITLE
Event Form Detail page screenshot is old

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1463]
URL : https://wp-eventmanager.com/knowledge-base/adding-your-first-event/

Title Name :  Event Form Detail

Old screenshot  : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/3091c5ba-6483-41f5-89b3-22462bb42da3)

New screenshot : 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/2ff2e7ba-3355-4b27-ae99-bfd13d4ddac4)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1a4_zpKHEB0UIcpaip_opHRu6XLyb4IpuCvjGiYnqMuc/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
A new screenshot is available on the KB pages.
So I closed the issue.
