### ISSUE TITLE
Need to explain with steps and screenshot for the how to change field priority topic

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1466]
**Event form fields** :  Need to explain with steps and screenshots the how to change the field priority topic.

URL : https://wp-eventmanager.com/knowledge-base/event-fields/

Title Name: How to change the field priority?

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1kpIibVGxB6X66RQNaw7zAmB6H5S5piBILMrxc0LX8BY/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now new screenshots and steps are available on the KB pages in the Event Fields section.
This issue is fixed.So I closed the issue.
