### ISSUE TITLE
Updated title name in the organizer section 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1467]
URL : https://wp-eventmanager.com/knowledge-base/organizer-fields/

**Old title name:**  How to add a field to the Event Submission Form?

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/368ff5df-7b9b-4215-82df-e3572de13f2e)

**Correct title Name**:  How to add a field to the Organizer Submission Form?

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1d4ZbZi76Kn1b7sY14wbiGELtbxRtkA10fBcnSTKXwM0/edit

**Comment by mistry-jignesh** [comment]
I have updated the title name. Now this issue is fixed.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/64002a1f-d39f-43e3-863a-32c5c633739c)

So I closed the issue.
