### ISSUE TITLE
For organizer  : Explain with steps and screenshot for the how to change field priority topic

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1468]
For organizer: Explain with steps and screenshots for the how to change the field priority topic.

URL :  https://wp-eventmanager.com/knowledge-base/organizer-fields/

Title Name : How to change the field priority?

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1d4ZbZi76Kn1b7sY14wbiGELtbxRtkA10fBcnSTKXwM0/edit#heading=h.7i6amihhledh

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
New screenshots and steps are available on the KB page in the Organizer field section.
So I closed the issue.
