### ISSUE TITLE
Need to update venue form field editor screenshot

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1470]
URL :  https://wp-eventmanager.com/knowledge-base/venue-fields/

Title Name:  Venue Fields

**Old screenshot**  :  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/f904353d-b23a-4492-8769-f6b30bbf804e)

**New screenshot**  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/28cd22de-fa6b-48f0-974f-caa9355c61be)

**Comment by kaushikpokal** [comment]
https://docs.google.com/document/d/1GHQiAK_tNWiMiPgCfhfbF6by-I7yt-RQDb8wCJW_7JU/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now new screenshot is updated on the KB.
This issue is fixed. So I closed the issue.
