### ISSUE TITLE
For venue : Explain with steps and screenshot for the how to change field priority topic

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1471]
For venue: Explain with steps and screenshots for the how to change field priority topic 

URL: https://wp-eventmanager.com/knowledge-base/venue-fields/

Title Name: How to change the field priority?

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1GHQiAK_tNWiMiPgCfhfbF6by-I7yt-RQDb8wCJW_7JU/edit

**Comment by mistry-jignesh** [comment]
Now this issue is fixed. It is working fine.
The screenshot and steps are changed. So I closed the issue.
