### ISSUE TITLE
Date & time and Pages tabs : All Screenshot are old 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1477]
URL : https://wp-eventmanager.com/knowledge-base/other-settings/

![Settings - WP-Event-Manager](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/8f3e08be-12d5-4b5a-849f-e2dd0445c591)

**Latest screenshot :** 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d2e7a054-1a9a-4f8f-b235-0690663727ec)

------------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/84105b9d-1b4c-490f-adb3-fbc41fa85b88)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1uYidkI79qqO6U6MbM0OO6Wyf7nCvfgBkD2hKiv9WeK4/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
Date & time and pages tabs screenshot are updated,
This issue is fixed. So I closed the issue.
