### ISSUE TITLE
Problem with apostrophes in field names.

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1478]
When I add extra fields containing apostrophes in the name (') in the field editor, no matter which type, they are not sanitized and, when returned, show a \ before the '

**Comment by mistry-jignesh** [comment]
I have verified this issue. I have added 2 fields using apostrophes.
Event details page shows the "\" symbol also added content is not saved in the field.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/92c51bf6-ab57-457f-9230-815e3220e2b6)
