### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1483]
https://github.com/Jacky-Y/vuls/blob/main/vul5.md

**Comment by Jacky-Y** [comment]
It's great to see the issue acknowledged and a fix already in place in the codebase.
I noticed that the fix hasn't been included in an official release yet. Considering the security implications of the vulnerability, I would kindly urge you to expedite the release process if possible. 
Thank you again for your prompt attention to this matter. Looking forward to the official release.

**Comment by patel-nimesh** [comment]
Now all things are working properly, So I am going to close this issue.
