### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by bungphe** [wpeventmanager/wp-event-manager#1484]
I use per_page like the code below, but it only shows 3 in 1 line. I want to display all 4 on 1 line, how do I do that?

`[events per_page="4" show_filters="false"  layout_type="box" featured="true" orderby="event_start_date" order="ASC/DESC"
show_categoies="false" show_event_types="false"
]`

**Comment by ritakikani** [comment]
Hi @bungphe ,

per_page attribute would be used to get total no. of events when you click on "Load more" button, this will not used to set design like if you pass per_page="4" then 4 column you will get in box-layout.

To achieve this functionality, we already provide filter, using that filter you can change the no. of column in your event listing page.
For that, you need to write below code in your theme functions.php file.

`function wpem_event_listing_column( $column ) {
	return '3';
}
add_filter('event_manager_event_wpem_column', 'wpem_event_listing_column');`

**Comment by ritakikani** [comment]
I did not get any confirmation from user since long so I am closing this issue.
