### ISSUE TITLE
Frontside : If we create event from frontside then type and category display as number

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager#1487]
If from frontside we create an event then in preview the given category and type is not displaying as text. It is displaying as number

![image](https://github.com/wpeventmanager/wp-event-manager/assets/121149500/3a2213c0-8568-4935-b375-b78283258571)

**Comment by ritakikani** [comment]
This issue would be resolve as the term selection issue resolved.  Admin : Field editor change in type display warning on edit event. #1485

**Comment by patel-nimesh** [comment]
Still facing the issue.

**Comment by patel-nimesh** [comment]
Now Event Type and Category look proper 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/121149500/2205677c-5216-498f-aa4c-9c56a5c7e343)
