### ISSUE TITLE
Issue in field-editor

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1493]
There was a client, who had problem in field-editor, he/she was not able to view/edit/update field-editor page at back-end side.

Client says : 
We need to get support from your team as there’s a fatal error on the Field Editor page after updating the plugin to the latest version.

![image (1)](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/113b4d6f-2627-4ba0-a393-bc1643abe980)

actually this is what we got in the debug log. which shows that there’s an issue getting the string in the array

we have a custom “select” field for time selection.
This is what we have for the “Options” field:
closed : Closed |0900 : 09.00 am |0930 : 09.30 am

![image (2)](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/9fbd29a4-7567-4593-be5c-52d931da5530)

we were able to fix this, if we replace the $options variable with the highlighted code, but after fixing this fatal error, we cannot save the changes on the Field Editor page.

**Comment by mistry-jignesh** [comment]
I have verified above issue using the steps mentioned. Now fatal error message issue is fixed.
Now it is saved properly at the backend. So I closed the issue.
