### ISSUE TITLE
wp_editor field not showing default placeholder - part 2

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1496]
In reference to [https://github.com/wpeventmanager/wp-event-manager/issues/1448](https://github.com/wpeventmanager/wp-event-manager/issues/1448); as long as it is not possible for me to reopen the issue.

The solution proposed is not really fixing the "issue". Customizing the child theme to add a function that should be core into your plugin is not a good logic. Beside this, it is already possible to define a default placeholder for almost all other fields directly in the field editor but not for the wp-editor itself. Sic.

To achieve this, you only have to modify the wp-editor-field.php file, under templates/form-fields/, and anyhow add the $field['placeholder'] in the function on the line 23.

Shouldn't have been that difficult and would have taken less time than writing the long answer on July 31 to explain me why it wasn't possible. Or do I miss something ?

**Comment by ritakikani** [comment]
Hi @designboxcom , You just need to add placeholder text in "Field Editor" at backend.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/b5092b7b-d2ef-4bc6-9832-97dba2ef7153)

**Comment by ritakikani** [comment]
This issue is resolve from our end, also does not get any updates from user-side, so I am closing this issue.
