### ISSUE TITLE
Event submissions from appearing in the site-wide search

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1500]
Event submissions from appearing in the site-wide search.

Client is using the default search function.

In the below image click on the read more button then post an event page appear.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ed35c653-56db-4cf8-969c-9c21deeb703b)

**Comment by ritakikani** [comment]
We can not control wordpress core functionality like site search, but we can add below code to achieve above functionality in out theme functions.php file.

`add_action('pre_get_posts','wp_event_submit_form_exclude_posts_from_search');
function wp_event_submit_form_exclude_posts_from_search( $query ){

    if( $query->is_main_query() && is_search() ){
         //Exclude posts by ID
         $post_ids = array(6); // Here you have to pass id of your page which you want to exclude from default search
         $query->set('post__not_in', $post_ids);
    }
}`

Here, in code $post_ids, you just have to pass the page Id of the page which you want to exclude from the site search result.

**Comment by mistry-jignesh** [comment]
I have added above code to the theme functions.php file. Pass the page ID of the page that I want to exclude from the site search result. This code is working fine.
So I closed the issue.
