### ISSUE TITLE
Event listing page : Calendar view should set default view with filter option

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1501]
https://github.com/wpeventmanager/wp-event-manager-calendar/issues/142

Event listing page : Calendar view should set default view with filter option

**Comment by mistry-jignesh** [comment]
I have verified this issue. For a default calendar view, I have use the below shortcode.
[events per_page="5"  layout_type="calendar"]
It is working fine. So I closed the issue.
