### ISSUE TITLE
Enhacement : Related events list

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1515]
We need to give shortcode for related events based on current open event.

**Comment by RHSRSK** [comment]
Shortcode for Related events are prepared [related_events post_id='']

@kaushikpokal Now we need to create template for related events.

**Comment by RHSRSK** [comment]
Related events are display on detail event page like this... Please check the below video 
https://github.com/user-attachments/assets/9ac0e141-505c-4396-9c18-eab12ebd3637

**Comment by mistry-jignesh** [comment]
I have checked the issue. Related events are displayed fine on the events listing page.
Also, shortcode is working fine.
[related_events post_id='10125']
So I closed the issue.
