### ISSUE TITLE
Action need to add for blank value validation in single event listing

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1522]
Action need to add for blank value validation in single event listing

**Comment by ritakikani** [comment]
This hook would be used to validate additional fields, like if user wants to hide the additional fields which has no value or blank.

For this need to add below code in theme functions.php file.

**Comment by mistry-jignesh** [comment]
I have verified this issue. As per Dev team this hook would be used to validate additional fields.
So I closed the issue.
