### ISSUE TITLE
Event Banner missing on single event page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1523]
If we have design our single event page or submit event page using elementor or any block editor plugin, then the event banner is not seen on the single event page , preview page of submit event page and on admin side all event page.

**Comment by ritakikani** [comment]
If user has elemtor and design all event plugin pages, using elementor then the event banner is stored as a post attachment, so we have to verify that the event banner is not store in post meta then we have to check for the event attachment to verify the event banner.

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Event banner is available on a single event page using elementor.
This is working fine. So I closed the issue.
