### ISSUE TITLE
Readme need to update

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1526]
Readme need to update.

Some links are not working and we have new packages.

<img width="740" alt="Screenshot 2023-10-05 at 09 02 46" src="https://github.com/wpeventmanager/wp-event-manager/assets/15089059/3838053e-ff91-4859-9a5b-0c2f261926b2">

Please make perfect accordingly our competitor :  https://wordpress.org/plugins/wp-event-solution/#description

Do not change current text but add missing one and correct wrong one..

**Comment by live-aamir** [comment]
@krinaydhanani provide the text content, logo and position to update the readme

**Comment by krinaydhanani** [comment]
This issue is fixed. I am going to close this issue.
