### ISSUE TITLE
image missing at installation process

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1527]
<img width="606" alt="Screenshot 2023-10-05 at 09 09 40" src="https://github.com/wpeventmanager/wp-event-manager/assets/15089059/c046e316-3bbd-46df-9dee-526ccf56a2b4">

**Comment by ritakikani** [comment]
@ashokdudhat sir, Video is already there.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/680b25c8-052e-452e-aed9-8be111d82f03)

**Comment by mistry-jignesh** [comment]
Currently, Live preview button is hidden. So this issue is unable to verify.
https://wordpress.org/plugins/wp-event-manager/

**Comment by live-aamir** [comment]
@ashokdudhat I have checked we cannot check this issue as wordpress has not showing the feature to test the plugin live as discussed with @krinaydhanani

**Comment by mistry-jignesh** [comment]
I have verified this issue on the Wordpress ORG site .Currently, Live preview button is hidden  & as per @live-aamir -  he has checked and cannot check this issue as wordpress has not showing the feature to test the plugin live as discussed with @krinaydhanani.

So I closed the issue.
