### ISSUE TITLE
Post an event page : Create a new organizer issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1528]
Post an event page 1st and 2nd time organizer added without issue.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/89f70dda-56d1-4f51-99ae-c6819b010497)

After adding 2 organizers continuing to try to add 3rd time organizer then unable to add an organizer on post an post-event page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d469cffb-cbdf-42b3-a554-0a016c558091)

**Comment by live-aamir** [comment]
@mistry-jignesh I have checked this is working fine. Below is the screenshot.
![Screenshot_12](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/94790d52-723b-49bd-8970-5278a6ee8a5f)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine.
So I closed the issue
