### ISSUE TITLE
Event Health guidelines options and settings.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1532]
We should provide health guideline options and settings for all events so the organiser can set guidelines as per settings.

**Options :** 

- Enable health guidelines for this event
- Face masks required
- Temperature will be checked at entrance
- Physical distance maintained event
- Event area sanitized before event
- Event is held outside
- Vaccination Required
- Other additional health guidelines " Custome text box " 

-------------

<img width="1487" alt="image" src="https://github.com/wpeventmanager/wp-event-manager/assets/35419531/87c397b7-67ef-4398-b623-62e4921b0e33">

**Comment by RHSRSK** [comment]
We can add this extra notes/guidelines with our field editor functionality. Please review the video.
https://github.com/user-attachments/assets/f4beef04-1cbd-40db-8fc7-3899c22567ad

**Comment by mistry-jignesh** [comment]
As per @RHSRSK : Extra notes/guidelines with our field editor functionality .

![image](https://github.com/user-attachments/assets/5f506b0f-d533-4f7f-8901-70f5ea74f3b1)


This issue is working with wp editor. So I closed the issue.
