### ISSUE TITLE
How to find country code for the online event

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#1541]
How to find country code for the online event

We have to ask details from the organiser

- City
- Country

For that we have to change in core plugin .. we have to make this mandatory fields and it can not delete from field editor too.

Once it done then from above value we will get country code and then our country base fee settings will work .

When we have multiple orginzer then whoever submitted event or connected organiser with event , country code will get from this organiser. It means we will take always first organiser country code for the fee settings.

Connection with :  
[#49](https://github.com/wpeventmanager/wp-event-manager-stripe-split-payment/issues/49)
[#54](https://github.com/wpeventmanager/wp-event-manager-stripe-split-payment/issues/54)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now on the submit organizer page **Organizer Country**  dropdown box is available.
User can select a country as per their need.
It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/b7c2490b-d4e5-40e3-bcbb-479fcf55266b)

So I closed the issue.
