### ISSUE TITLE
Backend :  Display the organizer & venue id in the tooltip 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1542]
Backend :  Display the organizer & venue ID in the tooltip. Same as Events.

**Events :**  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/e5d0b45d-894b-412d-b6eb-1d9dac35470b)

**Organizer & Venues**

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/99be37fa-862a-462b-8a04-b0083e9a13fb)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/59f134f6-24aa-48f5-a38d-78192325fc70)

**Comment by ritakikani** [comment]
@mistry-jignesh  in event, that page we design manually, while for organizer and venue, we used wordpress default cpt page.So this is wordpress core functionality, that we can not change.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  :In event, that page we design manually, while for organizer and venue, we used wordpress default cpt page.So this is wordpress core functionality, that we can not change .So I closed the issue.
