### ISSUE TITLE
Issue with hybrew character in event type or category

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1552]
If we have any hebrew character in event type or category then event listing page return critical error and list is not display.

https://wordpress.org/support/topic/events-wont-load-if-using-hebrew-in-event-type-names/

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now events are loading fine with Hebrew characters.
This issue is fixed. 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/df15a6d2-5b0d-44ea-84c2-381472a35385)

So I closed the issue.
