### ISSUE TITLE
Event Country field for event submission form 

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1554]
Need to add event country field when event is offline.

**Comment by mistry-jignesh** [comment]
On the front side, we are unable to update the online event.
It displays an error message on the page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/1c990bd0-5aee-422f-b0be-f5e62ddfec50)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
Now on the front side, we are to update the online event.
An error message issue is fixed.
So I closed the issue.
