### ISSUE TITLE
Change twitter icon

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1556]
Need to change twitter icon for our event listing page as twitter has change the icon

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/66336625-1517-4d98-8ed7-51ba84b78ce4)
Now new twitter icon is available. So I closed the issue.
