### ISSUE TITLE
Frontside :  On Post Event Page In Event Type display by default Value ehrn user is logout.

### ISSUE THREAD

**Issue by dhruvikathrotiya** [wpeventmanager/wp-event-manager#1557]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/136054608/8f3e0707-436a-4bd1-a7db-b899f9f3f6bf)

**Comment by ritakikani** [comment]
This is not a bug or issue but we are giving in code that if you have an term-multi-select then by default one option would be selected for loggedin and non-loggedin user, if any one want to remove default selection then we provide hooks for that.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  : This is not a bug or issue but we are giving in code that if you have an term-multi-select then by default one option would be selected for loggedin and non-loggedin user, if any one want to remove default selection then we provide hooks for that. so I closed the issue.
