### ISSUE TITLE
Fields editor adds \ before '

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1561]
There is a bug with the fields editor. Each time I edit and save a field, it adds a \ before evey ' of all fields on the event description page.
I need each time to edt and remove those \ from the database (phpmyadmin)

**Comment by live-aamir** [comment]
@designboxcom No such issue is found. Below is the screencast of the mentioned issue.

https://github.com/wpeventmanager/wp-event-manager/assets/49248762/5d2f1f4f-74f1-490e-a8f2-d16eb68945b0

**Comment by designboxcom** [comment]
OMG, more than a month and you didn't even understand the question. 
The problem is not to add a language field but when you add a ' (like n several foreign languages) in a field ! It will be escaped with a \ when you save !

**Comment by live-aamir** [comment]
@designboxcom this not just to add language field but any field. Explain your issue with screenshots or a screencast.
That would make the understanding of issue in better way.

**Comment by designboxcom** [comment]
Try to write, for example, l'accès (access in French) in a field. With the quote ( ' ). Check the event page and you'll notice the ' will be escaped with a \. I guess a kind of sanitization is needed in PHP for ' (quotes) and " (double quotes) !

**Comment by live-aamir** [comment]
@designboxcom Below is the screencast as per your comment. No such issue found.

https://github.com/wpeventmanager/wp-event-manager/assets/49248762/a1ac6ec9-b20c-4c80-bc70-444d2aab0a1c

**Comment by designboxcom** [comment]
Thank you.
Could you try in the description as well ?

**Comment by designboxcom** [comment]
I checked around and we were using an outdated customized WPEM template in our Child theme (before stripslashes were inserted). I apoligize for raising the issue back but everything works as it should. Thanks for your time and patience.
