### ISSUE TITLE
Code Improvements : 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1564]
<img width="575" alt="image" src="https://github.com/wpeventmanager/wp-event-manager/assets/35419531/b8c352ae-0604-464e-b740-4d1b2a608e15">

**Comment by live-aamir** [comment]
@vijayrathod245 I am assigning you as you are already working with same issue as discussed with @krinaydhanani

**Comment by live-aamir** [comment]
@krinaydhanani This issue is covered in https://github.com/wpeventmanager/wp-event-manager/issues/1571

**Comment by mistry-jignesh** [comment]
As per @live-aamir: This issue is covered in #1571.
It is working fine.So I closed the issue.
