### ISSUE TITLE
Order by name attribute is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1565]
The order-by **name** attribute is not working.

[events per_page="12" orderby="name" order="ASC"]

**Comment by live-aamir** [comment]
@mistry-jignesh The name parameter is related to slug name. So the the sorting would be on the basis of slug name, below are the screenshot and link form the wordpress codex.
![Screenshot_11](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/0af311c0-0fed-4aaa-b738-0a89a67eff59)


https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters

**Comment by mistry-jignesh** [comment]
As per @live-aamir : The name parameter is related to **slug name**. So the the sorting would be on the basis of **slug name**, above are the screenshot and link from the WordPress codex. So this is not an issue.
So I closed the issue.
