### ISSUE TITLE
Events Listing View Bug: Calendar

### ISSUE THREAD

**Issue by Logikly** [wpeventmanager/wp-event-manager#1568]
Option to disable specific listing views on different pages.

Let's say I use the event listing on /events and homepage and just want the box view for the homepage.

Actually, even if specify the default listing view as box on homepage, as soon as we select <s>list or</s> calendar view on /events page, it automatically change the view on homepage.

**Comment by Logikly** [comment]
Definitely a Calendar Add-On bug.

To replicate the issue:

Create 2 separate pages.

Page #1, add events listing shortcode with events layout_type="box"

Page #2, add events listing shortcode without a default layout.

Once pages created, select calendar view on Page #2 and go back to Page #1.

The default box layout type is gone and no way to get it back.

**Comment by ritakikani** [comment]
Hi @Logikly ,

Thank you for the report us the issue, we will resolve this issue in our upcoming version and release it as soon as possible.

**Comment by live-aamir** [comment]
@Logikly Found no such issue. I have attached below screencast.

https://github.com/wpeventmanager/wp-event-manager/assets/49248762/a148ba68-e613-48ec-9fa3-af964142fb16

**Comment by Logikly** [comment]
Confirming this bug persist with the latest WPEM version.

Tested with Shortcode and Event Listing widgets.

Event Calendar is Premium Add-On

Suggesting to Reopen this issue and label it as Bug

**Comment by live-aamir** [comment]
@Logikly we have already fixed it in our calander add on upcoming version.
