### ISSUE TITLE
event venue and organizer are mentioned separately in event dashboard

### ISSUE THREAD

**Issue by heebakhan37** [wpeventmanager/wp-event-manager#1570]
[wp-event-manager-plugin.pdf](https://github.com/wpeventmanager/wp-event-manager/files/13443765/wp-event-manager-plugin.pdf)
it's a design issue all user want there website to look clean and attractive 
check out pdf to understand the bug

**Comment by krinaydhanani** [comment]
Thank you for your suggestions As a plugin developing organisation right now we are working on developing plugin core functionality so we are not much focusing on design part. We will do in future thanks.
