### ISSUE TITLE
Make the country field NOT madatory and hide it ?

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1572]
How to make the new country field not mandatory and hide it from a form ?

**Comment by ritakikani** [comment]
Hi @designboxcom , 

To remove country field from the event form, you need to write below code in your child theme functions.php file :

add_filter('submit_event_form_fields', 'wpem_hide_country_field');
function wpem_hide_country_field($fields){
	// delete country field from event submit form
	unset($fields['event']['event_country']);
	
	return $fields;
}

Thank you.

**Comment by designboxcom** [comment]
Thank you very much Rita. Maybe, you could add this to the documentation as well.

**Comment by ritakikani** [comment]
@designboxcom  , Definitely, we will add this in documentation.

Thank you for the patience and report your query.

**Comment by designboxcom** [comment]
On the same topic, how to hide the country field from the Organizers registration form ?

**Comment by ritakikani** [comment]
Hi @designboxcom , To hide country field from your organizer form, you need to add filter same like above in your child/parent theme functions.php file : 

add_filter('submit_organizer_form_fields', 'wpem_hide_organizer_country_field');
function wpem_hide_organizer_country_field($fields){
// delete country field from organizer submit form
unset($fields['organizer']['organizer_country']);

return $fields;

}

Thank you.

**Comment by ritakikani** [comment]
As we doesnot get any reply, we considering this as resolved and closing this issue.
