### ISSUE TITLE
Enhacement : Review for Organizer

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1575]
We have to add review feature through which registered user of particular event will post review for that event organizer.
This would be beneficial for organizer to attract attendee for his future or next event.

**Comment by RHSRSK** [comment]
This features is from Event Review plugin.
https://github.com/wpeventmanager/wpem-event-review

**Comment by mistry-jignesh** [comment]
This issue is related to event review addon.So I closed the issue.
