### ISSUE TITLE
Without login : Click on the post an event page then message is missing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1576]
Without login : Click on the post an event page message is missing.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/d4d2b3de-b4b6-43f3-a80f-27f46132ae55)

**Below message should be display .**

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7a1c477c-f7ef-4fdf-bee0-e1c287a366ab)

**Comment by live-aamir** [comment]
@mistry-jignesh This is working fine. Below is the screenshot.
![Screenshot_13](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/2b732faf-277d-483d-8d16-97d0d0251efc)
