### ISSUE TITLE
Enhancement : Event News

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1579]
We have to provide feature for adding news of events, So organizer/admin can post news regarding event so user can read and get idea about event.

**Comment by RHSRSK** [comment]
As per discussion with @ritakikani  Need to develop this after discussion.

**Comment by RHSRSK** [comment]
We can add this feature with our field editor functionality as per shown in below video

https://github.com/user-attachments/assets/af879534-2c74-48cd-9e28-083b974f519d

**Comment by mistry-jignesh** [comment]
As per @RHSRSK : This functionality is available in our field editor functionality.
This issue is working fine. So I closed the issue.

![image](https://github.com/user-attachments/assets/6a24d994-2300-4687-b192-f0b7c9eac0bd)
