### ISSUE TITLE
Secuirity issue with event title field

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1587]
First, go to the backend.
Click on the field editor section.
![BN1](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/fcbca1f5-f8a2-4942-8a2e-f84864c48068)

Launch Burp Suite to capture the network traffic.
Click on "save changes" below the form. Burp Suite will intercept the outgoing POST request.
Modify the value of the event[event title][type] parameter to onmouseover="alert(/XSS/) and then allow the request to proceed.

![Bn2](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/69e3ee34-44b0-44bb-bc8d-bc622bf792f6)

Now check that the field editor event title field type is blank.
Also, the front end posts an event page and the event title field is  removed. Only a label is available on the form.

![Bn3](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7bf89be2-2dbd-4836-a051-0a7c201c762c)
![Bn4](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/28e96453-874b-4301-8347-533784abe4a5)

**Comment by ritakikani** [comment]
@mistry-jignesh , this is not security issue, this is working fine, if there is no any type selected then will not get any template file of field so this will not show any field at front-back side in event form.

**Comment by mistry-jignesh** [comment]
As per @ritakikani : This is not security issue, this is working fine, if there is no any type selected then will not get any template file of field so this will not show any field at front-back side in event form.
