### ISSUE TITLE
Hide an additionnal field on the event single page ?

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1588]
Hello,

Sorry to ask but I wasn't able to find this information by myself. 
How to hide an additionnal field on the single event page ?

Thank you.

**Comment by ritakikani** [comment]
Hi @designboxcom , You need to override template file call "content-single-event_listing.php" , in this file you just need to remove additional fields code block at you theme side.

You can read doc for how to override template file : https://wp-eventmanager.com/knowledge-base/template-files-override/

**Comment by ritakikani** [comment]
As I suggest the solution, I am closing this issue.
