### ISSUE TITLE
Usage Tracking feature improvement.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1590]
Whenever users are going to deactivate our addon we have to ask them for a reason why they are deactivate our addon and we have to collect all the data on our WPEM Store. 

We have to implement the user tracking feature.

**Comment by ashokdudhat** [comment]
@krinaydhanani did you select best option which way we have to do it ?

**Comment by krinaydhanani** [comment]
Yes, we can use a reference from **Elementor** but this is a duplicate issue so I am going to close this issue.


https://github.com/wpeventmanager/wp-event-manager/issues/441
