### ISSUE TITLE
show_pagination attribute is not working upcoming_events

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1592]
[upcoming_events show_pagination="3"  orderby="rand" order="ASC"]

**Comment by live-aamir** [comment]
@mistry-jignesh the above shortcode is incorrect. Please check. Below is the screenshot.
![Screenshot_1](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/f941d6ed-0914-44d0-b1f3-fbeb09ced814)

**Comment by mistry-jignesh** [comment]
I have verified this issue. I have update value in the attribute.
[upcoming_events per_page="4" show_pagination="false"]
Now it is working fine. So I closed the issue.
