### ISSUE TITLE
Problem with undefined array key “visibility” in

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1600]
When updating Elementor to the latest version, the event page started showing the following error message:

Warning: Undefined array key “visibility” in /home/storage/3/e7/4a/public_html/wp-content/plugins/wp-event-manager/external/elementor-widgets/elementor-single-event-field.php on line 106

https://wordpress.org/support/topic/problem-with-undefined-array-key-visibility-in/

**Comment by mistry-jignesh** [comment]
I have verified this issue. Issue facing with single event field. Many fields are missing.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/60ada541-c7e4-460a-8926-e3b9700c49b6)

**Comment by mistry-jignesh** [comment]
I have verified issues.Now issues are fixed like undefined arry  and missing fields .
It is working fine.
So I closed the issue.
