### ISSUE TITLE
Elementor : Event listing : Events are taking times to load on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1604]
Elementor : Event listing: Events take time to load on the page.

When I performed settings like false and false

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/b33798bc-fcc9-45f6-acfc-6c1f75c0d473)

https://github.com/wpeventmanager/wp-event-manager/assets/75515088/48719878-6e04-4631-bd49-418a25ce4584

**Comment by live-aamir** [comment]
@mistry-jignesh This happens when it loads first and events are many, after that it cached and works fine. Please check.

**Comment by mistry-jignesh** [comment]
As per @live-aamir : This happens when it loads first and events are many, after that it caches and works fine. 
So I closed the issue.
