### ISSUE TITLE
Elementor : Featured event is not display on the listing page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1605]
When I have set show featured event as true and show cancelled event as true then Featured event is not display on the listing page.
It should be displayed on the listing page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/de94b1df-5acd-44fa-b1b0-89689cfc2237)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/1a03935b-3a98-43bd-9c1e-efb501cbb475)

**Comment by live-aamir** [comment]
@mistry-jignesh for an event to appear in this case needs to have both attributes. Please check.

**Comment by mistry-jignesh** [comment]
I have verified this issue. In the event, if both attributes cancelled & featured are selected then event is display.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/2cde599b-c368-40a5-9362-d8fc16f4a4aa)

So I closed the issue.
