### ISSUE TITLE
Elementor : Selected date : Tomorrow attribute wrong event is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1608]
Elementor : Selected date : Tomorrow attribute wrong event is displayed.

When I have performed the below setting but If I have tomorrow's date there is no event then the other date event is display.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/c4302fb8-9aa9-4026-846a-a77b6b8befa1)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/cd9d5ef9-b815-469d-8625-160e1e628bd0)

**Comment by ritakikani** [comment]
@mistry-jignesh  I had checked with the same stpes, you mention, but I am not facing this type of any issue.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/f799adfb-f1f8-473e-93e0-bd6e4d3b5ec0)


![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/49bad462-ff9d-4acc-9176-c9bd880c7af8)

**Comment by mistry-jignesh** [comment]
I have verified this issue with elementor. This issue is working.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/f1f7347f-4f03-4720-8fdb-16b7d82e249e)

So I closed the issue.
