### ISSUE TITLE
Event registrations add-on doesn't work aymore.

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1616]
WP Event Manager 3.1.39 and WP Event Registrations Addon 1.6.18
How can I log errors to see why the registration are not anymore added to the overview list ?
Is there a new settings that I forgot to activate ?
The documentation is not really helping there.

**Comment by designboxcom** [comment]
I am still investigating what could be the problem there and I have the feeling accent in Event title could be the cause.
For example, I see in the error log the following message:
`shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673950 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7478] => Arbr\xe2\x80\x99Ap\xc3\xa9ro : \xc3\xa0 la d\xc3\xa9couverte du plus beau h\xc3\xaatre pleureur de Lausanne, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673944 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7481] => Arbr\xe2\x80\x99Ap\xc3\xa9ro : \xc3\xa0 la d\xc3\xa9couverte du plus beau platane de Lausanne, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673939 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7484] => Arbr\xe2\x80\x99Ap\xc3\xa9ro : \xc3\xa0 la d\xc3\xa9couverte du plus bel if et de la plus belle l\xc3\xa9gende de Lausanne, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673934 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7487] => Arbr\xe2\x80\x99Ap\xc3\xa9ro sp\xc3\xa9cial Festival de la Salamandre : \xc3\xa0 la d\xc3\xa9couverte du plus beau s\xc3\xa9quoia de Morges, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673929 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7490] => Arbr\xe2\x80\x99Ap\xc3\xa9ro : \xc3\xa0 la d\xc3\xa9couverte du plus beau cypr\xc3\xa8s chauve de Lausanne, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673924 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7493] => Arbr'Ap\xc3\xa9ro sp\xc3\xa9cial No\xc3\xabl en famille : \xc3\xa0 la d\xc3\xa9couverte du plus beau sapin de Lausanne, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673919 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7508] => La Terre, le Feu et l'Homme, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673915 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [7511] => L'Eau, l'Air et l'Homme, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673910 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [] => S\xc3\xa9lectionner l\xe2\x80\x99\xc3\xa9v\xc3\xa9nement, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673905 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: (, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673900 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [options] => Array, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673895 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [value] => 0, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673891 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [placeholder] => Post ID of the event ID for registration, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673886 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [type] => select, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673882 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: [label] => Event Name, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673877 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: (, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673874 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: PHP message: Array, referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration
shop.xxxxxxxxxxx.xxx [Tue Jan 23 10:22:30.673869 2024] [-:error] [pid 74080:tid 139622751340288] [client 85.193.135.111:0] FastCGI: server "/home/clients/8b6661c1cd19fb78d6c05663cd8c933a/.config/apache/shop.xxxxxxxxxxx.xxx/.fpm/php5.external" stderr: ), referer https://shop.xxxxxxxxxxx.xxx/wp-admin/edit.php?post_type=event_registration`

**Comment by ritakikani** [comment]
Hi @designboxcom ,

Please open support ticket, because we need to identify the issue in your site.

**Comment by designboxcom** [comment]
I will but, to be honest, for the last months I used your support desk, I NEVER got an issue fixed there; or an acceptable answer rather than a copied/pasted useless sentence.

**Comment by designboxcom** [comment]
Ticket id #17553

**Comment by jathinkj** [comment]
Resolved
