### ISSUE TITLE
Include events without a starte date and time in the selected_datetime filter

### ISSUE THREAD

**Issue by karolisdailidonis** [wpeventmanager/wp-event-manager#1617]
I use the shortcode with selected_datetime="today, 31.12.2099"
The problem is that it only shows events that have a start date and start time. I would like to include the events without a date as well.
So far I have not found a setting or a hook with which I could overwrite the filter in functions.php.

**Comment by ritakikani** [comment]
Hi @karolisdailidonis ,

To override query arguments for filter, you need to use below filter ;

`	$query_args = apply_filters('event_manager_get_listings', $query_args, $args);`

I hope this will help you.

**Comment by karolisdailidonis** [comment]
Hey @ritakikani,

thank you it was helpful, here is an example from my functions.php:

```php
// functions.php

add_filter('event_manager_get_listings', 'custom_event_manager_get_listings', 10, 2);

function custom_event_manager_get_listings($query_args, $args)
{
	if(is_home() || is_front_page()) {

		$query_args['meta_query'] = array(
			'relation' => 'OR',
			 Array(
				'key' => '_event_start_date',
				'value' => date('Y-n-d'),
				'compare' => '>=',
				'type' => 'date'
				),
			 Array(
				'key' => '_event_start_date',
				'value' => null,
				'compare' => '=',
				),
		);
	}

	return $query_args;
};
```
