### ISSUE TITLE
Event is not exipred at end time

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1620]
I have created one event. I have set the below date for event

Start Date : 05-02-2024  And time 3:00 AM
End Date  : 05-02-2024 And time  1:30 PM

I have checked after 1: 30 PM . Event is display active .
From backend manually try to update event but event is not expired.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/4a101fb5-e967-40d6-9d36-feab9b2e1bb4)

**Comment by ritakikani** [comment]
@mistry-jignesh , As per our plugin functionality, event will expires on event expire date + 23:59:00 time. If you want that, your event should be expired at the same date and time you entered for event end datetime, then you need to add custom code which I provide you as a snippet.

**Comment by mistry-jignesh** [comment]
I have verifiedt this issue with provided steps.
Now this issue is working fine. So I closed the issue.
