### ISSUE TITLE
 vulnerable to Cross Site Scripting (XSS)

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1626]
https://wordpress.org/support/topic/3-1-42-is-vulnerable-to-cross-site-scripting-xss/

**Comment by mistry-jignesh** [comment]
1 . When trying to update event then display the event.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/bf3eec95-19a9-463f-b3d7-91a70448fd56)

**Comment by mistry-jignesh** [comment]
3 .Backend admin : Try to update event from the backend side then display fatal error message.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/a2c47000-d17f-456a-bbfc-01f8e38bd2cb)
