### ISSUE TITLE
Compatibility issue with WPML

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1627]
A client is getting an error message from the browser “redirected you too many times”, when trying to check translated “past events” with the WPML plugin.

https://wordpress.org/support/topic/compatibility-issue-with-wpml-12/

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine. I have tested it and below is the screenshot. Please check.
![Screenshot 2024-03-18 124301](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/a8bb6865-7ab6-43a8-acb7-29ee92e1faa9)

**Comment by mistry-jignesh** [comment]
I have verified this issue .Past events are working fine with WPML.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/24696b37-c46e-496b-9993-cc6f7f38e699)


So I closed the issue.
