### ISSUE TITLE
Unable to translate the “Select Date Range” label in Datepicker

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1628]
No matter how hard I try, I cannot get the “Select Date Range” label in Datepicker translated into Italian, despite the translation being correct in the localization file (checked with Loco Translation).
The only way I was able to have it translated is by editing the wp-event-manager.php file (line 302) in the root folder of the plugin, but this edit will be wiped away on the next plugin update.
How should I fix it?

https://wordpress.org/support/topic/unable-to-translate-the-select-date-range-label-in-datepicker/

**Comment by mistry-jignesh** [comment]
I have verified this issue.“Select Date Range” label is translated into Italian language.
This is working fine. Need to provide new .mo and .po files.

Screebshot : https://prnt.sc/xb4qAKVrpEIC

**Comment by ritakikani** [comment]
This is working fine with latest version of our plugin.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/7664d08b-31bf-4815-87c3-453f5f4efe02)

**Comment by mistry-jignesh** [comment]
I have verified this issue .The translation issue is working fine.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/89497530-f281-44fb-9b8b-af7a3083cc82)
So I closed the issue.
