### ISSUE TITLE
Name of the current event

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1632]
How to get the current event? How to get the name of the current event?

I’m not interested in the shortcode, but in the output to PHP.

https://wordpress.org/support/topic/name-of-the-current-event/

**We have informed but still have not opened a ticket by client.**

**Comment by ritakikani** [comment]
If client wants to get event name on wordpress website single post page then he can use default $post in which he can get all the information of that post like name, banner, location, everything.

But, he want to display event name on other page then he must need to fetch data from database and then he can print or echo the information of event.

**Comment by mistry-jignesh** [comment]
As per @ritakikani :  If client wants to get event name on wordpress website single post page then he can use default $post in which he can get all the information of that post like name, banner, location, everything.

But, he want to display event name on other page then he must need to fetch data from database and then he can print or echo the information of event. 

So I closed the issue.
