### ISSUE TITLE
Hide licence message

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1636]
How can I hide these messages? They are very annoying. Other plugins just allow you to hide them with a little x at the top right of the message.

https://wordpress.org/support/topic/hide-licence-message/

**Comment by ritakikani** [comment]
@mistry-jignesh  this is not an issue of core plugin. but we need to check in core plugin as update code is not in core plugin but in addons, so.

**Comment by mistry-jignesh** [comment]
As per @ritakikani : This is not an issue of core plugin. but we need to check in core plugin as update code is not in the core plugin but in addons, so.
So I closed the issue.
