### ISSUE TITLE
In the Organizer account visible other organizer venue & organizer

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1642]
1. First login as one organizer.
2. Now create one organizer & venue.
3. Log in with other users (like Subscribers, Author).
4. Click on the organizer or Venue link button.
5. Observed that visible other organizer venue & organizer.

**Comment by live-aamir** [comment]
@mistry-jignesh One organizer cannot see other organizers on organizer dashboard but see all organizers on event organizers page.
![Screenshot_2](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/cb0e09f3-4b1b-404e-bda8-60ffee3b06f3)

**Comment by mistry-jignesh** [comment]
As per @live-aamir: One organizer cannot see other organizers on the organizer dashboard but see all organizers on the event organizers page. So I closed the issue.
