### ISSUE TITLE
Need to update readme file

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1643]
![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/14828398-2da2-421b-8c9e-690663829c14)

**Comment by krinaydhanani** [comment]
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/7fe28492-011f-49b9-ba46-52f2b10149a8">

**Comment by RHSRSK** [comment]
I Update readme.txt file in this issue https://github.com/wpeventmanager/wp-event-manager/issues/1526

**Comment by mistry-jignesh** [comment]
This issue is fixed on the Wordpress.org. So I closed the issue.
