### ISSUE TITLE
Need to add diable attribute for form fields for customization

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1644]
Need to add diable attribute for form fields for customization

**Comment by ritakikani** [comment]
Connected to this : https://github.com/wpeventmanager/wp-event-manager-registrations/issues/343

**Comment by mistry-jignesh** [comment]
This issue is related registration addon https://github.com/wpeventmanager/wp-event-manager-registrations/issues/343.
I verified this issue on the registration addon. This issue is working fine.
Now attendee's name is edited without issue. So I closed the issue.
