### ISSUE TITLE
Shortcode menu : Filter button is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1646]
When I selected WP Event Manager Registrations option from the dropbox.
Now click on the filter button but filter button is not working.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/99e98aa1-9917-49dd-8f2d-80d99a1eb1ac)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ae429107-9310-44f7-ae2d-0f8455c3f2ea)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine below is the screenshot. Please check.
![Screenshot_18](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/44d54da6-cabe-4bc1-8cd5-6125492b2916)

**Comment by mistry-jignesh** [comment]
I have verified this issue with updated version. This issue is working fine.
So I closed the issue.
