### ISSUE TITLE
customizing event listening widget

### ISSUE THREAD

**Issue by egncln** [wpeventmanager/wp-event-manager#1650]
hi, 
i'm trying to customize the widget adding and displaying my custom field on each single event, like "event type", "start time", etc,... like these screenshots. Where are functions to make it?

how can i do it?
![custom fields](https://github.com/wpeventmanager/wp-event-manager/assets/164171903/be7244c5-b119-424c-ad52-052b1441343a)
![view](https://github.com/wpeventmanager/wp-event-manager/assets/164171903/31924a82-dd46-47e6-aa0b-d1b86fd6376e)

thx

**Comment by live-aamir** [comment]
@egncln you need to customize "content-event_listing.php" file in plugin or override the template in your theme using [this link](https://wp-eventmanager.com/knowledge-base/template-files-override/). To get the value of the addtional field use 
**get_post_meta( $post->ID, your_meta_key_under_meta_key +heading, true )**  on the template file where you want to show it.


Note: The addtional field will be appear on event detail page. To hide use the following function in your theme function.php file:
add_filter( 'event_manager_show_additional_details_fields', 'hide_additional_field' );

function hide_additional_field($additional_fields){

	 unset($additional_fields['your_field_name']);

	return $additional_fields;	

}

**Comment by mistry-jignesh** [comment]
No update has been provided from the client side. So we are closing this issue.
