### ISSUE TITLE
Shortcode issue with paid ticket 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1652]
First I created an event and sell ticket plugin is activated.
Created one paid ticket.
I have used the below shortcode.
[events show_filters="true" ticket_prices="paid"]
It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/9192dfdf-c9f5-42b0-8354-4c261b49fed0)

Now I have deactivated the sell ticket plugin.
[events show_filters="true" ticket_prices="paid"]

Then after the paid ticket event is displayed.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/5e3dd0f7-5bbd-4581-9f6d-b599ab4139f1)

**Comment by live-aamir** [comment]
@mistry-jignesh This is working fine. Below is the screenshot.
![Screenshot_14](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/c49adbd1-0080-4502-854f-0069968a26ef)

**Comment by mistry-jignesh** [comment]
I have checked the issue in the new setup. It is working fine.
So I closed the issue.
