### ISSUE TITLE
Need to set proper text for multiple-selection in filter

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#1656]
In settings, there is "Multi-select Event Types" is selcted, so On front-end side, in events page, I am getting "Choose an event type" text rather shows "Choose event types".

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/d3f727dd-0962-4b98-93ba-663ad83899c4)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/dab6ca4b-bcb9-4d09-84cd-166ca87b532a)

**Comment by mistry-jignesh** [comment]
I have verified this issue. On front-end side, the events listing page text is display "Choose event types"
Now this issue is fixed.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/98f3a19e-8920-499e-a94d-ac0ceb1cafe5)

So I closed the issue.
