### ISSUE TITLE
Embed Youtube doesn't work

### ISSUE THREAD

**Issue by designboxcom** [wpeventmanager/wp-event-manager#1660]
Updated today to the latest WPEM Version and the embed youtube gutenberg blocks are still not working into the event description....
https://shop.homme-nature.ch/%C3%A9v%C3%A8nement/plantes-source-de-vie-conference-francois-couplan-2024/

**Comment by vijayrathod245** [comment]
Can you please try this and follow this step with the "Custom HTML" block. It's working fine, we have checked. 
![image](https://github.com/wpeventmanager/wp-event-manager/assets/46293565/e4303bb2-cfc7-4e6e-bdfc-1b5429f572be)

**Comment by designboxcom** [comment]
Hello,
I tried to add a youtube iframe in html block as you suggested but, still, the video doesn't appear on the page (What you see actually is a picture linked to the video). The HTML Block is just below this picture and doesn't appear.

**Comment by vijayrathod245** [comment]
I have checked the issue from our end and it's working fine. Now we need to check from your end, so please open a support ticket so we can check issue in details.

https://github.com/wpeventmanager/wp-event-manager/assets/46293565/dd1075cc-20a3-4912-9572-4148fc0f5ec9

**Comment by designboxcom** [comment]
Thank you. I opened a ticket.

**Comment by vijayrathod245** [comment]
I hope the issue is resolved now.
