### ISSUE TITLE
Translation issue with German language

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1662]
Some fields are English and some are German. Like “Select Date Range” and “Choose an Event Category” on the event list page or “Date And Time” and “Share With Friends” on the single event page. The WordPress site language is German and I also installed the Loco Translate plugin but I don’t know how to configure it, because it seems like the translations are correct.

**Comment by live-aamir** [comment]
@mistry-jignesh you need to configure loco translate properly and translate strings to overcome this issue.

**Comment by mistry-jignesh** [comment]
1. Select date range :  

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/f4d17f43-92fb-4213-add3-23c58e370ef5)

2.Choose an event category 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/6cec39f9-a983-4aee-9c36-b0caf2b312d8) 


3. Date And Time and shared with a friend

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/632e3cb3-81d7-43c5-9e1e-9d3b706e1f6c)


All the text are translated fine. So I closed the issue.
