### ISSUE TITLE
Issue in the field editor.

### ISSUE THREAD

**Issue by NikhilChangappa** [wpeventmanager/wp-event-manager#1664]
when he  create a field in the field editor with following settings:
* Type: "Term Select"
* Placeholder / Options: <my custom taxonomy>

it doesn't show up in the "add new event" fields.

issue vedio I've uploaded it to youtube: https://www.youtube.com/watch?v=nrZ1TrQHRlo

#18821  Daniel Wagner

the codes which he used to add 
Hey,

Here is a example of the taxonomy creation:
 
   public function register_taxonomies() {
        if (!taxonomy_exists('user_taxonomy')) {
            register_taxonomy(
                'user_taxonomy',
                array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
                array(
                    'label' => __('Users', 'textdomain'),
                    'rewrite' => array('slug' => 'user'),
                    'hierarchical' => true,
                    'show_ui' => false,
                )
            );
        }
        if (!term_exists('User', 'user_taxonomy')) {
            wp_insert_term('User', 'user_taxonomy');
        }
        if(!taxonomy_exists('contact_taxonomy')) {
            register_taxonomy(
                'contact_taxonomy',
                array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
                array(
                    'label' => __('Contacts', 'textdomain'),
                    'rewrite' => array('slug' => 'contact'),
                    'hierarchical' => true,
                    'show_ui' => false,
                )
            );
        }
        if (!term_exists('Contact', 'contact_taxonomy')) {
            wp_insert_term('Contact', 'contact_taxonomy');
        }
        if (!taxonomy_exists('host_country_taxonomy')) {
            register_taxonomy(
                'host_country_taxonomy',
                array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
                array(
                    'label' => __('Host Countries', 'textdomain'),
                    'rewrite' => array('slug' => 'host-country'),
                    'hierarchical' => true,
                    'show_ui' => false,
                )
            );
        }
        if (!term_exists('Host Country', 'host_country_taxonomy')) {
            wp_insert_term('Host Country', 'host_country_taxonomy');
        }
    }

Example of post creation and assignment to taxonomy
/* HOST COUNTRIES */
            foreach ($data['hostcountries'] as $hostcountry) {
                $existing_post = post_exists(wp_strip_all_tags($hostcountry['Name']));
                if(!$existing_post) {
                    $post_id = wp_insert_post([
                        'post_title' => wp_strip_all_tags($hostcountry['Name']),
                        'post_type' => 'zoho-crm-event',
                        'post_status' => 'publish',
                    ]);
                    wp_set_object_terms($post_id, 'Host Country', 'host_country_taxonomy');
                } else {
                    wp_update_post([
                        'ID' => $existing_post,
                        'post_title' => wp_strip_all_tags($hostcountry['Name']),
                        'post_type' => 'zoho-crm-event',
                        'post_status' => 'publish',
                    ]);
                }
            }
            /* HOST COUNTRIES END */

**Comment by live-aamir** [comment]
@NikhilChangappa The custom taxanomy when created will show in right side of event post in admin area. Below is the screenshot. And the field created as term-select will show in front-end and currently its not working and I am looking into it.
![Screenshot_18](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/e0ca8e14-e7bb-4141-9771-890cd65b0d2a)

**Comment by live-aamir** [comment]
@NikhilChangappa @mistry-jignesh It will show in front-end at form submit page, below is the screenshot.
![Screenshot_20](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/7d1146cd-6162-475f-be20-499aab7cf943)
and to get this value in front-end need to customize **content-single-event_listing.php** file. To get the custom taxanomy value use wordpress function **wp_get_post_terms($event->ID, 'your_field_meta_key')**;  and unset the default field to not appear under addtional details in single event page like below screenshot.
![Screenshot_21](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/a1c43a40-1a12-458d-9b82-988a4f370934)

**Comment by 4dwag** [comment]
Hey @live-aamir @NikhilChangappa,

sadly my custom taxonomies are not showing up in the event creation sidebar, I've tried to debug it but lost the focus, some details:

The file with the rendering of the fields is getting called correctly in templates/event-submit.php line 34.

Some output of the term-select-field file:
wp-event-manager/templates/form-fields/term-select-field.php file
```
[03-Jul-2024 19:48:35 UTC] WP EVENT MANAGER TERM FIELD KEY: owner
[03-Jul-2024 19:48:35 UTC] FIELD: Array
(
    [label] => Owner
    [type] => term-select
    [description] => ZOHO Integration
    [placeholder] =>
    [multiple] => 0
    [taxonomy] => user_taxonomy
    [required] => 1
    [visibility] =>
    [priority] => 33
    [default] =>
)

[03-Jul-2024 19:48:35 UTC] WP EVENT MANAGER TERM FIELD KEY: host_country
[03-Jul-2024 19:48:35 UTC] FIELD: Array
(
    [label] => Host Country
    [type] => term-select
    [description] => ZOHO Integration
    [placeholder] =>
    [multiple] => 0
    [taxonomy] => host_country_taxonomy
    [required] => 1
    [visibility] =>
    [priority] => 34
    [default] =>
)

[03-Jul-2024 19:48:35 UTC] WP EVENT MANAGER TERM FIELD KEY: host_sales_rep
[03-Jul-2024 19:48:35 UTC] FIELD: Array
(
    [label] => Host Sales Rep
    [type] => term-select
    [description] => ZOHO Integration
    [placeholder] =>
    [multiple] => 0
    [taxonomy] => user_taxonomy
    [required] => 1
    [visibility] =>
    [priority] => 35
    [default] =>
)

[03-Jul-2024 19:48:35 UTC] WP EVENT MANAGER TERM FIELD KEY: lecturer
[03-Jul-2024 19:48:35 UTC] FIELD: Array
(
    [label] => Lecturer
    [type] => term-select
    [description] => ZOHO Integration
    [placeholder] =>
    [multiple] => 0
    [taxonomy] => contact_taxonomy
    [required] => 1
    [visibility] =>
    [priority] => 36
    [default] =>
)
```

is there maybe a problem with this "wp_dropdown_categories" function? (term-select-field.php)

```php
wp_dropdown_categories(apply_filters('event_manager_term_select_field_wp_dropdown_categories_args', array(
        'taxonomy'         => $field['taxonomy'],
        'hierarchical'     => 1,
        'show_option_all'  => $placeholder ?? '',
        'show_option_none' => $field['required'] ? '' : '-',
        'name'             => isset($field['name']) ? $field['name'] : $key,
        'orderby'          => 'name',
        'selected'         => $selected,
        'hide_empty'       => false
), $key, $field));
```

thank you!

**Comment by live-aamir** [comment]
@4dwag Try below code in your themes function.php or your plugin main file to get the location taxanomy on 
event creation page.

`/**
 * Add custom taxonomies
 *
 * Additional custom taxonomies can be defined here
 * https://codex.wordpress.org/Function_Reference/register_taxonomy
 */
function add_custom_taxonomies() {
  // Add new "Locations" taxonomy to Posts
  register_taxonomy('location', 'event_listing', array(
    // Hierarchical taxonomy (like categories)
    'hierarchical' => true,
    'show_in_rest'          => true,
    // This array of options controls the labels displayed in the WordPress Admin UI
    'labels' => array(
      'name' => _x( 'Locations', 'taxonomy general name' ),
      'singular_name' => _x( 'Location', 'taxonomy singular name' ),
      'search_items' =>  __( 'Search Locations' ),
      'all_items' => __( 'All Locations' ),
      'parent_item' => __( 'Parent Location' ),
      'parent_item_colon' => __( 'Parent Location:' ),
      'edit_item' => __( 'Edit Location' ),
      'update_item' => __( 'Update Location' ),
      'add_new_item' => __( 'Add New Location' ),
      'new_item_name' => __( 'New Location Name' ),
      'menu_name' => __( 'Locations' ),
    ),
    // Control the slugs used for this taxonomy
    'rewrite' => array(
      'slug' => 'locations', // This controls the base slug that will display before each term
      'with_front' => false, // Don't display the category base before "/locations/"
      'hierarchical' => true // This will allow URL's like "/locations/boston/cambridge/"
    ),
  ));
}
add_action( 'init', 'add_custom_taxonomies', 0 );`

**Comment by 4dwag** [comment]
Hey @live-aamir, I've tried your code, but it also, doesn't show up in the right sidebar of the event creation, here is my code.
Am I doing something wrong in the register() function? The taxonomies are there, but not getting rendered in the right sidebar after I've created the fields in the field editor.

```php
<?php

namespace DHSV\ZohoCRMEvents;

use DHSV\ZohoCRMEvents\WPSync;
use DHSV\ZohoCRMEvents\OverviewContent;
use DHSV\ZohoCRMEvents\SettingsContent;
use DHSV\ZohoCRMEvents\UserDataContent;
use DHSV\ZohoCRMEvents\HostCountryDataContent;
use DHSV\ZohoCRMEvents\ContactDataContent;

class PostTypes {
	private $overviewContent;
	private $settingsContent;
	private $userDataContent;
	private $hostCountryDataContent;
	private $contactDataContent;
    private $WPSync;

	public const SOME_POST_TYPE = 'zoho-crm-event';
	public function __construct() {
		$this->overviewContent = new OverviewContent();
		$this->settingsContent = new SettingsContent();
		$this->userDataContent = new UserDataContent();
		$this->hostCountryDataContent = new HostCountryDataContent();
		$this->contactDataContent = new ContactDataContent();
	}
	public function register() {
		$this->register_post_type(
			$this::SOME_POST_TYPE,
			'Zoho CRM Event',
			'Zoho CRM Events',
		);
		add_action('admin_menu', array($this, 'remove_unnecessary_submenus'), 999);
		add_action('admin_menu', array($this, 'add_overview_submenu'));
		add_action( 'admin_menu', array( $this, 'add_settings_submenu' ) );
		add_action( 'admin_menu', array( $this, 'add_user_data_submenu' ) );
		add_action( 'admin_menu', array( $this, 'add_host_country_data_submenu' ) );
		add_action( 'admin_menu', array( $this, 'add_contact_data_submenu' ) );
		add_action( 'init', array( $this, 'add_custom_taxonomies' ), 0);
		add_action( 'init', array( $this, 'register_taxonomies' ), 0);
		// Listener for WP-Event-Manager Event creation
		$wpSync = new WPSync();
		add_action('transition_post_status', array($wpSync, 'syncWpemEventListing'), 10, 3);
	}

	public function add_custom_taxonomies() {
	// Add new "Locations" taxonomy to Posts
		register_taxonomy('location', 'event_listing', array(
		// Hierarchical taxonomy (like categories)
			'hierarchical' => true,
			'show_in_rest' => true,
		// This array of options controls the labels displayed in the WordPress Admin UI
			'labels' => array(
				'name' => _x( 'Locations', 'taxonomy general name' ),
				'singular_name' => _x( 'Location', 'taxonomy singular name' ),
				'search_items' => __( 'Search Locations' ),
				'all_items' => __( 'All Locations' ),
				'parent_item' => __( 'Parent Location' ),
				'parent_item_colon' => __( 'Parent Location:' ),
				'edit_item' => __( 'Edit Location' ),
				'update_item' => __( 'Update Location' ),
				'add_new_item' => __( 'Add New Location' ),
				'new_item_name' => __( 'New Location Name' ),
				'menu_name' => __( 'Locations' ),
			),
		// Control the slugs used for this taxonomy
			'rewrite' => array(
				'slug' => 'locations', // This controls the base slug that will display before each term
				'with_front' => false, // Don't display the category base before "/locations/"
				'hierarchical' => true // This will allow URL's like "/locations/boston/cambridge/"
			),
		));
	}

	public function register_post_type( string $slug, string $singular, string $plural, array $args = array() ) {
		$labels = array_merge(
			array(
				'name'               => $plural,
				'singular_name'      => $singular,
				'menu_name'          => $plural,
			),
			isset( $args['labels'] ) ? $args['labels'] : array()
		);

		\register_post_type(
			$slug,
			array_merge(
				array(
					'public'       => true,
					'has_archive'  => false,
					'show_ui'      => true,
					'show_in_rest' => true,
					'supports'     => array(),
					'rewrite'      => array( 'with_front' => false ),
				),
				$args,
				array( 'labels' => $labels )
			)
		);
	}

	public function remove_unnecessary_submenus() {
		remove_submenu_page('edit.php?post_type=' . $this::SOME_POST_TYPE, 'post-new.php?post_type=' . $this::SOME_POST_TYPE);
		remove_submenu_page('edit.php?post_type=' . $this::SOME_POST_TYPE, 'edit.php?post_type=' . $this::SOME_POST_TYPE);
	}

	public function add_overview_submenu() {
		add_submenu_page(
			'edit.php?post_type=' . $this::SOME_POST_TYPE,
			__('Overview', 'textdomain'),
			__('Overview', 'textdomain'),
			'manage_options',
			$this::SOME_POST_TYPE . '_overview',
			array($this->overviewContent, 'render')
		);
	}

	public function add_settings_submenu() {
		add_submenu_page(
			'edit.php?post_type=' . $this::SOME_POST_TYPE,
			__('Settings', 'textdomain'),
			__('Settings', 'textdomain'),
			'manage_options',
			$this::SOME_POST_TYPE . '_settings',
			array($this->settingsContent, 'render')
		);
	}

	public function add_user_data_submenu() {
		add_submenu_page(
			'edit.php?post_type=' . $this::SOME_POST_TYPE,
			__('Users', 'textdomain'),
			__('Users', 'textdomain'),
			'manage_options',
			$this::SOME_POST_TYPE . '_users',
			array($this->userDataContent, 'render')
		);
	}

	public function add_host_country_data_submenu() {
		add_submenu_page(
			'edit.php?post_type=' . $this::SOME_POST_TYPE,
			__('Host Countries', 'textdomain'),
			__('Host Countries', 'textdomain'),
			'manage_options',
			$this::SOME_POST_TYPE . '_host_countries',
			array($this->hostCountryDataContent, 'render')
		);
	}

	public function add_contact_data_submenu() {
		add_submenu_page(
			'edit.php?post_type=' . $this::SOME_POST_TYPE,
			__('Contacts', 'textdomain'),
			__('Contacts', 'textdomain'),
			'manage_options',
			$this::SOME_POST_TYPE . '_contacts',
			array($this->contactDataContent, 'render')
		);
	}

	public function register_taxonomies() {
		// User Taxonomy
		if (!taxonomy_exists('user_taxonomy')) {
			register_taxonomy(
				'user_taxonomy',
				array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
				array(
					'hierarchical' => true,
					'show_in_rest' => true,
					'labels' => array(
						'name' => _x('Users', 'taxonomy general name'),
						'singular_name' => _x('User', 'taxonomy singular name'),
						'search_items' => __('Search Users'),
						'all_items' => __('All Users'),
						'parent_item' => __('Parent User'),
						'parent_item_colon' => __('Parent User:'),
						'edit_item' => __('Edit User'),
						'update_item' => __('Update User'),
						'add_new_item' => __('Add New User'),
						'new_item_name' => __('New User Name'),
						'menu_name' => __('Users'),
					),
					'rewrite' => array(
						'slug' => 'user',
						'with_front' => false,
						'hierarchical' => true,
					),
					'show_ui' => false,
				)
			);
		}
		if (!term_exists('User', 'user_taxonomy')) {
			wp_insert_term('User', 'user_taxonomy');
		}

		// Contact Taxonomy
		if (!taxonomy_exists('contact_taxonomy')) {
			register_taxonomy(
				'contact_taxonomy',
				array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
				array(
					'hierarchical' => true,
					'show_in_rest' => true,
					'labels' => array(
						'name' => _x('Contacts', 'taxonomy general name'),
						'singular_name' => _x('Contact', 'taxonomy singular name'),
						'search_items' => __('Search Contacts'),
						'all_items' => __('All Contacts'),
						'parent_item' => __('Parent Contact'),
						'parent_item_colon' => __('Parent Contact:'),
						'edit_item' => __('Edit Contact'),
						'update_item' => __('Update Contact'),
						'add_new_item' => __('Add New Contact'),
						'new_item_name' => __('New Contact Name'),
						'menu_name' => __('Contacts'),
					),
					'rewrite' => array(
						'slug' => 'contact',
						'with_front' => false,
						'hierarchical' => true,
					),
					'show_ui' => false,
				)
			);
		}
		if (!term_exists('Contact', 'contact_taxonomy')) {
			wp_insert_term('Contact', 'contact_taxonomy');
		}

		// Host Country Taxonomy
		if (!taxonomy_exists('host_country_taxonomy')) {
			register_taxonomy(
				'host_country_taxonomy',
				array('zoho-crm-event', 'event_listing'), // 'event_listing' is the post type for WP-Event-Manager
				array(
					'hierarchical' => true,
					'show_in_rest' => true,
					'labels' => array(
						'name' => _x('Host Countries', 'taxonomy general name'),
						'singular_name' => _x('Host Country', 'taxonomy singular name'),
						'search_items' => __('Search Host Countries'),
						'all_items' => __('All Host Countries'),
						'parent_item' => __('Parent Host Country'),
						'parent_item_colon' => __('Parent Host Country:'),
						'edit_item' => __('Edit Host Country'),
						'update_item' => __('Update Host Country'),
						'add_new_item' => __('Add New Host Country'),
						'new_item_name' => __('New Host Country Name'),
						'menu_name' => __('Host Countries'),
					),
					'rewrite' => array(
						'slug' => 'host-country',
						'with_front' => false,
						'hierarchical' => true,
					),
					'show_ui' => false,
				)
			);
		}
		if (!term_exists('Host Country', 'host_country_taxonomy')) {
			wp_insert_term('Host Country', 'host_country_taxonomy');
		}
	}
}
```

**Comment by NikhilChangappa** [comment]
The issue has been resolved.

**Comment by 4dwag** [comment]
Hey @NikhilChangappa, can I download the update somewhere?

**Comment by NikhilChangappa** [comment]
Here is the link to download the ZIP file,
https://github.com/wpeventmanager/wp-event-manager.git
Please click on clone and download the zip file.
![image (104)](https://github.com/user-attachments/assets/86564817-3a72-48fd-813b-2ed5aa3904a9)

**Comment by NikhilChangappa** [comment]
Hello @4dwag  Can you please confirm If the issue has been resolved from your end?

**Comment by 4dwag** [comment]
@NikhilChangappa yes, this works now.
