### ISSUE TITLE
WPML and loco translate : Event Categoty & Event type translate issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1665]
WPML and loco translate Event category & Event type translate issue.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/cc20aa80-180e-41ac-ae5a-4f956a39600f)

**Comment by live-aamir** [comment]
@mistry-jignesh These taxanomy are get inserted in database when we install the plugin in classic view that cannot be translated. But when we use block editor we choose any category generated by user with their own language after deleting the default one.
Below is the screenshot.
![Uploading Screenshot_22.png…]()

**Comment by mistry-jignesh** [comment]
As per @live-aamir :   These taxanomy are get inserted in a database when we install the plugin in classic view that cannot be translated. But when we use block editor we choose any category generated by a user with their own language after deleting the default one. Below is the screenshot.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/97cb9947-ab3b-40fe-957f-c7669b2d48a3)
