### ISSUE TITLE
WPML : Organizer and venue form some fields do not translated 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1667]
WPML: Organizer and venue form fields are not translated.

**Organizer Form** and **Venue Form** and **Post an event Form**

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/4baa79fa-2f32-4fa2-b947-6357613f70b9)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/15e71cf7-b50d-4c00-b654-cad4537d95e5)

**Comment by live-aamir** [comment]
@mistry-jignesh this cannot be translated as it is browser generated text. Check here https://stackoverflow.com/questions/20517321/change-language-input-type-file

**Comment by live-aamir** [comment]
@mistry-jignesh file Input text cannot be translated as it is browser generated text, other one is fixed. Check below . https://stackoverflow.com/questions/20517321/change-language-input-type-file
![Screenshot_20](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/da382b93-0e47-4bbd-a898-81fd0d83efb8)

**Comment by mistry-jignesh** [comment]
Now  Select country and Organizer country text properly translate. Both text need to be translated manually.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/6e33708a-c623-417a-baaf-344d7bd67369)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/bbb1b369-26c8-4948-9504-2089298ddd65)

Now I closed the issue.
