### ISSUE TITLE
upcoming events shortcode

### ISSUE THREAD

**Issue by jathinkj** [wpeventmanager/wp-event-manager#1668]
Issue: When using [upcoming_events] short if the end is not mentioned automatically date is being displayed
![image](https://github.com/wpeventmanager/wp-event-manager/assets/144658262/11b732c7-82aa-47e6-b73c-c0b3755c36fd)

**Comment by mistry-jignesh** [comment]
I have verified this issue. 
Now automatically date is not being displayed.This issue is fixed.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ce91e083-88d1-4808-b253-02dfab95935f)

So I closed the issue.
