### ISSUE TITLE
depreciated code

### ISSUE THREAD

**Issue by jathinkj** [wpeventmanager/wp-event-manager#1673]
When I turn on debug = true in my wp-config.php file, I get a LOT of deprecated items from WP Event Manager, as per below.

Can you please take a look at and advise/provide a solution.

I have the latest versions of your plugins installed.

Regards,

Luke

-

Deprecated: Creation of dynamic property WP_Event_Manager_Alerts::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php on line 88

Deprecated: Creation of dynamic property WPEM_Registrations::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php on line 96

Deprecated: Creation of dynamic property WP_Event_Manager_Settings::$settings_group is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-settings.php on line 21

Deprecated: Creation of dynamic property WP_Event_Manager_Admin::$settings_page is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-admin.php on line 29

Deprecated: Creation of dynamic property WP_Event_Manager::$forms is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 104

Deprecated: Creation of dynamic property WP_Event_Manager::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 105

Deprecated: Creation of dynamic property WPEM_Guests::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wpem-guests/wpem-guests.php on line 73

Deprecated: Creation of dynamic property WPEM_Name_Badges_Dashboard::$generate_badges is deprecated in /home/wazzonau/public_html/wp-content/plugins/wpem-name-badges/includes/wpem-name-badges-dashboard.php on line 24

Deprecated: Creation of dynamic property WPEM_Name_Badges_Registrations::$generate_badges is deprecated in /home/wazzonau/public_html/wp-content/plugins/wpem-name-badges/includes/wpem-name-badges-registrations.php on line 18

Deprecated: Creation of dynamic property WPEM_Name_Badges_Admin::$settings_class is deprecated in /home/wazzonau/public_html/wp-content/plugins/wpem-name-badges/admin/wpem-name-badges-admin.php on line 17

Deprecated: Creation of dynamic property WPEM_Name_Badges_Admin::$generate_badges is deprecated in /home/wazzonau/public_html/wp-content/plugins/wpem-name-badges/admin/wpem-name-badges-admin.php on line 24

Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-stripe-split-payment/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 36

Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-stripe-split-payment/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 48

Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-stripe-split-payment/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 26

Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-stripe-split-payment/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 42

Deprecated Code - I have turned debugging on so if you visit the home page of the TEST site, you will see all of the debug warnings. I will also paste them here: Deprecated: Creation of dynamic property WPEM_Registrations::$post_types is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php on line 96 Deprecated: Creation of dynamic property WP_Event_Manager::$forms is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 104 Deprecated: Creation of dynamic property WP_Event_Manager::$post_types is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 105 Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 36 Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 48 Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 26 Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Util/CaseInsensitiveArray.php on line 42 Deprecated: Return type of Stripe\Util\Set::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Util/Set.php on line 40 Deprecated: Return type of Stripe\StripeObject::offsetExists($k) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 186 Deprecated: Return type of Stripe\StripeObject::offsetGet($k) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 196 Deprecated: Return type of Stripe\StripeObject::offsetSet($k, $v) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 181 Deprecated: Return type of Stripe\StripeObject::offsetUnset($k) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 191 Deprecated: Return type of Stripe\StripeObject::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 202 Deprecated: Return type of Stripe\StripeObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/StripeObject.php on line 402 Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/ApiResource.php on line 87 Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/SingletonApiResource.php on line 28 Deprecated: Return type of Stripe\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/stripe-php/lib/Collection.php on line 111 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_testmode is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 58 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_connect is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 60 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 63 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 64 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 65 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 66 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 67 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 68 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_receipt_email is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 72 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_saved_cards is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 75 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_shipping_address is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 78 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_logging is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 80 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_testmode is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 58 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_connect is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 60 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 63 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 64 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 65 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 66 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 67 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 68 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_receipt_email is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 72 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_saved_cards is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 75 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_shipping_address is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 78 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_logging is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 80 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment::$settings_page is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/wp-event-manager-stripe-split-payment.php on line 137 Deprecated: Creation of dynamic property WC_Product_Event_Ticket::$product_type is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-sell-tickets/includes/wp-event-manager-product-event-ticket.php on line 17 Warning: Cannot modify header information - headers already sent by (output started at /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php:96) in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-registrations/includes/wp-event-manager-registrations-register.php on line 346 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_testmode is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 58 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_connect is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 60 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 63 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 64 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_test_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 65 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_clientid is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 66 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_publishablekey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 67 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_live_secretkey is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 68 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_receipt_email is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 72 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_saved_cards is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 75 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_shipping_address is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 78 Deprecated: Creation of dynamic property WPEM_Stripe_Split_Payment_Gateway::$stripe_logging is deprecated in /home/nethosti/test.events4kids.co.uk/wp-content/plugins/wp-event-manager-stripe-split-payment-1_0_2/includes/wpem-stripe-split-payment-gateway.php on line 80

**Comment by live-aamir** [comment]
@jathinkj we are working on it as it is related to **PHP 8.2** , meanwhile ask the client to turn off the debug.

**Comment by jathinkj** [comment]
client has turned off the debug.

**Comment by mistry-jignesh** [comment]
I have verified this issue .Now this issue is fixed. 
Depreciated error message is not availlabel. 
So I closed the issue

**Comment by ritakikani** [comment]
this error comes as we directly initialize public variable in public function in class. We must need to first define variable in class then only we have to use that public variable in any function of that class.

For example.

    Deprecated: Creation of dynamic property WP_Event_Manager_Alerts::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php on line 88

for this error, you can go in wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php file and check, this $post_types variable you used as public variable in function but you didnot define it in class any where.

ans .

class WP_Event_Manager_Alerts {
public $post_types;

public function __construct() {
    $this->post_types = Initialize the here
}

}

NOTE :

The best solution is to explicitly define all properties within the class. This approach ensures compatibility with future PHP versions and aligns with best practices for code clarity and maintainability. Explicitly defining properties avoids relying on workarounds that might become deprecated or less supported in the future.

Explicitly Defining Properties (Recommended Solution)
Define Properties in the Class: Ensure all properties are declared within the class definition.
Initialize Properties in the Constructor: Initialize properties in the constructor or appropriate methods.

ex.

class WP_Event_Manager_Alerts {
public $post_types;

public function __construct() {
    $this->post_types = array(); // Initialize the property
}

}

Why Explicit Definition is Better ?

    Future Compatibility: Ensures code remains compatible with future PHP versions.
    Code Clarity: Makes the code easier to read and understand.
    Maintainability: Simplifies maintenance and debugging.

Using #[AllowDynamicProperties] (Temporary Workaround)
While using #[AllowDynamicProperties] is a valid and quick solution, it should be considered a temporary workaround rather than a permanent fix. This approach is less future-proof and doesn't address the underlying issue of dynamic property creation.
ex.
#[AllowDynamicProperties]
class WP_Event_Manager_Alerts {
// Existing properties and methods
}

Explicitly defining properties is the best and recommended solution for long-term code quality and compatibility. It aligns with best practices and prepares your code for future PHP versions. Use #[AllowDynamicProperties] only as a temporary measure if immediate fixes are needed.

**Comment by ritakikani** [comment]
This fields comes from parent class, so need to remove from child class

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/8b8d869e-52d9-4dce-9dc2-c6bfedd69a57)

**Comment by ritakikani** [comment]
@mistry-jignesh done from my side.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now, a depreciated error message is not available.
This issue is fixed and working properly.
So I closed the issue.
