### ISSUE TITLE
Venue & organizer : Edit - Multiple image is not save

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1674]
First, enable the below option from the field Editor

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/f877650e-4716-4ce4-9689-b4341579241d)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/1231b58c-0e47-4a32-b843-58454e59356d)

Now add a new organizer and venue .

Here add multiple logo for venue and organizer.

Now edit organizer and venue .

Observed that multiple logo image is not show.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now multiple logos are saving properly.
It is working fine. So I closed the issue.

**Comment by ritakikani** [comment]
@mistry-jignesh  logo for anything either event or organizer or venue, must be only 1. Banner can multiple but logo should be only 1, so we need some improve like we have to disable mulitple selection from field editor for organizer and venue logo. and need to revert code which done in this issue.
