### ISSUE TITLE
WPML : Event listing : Button is not trasnlated 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1677]
WPML : Event listing: Button is not translated.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/6001ce69-f850-4a46-b878-d4710ab3c1c9)

**Comment by live-aamir** [comment]
@mistry-jignesh This working fine with WPML. Below is the screenshot.
![Screenshot_18](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/be606a65-6924-452a-9909-cde796f4ef00)

**Comment by mistry-jignesh** [comment]
I have verified this issue. It is working fine.
So I closed it.
