### ISSUE TITLE
Error message is display on the signout page 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1678]
An error message is display on the signout page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/be8dca1d-7de7-4005-8395-7c840c15cd89)

Also display error messages on the event details page and organizer details, Venue details page.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/559dd3d8-709c-414f-a318-a46a15b11b43)

**Comment by live-aamir** [comment]
@mistry-jignesh i ahve fixed the first one, another one is from wordpress.
