### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by jathinkj** [wpeventmanager/wp-event-manager#1679]
disable events from appearing in search results if their registrations are closed.

**Comment by mistry-jignesh** [comment]
If registration is closed then the event is also searched.

![image](https://github.com/user-attachments/assets/5990b3ee-8559-4250-822e-0ee4c1ac4f7d)

![image](https://github.com/user-attachments/assets/2f85afec-c1ca-4e41-8533-8531740a07f6)

**Comment by RHSRSK** [comment]
@mistry-jignesh  To test this feature make sure first you have to enable setting in event listing tab.
https://github.com/user-attachments/assets/39024051-91d3-46b2-bb03-7a1fb1eda03e

**Comment by mistry-jignesh** [comment]
I have taken the latest coreplugin and registration addon.
It is working fine. So Closed the issue.
