### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1681]

**Comment by ritakikani** [comment]
Provide description that why this class is used in comment

![image](https://github.com/user-attachments/assets/bcca7955-6883-48a4-a905-a9a3d59d611a)

**Comment by ritakikani** [comment]
Need to write comment before function

![image](https://github.com/user-attachments/assets/e35f46d8-c3f3-470a-a6d1-05eeb5e9398e)

**Comment by ritakikani** [comment]
for https://github.com/wpeventmanager/wp-event-manager/issues/1664, please revert your code which you push in this bug, and write comment in bug as per we talked and provide code to client in comment.

**Comment by ritakikani** [comment]
delete this file

![image](https://github.com/user-attachments/assets/ad5b7841-94a4-4a21-80f6-af86b335f7b0)

**Comment by ritakikani** [comment]
This is commented code so please remove if condition and commented code + function call in hook.

![image](https://github.com/user-attachments/assets/1a2b9627-1d99-45fd-8b23-ac06717607c5)

**Comment by ritakikani** [comment]
Write proper comment before function

![image](https://github.com/user-attachments/assets/84b39864-b4a1-4ebb-b309-a2601639f341)

**Comment by ritakikani** [comment]
I think this type  (group field) is not in our plugin so please remove this code.

![image](https://github.com/user-attachments/assets/7fd5cbd8-c964-4555-870c-32b0724fb496)

![image](https://github.com/user-attachments/assets/1e1c6073-7a9e-44e4-86ba-a2b6aa3cdbc7)

**Comment by mistry-jignesh** [comment]
Backend side : Edit any event -->  Custom fields section error message is displayed.

![image](https://github.com/user-attachments/assets/d119a5f9-2fb0-4dfa-8207-02388b13a525)

**Comment by RHSRSK** [comment]
This is working fine I did not see any error on staging as well as in localhost
![image](https://github.com/user-attachments/assets/a7d85d21-05a1-4627-b347-9b0c5d21ffbd)
