### ISSUE TITLE
 Custom Field Displays Country Code Instead of Full Country Name in Elementor

### ISSUE THREAD

**Issue by NikhilChangappa** [wpeventmanager/wp-event-manager#1682]
The "Publico" custom field is showing the country code (pt) instead of the full name (Portugal) in Elementor. We need to make it display the full country name. This could be fixed by changing how the field is set up in the backend, or by adjusting how Elementor pulls and displays the data.

ticket :-GTI(#20036)

[275c-61f6-46e3-8aea-c5fc943c10a2 (1) (1).webm](https://github.com/wpeventmanager/wp-event-manager/assets/163304776/e6db5aff-7dab-4eb4-9e55-dbf18b5e8b04)

![Screenshot 2024-07-04 185047](https://github.com/wpeventmanager/wp-event-manager/assets/163304776/1f599918-544e-45e2-a582-c7722c2b2065)

**Comment by RHSRSK** [comment]
[Field Editor ‹ Event Organizer — WordPress.webm](https://github.com/user-attachments/assets/0bed38c9-2e7c-4e09-87e3-00fe729bd908)
This is working fine

**Comment by mistry-jignesh** [comment]
I have checked this issue using elementor.
The country name displays the full name on the event details page. This issue is working fine.

![image](https://github.com/user-attachments/assets/c3e6e026-628d-4980-b004-d7e11b421a28)

So I closed the issue
