### ISSUE TITLE
Translation issue with german language

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1683]
Translation issue with german language.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/463288e0-5220-4cc6-9cf0-d5ab9c66618a)

**Comment by RHSRSK** [comment]
Language Translation issue in German language is solved 
![image](https://github.com/user-attachments/assets/f695d0ec-c736-453b-ad2b-e0b79cf345b9)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
Text is translated into the german language.

![image](https://github.com/user-attachments/assets/00cabb1f-dcaa-46ff-8e4b-7437893c8012)
