### ISSUE TITLE
saving the start time with the start date

### ISSUE THREAD

**Issue by jathinkj** [wpeventmanager/wp-event-manager#1685]
You appear to be saving the start time with the start date, and the end time with the end date; thus 2024-09-12 22:00:00
This means that when you get to the event listings in the content-event_listing.php, content-past_event_listing.php, and content-single-event_listing.php for example, the code that is supposed to prevent a duplication of dates doesn't work.  On the content-event_listing.php for instance, that code is as follows:
<div class="wpem-event-date-time">
<span class="wpem-event-date-time-text">
<?php display_event_start_date(); ?>
<?php
if (!empty($start_time)) {
display_date_time_separator();
}
display_event_start_time();
if (!empty($end_date) || !empty($end_time)) {
?> - <?php
}
if (isset($start_date) && isset($end_date) && $start_date != $end_date) {
display_event_end_date();
}
if (!empty($end_date) && !empty($end_time)) {
display_date_time_separator();
}
display_event_end_time(); ?>
</span>
</div>
By being lazy and not story the date and times separately this part ($start_date != $end_date) will never work.  The dates may be the same but the times will not be.  It would be too difficult to go back and change the way you store these dates etc., so here is my solution.
<div class="wpem-event-date-time">
<span class="wpem-event-date-time-text">
<?php display_event_start_date(); ?>
<?php
if (!empty($start_time)) {
display_date_time_separator();
}
?>
<?php display_event_start_time(); ?>
<?php
if (!empty($end_date) || !empty($end_time)) {
?> - <?php } ?>
<?php
if ((!empty($start_date) && !empty($end_date)) && (substr($start_date, 0, 10) != substr($end_date, 0, 10))) {
display_event_end_date();
if (!empty($end_time)){
display_date_time_separator();
}
// separator is only needed if displaying the date so moved to here
}
?>
<?php display_event_end_time(); ?>
</span>
</div>
I've applied a similar fix to all the other templates where the start and end date might be displayed.

**Comment by RHSRSK** [comment]
As Client said "By being lazy and not story the date and times separately this part ($start_date != $end_date) will never work. The dates may be the same but the times will not be."
But the Start date and End date will never same, if start date and end date is exact same then the event expire on same time when it start and it's not possible and this condition is working fine in our module.
If client want to separate time and date then he/she can use action/filter that we provide or override the template.

**Comment by jathinkj** [comment]
1) Of course the start and end date can be the same, and I can point you to several examples on just one of your reference sites. https://www.motorhype.co.uk/events/ Here's one.
2) The start and end time should have nothing to do with the dates of the event. In the above example the dates are the same but the times are different.
3) If the start and end date can never be the same, why do you check for a match in your code.
You created this issue by storing the event times with the date.  I've provided you with a solution. If you don't want to accept that you've made a mistake and gracefully accept my solution then that's up to you

**Comment by jathinkj** [comment]
<div class="wpem-event-date-time">
<span class="wpem-event-date-time-text">
<?php display_event_start_date(); ?>
<?php
if (!empty($start_time)) {
display_date_time_separator();
}
display_event_start_time(); 
if (!empty($end_date) || !empty($end_time)) {
?> - <?php
} 
if (isset($start_date) && isset($end_date) && $start_date != $end_date) {
display_event_end_date();
}
if (!empty($end_date) && !empty($end_time)) {
display_date_time_separator();
}
display_event_end_time(); ?>
</span>
</div>

By being lazy and not story the date and times separately this part ($start_date != $end_date) will never work.  The dates may be the same but the times will not be.  It would be too difficult to go back and change the way you store these dates etc., so here is my solution.

<div class="wpem-event-date-time">
<span class="wpem-event-date-time-text">
<?php display_event_start_date(); ?>
<?php
if (!empty($start_time)) {
display_date_time_separator();
}
?>
<?php display_event_start_time(); ?>
<?php
if (!empty($end_date) || !empty($end_time)) {
?> - <?php } ?>

<?php
if ((!empty($start_date) && !empty($end_date)) && (substr($start_date, 0, 10) != substr($end_date, 0, 10))) {
display_event_end_date();
if (!empty($end_time)){
display_date_time_separator();
}
// separator is only needed if displaying the date so moved to here
}
?>
<?php display_event_end_time(); ?>
</span>
</div>

**Comment by RHSRSK** [comment]
As per discussion with TechLeader @ritakikani This is working fine in our addon, So we don't need to change anything and If client want change he can overwrite the template and do the changes easily.
