### ISSUE TITLE
Version 3.1.45.1 update.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1695]
Fixed: Solved fatal error on event listing page on front end.

**Comment by mistry-jignesh** [comment]
I have checked the issue and It is fixed.
This milestone is released so I am going to close this issue.

**Comment by chsienki** [comment]
Hi, just a heads up, but 3.1.45.1 isn't available in the wordpress plugin directory yet: https://wordpress.org/plugins/wp-event-manager/. 

If you install or update to latest from WP dashboard you still get the broken version.

**Comment by mistry-jignesh** [comment]
@chsienki 

 Now 3.1.45.1 version is available on the ORG. Please download and install it.

![image](https://github.com/user-attachments/assets/400c4102-474f-4e6f-a4b6-e5b7ac7bdc18)
