### ISSUE TITLE
Plugin check : Error availlabel using General Option

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1697]
Install the plugin Plugin Check (PCP)
https://wordpress.org/plugins/plugin-check/

Set the setting and select the plugin and check it.

Need to fix all warning and errors

-------------------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/4cdcce3c-92a6-4ead-bddb-3d2f26e9cdb3)

![image](https://github.com/user-attachments/assets/338faa49-777a-4929-b2ae-748683a12b56)

![image](https://github.com/user-attachments/assets/9bbb1767-cd8d-4949-b66c-c1c803712650) 

![image](https://github.com/user-attachments/assets/665af26d-55c0-4be5-af76-339537d70a01) 

![image](https://github.com/user-attachments/assets/3dc6977d-4866-4ba3-8475-47b2e15b2192)  

![image](https://github.com/user-attachments/assets/d021789c-ea7f-4cb9-92c8-adf2c8d08bed) 

![image](https://github.com/user-attachments/assets/8b8900f6-0fc8-456a-ad32-70e118646251) 

![image](https://github.com/user-attachments/assets/f9559d33-aae9-438a-9919-938a65f2ef34) 

![image](https://github.com/user-attachments/assets/6c489728-1bac-47a0-b213-d34e9f906fac) 

![image](https://github.com/user-attachments/assets/f0d9912d-2f41-493e-a3ae-2e12b8aa37f4)

![image](https://github.com/user-attachments/assets/bc5f87f0-9c78-42f1-b909-f2d3748da6b6)

![image](https://github.com/user-attachments/assets/106a636d-dada-4c9b-83dd-fbe7de1860fd) 

![image](https://github.com/user-attachments/assets/e04970d7-c899-435b-8264-7e434315df49) 

![image](https://github.com/user-attachments/assets/2b3b06a2-e8c6-4e32-ac12-a5bd06f77247) 

![image](https://github.com/user-attachments/assets/a5943de4-e441-4d1a-8396-c1d45d30d006)

![image](https://github.com/user-attachments/assets/7b1f887b-b17b-4390-8d82-bff297fa2154)  

![image](https://github.com/user-attachments/assets/232abe88-193f-45d8-8d7e-b30c4f6f0eff)

**Comment by RHSRSK** [comment]
All the error is resolved in general settings
![image](https://github.com/user-attachments/assets/513edb4b-4fe9-4f36-92df-ddd7c0bd2afe)

**Comment by mistry-jignesh** [comment]
Now this issue is working fine. So I closed the issue.
