### ISSUE TITLE
Dashboard icons are not display and layout of edit event page also disturbed.

### ISSUE THREAD

**Issue by RHSRSK** [wpeventmanager/wp-event-manager#1701]
![image](https://github.com/user-attachments/assets/0d88920d-7f54-44c0-bab1-2ba524488994)

![localhost_MySite_wp-admin_post php_post=44 action=edit](https://github.com/user-attachments/assets/8e08571f-3842-4be8-b892-04ace301f570)

**Comment by RHSRSK** [comment]
![image](https://github.com/user-attachments/assets/eca11d19-72e3-4bc9-85c2-d496b66c29c8)
![localhost_MySite_wp-admin_post php_post=44 action=edit (2)](https://github.com/user-attachments/assets/2a5691d6-a679-4731-8dab-f01274509c1c)

**Comment by mistry-jignesh** [comment]
I have checked the issue. The dashboard icon and layout page are displayed properly.
So I closed the issue
