### ISSUE TITLE
Event details page warning error message is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1705]
Event details page warning error message is displayed on the page. 

![image](https://github.com/user-attachments/assets/54edb78e-55c4-4f21-8459-a488692e857d)

**Comment by RHSRSK** [comment]
This issue is solved within this bug https://github.com/wpeventmanager/wp-event-manager/commit/21b29cf61185ef68e8f59136c4be7ff315f4b03f

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now, the error message on the event details page is not displayed.
This issue is fixed. So I closed the issue.
