### ISSUE TITLE
When I deactivated calendar addon then first load more events text is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1707]
When I deactivated calendar addon then first load more events text is display.

Clicked on the either box and list view then events are load on the page.

![image](https://github.com/user-attachments/assets/8bffaefe-67b1-4607-81c0-c6343209feba)

**Comment by RHSRSK** [comment]
This issue is solved in #1710
@mistry-jignesh Load More Button is now working fine
https://github.com/user-attachments/assets/33a9551d-3ff9-496c-91e4-31aa06122e67

**Comment by mistry-jignesh** [comment]
I have verified the issue. Still load more event text is displayed on the page.
When I deactivated calendar addon .Need to check it.

**Comment by RHSRSK** [comment]
Now events are display proper after deactivate calendar addon
https://github.com/user-attachments/assets/dad3dbe7-6026-49d8-9df4-5c9d57b80e19

**Comment by mistry-jignesh** [comment]
I have verified the issue. When I deactivated calendar addon .
Here load more event text issue is fixed. 
So I closed the issue.
