### ISSUE TITLE
Adding custom field then default content tab is visible in the backend event page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1708]
Adding a custom field in the field editor then the default content tab is visible in the backend event page.

![image](https://github.com/user-attachments/assets/7ca40b5e-4bf5-4efa-9bcb-4eb684daa64e)

![image](https://github.com/user-attachments/assets/75389fad-0105-4fa5-99c8-da9f976973dd)

**Comment by mistry-jignesh** [comment]
Also, the issue is available on the backend edit venue/organizer page.

![image](https://github.com/user-attachments/assets/d1aa3473-01fe-442c-94b4-5675b84eb29e)


![image](https://github.com/user-attachments/assets/164f1894-d855-48b7-b5cc-05a29df163e2)

**Comment by RHSRSK** [comment]
Now this is working fine
![image](https://github.com/user-attachments/assets/edc488fb-f27c-4119-abe0-d928f24c69b7)
![image](https://github.com/user-attachments/assets/b1481478-6ae5-4d3a-9037-9f45680280ac)
![image](https://github.com/user-attachments/assets/9a44fb5f-38e2-4f16-b2c5-cb77d23859a5)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now custom field default tab content is not visible.
It is working fine. So I closed the issue.
