### ISSUE TITLE
When calendar addon active then list and box shortcode is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1709]
When the calendar addon is active then list and box shortcode are not working.

[events per_page="5" layout_type="box"] 

[events per_page="5" layout_type="list"]

**Comment by RHSRSK** [comment]
This is working fine 
https://github.com/user-attachments/assets/bcd85101-9bba-4677-8e03-3e4172c10e06

**Comment by mistry-jignesh** [comment]
I have checked the issue.Now this issue is working fine.
So I closed the issue.
