### ISSUE TITLE
In between events Map section is available

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1711]
The map section should be displayed after the box and list view.
Currently, it displays the In between events.

![image](https://github.com/user-attachments/assets/22d0621d-a490-4e23-80e6-361ca1ca00f4)

**It should be displayed as below.**

![image](https://github.com/user-attachments/assets/d4342b88-0883-4d62-bc54-fe2b486e8ce3)

**Comment by RHSRSK** [comment]
@mistry-jignesh Google map is load fine on the top of event list and didn't face any issue regarding this.

**Comment by mistry-jignesh** [comment]
I have checked this issue. Now this issue is working fine.
So I closed the issue.
