### ISSUE TITLE
Box view layout is not display proper

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1712]
When I activated the Google Maps addon then box view layout is not displayed properly.

Need to take Google map Version 1.8.8 

![image](https://github.com/user-attachments/assets/fa67d84c-9bcf-4707-a679-a1eb7bdacf13)

**Comment by RHSRSK** [comment]
This is design issue so assigned to @kaushikpokal

**Comment by mistry-jignesh** [comment]
This issue is fixed. So I closed the issue.

![image](https://github.com/user-attachments/assets/63f56186-d9c2-42d3-8df3-420aedeacb7e)
