### ISSUE TITLE
Addons details page details is not visible.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1716]
issue with **WordPress version 6.7**

Click on the WP Event Manager >> Addons

Here Addons details page details are not visible.

![image](https://github.com/user-attachments/assets/743bd14c-3a00-4341-a5d0-35d327dc7317)

It should be displayed below the list.

![image](https://github.com/user-attachments/assets/6fd6123b-3fbf-4677-945a-8dda7d9bd61e)

**Comment by RHSRSK** [comment]
Wordpress 6.7 is not release Once It will release I will check this bug

**Comment by mistry-jignesh** [comment]
As per @RHSRSK :  Once the new WordPress version will be released. She will check this bug.
So I am moving an issue to the new version **3.1.47**

**Comment by RHSRSK** [comment]
Addons page in version 6.7 is working fine 
https://github.com/user-attachments/assets/59ef7aa6-5560-4732-9423-31886b3f1f01

**Comment by mistry-jignesh** [comment]
I have checked the issue in the other setup.
It is working fine. So I closed the issue.
