### ISSUE TITLE
Deprecated error message is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1717]
A deprecated error message is displayed on the page.

We need to enable debugging from the config file.

![image](https://github.com/user-attachments/assets/6e8f7ed6-b646-452b-8f7e-bdee76c9d88c)

**Comment by RHSRSK** [comment]
With enable error log error is not display, And working fine
![image](https://github.com/user-attachments/assets/9fe19ad8-96c3-4d26-ac57-615343951539)
![image](https://github.com/user-attachments/assets/ca502da6-2c13-4d6f-acd7-b4a80c33c1e2)

**Comment by mistry-jignesh** [comment]
Now this error message is not available.
So I closed the issue.
