### ISSUE TITLE
Enable debug log file then event listing page events are not load

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1718]
Enable debug log file then event listing page events are not load.

![image](https://github.com/user-attachments/assets/6846854e-f44d-4afe-b0d2-4b13d02a117c)

**Comment by RHSRSK** [comment]
Event listing works properly you can check in this video with enable error log 
https://github.com/user-attachments/assets/f6ffc202-5122-423c-8e8c-a04cce447977

**Comment by mistry-jignesh** [comment]
Now this issue is working fine. So I closed the issue.
