### ISSUE TITLE
Edit event page is mess-up

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1719]
Edit event page is mess-up.

![image](https://github.com/user-attachments/assets/6b2152e8-61ea-4a97-9060-9ca05af8b60c)

**Comment by RHSRSK** [comment]
Now it is working fine 
![image](https://github.com/user-attachments/assets/c513473c-501f-425e-96bc-63192490da33)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now this issue is fixed.
The page is displayed properly. So I closed the issue.
