### ISSUE TITLE
Post an event  : Add organizer and venue page field name is not visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1721]
Post an event : Add organizer and venue page field name is not visible.

![image](https://github.com/user-attachments/assets/6c1a542a-7023-4a63-a94c-1355a0491a3c) 

![image](https://github.com/user-attachments/assets/f02b820f-5217-49dd-a217-aee1aedaf741)

**Comment by RHSRSK** [comment]
Organizer popup field label :
![image](https://github.com/user-attachments/assets/6ab80c2b-2c0d-4126-83e7-6e2bee4120a0)
Venue popup field label :
![image](https://github.com/user-attachments/assets/e6c8212c-2c02-4d0f-b041-6cb6ff33b2bb)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now fields are visible on the organizer and venue form.
This issue is fixed. So I closed the issue.
