### ISSUE TITLE
Organizer and Venue form button is not display proper

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1723]
The organizer and Venue form button is not displayed properly.

![image](https://github.com/user-attachments/assets/ae3fa34a-f86b-4f9b-af5f-918e91bce16e)

![image](https://github.com/user-attachments/assets/50082961-970a-4b39-a5ef-54d95a0c0ff0)

**Comment by RHSRSK** [comment]
Venue form : 
![image](https://github.com/user-attachments/assets/a5b46c47-40b7-48ec-87b2-8de27a569d30)

Organizer form :
![image](https://github.com/user-attachments/assets/41bd47b8-2968-47ee-abb6-f92269f028cb)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now organizer and venue form submit button is display fine.
Now this issue is fixed. So I closed the issue.
