### ISSUE TITLE
New organizer and venue is not created 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1725]
A new organizer and venue is not created.

**Comment by RHSRSK** [comment]
Organizer and venue is created successfully 
https://github.com/user-attachments/assets/aee028cd-afe8-48f0-8bed-57944f45aaf0

**Comment by mistry-jignesh** [comment]
I have checked the issue. This issue is working fine.

The organizer and venue are created successfully.

So I closed the issue.
