### ISSUE TITLE
Placeholder is missing on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1726]
Placeholder is missing on the page.

![image](https://github.com/user-attachments/assets/7891c528-baf2-4a51-a4e5-8dad0a5f38f6)

**Comment by RHSRSK** [comment]
placeholder is display fine now...
![image](https://github.com/user-attachments/assets/3827838f-63a9-48b1-a128-ec22ce0f13c1)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Still facing the same issue.

![image](https://github.com/user-attachments/assets/4d00e46c-52b2-4dc9-b8ee-f55d6884357f)

It should be like below image.


![image](https://github.com/user-attachments/assets/0602a7ad-85b5-422f-a759-ed52bb8e87c7)

**Comment by RHSRSK** [comment]
![localhost_EventManager_post-an-event_](https://github.com/user-attachments/assets/3abc4147-9dbf-4437-bac9-34933f11bfd2)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now this issue is fixed.
It is  working fine. So I closed the issue.
