### ISSUE TITLE
Backend add event :  In the many text box display ? > symbol

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1731]
Backend : Add event:  In the many text box display  ? > symbol.

![image](https://github.com/user-attachments/assets/80114aee-c5b3-41cf-9093-ef13a34a061d)

**Comment by RHSRSK** [comment]
It's working fine now
![image](https://github.com/user-attachments/assets/1598cd3e-8454-438f-97c4-55aca2fe6d29)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now this issue is fixed.
So I closed the issue.
