### ISSUE TITLE
Event listing :  Box and list view date is missing for event

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1732]
Event listing : The box and list view date for an event are missing.

![image](https://github.com/user-attachments/assets/0b1ccec6-e444-4f38-9ecb-e3eef06cc23c)

![image](https://github.com/user-attachments/assets/74677f84-888e-49df-ac18-53d40992c161)

**It should be like as below.**  

List view : 

![image](https://github.com/user-attachments/assets/bf749de3-20bd-40a7-bb6f-0a9dcb1ec6a1)

Box view :  

![image](https://github.com/user-attachments/assets/23f31ba5-3a6e-4ea7-a5d3-54ca2028e3a3)

**Comment by RHSRSK** [comment]
Date is display fine. Tested on multiple server.

**Comment by mistry-jignesh** [comment]
This issue is working fine on other servers.

![image](https://github.com/user-attachments/assets/814c94f1-5dde-491d-a87e-63390e10d710)

So I closed the issue.

**Comment by RHSRSK** [comment]
This issue solved within #1734 Bug

**Comment by mistry-jignesh** [comment]
This issue is covered #1734 . So I am closed the issue.
