### ISSUE TITLE
Event listing page : When click on the load more button then few events are not visible.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1737]
Event listing page : When clicking on the load more button, a few events are not visible on the page.

[events]

**Comment by RHSRSK** [comment]
@mistry-jignesh  I have checked this issue in our server as well as in local set up It is working fine 
In our server it's just taking some time to load events that's it.
https://github.com/user-attachments/assets/9178d739-7131-4e94-9b45-07220693d6f9
