### ISSUE TITLE
Missing translation in the "Event Listing" filter

### ISSUE THREAD

**Issue by mzeman18** [wpeventmanager/wp-event-manager#1738]
Missing translation in the "Event Listing" filter

![Miss](https://github.com/user-attachments/assets/b08e101a-9888-4fa7-a15e-27c7fabc2f19)

**Comment by RHSRSK** [comment]
Hi @mzeman18, Can you please tell me in which language you faced this translation issue ? 
I checked with German language as well as Hindi language It is working fine 
![image](https://github.com/user-attachments/assets/60a982a6-8769-45be-a85e-e83729954052)
![image](https://github.com/user-attachments/assets/a2c8c60a-4f76-4699-9848-5cd3e352c410)

**Comment by mzeman18** [comment]
@RHSRSK Hello, Czech language.

**Comment by RHSRSK** [comment]
@mzeman18  I tested translation with  Czech language and it is working fine.
Please make sure that you are set language from WordPress dashboard -> settings -> site language option
![image](https://github.com/user-attachments/assets/cc947dac-9b33-4e40-8abc-f8ff5a308d94)

**Comment by mzeman18** [comment]
I have the language settings correctly set to Czech.  In the picture you attached, the translation for one item is incorrect - it is in English.

**Comment by mzeman18** [comment]
@RHSRSK please respond.

**Comment by RHSRSK** [comment]
@mzeman18 Can you please check that language file wp-event-manager-cs_CZ.po in language folder.
For example "Select Date Range" is not translated then you can search this string in this .po file and check the line no of this string in related file is correct or not?

**Comment by mzeman18** [comment]
@RHSRSK the translation is fine. I am using the Divi template.

![CZ](https://github.com/user-attachments/assets/5e87472d-29c6-46ab-91c9-3640c8ef590c)

**Comment by mzeman18** [comment]
@RHSRSK I would also like to add that the translations on lines 2230 and 2234 do not work - see the picture.

![lang](https://github.com/user-attachments/assets/9756293b-a900-47b1-96b4-c026ce55b98e)

**Comment by RHSRSK** [comment]
@mzeman18 Can you please create Support ticket or Can you please give your site details to us?

**Comment by mzeman18** [comment]
Thank you for your help. Resolved by support.
