### ISSUE TITLE
When I deactivated calendar addon then first load more events text is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1739]
When I deactivated calendar addon then first load more events text is display.

Clicked on the either box and list view then events are load on the page. 

![image](https://github.com/user-attachments/assets/67ac5884-a62c-4e5d-be52-e0b6ae7fa91a)

We have already fixed this issue but again this issue is available.
Need to check  issue # : https://github.com/wpeventmanager/wp-event-manager/issues/1707

**Comment by RHSRSK** [comment]
This is working fine now
https://github.com/user-attachments/assets/f6b9c6b4-1e67-49c4-a7d2-51bab85f60b1

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now this issue is fixed.
So I closed the issue.
