### ISSUE TITLE
Backend : Custom field default content value is visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1741]
The custom field default content value is visible.

![image](https://github.com/user-attachments/assets/e9b4a7d5-31a1-49ae-a8f5-82b5838c53f5)

**Comment by mistry-jignesh** [comment]
I have checked the issue when I edit old events from the backend side.
Still, issue is available.
![image](https://github.com/user-attachments/assets/6b4fc00c-ee9e-4359-a681-7dcd8720a900)

**Comment by RHSRSK** [comment]
@mistry-jignesh This is working fine as per when we add new field with field editor and check it in event edit page that default address is not display in that new added field.
https://github.com/user-attachments/assets/51427764-e9c8-46be-88df-b63cfea7d4ed
