### ISSUE TITLE
Past events do not display titles with ASC order 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1744]
Past events do not display titles with ASC order.

[past_events per_page="5" orderby="title"order="ASC"]

![image](https://github.com/user-attachments/assets/27098465-ab20-4f11-b577-6f2e9244a0c1)

**Comment by RHSRSK** [comment]
@mistry-jignesh  This shortcode is working fine. Please add one space before order="ASC" in your shortcode which is mention you in bug description.

**Comment by mistry-jignesh** [comment]
Need to add space before order="ASC" in your shortcode . This issue is working fine.
So I closed the issue.
