### ISSUE TITLE
Google map is not load on Event listing page after filters

### ISSUE THREAD

**Issue by RHSRSK** [wpeventmanager/wp-event-manager#1753]
![image](https://github.com/user-attachments/assets/0650f60c-b61d-40f2-8ed0-cfb188d90904)

**Comment by mistry-jignesh** [comment]
I have checked the issue. Now this issue is fixed.


![image](https://github.com/user-attachments/assets/83c2a324-6387-43f8-8eb1-29962db9c091)

So I closed the issue.
