### ISSUE TITLE
Notice error message is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1754]
Notice error message is display on the page.

![image](https://github.com/user-attachments/assets/1f53cb47-5898-400b-aa7d-634d7d156a3c)

**Comment by RHSRSK** [comment]
@mistry-jignesh I have checked in our staging site but I could not see any error message on backend as well as in front end.(with error log - on mode)
![image](https://github.com/user-attachments/assets/aa51f989-3a35-4901-9c60-0aba38d97cf5)

**Comment by mistry-jignesh** [comment]
I have checked the issue. This error message no longer is available.
So I closed the issue.
