### ISSUE TITLE
Filter out types in past events list

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#176]
Still, I wonder: wouldn’t it be more practical to just add a time option to the [events] shortcode/function than to copy-paste the whole element?

Especially considering there is already a daterangepicker filter GUI on top of the lists…

A simple next/current/previous selector would probably do the trick.

Another proposal: I think it would be simpler to just filter out these passed or previous events based on date end if it exists, the date starts otherwise than adding an extra “Listing Expiry Date” that comes to be mandatory when an event doesn’t have any end time.
I think it adds an unnecessary level of complexity: does anyone use another expiry date than the date of the event itself?

**Comment by krinaydhanani** [comment]
Please put proper comment with screen shots so tester can easily understand and test it well.
