### ISSUE TITLE
Sendingblue icon change

### ISSUE THREAD

**Issue by kaushikpokal** [wpeventmanager/wp-event-manager#1760]
![image](https://github.com/user-attachments/assets/5495352a-7ef7-4096-8913-bdfa7f29ec0b)

**Comment by mistry-jignesh** [comment]
I have checked the issue . Now Sendinblue issue is changed.
![image](https://github.com/user-attachments/assets/6f7e1aed-483f-412d-8ef1-52eb048c3b24)
So I closed the issue.
