### ISSUE TITLE
Author Meta Box at admin panel

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#181]
We need an author meta box so the user can change easily author(organizer) from the admin panel instead of showing Combobox id. 

Please have look below.

<img width="1148" alt="Screenshot 2020-04-19 at 23 27 53" src="https://user-images.githubusercontent.com/15089059/79700414-b3699300-8295-11ea-8652-f049138f482b.png">

**Comment by ritakikani** [comment]
@ashokdudhat , we already provide Organizer meta box for Event Organizer, and the "posted by" id is a author of the event which is default functionality provided by the wordpress itself.So we cannot interrupt it.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  :  We already provide an Organizer meta box for Event Organizer, and the "posted by" id is a author of the event which is the default functionality provided by the WordPress itself. So we cannot interrupt it.

So I closed the issue.
