### ISSUE TITLE
Default event category and type dropdown

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#183]
Unless an event category and type is added to new events, the categories and type dropdown is not seen on the event listing page. please make sure, to show the drop-down irrespective of mentioning of any event category or type.
![Screenshot_5](https://user-images.githubusercontent.com/65893994/82800112-c543e480-9e98-11ea-96f6-78a012a03407.png)
![Screenshot_6](https://user-images.githubusercontent.com/65893994/82800104-c1b05d80-9e98-11ea-92b9-de5a8b84dd05.png)
![Screenshot_7](https://user-images.githubusercontent.com/65893994/82800158-d68cf100-9e98-11ea-8cbc-d2a953ea11d0.png)
![Screenshot_8](https://user-images.githubusercontent.com/65893994/82800154-d55bc400-9e98-11ea-98c7-d606b36cade3.png)/;

**Comment by krinaydhanani** [comment]
Now it's working fine.
