### ISSUE TITLE
Show Organizer data in single event page.

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#185]
Show Organizer data single event page when organizer separate post type.

**Comment by krinaydhanani** [comment]
Please put proper comment with screen shots so tester can easily understand and test it well.

**Comment by wpem-kishan** [comment]
Organizer data on single event page.

![image](https://user-images.githubusercontent.com/61741365/93068630-61893580-f69a-11ea-90b3-7487665d22e7.png)

**Comment by krinaydhanani** [comment]
It's working fine.
