### ISSUE TITLE
Multiple dropdown says “0 selected” on mobile

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#186]
I have the user front-end submission form set up with 2 multi-select fields – one for the event type and another with custom values.

I have now noticed that when using it on a mobile the dropdown says “0 selected” even though options have been chosen. The pop up to select options works and I can tap on them but they do not appear once chosen.

I have tested it on 3 mobiles and it only works on a small screen Nokia. It does not work on my primary Samsung S10+ or a Motorola G5 I also use for testing. Turning the screen landscape on these phones also does not fix the problem. It works fine on an iPad and PC.

Do you have any suggestions to fix this and is it a known issue?

Thanks!

**Comment by wpem-kishan** [comment]
https://harvesthq.github.io/chosen/

**Comment by ritakikani** [comment]
As per me, this is an issue of mobile browser, so we are not able to resolve this. 

For more information, please read below thread, this may help.

https://stackoverflow.com/questions/16152671/multiselect-field-displays-0-items-instead-of-actual-option-names-anyone-fixed

https://github.com/harvesthq/chosen/issues/2746

 https://forums.cubecart.com/topic/56504-advanced-search-on-phone-odd-item/

**Comment by mistry-jignesh** [comment]
As per comment :  This is an issue of mobile browser, so we are not able to resolve this.

For more information, refer above URL .
