### ISSUE TITLE
Delete event option need to improve

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#187]
We are not interested at the end of the day, we are interested only in the end of the event (immediately, when event is finished > means event not displayed anymore > gone). We are here with 3 people and not 1 understand what you mean to say 2 days long already.

**Comment by wpem-kishan** [comment]
I have fixed this issue. Please check settings : https://prnt.sc/t4wuta

**Comment by krinaydhanani** [comment]
Please put proper comment with screen shots so tester can easily understand and test it well.

**Comment by wpem-kishan** [comment]
I fixed this issue. You can check on staging site because cronjob not working on localhost. Crobjob running every hour so delete event when cronjob run.

**Comment by krinaydhanani** [comment]
It's working fine.
