### ISSUE TITLE
date select as per shortcode parameter

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#190]
date select as per shortcode parameter in event listing shortcode

**Comment by krinaydhanani** [comment]
Please put proper comment with screen shot so taster can understand easily and verify it.

**Comment by wpem-kishan** [comment]
[events selected_datetime="2020-08-01,2020-08-31"]
[events selected_datetime="today,2020-08-31"]
[events selected_datetime="tomorrow,2020-08-31"]

**Comment by ritakikani** [comment]
Do i need to change date format of datepicker or Date Format from settings to test this code?
Please provide proper information so i can test code and verify.

**Comment by wpem-kishan** [comment]
Yes, you can add as per your date picker format.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/the-event-listings/
