### ISSUE TITLE
Event Listing and other Shortcodes for Visual Editor

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#194]
Please add the following shortcodes option to visual editor.

Past Events
The Event Dashboard
The event listings
The event submission form
The Event Summary
The Single Event Listing

Same like we have done for the WP User profile avatar.

**Comment by bikasraj** [comment]
//For Past Events

// Add a shortcode for past events
function wpem_past_events_shortcode($atts) {
    $args = array(
        'post_type' => 'event', 
        'posts_per_page' => -1,
        'meta_key' => '_event_end_date',      
        'orderby' => 'meta_value',
        'order' => 'DESC',
        'meta_query' => array(
            array(
                'key' => '_event_end_date',
                'value' => date('Y-m-d'),
                'compare' => '<',
                'type' => 'DATE',
            ),
        ),
    );

    $query = new WP_Query($args);

    if ($query->have_posts()) {
        ob_start();
        ?>
        <ul>
            <?php while ($query->have_posts()) : $query->the_post(); ?>
                <li><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></li>
            <?php endwhile; ?>
        </ul>
        <?php
        wp_reset_postdata();

        return ob_get_clean();
    } else {
        return 'No past events found.';
    }
}
add_shortcode('past_events', 'wpem_past_events_shortcode');

**Comment by bikasraj** [comment]
//For The event listings and The event submission form

// Shortcode for Event Listings
function event_listing_shortcode($atts) {
    ob_start();
    echo do_shortcode('[event_listing]');
    return ob_get_clean();
}
add_shortcode('event_listing', 'event_listing_shortcode');

// Shortcode for Event Submission Form
function event_submission_form_shortcode($atts) {
    ob_start();
    echo do_shortcode('[submit_event_form]');
    return ob_get_clean();
}
add_shortcode('event_submission_form', 'event_submission_form_shortcode');

// Shortcode for Event Dashboard
function event_dashboard_shortcode($atts) {
    ob_start();
    echo do_shortcode('[event_dashboard]');
    return ob_get_clean();
}
add_shortcode('event_dashboard', 'event_dashboard_shortcode');

// Shortcode for Single Event Page
function single_event_shortcode($atts) {
    $atts = shortcode_atts(array(
        'id' => null, // Specify the event ID here if needed
    ), $atts);

    ob_start();
    echo do_shortcode('[single_event id="' . $atts['id'] . '"]');
    return ob_get_clean();
}
add_shortcode('single_event', 'single_event_shortcode');

**Comment by pinky-mahto** [comment]
// Add this code to your theme's functions.php file or a custom plugin

// Shortcode to display past events
function past_events_shortcode($atts) {
    // Add your logic to retrieve and display past events here
    return '<div class="past-events">...</div>';
}
add_shortcode('past_events', 'past_events_shortcode');

// Shortcode for the Event Dashboard
function event_dashboard_shortcode($atts) {
    // Add your logic for the event dashboard here
    return '<div class="event-dashboard">...</div>';
}
add_shortcode('event_dashboard', 'event_dashboard_shortcode');

// Shortcode for the event listings
function event_listings_shortcode($atts) {
    // Add your logic for displaying event listings here
    return '<div class="event-listings">...</div>';
}
add_shortcode('event_listings', 'event_listings_shortcode');

// Shortcode for the event submission form
function event_submission_form_shortcode($atts) {
    // Add your logic for the event submission form here
    return '<div class="event-submission-form">...</div>';
}
add_shortcode('event_submission_form', 'event_submission_form_shortcode');

// Shortcode for the Event Summary
function event_summary_shortcode($atts) {
    // Add your logic for displaying the event summary here
    return '<div class="event-summary">...</div>';
}
add_shortcode('event_summary', 'event_summary_shortcode');

// Shortcode for the Single Event Listing
function single_event_listing_shortcode($atts) {
    // Add your logic for displaying a single event listing here
    return '<div class="single-event-listing">...</div>';
}
add_shortcode('single_event_listing', 'single_event_listing_shortcode');

You can then use these shortcodes in the visual editor by entering them in the post or page content. For example:
[past_events]
[event_dashboard]
[event_listings]
[event_submission_form]
[event_summary]
[single_event_listing]

**Comment by mistry-jignesh** [comment]
I have verified this issue. I have found an issue with the visual editor.
After fix issues #: 1610,1611,1612.  I will closed the issue.

**Comment by mistry-jignesh** [comment]
I have created visual editor issues separately.
It is working fine. So I closed the issue.
