### ISSUE TITLE
Event should automatically expire on event end date if selected that settings

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#195]
After testing it has been found that when I select this option on the backend, the listings must automatically expire on the event end date even if the expiry date option is left blank. However, Even though this option is selected there is a compulsion to mention event expiry date, if not, the event listing still appears on the frontend.

![image](https://user-images.githubusercontent.com/65893994/85292466-8ca82280-b4b9-11ea-884c-4872925cd9e2.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/85362966-72178d00-b53d-11ea-856b-804760ac984f.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/85363029-8491c680-b53d-11ea-8382-70341b8d0f5e.png)
https://wordpress.org/support/topic/event-expiry-date-not-set-on-same-date-as-end-date-automatically/

**Comment by wpem-kishan** [comment]
@Priya-Goenka I have already fixed.
https://github.com/wpeventmanager/wp-event-manager/issues/187
