### ISSUE TITLE
Loading more events fails when show_filters=false

### ISSUE THREAD

**Issue by MatthiasKunnen** [wpeventmanager/wp-event-manager#196]
When using `[events show_filters="false"]`, clicking the load more button results in an error.

The problem seems to be that with filters disabled, the search arguments used in the `get_listings` AJAX call do not get set correctly.

Params with `[events show_filters=false]`:
```
lang: 
search_keywords: 
search_location: 
search_datetimes: Any Date,Today,Tomorrow,This Week,This Weekend,This Month,This Year,Next Week,Next Weekend,Next Month,Next Year
search_categories: 
search_event_types: 
search_ticket_prices: Any Ticket Price,Paid,Free
per_page: 10
orderby: meta_value
order: ASC
page: 2
show_pagination: false
```

Params with `[events]`
```
lang: 
search_keywords: 
search_location: 
search_datetimes[]: 
per_page: 10
orderby: meta_value
order: ASC
page: 2
show_pagination: false
form_data: search_keywords=&search_location=&search_datetimes%5B%5D=
```

## Error
> ( ! ) Notice: Trying to access array offset on value of type null in wp-event-manager/wp-event-manager-functions.php on line 275

Call stack
| # | Time | Memory | Function | Location|
| --- | --- | --- | --- | --- |
| 1 | 0.0062 | 408472 | {main}( ) | .../index.php:0|
| 2 | 0.0680 | 410728 | require( 'wp-blog-header.php' ) | .../index.php:5|
| 3 | 3.1213 | 56532848 | require_once( '/var/www/html/web/wp/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19|
| 4 | 3.1214 | 56532848 | do_action( ???, ...variadic() ) | .../template-loader.php:13|
| 5 | 3.1214 | 56533224 | WP_Hook->do_action( ??? ) | .../plugin.php:478|
| 6 | 3.1214 | 56533224 | WP_Hook->apply_filters( ???, ??? ) | .../class-wp-hook.php:312|
| 7 | 3.1214 | 56534416 | WP_Event_Manager_Ajax::do_em_ajax( ??? ) | .../class-wp-hook.php:288|
| 8 | 3.1215 | 56534496 | do_action( ???, ...variadic() ) | .../wp-event-manager-ajax.php:126|
| 9 | 3.1215 | 56534872 | WP_Hook->do_action( ??? ) | .../plugin.php:478|
| 10 | 3.1215 | 56534872 | WP_Hook->apply_filters( ???, ??? ) | .../class-wp-hook.php:312|
| 11 | 3.1215 | 56536000 | WP_Event_Manager_Ajax->get_listings( ??? ) | .../class-wp-hook.php:288|
| 12 | 3.1218 | 56555832 | get_event_listings( ??? ) | .../wp-event-manager-ajax.php:231|

Plugin version: 3.1.13

Sidenote, I observed similar problems with 3.1.11 regarding `search_ticket_prices'

**Comment by wpem-kishan** [comment]
I checked on our demo, load more working fine. Please check below link:
https://staging-wpeventmanagerdemo.kinsta.cloud/event-listings/

**Comment by MatthiasKunnen** [comment]
This demo does not have `show_filters=false`. This bug only happens when filters are disabled.
Examples:
- [show_filters=false](https://biovox.eu/events-broken)
- [show_filters=true](https://biovox.eu/events)

**Comment by MatthiasKunnen** [comment]
The demo does not have `show_filters=false`. This bug only happens when filters are disabled.
Examples:
- <https://demo.wp-eventmanager.com/qut0ixzys8okg17/blog/showfilters-false/>
- <https://demo.wp-eventmanager.com/qut0ixzys8okg17/blog/showfilters-true/>

**Comment by hiteshmakvana** [comment]
#174
