### ISSUE TITLE
I can see 2 buttons with same name on single event organizer page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#198]
I can see 2 buttons with the same name on single event organizer page. 

And more info means which information you provide after a click on more info button.

![organizer](https://user-images.githubusercontent.com/35419531/85386546-60e07780-b561-11ea-8929-a177fa2d00a2.png)

**Comment by wpem-kishan** [comment]
we have merge wp-event-manager-organizers addons core plugins so before testing deactivate wp-event-manager-organizers plugins.

**Comment by krinaydhanani** [comment]
After deactivating wp-event-manager-organizers plugins I can see one MORE INFO button but It's not working.

When I clicked on it only the page will be refresh.

**Comment by krinaydhanani** [comment]
Now It's working fine.
