### ISSUE TITLE
Do separate events and event name on Organizer Dashboard page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#199]
Do separate events and event name section on Organizer Dashboard page.

![organizer_dashboard](https://user-images.githubusercontent.com/35419531/85390469-7c01b600-b566-11ea-84bb-9ae8bfa04acd.png)

**Comment by wpem-kishan** [comment]
1 is is not an event. 1 is count of Organizer how many times used in event.

**Comment by krinaydhanani** [comment]
Make a separate column for both.

Event and Organizer count.
