### ISSUE TITLE
Do separate events and event name on Venue Dashboard page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#201]
Do separate events and event name on Venue Dashboard page.

![venue_dashboard_1](https://user-images.githubusercontent.com/35419531/85393667-01876500-b56b-11ea-9ee0-5147e1ab0bc0.png)

**Comment by wpem-kishan** [comment]
1 is is not an event. 1 is count of Venue how many times used in event.

**Comment by krinaydhanani** [comment]
Make a separate column for both. 

Event and Venue count.
