### ISSUE TITLE
Require URL behind event name.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#205]
Require URL behind event name on organizer dashboard, so when users click on it we redirect them on the event.

![organizer_url](https://user-images.githubusercontent.com/35419531/85402967-364ee880-b57a-11ea-909b-4dc352951c58.png)

**Comment by hiteshmakvana** [comment]
Need proper design on the event section.

**Comment by krinaydhanani** [comment]
Yes, I test it.

It's working fine.
