### ISSUE TITLE
Use separator between 3 options in the event organizer page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#208]
Use separator between 3 options in the event organizer page.

![organizer_separator](https://user-images.githubusercontent.com/35419531/85511207-ffc6ab80-b615-11ea-95c6-e0fa27114bf8.png)

**Comment by wpem-kishan** [comment]
There is tabs so why we add separator

**Comment by hiteshmakvana** [comment]
It is just small div problem try to use wpem row or wpem-col to make proper structure it will automatically separate them

**Comment by krinaydhanani** [comment]
I can't see any changes on this page.

**Comment by krinaydhanani** [comment]
Now it's look good and working fine.
