### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#210]
[past_events orderby="event_start_date"] not working
![image](https://user-images.githubusercontent.com/65893994/85656481-6c9d7c80-b6ce-11ea-8e8b-0201e861aae5.png)
![image](https://user-images.githubusercontent.com/65893994/85656512-758e4e00-b6ce-11ea-8c49-401b99ca8af4.png)

**Comment by Priya-Goenka** [comment]
Still Not working

**Comment by wpem-kishan** [comment]
@Priya-Goenka when you test please download latest plugin form here and upload on your site.

**Comment by Priya-Goenka** [comment]
Can I please get the changes done in the file here. The user can't wait till the update releases.

**Comment by Priya-Goenka** [comment]
fixed
