### ISSUE TITLE
Cancelled event- No Notification

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#223]
Once as an organizer I marked an event cancelled from the frontend, there is no notification on the backend to Admin. Also, the admin panel should display some other colour instead of green for events that are cancelled.
![image](https://user-images.githubusercontent.com/65893994/87044124-be3c2000-c213-11ea-8855-721f55cae903.png)![image](https://user-images.githubusercontent.com/65893994/87044025-96e55300-c213-11ea-92b4-02b5bbcd3cad.png)

**Comment by wpem-kishan** [comment]
we already show admin side column.

![image](https://user-images.githubusercontent.com/61741365/91853798-5a1c6200-ec80-11ea-884f-b8e1f32a1bfc.png)

**Comment by krinaydhanani** [comment]
Working fine. We already provide cancelled column so users can understand easily.
