### ISSUE TITLE
Shortcodes not working

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#224]
1.order="ASC" "DESC"
2. There should be shortcode for enabling or disabling **Keyword/location/date** as well, Just like show_categories, show_types, show_ticket_prices
3. If show_filter="false", show_categories="true", the search bar should show category dropdown, It is showing all the filters.
4.[show_filters="false" show_pagination="true"](Not working)(New events are not loaded, same page comes again)
5.**[events per_page="2" show_filters="false" categories="fitness" show_pagination="true"]** not working, the events are not filtered according to fitness category, rather more events are displayed when page 2 is clicked, more on 3rd page..likewise
However, when shortcode, **[events per_page="10" show_filters="false" categories="fitness" show_pagination="true"]** is entered, the events are displayed on basis of fitness category(Please see there are only 4 events based on category Fitness)
6. **[events per_page="1" show_filters="true" event_types="test" show _pagination="true"]** the pagination does not works, shows, load more instead on 1-2-3
7. **[events per_page="5" keyword="Recurring" ]** **[events per_page="5" show_filters="false" keyword="Recurring" ]**(not working, it does not shows events by selected keyword(recurring)
8.**[events per_page="5" show_filters="false" selected_event_type="test"]** Doesnot classify events by selected type. while,[events per_page="5" selected_event_type="test"] does classify the events according to types.

**Comment by sapnadudhat03** [comment]
This is the doc in which we have added above shortcodes: https://wp-eventmanager.com/knowledge-base/the-event-listings/.

Need to fix this issue.

**Comment by Priya-Goenka** [comment]
[events selected_categories="fitness"]

**Comment by wpem-kishan** [comment]
@Priya-Goenka before add shortcode please check shorcode parameter name.
[events selected_category="fitness"]

**Comment by wpem-kishan** [comment]
@Priya-Goenka use below shortcode and verify
1. [events orderby="event_start_date" order="ASC"]
2. follow event setting in admin side
3. [events show_filters="false" show_pagination="true"]
4. [events show_filters="false" show_pagination="true" per_page="3"]
5. [events show_filters="false" show_pagination="true" per_page="3" selected_category="fitness"]
6. [events show_filters="false" show_pagination="true" per_page="3" selected_event_type="attraction"]
7. [events keywords="Recurring"] OR [events show_filters="false" keywords="Recurring"]
8. [events show_filters="false" show_pagination="true" per_page="3" selected_event_type="attraction"]

**Comment by krinaydhanani** [comment]
All the filters working fine.
