### ISSUE TITLE
Add new post- Add new organizer

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#225]
Please see the heading of the page should be add new organizer.

![image](https://user-images.githubusercontent.com/65893994/87125087-88487b80-c2a7-11ea-9e9a-74aa477ffde2.png)

**Comment by sapnadudhat03** [comment]
Heading should be "Add New Organizer"

**Comment by krinaydhanani** [comment]
Now it's working fine.
