### ISSUE TITLE
Inspite of selecting the page, shortcode doesnot appears automatically!

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#227]
![image](https://user-images.githubusercontent.com/65893994/87128470-4a4e5600-c2ad-11ea-8ad0-cd8a92f47e59.png)
![image](https://user-images.githubusercontent.com/65893994/87128532-66ea8e00-c2ad-11ea-9f9e-f6999ff0ec21.png)

**Comment by hiteshmakvana** [comment]
In some case, people want to use two separate page with different shortcode attributes.

This is required to work with dashboard.
