### ISSUE TITLE
Submit organizer form page and dashboard not visible on frontend

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#228]
![image](https://user-images.githubusercontent.com/65893994/87161016-89969a00-c2e1-11ea-8080-b08d0f116c27.png)
![image](https://user-images.githubusercontent.com/65893994/87161051-92876b80-c2e1-11ea-8701-1d7c03880d81.png)

**Comment by wpem-kishan** [comment]
I have checked both pages working fine with shortcode.
