### ISSUE TITLE
Silk Js file 

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#230]
Silk Js file, we need it in the core for which purpose?

**Comment by ashokdudhat** [comment]
https://speckyboy.com/open-source-carousel-sliders-css/
https://css-tricks.com/css-only-carousel/

**Comment by hiteshmakvana** [comment]
We need it for single event page slider section. Need to discuss with designer about the slider section if not needed then we can delete it.

**Comment by hiteshmakvana** [comment]
This is required for slider addon and core plugin slider section in multiple banner.
