### ISSUE TITLE
Remove unnecessary icons

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#231]
<img width="1074" alt="Screenshot 2020-07-12 at 16 34 15" src="https://user-images.githubusercontent.com/15089059/87249125-904a1c00-c45d-11ea-9d73-357a3cece4a7.png">

**Comment by wpem-kishan** [comment]
I have checked all images, below two images not used.
- organizer.png
- wpem-share-icon.svg

**Comment by hiteshmakvana** [comment]
Just remove organizer icon share will implement in future version or customize user can use it

**Comment by krinaydhanani** [comment]
It's done.
