### ISSUE TITLE
Cleaning JS folder and unnecessary jQuery UI folder.

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#232]
As per WordPress standard and their documentation, they are offering jQuery UI files.

Please check https://developer.wordpress.org/reference/functions/wp_enqueue_script/#notes

Please clean this js folder.
<img width="472" alt="Screenshot 2020-07-12 at 18 06 41" src="https://user-images.githubusercontent.com/15089059/87251245-77943300-c46a-11ea-99d2-904042b4f4f5.png">

**Comment by wpem-kishan** [comment]
I checked right now all js file used in our plugin. When we add custom slider on single event page after we will remove slick folder.

**Comment by krinaydhanani** [comment]
It's working fine.
