### ISSUE TITLE
Move to trash events older than

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#234]
This option allows you to automatically move past events to trash.
<img width="763" alt="Screenshot 2020-07-12 at 21 08 36" src="https://user-images.githubusercontent.com/15089059/87254584-de721600-c483-11ea-97de-8d03da9bffce.png">

**Comment by wpem-kishan** [comment]
We alredy given setting for that.

![image](https://user-images.githubusercontent.com/61741365/91939630-cdbb7f00-ed13-11ea-8e1d-4dcf9ca9518d.png)

**Comment by krinaydhanani** [comment]
We already provide this feature.
