### ISSUE TITLE
Permanently delete events older than

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#235]
This option allows you to bulk delete past events. Be careful and backup your database before removing your events as there is no way to reverse the changes.

<img width="783" alt="Screenshot 2020-07-12 at 21 10 48" src="https://user-images.githubusercontent.com/15089059/87254638-301aa080-c484-11ea-9fad-ad18f1cb0f9a.png">

**Comment by wpem-kishan** [comment]
we have already give setting.

![image](https://user-images.githubusercontent.com/61741365/91853672-2b9e8700-ec80-11ea-916d-9072f32d318a.png)

**Comment by krinaydhanani** [comment]
We already provide this feature.
