### ISSUE TITLE
change old documentation link in setup wizard

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#237]
We have to change all old documentation link in WP Event Manager core plugin.

<img width="1440" alt="Screenshot 2020-07-12 at 21 19 22" src="https://user-images.githubusercontent.com/15089059/87254783-6c9acc00-c485-11ea-8c47-3207cd3d47b2.png">

**Comment by krinaydhanani** [comment]
It's working fine.
