### ISSUE TITLE
Design is not fit for the date selection

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#238]
<img width="1312" alt="Screenshot 2020-07-12 at 21 24 01" src="https://user-images.githubusercontent.com/15089059/87254838-0cf0f080-c486-11ea-99d7-c37790840d2d.png">

**Comment by siddharthgotawala** [comment]
Please check now

**Comment by siddharthgotawala** [comment]
Already Concerned with @ashokdudhat and @hiteshmakvana 
#5 & #238 same issue

**Comment by hiteshmakvana** [comment]
This is clear now we will not add any kind of extra css to make calendar fancy. It will automatically adapt the css of the theme.
