### ISSUE TITLE
Show comments setting option for admin

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#240]
Enable comments on event pages. if it is enabled then it will show at single event page.

**Comment by wpem-kishan** [comment]
If you don't show comment section then add below code on functions.php

```
function wpem_comment_disable( $open, $post_id ) 
{
    $post_type = get_post_type( $post_id );

    if ( $post_type == 'event_listing' ) {
        return false;
    }

    return true;
}
add_filter( 'comments_open', 'wpem_comment_disable', 10 , 2 );
```

**Comment by krinaydhanani** [comment]
It's working fine.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1ipTLsd-VjTSWFygH7Xf-KtDCqehE2lwmlJ5PxDoKhDI/edit

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Add in live site.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/hide-comment-on-listing-page/
