### ISSUE TITLE
List Venues and Organizers Shortcodes

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#243]
https://theeventscalendar.com/extensions/list-venues-and-organizers-shortcodes/

**Comment by krinaydhanani** [comment]
It's working fine. we have added all the short code.

**Comment by gorfreed** [comment]
Sorry, but this is not true. I cannot find any similar shortcode for the functionality described by the link of the issue @ashokdudhat (https://theeventscalendar.com/extensions/list-venues-and-organizers-shortcodes/). I am looking for exactly the same feature!
