### ISSUE TITLE
While setting up the Widget Up coming Events, Order by- Event start date doesnot works-

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#244]
![image](https://user-images.githubusercontent.com/65893994/87429955-23bc5200-c602-11ea-87ce-42eb9dc03a7f.png)
![image](https://user-images.githubusercontent.com/65893994/87430080-4d757900-c602-11ea-9a11-00ffaa4dfd1f.png)

**Comment by sapnadudhat03** [comment]
https://crmplus.zoho.com/wpeventmanager/index.do/cxapp/support/wpeventmanager/ShowHomePage.do#Cases/dv/505728000001476003

**Comment by krinaydhanani** [comment]
Upcoming event feature not working.

**Comment by wpem-kishan** [comment]
I have verified working fine. Please double check then add or reopen bug.

**Comment by krinaydhanani** [comment]
It's working fine.
