### ISSUE TITLE
Adding filter dropdowns at Event dashboard page.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#245]
![image](https://user-images.githubusercontent.com/65893994/87673557-5f862180-c792-11ea-8b0b-143e557a8bc9.png)

**Comment by krinaydhanani** [comment]
We should provide some highlier so the user can understand easily we are providing the shorting.

**Comment by krinaydhanani** [comment]
It's working fine.
