### ISSUE TITLE
Event list view in Elementor as well. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#246]
Making List view as a default view should also be available in Elementor. It can now only happen via shortcode, not elementor.

**Comment by hiteshmakvana** [comment]
Result is not populating under filters?

**Comment by live-aamir** [comment]
@mistry-jignesh i have tested it with @Priya-Goenka this is working fine. Below is the configuration screenshot.
![Screenshot 2024-02-01 144006](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/5cd70421-fb85-415c-8534-f01d94bba51a)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Event list view type is available.
This issue is working fine. So I closed the issue.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/3a8d3e91-f898-4dcb-9131-f708642374e3)
