### ISSUE TITLE
After edit expire event date it will not show in Active.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#248]
After edit expire event date the status will not update to Active.

**Comment by wpem-kishan** [comment]
If we edit event from front side then we change expire event date but If we event edit from admin site then need to change expire event date because we provide expire event date input box.

**Comment by krinaydhanani** [comment]
I think we need to provide facility to user when user change the event end date that time the expiry event date change automatically.

**Comment by hiteshmakvana** [comment]
For adminsid we don't need to double verify because there is already field with data if they update it will override the value.
