### ISSUE TITLE
Need to improve design.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#252]
We need to improve design of event-summary.

https://demo.wp-eventmanager.com/event-summary/

![image](https://user-images.githubusercontent.com/35419531/88547153-f4aed300-d03a-11ea-8203-efef3d4091e7.png)

**Comment by siddharthgotawala** [comment]
We have fixed this issue kindly recheck.

**Comment by krinaydhanani** [comment]
Now it's look good.
