### ISSUE TITLE
Need to fix image duplication issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#254]
We need to images duplication issue. Event banner will automatically duplicate in backed.

**Comment by krinaydhanani** [comment]
I try to find out the duplication issue much time but I can not reproduce it. If I found in future anything regarding duplication I will open the issue with proper stapes.

**Comment by tamanna-ahuja** [comment]
Would request you to close this issue if we are not able to reproduce now

**Comment by mistry-jignesh** [comment]
I have verified issue . 

Now this issue working fine. Image banner not duplicate in the media folder.

So I closed the issue.
