### ISSUE TITLE
ELEMENTOR : - Need to improve elementor for change font , font size , font color.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#261]
Please consider adding Styling options to Elementor elements like all other elementor elements from other plugins. i.e. change font, font size, colors, etc. Otherwise having an element is only 50% useful.

**Comment by wpem-kishan** [comment]
We do not provide styling in list page if user need custom design than create custom template for single event.

**Comment by krinaydhanani** [comment]
If we are not providing this feature then it's working fine.
