### ISSUE TITLE
Unwanted space in field option value

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#266]
Every time 1 space added before and after the value of options for pipe separated options.
For example, if option is “yes : Yes |no :No” then 1 space will be added before and after “Yes” when you “Save Changes” in field editor.

![FireShot Capture 021 - Field Editor ‹ Event Manager — WordPress - localhost](https://user-images.githubusercontent.com/25837982/89297623-cefc7c00-d681-11ea-9f58-222e1e9bae4a.png)

**Comment by wpem-kishan** [comment]
We have already fixed this issue. Which version you are using?

**Comment by ritakikani** [comment]
This bug is in master directory of core plugin. In organizer_venue, it is solved.
