### ISSUE TITLE
Ticket Field not enable after save field editor

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#267]
Once save changes in field editor then the settings of ticket price not work.
ex. If i save field editor then enable/disable "Ticket  Prices" from settings then "Ticket Option" fields not enable in field editor in any case.

**Comment by wpem-kishan** [comment]
I have tested, form filter and editor working fine.

**Comment by ritakikani** [comment]
This bug is in master directory of core plugin. In organizer_venue, it is solved.
