### ISSUE TITLE
Category & type setting text may mislead

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#271]
In Settings -> Event Submission -> Categories, the text is "Enable categories for listings". this setting is used for bot submission and listing event so i think we need to change text description. It shows like it is only for event listing.

![FireShot Capture 039 - Settings ‹ Event Manager — WordPress - localhost](https://user-images.githubusercontent.com/25837982/89385002-9a89ce00-d71c-11ea-9bd7-515dfda7b96e.png)

**Comment by ritakikani** [comment]
This bug is in master directory of core plugin. In organizer_venue, it is solved.

**Comment by wpem-kishan** [comment]
Duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/297

**Comment by krinaydhanani** [comment]
Text updated working fine.
