### ISSUE TITLE
Need to improve installing time of wp-event manager from admin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#275]
While installing WP Event Manager from admin side it will take too much time.

Install fresh WordPress 
Go to the plugin 
Click on add-new plugin 
Search wp event manager 
Then click on install now.

Also need to fix Installation failed issue.

![image](https://user-images.githubusercontent.com/35419531/89522680-3ee44100-d7ff-11ea-9573-4afa81ff93e6.png)

**Comment by wpem-kishan** [comment]
This is not plugin issue. Some this internet slow or server slow that's what we getting issue

**Comment by krinaydhanani** [comment]
Right now it's working fine.
