### ISSUE TITLE
WPML Compatibility DOC

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#277]
Please check the following.

The guides listed below includes all the information that you might need to make WP Event Manager plugin compatible with WPML:

[Achieving WPML compatibility for your themes and plugins](https://wpml.org/documentation/support/achieving-wpml-compatibility-for-your-themes-and-plugins/)
[Debugging theme compatibility](https://wpml.org/documentation/support/debugging-theme-compatibility/)
[Language configuration files](https://wpml.org/documentation/support/language-configuration-files/)
[WPML compatibility test tools](https://wpml.org/documentation/related-projects/wpml-compatibility-test-tools-plugin/)

Please also check this in zoho desk (#4302 Field Editor with WPML) when you will test so you will get more idea.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/multilingual-website-using-wpml/
