### ISSUE TITLE
All the data not deleted in database after remove the event.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#278]
Need to improve like all the event data delete after event deleted from admin side.

**Comment by wpem-kishan** [comment]
I have verified in database all data clear after event delete.

**Comment by krinaydhanani** [comment]
I check and verify multiple time there is no every data clear after deleting event.

**Comment by krinaydhanani** [comment]
Still not working fine.

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by ritakikani** [comment]
It is not working for me with latest wordpress 5.5 and core plugin with organizer feature.

![image](https://user-images.githubusercontent.com/25837982/90309225-49d85900-df04-11ea-9bd6-cfaabfee1008.png)

![image](https://user-images.githubusercontent.com/25837982/90309230-5c529280-df04-11ea-8b76-b0dc220e77b7.png)

![image](https://user-images.githubusercontent.com/25837982/90309237-6f656280-df04-11ea-8560-153ac37a0c4c.png)

**Comment by krinaydhanani** [comment]
It's working fine.
