### ISSUE TITLE
While installing second time WP Event Manager they not ask me about page setup.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#281]
After selecting Delete Data On Uninstall I deactivate and deleted add-on then again I install the add-on at that time WP Event Manager not ask me about page setup.

For developer testing follow the step. 

1. Click on Delete Data On Uninstall from setting.
2. Deactivate and delete WP Event Manager.
3. Again Activate WP Event Manager. 

It will not ask about page set up.

If all the data will be deleted while installing the they need to ask me about page setup.

**Comment by wpem-kishan** [comment]
We have added some fields in uninstall file: https://github.com/wpeventmanager/wp-event-manager/issues/280

so right now working fine.

**Comment by krinaydhanani** [comment]
Still not working fine.

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by krinaydhanani** [comment]
Now it's working fine.
