### ISSUE TITLE
Need to update following URLS.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#287]
We need to update following URLS because WordPress move this pages to other URLS.

**Pages**

![image](https://user-images.githubusercontent.com/35419531/89620826-d56f3b80-d8ad-11ea-8b27-80df43051418.png)

Current URL : - http://codex.wordpress.org/Pages

Replace with : - https://wordpress.org/support/article/pages/

**Short code Documentation**

![image](https://user-images.githubusercontent.com/35419531/89621131-71994280-d8ae-11ea-8fa9-02a5882d05de.png)

Current URL : - http://www.wp-eventmanager.com/plugins-documentation/wp-event-manager/

Replace with : - https://wp-eventmanager.com/help-center/     OR     https://wp-eventmanager.com/knowledge-base/

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by ritakikani** [comment]
Verify and working fine now!
