### ISSUE TITLE
Past events should have functionality of enabling shortcodes 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#288]
https://wp-eventmanager.com/knowledge-base/the-event-listings/#articleTOC_2- These shortcodes are applicable only on the event listing page. These should be enabled on past events and calendars (whichever can be applied).

**Comment by wpem-kishan** [comment]
These are attributes of past event shortcode. Please update on documents.

show_pagination
per_page
order
orderby
location
keywords
selected_datetime
selected_categories
selected_event_types
