### ISSUE TITLE
Need to updates URLS in Support the Ongoing Development of this Plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#289]
**Leave a positive review**

![image](https://user-images.githubusercontent.com/35419531/89621908-c4bfc500-d8af-11ea-8848-1afb320a3ff6.png)

Current URL : - https://wordpress.org/support/view/plugin-reviews/wp-event-manager#postform

Replace with : - https://wordpress.org/support/plugin/wp-event-manager/reviews/#postform

**Contribute code or report a bug**

![image](https://user-images.githubusercontent.com/35419531/89622107-22541180-d8b0-11ea-84fa-7e3172e8ea19.png)

Current URL : -  http://www.wp-eventmanager.com/forum/ 

URL not working.

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by ritakikani** [comment]
Verify and done!
