### ISSUE TITLE
Disable Organizer section in event submit form

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#290]
I had enable "Enable organizer" from settings at admin side, then add 1 organizer. But then also i can not get "Organizer Details" section on front-end side and admin-side event submission form.

**Comment by wpem-kishan** [comment]
This is not a bug. First, you need to create 2 pages and selection here

![image](https://user-images.githubusercontent.com/61741365/89754176-7cdfae80-daf8-11ea-968c-5192b5f13399.png)

**Comment by ritakikani** [comment]
ok. this is done and working fine.
