### ISSUE TITLE
Suggestion: the event will expire by time

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#292]
I would also like to know if it is possible, the event will expire by time and not by date.

**Comment by hiteshmakvana** [comment]
```
function my_cron_schedules($schedules){ if(!isset($schedules["1min"])){ 
$schedules["5min"] = array( 'interval' => 1*60, 'display' => __('Once every 1 minutes')); } 
return $schedules; } add_filter('cron_schedules','my_cron_schedules');
$args = array(false);
function schedule_my_cron(){

wp_schedule_event(time(), '1min', 'my_schedule_hook', $args); } if(!wp_next_scheduled('my_schedule_hook',$args)){ add_action('init', 'schedule_my_cron'); }
function my_schedule_hook(){ global $wpdb;
$event_ids = $wpdb->get_col( $wpdb->prepare( "

				SELECT posts.ID FROM {$wpdb->posts} as posts

				WHERE posts.post_type = 'event_listing'

				AND posts.post_modified < %s

				AND posts.post_status = 'expired'

			", current_time('mysql')) );
			
			if ( $event_ids ) {

				foreach ( $event_ids as $event_id ) {

					wp_trash_post( $event_id );
				}
			}
}
```

**Comment by hiteshmakvana** [comment]
Please test the code and improve it as per needs.

**Comment by krinaydhanani** [comment]
function my_cron_schedules($schedules)
	{ 
		if(!isset($schedules["1min"]))
		{ 
			$schedules["5min"] = array( 'interval' => 1*60, 'display' => __('Once every 1 minutes')); 
		} 
		return $schedules; 
	} 
	add_filter('cron_schedules','my_cron_schedules');

	$args = array(false);
	
	function schedule_my_cron($args)
	{
		wp_schedule_event(time(), '1min', 'my_schedule_hook', $args); 
	} 
	if(!wp_next_scheduled('my_schedule_hook',$args)){ add_action('init', 'schedule_my_cron'); }
	
	function my_schedule_hook()
	{ 
		global $wpdb;
		
		$event_ids = $wpdb->get_col( $wpdb->prepare( "

			SELECT posts.ID FROM {$wpdb->posts} as posts

			WHERE posts.post_type = 'event_listing'

			AND posts.post_modified < %s

			AND posts.post_status = 'expired'

		", current_time('mysql')) );
		
		if ( $event_ids ) {

			foreach ( $event_ids as $event_id ) {

				wp_trash_post( $event_id );
			}
		}
	}

**Comment by krinaydhanani** [comment]
@Priya-Goenka you can put above code.

**Comment by ritakikani** [comment]
Tested the code and code @krinaydhanani 's code working perfect.so now @Priya-Goenka  can prepare doc.

**Comment by sapnadudhat03** [comment]
@Priya-Goenka Pls make a doc of it today.

**Comment by Priya-Goenka** [comment]
can someone please provide me the path? 
This code needs to be put in Theme-functions.php,?

**Comment by ritakikani** [comment]
Need to put this code theme -> functions.php file.

Then need to create one field with field type "Time" in field editor at admin side.
Then need to add event expirytime at the time of event creation.

Then that event will expire on time which you entered in your field.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1VDdkBiSnX2vkQ1ok2BpqKhGWy-GtHyLv-QcqoAMSr4k/edit

**Comment by Priya-Goenka** [comment]
Let me know if any changes needed.

**Comment by ritakikani** [comment]
I prepare this code to expire event on time, please verify it.If any changes needed then suggest here.

`/* event Expire by time */

function my_cron_schedules($schedules)
{
if(!isset($schedules["5min"]))
{
$schedules["5min"] = array( 'interval' => 5*60, 'display' => __('Once every 5 minutes'));
}
return $schedules;
}
add_filter('cron_schedules','my_cron_schedules');

$args = array(false);

function schedule_my_cron($args)
{
wp_schedule_event(time(), '5min', 'my_schedule_hook', $args);
}
if(!wp_next_scheduled('my_schedule_hook',$args)){ add_action('init', 'schedule_my_cron'); }

function my_schedule_hook()
{
	$today_date=date('Y-m-d g:i:s');
	$current_date = explode(" ", $today_date)[0];
	$current_time = explode(" ", $today_date)[1];
		$args = array(
		    'post_type'   => 'event_listing',
		    'post_status' => 'publish',
		);
		
		$args['meta_query'] = array(
		    array(
		        'key'     => '_event_expiry_date',
		        'value'   => $current_date,
		        'type'    => 'DATE',
		        'compare' => '='
		    )
		);
	
	$events = new WP_Query( $args );

	if ( $events->have_posts() ){
		while ( $events->have_posts() ) : 
			$events->the_post(); 
			if(get_post_meta(get_the_ID(), '_expire_time') == $current_time){
				wp_update_post(array(
	        		'ID'    =>  get_the_ID(),
	        		'post_status'   =>  'expired'
        		));	
			}
		endwhile; 			
			
	}
}

`

**Comment by ritakikani** [comment]
@Priya-Goenka  This code is to expire event on event expire time added by user.


`/* event Expire by time */
function my_cron_schedules($schedules){
    if(!isset($schedules["5min"])){
        $schedules["5min"] = array( 'interval' => 5*60, 'display' => __('Once every 5 minutes'));
    }
    return $schedules;
}
add_filter('cron_schedules','my_cron_schedules');


function schedule_my_cron($args){
    wp_schedule_event(time(), '5min', 'my_schedule_hook');
}

if(!wp_next_scheduled('my_schedule_hook')){ 
	 add_action('init', 'schedule_my_cron'); 
}
add_action('my_schedule_hook','my_schedule_hook');
function my_schedule_hook()
{
	$args = array(
	    'post_type'   => 'event_listing',
	    'post_status' => 'publish',
	);
	
	$args['meta_query']  = array(
	        'relation' => 'AND',
	        array(
	            'key'     => '_event_expiry_date',
	            'value'   => date( 'Y-m-d'),
	            'compare' => '<=',
	        ),
	        array(
	            'key'     => '_expire_time',
	            'value'   => date( 'H:i A'),
	            'compare' => '<',
	        ),
	    );
	
	$events = new WP_Query( $args );

	if ( $events->have_posts() ){
		while ( $events->have_posts() ) : 
			$events->the_post(); 
				wp_update_post(array(
	        		'ID'    =>  get_the_ID(),
	        		'post_status'   =>  'expired'
        		));	
		endwhile; 			
			
	}
}
`

**Comment by ritakikani** [comment]
Please test the code and prepare doc.

**Comment by Priya-Goenka** [comment]
Krinay please let me know after checking

**Comment by ashokdudhat** [comment]
@Rita code you need to test and support team, not able test code.

**Comment by hiteshmakvana** [comment]
I thinks we can create doc only for delete I am not sure expired is needed. Cron job is already inside the core plugin I don't think this we need to do.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/how-can-event-expire-by-time/?preview_id=22432&preview_nonce=7710439756&_thumbnail_id=-1&preview=true

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/how-can-event-expire-by-time/

Published.
