### ISSUE TITLE
Elementor : event dashboard shortcode has Problem with elementor

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#293]
When i create event dashboard page with the help of elementor(dashboard shortcode widget of elementor), on frontend side i can not able to perform any operation like, delete, duplicate etc.
but if i create this page without use of elementor then i can perform all operation on dashboard page at frontend side.

**Comment by ritakikani** [comment]
This problem occurred in all the actions like search on event listing page, I mean every where in plugin where action work with ajax.

**Comment by wpem-kishan** [comment]
Elementor provide only layout and result so user do not allow to dashborad action use in elementor editor mode..

**Comment by krinaydhanani** [comment]
I agree with @wpem-kishan it's working fine.
