### ISSUE TITLE
Need To check existing Organizer

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#294]
We must need to verify first then organizer exist or not before add organizer add. We can verify it by email/name. because without verify, duplicate entry can be added for same organizer with same name and email.

ex. If i have already added test organizer with email test@gmail.com then also i can easily add this same name and email with multiple times.

**Comment by ritakikani** [comment]
This is fixed from my side, i got error when i try to add duplicate email 

![image](https://user-images.githubusercontent.com/25837982/91166432-fd550080-e6ef-11ea-9b32-3945f599fb37.png)

**Comment by krinaydhanani** [comment]
Admin should not able to became organizer because of mail validation.

**Comment by wpem-kishan** [comment]
```
function check_organizer_exist($organizer_email) 
{
	$args = [
			'post_type' 	=> 'event_organizer',
			'post_status' 	=> ['publish'],
			'meta_query' => [
	        [
	            'key'     => '_organizer_email',
	            'value'   => $organizer_email,
	            'compare' => '=',
	        ],
	    ],
	];

	$args = apply_filters('check_organizer_exist_query_args', $args);

	$organizer = get_posts($args);

	if( !empty($organizer) && isset($organizer[0]->ID) )
	{
		return $organizer[0]->ID;
	}
	else
	{
		return false;
	}
}
```

**Comment by hiteshmakvana** [comment]
This is part of extra feature and it will restrict user for adding multiple organisers.

Also this makes conflict when different user add different organizer with same details it may show error and it became dead situation.


This need more vote to add incase we want to implement.
