### ISSUE TITLE
Delete page will not flush after refreshing the page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#296]
1. Delete any event form dashboard.
2. Then restore the event from admin.
3. Then again refresh the 1st page.

The event will again deleted.

**Comment by wpem-kishan** [comment]
we manage message after page refresh. I discuss with @hiteshmakvana this case may be face 1 customer out of 100 so we don't think so improve.

**Comment by krinaydhanani** [comment]
It's not working fine. If anyone customer face this issue we need to fix it. I move this bug on Enhancement.

**Comment by wpem-kishan** [comment]
Event delete then page reload and show message. If you again page refresh then we checked event status is trash then we do not show message.

**Comment by krinaydhanani** [comment]
Then it's working fine.
