### ISSUE TITLE
Check user login on organizer dashbaord page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#299]
Need to check it user is logged in then only show him organizer dashboard otherwise you can show him message for login with login link set in settings -> pages -> login page url.

![FireShot Capture 122 - Organizers – Beta Test - localhost](https://user-images.githubusercontent.com/25837982/89777666-bd0b5500-db29-11ea-8d94-d0dda74cef31.png)

**Comment by ritakikani** [comment]
I had test and above issue solve now.

**Comment by ritakikani** [comment]
verify and done!

**Comment by hiteshmakvana** [comment]
This is public listing same like events. No need to set any restriction.

**Comment by krinaydhanani** [comment]
It's working fine.
