### ISSUE TITLE
Login link in Organizer form

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#300]
Need to set login page link from Settings -> pages -> Login Page URL. currently it will redirect on wordpress default login page.

![FireShot Capture 125 - Add Organizer – Beta Test - localhost](https://user-images.githubusercontent.com/25837982/89777823-11aed000-db2a-11ea-8f0d-1de213d93e0d.png)

**Comment by wpem-kishan** [comment]
I have checked, login link comes form setting.

**Comment by ritakikani** [comment]
ok, done.
