### ISSUE TITLE
Add link to view perticular organizer event

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#301]
Need to set link on event organizer dashboard so one can view perticular organizer event list by click on them.
Here when i click on organizer name then nothing happens. So, if i want to show event of "test" organizer then i can't see it from organizer dashboard.

![FireShot Capture 128 - Organizers – Beta Test - localhost](https://user-images.githubusercontent.com/25837982/89778580-656de900-db2b-11ea-8140-329127719424.png)

**Comment by ritakikani** [comment]
If organizer has no event and i want to see the description and profile pic then this feature need.

**Comment by wpem-kishan** [comment]
we have to change organizer list layout so right now we do not show event list.

**Comment by krinaydhanani** [comment]
It's working fine.

**Comment by krinaydhanani** [comment]
It's working fine.
