### ISSUE TITLE
Need to change text

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#305]
We need to change description text of settings -> Event Listings -> Cancelled Events/Hide Expired Listings.

Because this settings also affect and used for widget event listing.

![FireShot Capture 140 - Settings ‹ Beta Test — WordPress - localhost](https://user-images.githubusercontent.com/25837982/89787870-dd440f80-db3b-11ea-8a54-748b5b63277c.png)

**Comment by Priya-Goenka** [comment]
I think this is correct, because event listings come in the widget form, so it does not make much difference.
