### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#308]
1. ![image](https://user-images.githubusercontent.com/65893994/89860494-36a25200-dbc1-11ea-8ff1-4049be3b3b59.png)

**Comment by Priya-Goenka** [comment]
#4488- Don't allow Organizers to add HTML links in the Description field of events. This only gives organizers a way to bypass paying for services from the site (selling tickets).

**Comment by Priya-Goenka** [comment]
Suggestion to add support for Live Stream event types. All that would be needed is to add a field for users to add either the Live Stream URL or Youtube/Vimeo channel URL. The business rules to support this would be as follows:

1. Organizers would have option to make the Livestream URL public (in the event desc.) or private to registered users only

2. If URL is private to registered users only, the URL would have to be sent by email and/or made visible in the Wordpress site (my-account/orders seems the most obvious place) when the event goes live. To some degree, this would prevent people who have not purchased a ticket from attending.

3. Some livestream platforms may require authentication or a use of a coupon code for entry. This might also be a consideration, depending on what livestream site you plan to support. Right now in the US, twitch.com is the most popular platform and second is stageit.com for hosting livestream events.

4. It would be nice to have a shortcode that displayed Livestream events only, and possibly a default Event category for all Livestream events so that users can easily search by this event type.
![image](https://user-images.githubusercontent.com/65893994/89860885-29d22e00-dbc2-11ea-9839-f385bbc6a438.png)
![image](https://user-images.githubusercontent.com/65893994/89860897-3060a580-dbc2-11ea-8114-484b00b1d0ab.png)

**Comment by Priya-Goenka** [comment]
#4482 suggestions for event sharing on Social

Current: when single event is shared using social share links, post is created with site logo.

Suggested: use event image instead of site logo. if event image is not available, use organizer logo. if neither are available, use site logo.

![image](https://user-images.githubusercontent.com/65893994/89860977-643bcb00-dbc2-11ea-972e-abeea5a53e7a.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/89861060-82a1c680-dbc2-11ea-92e1-6146d4710d53.png)
![image](https://user-images.githubusercontent.com/65893994/89861238-e7f5b780-dbc2-11ea-8eaa-112e597d841c.png)
![image](https://user-images.githubusercontent.com/65893994/89861252-f17f1f80-dbc2-11ea-9600-ff3978d4dc8a.png)
![image](https://user-images.githubusercontent.com/65893994/89861258-f5ab3d00-dbc2-11ea-8e5e-7b38023dd4f3.png)
![image](https://user-images.githubusercontent.com/65893994/89861268-fb088780-dbc2-11ea-93a2-2d6c5adf6055.png)
![image](https://user-images.githubusercontent.com/65893994/89861276-ff34a500-dbc2-11ea-8a2a-f46c50f9b322.png)
![image](https://user-images.githubusercontent.com/65893994/89861286-052a8600-dbc3-11ea-9198-b3bdb6735b54.png)
![image](https://user-images.githubusercontent.com/65893994/89861295-09ef3a00-dbc3-11ea-9995-3749de94a439.png)
![image](https://user-images.githubusercontent.com/65893994/89861302-0eb3ee00-dbc3-11ea-8278-66b72811b6fa.png)

![image](https://user-images.githubusercontent.com/65893994/89861312-14113880-dbc3-11ea-939b-406c3bc11be5.png)

![image](https://user-images.githubusercontent.com/65893994/89861320-196e8300-dbc3-11ea-9dc8-70e969aa3ccf.png)

**Comment by Priya-Goenka** [comment]
#4479 Bugs with events download
![image](https://user-images.githubusercontent.com/65893994/89861357-360abb00-dbc3-11ea-8133-5c7026b69fe8.png)
![image](https://user-images.githubusercontent.com/65893994/89861362-3c009c00-dbc3-11ea-94a8-f54db079ee33.png)
![image](https://user-images.githubusercontent.com/65893994/89861371-402cb980-dbc3-11ea-8054-62ae89c2fc5a.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/89904313-63c52380-dc06-11ea-8d77-ac64f9f104e1.png)
![image](https://user-images.githubusercontent.com/65893994/89904577-bbfc2580-dc06-11ea-862b-154d74ffabc2.png)
![image](https://user-images.githubusercontent.com/65893994/89904600-c3233380-dc06-11ea-9ec6-669a82f5657f.png)

**Comment by ritakikani** [comment]
To change this text, need to override template file of sell ticket plugin : "content-tickets-details.php"


![89861295-09ef3a00-dbc3-11ea-9995-3749de94a439](https://user-images.githubusercontent.com/25837982/89983684-a08c2b80-dc95-11ea-9765-10666b4e1bb7.png)

**Comment by ritakikani** [comment]
No, Zoom meeting not only for admin, Organizer or the person who posting the event can set zoom meeting at event create time, so this field is required.


![89861302-0eb3ee00-dbc3-11ea-8278-66b72811b6fa](https://user-images.githubusercontent.com/25837982/89984122-7b4bed00-dc96-11ea-8500-f14771d32760.png)

**Comment by mistry-jignesh** [comment]
As discussed with the team client need to follow the above instruction then it can work as per your request.
So I closed the issue.
