### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#309]
#4479 Bugs with events download
Exporting all the events rather should export only organizers events. 
![image](https://user-images.githubusercontent.com/65893994/89861378-46229a80-dbc3-11ea-9109-c3690c21a4b3.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/89861453-8550eb80-dbc3-11ea-930f-165a3d23fb97.png)
![image](https://user-images.githubusercontent.com/65893994/89861458-8b46cc80-dbc3-11ea-8160-8593af4f49e0.png)

![image](https://user-images.githubusercontent.com/65893994/89861474-939f0780-dbc3-11ea-9afa-8b4e122d8a92.png)
![image](https://user-images.githubusercontent.com/65893994/89861487-9863bb80-dbc3-11ea-8870-252754fbc22b.png)

**Comment by Priya-Goenka** [comment]
#4470 Several bugs and suggestions
![Screen Shot 2020-08-06 at 3 35 20 PM](https://user-images.githubusercontent.com/65893994/89862161-0197fe80-dbc5-11ea-8ec5-5518b8537543.png)
![Screen Shot 2020-08-06 at 3 44 11 PM](https://user-images.githubusercontent.com/65893994/89862164-02309500-dbc5-11ea-8889-e349a2ed4bb9.png)
![Screen Shot 2020-08-06 at 3 53 29 PM](https://user-images.githubusercontent.com/65893994/89862165-02c92b80-dbc5-11ea-807e-6c79870178a1.png)
![Screen Shot 2020-08-06 at 4 34 00 PM](https://user-images.githubusercontent.com/65893994/89862166-0361c200-dbc5-11ea-9b22-44dcdaa7a256.png)
![Screen Shot 2020-08-06 at 9 32 33 AM](https://user-images.githubusercontent.com/65893994/89862168-03fa5880-dbc5-11ea-97be-2bf0c6e946dd.png)
![Screen Shot 2020-08-06 at 9 48 09 AM](https://user-images.githubusercontent.com/65893994/89862169-03fa5880-dbc5-11ea-9529-698ea131380d.png)
![Screenshot 2020-08-06 at 4 22 34 PM](https://user-images.githubusercontent.com/65893994/89862171-0492ef00-dbc5-11ea-91a0-25e83f2968a1.jpeg)
![Shomee _ The Best Online Events, C oncerts, and Dining Experiences](https://user-images.githubusercontent.com/65893994/89862174-052b8580-dbc5-11ea-95a9-14571e225b29.jpeg)
![The AMP Virtual Arts Series GÇô Written to Remember  Online  GÇô Shomee](https://user-images.githubusercontent.com/65893994/89862176-05c41c00-dbc5-11ea-8e4d-1d0a5528b509.jpeg)
![Music Of The Stars at 75 Stutson Street GÇô Shomee](https://user-images.githubusercontent.com/65893994/89862178-065cb280-dbc5-11ea-9a6f-cb5d16997a62.jpeg)
![Screen Shot 2020-08-04 at 4 47 03 PM](https://user-images.githubusercontent.com/65893994/89862180-065cb280-dbc5-11ea-9ce4-bbe9b2a801cd.png)
![Screen Shot 2020-08-04 at 5 09 14 PM](https://user-images.githubusercontent.com/65893994/89862182-078ddf80-dbc5-11ea-8e24-f9887fb06f9e.png)
![Screen Shot 2020-08-04 at 5 25 57 PM](https://user-images.githubusercontent.com/65893994/89862183-078ddf80-dbc5-11ea-8014-24e4561ec3df.png)
![Screen Shot 2020-08-04 at 7 14 56 AM](https://user-images.githubusercontent.com/65893994/89862184-08267600-dbc5-11ea-8202-eb4761cbae14.png)
![Screen Shot 2020-08-05 at 5 50 37 PM](https://user-images.githubusercontent.com/65893994/89862185-08bf0c80-dbc5-11ea-9855-c00e2f4685b8.png)
![Screen Shot 2020-08-05 at 10 26 21 AM](https://user-images.githubusercontent.com/65893994/89862187-0957a300-dbc5-11ea-832a-c7962b13cdf5.png)
![Screen Shot 2020-08-05 at 11 10 48 AM](https://user-images.githubusercontent.com/65893994/89862188-09f03980-dbc5-11ea-86f9-9237b9b0f07e.png)
![Screen Shot 2020-08-05 at 11 15 09 AM](https://user-images.githubusercontent.com/65893994/89862190-09f03980-dbc5-11ea-9c60-6fb736631bbe.png)
![Screen Shot 2020-08-06 at 3 24 38 PM (2)](https://user-images.githubusercontent.com/65893994/89862192-0a88d000-dbc5-11ea-98ba-07cd5c136dbe.png)
![Screen Shot 2020-08-06 at 3 29 41 PM](https://user-images.githubusercontent.com/65893994/89862195-0b216680-dbc5-11ea-94a9-bbf71019e4c3.png)

**Comment by ritakikani** [comment]
Hello @Priya-Goenka , @sapnadudhat03 , 

      For text change like "Alert me" to "Notify me" and so on, he can override template files and change text as per his choice.

**Comment by ritakikani** [comment]
#4479 Bugs with events download issue, i will solve this issue and push into export addon.

**Comment by ritakikani** [comment]
This issue is resolved in updated version, i had checked on my local and staging demo.

![89862164-02309500-dbc5-11ea-8889-e349a2ed4bb9](https://user-images.githubusercontent.com/25837982/89902107-a76a5e00-dc03-11ea-9d47-777f99066e90.png)

**Comment by ritakikani** [comment]
![89862161-0197fe80-dbc5-11ea-8ec5-5518b8537543](https://user-images.githubusercontent.com/25837982/89906027-7d676a80-dc08-11ea-8808-e5ca422e63fa.png)

Yes, If you add expiry date then event will expire on that day.If you leave it blank then event will expire on your event end day.

**Comment by ritakikani** [comment]
![89862165-02c92b80-dbc5-11ea-807e-6c79870178a1](https://user-images.githubusercontent.com/25837982/89906183-b0116300-dc08-11ea-81b2-e36c70099c56.png)


You just need to override template file called "event-listings-start.php" here you can set text as per your choice.

**Comment by ritakikani** [comment]
![89862166-0361c200-dbc5-11ea-9b22-44dcdaa7a256](https://user-images.githubusercontent.com/25837982/89906299-d505d600-dc08-11ea-9208-3e10034866a6.png)


Need to set code for javascript to hide link from customer end.

**Comment by ritakikani** [comment]
![89862180-065cb280-dbc5-11ea-9ce4-bbe9b2a801cd](https://user-images.githubusercontent.com/25837982/89906476-126a6380-dc09-11ea-97c9-7a84f007316c.png)

Customer can add/edit subject/body content as per his choice for mail.

**Comment by sapnadudhat03** [comment]
**Customer can add/edit subject/body content as per his choice for mail.**

Rita, can you please change this line in our coding file because there is a mistake in a sentence so better to correct it in our end. 
Please write it as user said:

**You can contact the organizer directly at:**

**Comment by ritakikani** [comment]
> 
> 
> **Customer can add/edit subject/body content as per his choice for mail.**
> 
> Rita, can you please change this line in our coding file because there is a mistake in a sentence so better to correct it in our end. User is helping us to improve our product.
> Please write it as user said:
> 
> **You can contact the organizer directly at:**

sure, i will.

**Comment by ritakikani** [comment]
![89862169-03fa5880-dbc5-11ea-9529-698ea131380d](https://user-images.githubusercontent.com/25837982/89976466-1b4d4a80-dc86-11ea-9f55-7f0dd58f0d56.png)


Currently he can override tamplate file and change icon, In next version we will update icon.

**Comment by ritakikani** [comment]
![89862183-078ddf80-dbc5-11ea-8014-24e4561ec3df](https://user-images.githubusercontent.com/25837982/89977373-99125580-dc88-11ea-8518-97121cd39a8e.png)


This we will improve in our next version.

**Comment by ritakikani** [comment]
@sapnadudhat03  you can write better ans that As Wp Paid listing is part of Wp Event manager plugin, we provide our site link for installation, we cant give link of woocommerce installation.

![89862187-0957a300-dbc5-11ea-832a-c7962b13cdf5](https://user-images.githubusercontent.com/25837982/89977539-f908fc00-dc88-11ea-80f3-f6de4be7f0ce.png)

**Comment by ritakikani** [comment]
To change text like "Fees Pay By", customer can override template file called "html-event-ticket-data.php".

![89862188-09f03980-dbc5-11ea-86f9-9237b9b0f07e](https://user-images.githubusercontent.com/25837982/89978979-4a66ba80-dc8c-11ea-9e59-8d6353425a96.png)
