### ISSUE TITLE
Default image banner issue

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#316]
#4470 Several bugs and suggestions

Default image missing when event banner not uploaded. We solved this issue in our latest version then also we will test and verify again.

![89862176-05c41c00-dbc5-11ea-8e4d-1d0a5528b509](https://user-images.githubusercontent.com/25837982/89977111-f8239a80-dc87-11ea-9e99-07834771861d.jpeg)

**Comment by hiteshmakvana** [comment]
We have already fixed the issue in core plugin

**Comment by ritakikani** [comment]
I test on my local but not found this type of bug, but this we found from customer.
