### ISSUE TITLE
Need to change font in date picker

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#317]
There is issue with fonts in date picker(on event listing page search by date), so we need to change font as per theme.

![89862183-078ddf80-dbc5-11ea-8014-24e4561ec3df](https://user-images.githubusercontent.com/25837982/89977340-8730b280-dc88-11ea-9ae8-a6f89784690b.png)

**Comment by siddharthgotawala** [comment]
As Discussed with @ashokdudhat and @hiteshmakvana

We can't improve design of datepicker because if someone using same datepicker as our then it will conflict with their plugin or website.

#5 & #238 same issue
