### ISSUE TITLE
Suggestion: Past events shortcode - posts_per_page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#318]
For elementor **Past events shortcode**, there are no options like **posts_per_page** and other parameter options. But these parameters are there in other shortcodes like events.

**Comment by wpem-kishan** [comment]
I have verified all paramer we have provide.

![image](https://user-images.githubusercontent.com/61741365/90240350-b2610080-de46-11ea-8ff9-94069af8eded.png)
