### ISSUE TITLE
Elementor 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#320]
Do you have a default Elementor template for a single event I can import? This would save me a lot of work as opposed to starting from scratch.

**Comment by ritakikani** [comment]
Currently we have no feature for this. We can develop this feature in our next update.

**Comment by hiteshmakvana** [comment]
We have single event template with dynamic tags with element or pro. We will improve in next release

**Comment by hiteshmakvana** [comment]
I mean need to test dynamic tags

**Comment by wpem-kishan** [comment]
We have already created dynamic tags for all event fields. So using elementor pro create custom template for single event page.

**Comment by krinaydhanani** [comment]
We have provide dynamic tags for all event fields.
