### ISSUE TITLE
Error Event listing shortcode 

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#321]
When i passes "selected_event_type" argument in event listing shortcode then i got error.

![FireShot Capture 167 - The Event Listings - WP Event Manager - wp-eventmanager com](https://user-images.githubusercontent.com/25837982/90007859-19e94580-dcb9-11ea-9db1-c21b595c582c.png)

![FireShot Capture 164 - Beta Test - localhost](https://user-images.githubusercontent.com/25837982/90007869-1ce43600-dcb9-11ea-82c7-e66954fcdc9b.png)

**Comment by wpem-kishan** [comment]
duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/338

**Comment by ritakikani** [comment]
Error solved!
