### ISSUE TITLE
After update of Wordpress- Update and test box not working

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#324]
There are no edit box
![image](https://user-images.githubusercontent.com/65893994/90099129-62574080-dd57-11ea-80b5-797d1b40dbc1.png)

When I click on add file it redirects me on the same page. 
![image](https://user-images.githubusercontent.com/65893994/90099164-7733d400-dd57-11ea-8ef2-c7e88908d67f.png)

**Comment by hiteshmakvana** [comment]
@krinaydhanani Also test the same bug with Gutenberg enabled.

**Comment by wpem-kishan** [comment]
I this one of our js file but we have fixed this issue so now working fine.
