### ISSUE TITLE
Setting field not working properly after updating new WordPress version.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#326]
Event listing - Settings not working in new wordpress version.

After update WordPress 5.5 I was not able to select tabs.

Also all the setting tabs come in to one place.

**Comment by hiteshmakvana** [comment]
There is jQuery live event issue. Need to remove jQuery dependancy slowly.

**Comment by krinaydhanani** [comment]
Now it's working fine.
