### ISSUE TITLE
Organizer selection chosen missing admin side

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#329]
Admin side no any organizer selection afer updating to latest version organizer_venue.

Step to reproduce bug:

Install old version 3.1.13
update field editor with custom fields
Update to organizer venue version 

![image](https://user-images.githubusercontent.com/42602299/90114624-9be87580-dd70-11ea-9fa4-086c26bfa516.png)

Organizer selection missing frontend and backend.

**Comment by hiteshmakvana** [comment]
I have added one organizer in my account still not working.

**Comment by hiteshmakvana** [comment]
- This issue is occurring due to the page selection. 
- After update of 3.1.14 we need to set organizer pages if they have used our set up (installation set up if possible)
- Without organizer page set up user will not able to use this feature.

**Comment by krinaydhanani** [comment]
It's working fine.
