### ISSUE TITLE
There is no venue setting to enable or disable but still venue menu showing in menu

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#330]
As per the last bug #329 I am going same with old field editor and after plugin update.

Venue menu showing at backend side but there is no settings to disable this. @wpem-kishan we have already talked about this and you have removed the settings + venue feature (commented).

![image](https://user-images.githubusercontent.com/42602299/90115619-f6360600-dd71-11ea-999b-cbec9970f404.png)

**Comment by krinaydhanani** [comment]
It's working fine.
