### ISSUE TITLE
Auto update feature not working with our add-on.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#332]
WordPress 5.5 release auto update feature. Which is not working our add-on.

We need to upgrade our all add-on.

![image](https://user-images.githubusercontent.com/35419531/90125582-e6252300-dd7f-11ea-8405-33a6624826cb.png)

**Comment by wpem-kishan** [comment]
I noticed that if plugin not available on .org then auto update feature not come.

**Comment by krinaydhanani** [comment]
Then it's working fine.
