### ISSUE TITLE
Attendee Information not working properly in elementor. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#333]
If there is not any attendee then show notification like " There is not any attendee ".

![image](https://user-images.githubusercontent.com/35419531/90127477-de1ab280-dd82-11ea-84d1-c343c0a97ee1.png)

**Comment by wpem-kishan** [comment]
This is not core plguin bugs so please select right git reposetory then add properly git reposetory.

**Comment by krinaydhanani** [comment]
I move this bug in attendee information add-on.
