### ISSUE TITLE
If there is no any video in single event page then show the notification.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#334]
If there is no any video in single event page then show the notification like " There is no any video available. "

![image](https://user-images.githubusercontent.com/35419531/90128603-c3493d80-dd84-11ea-83b4-3baf59fba4bb.png)

**Comment by wpem-kishan** [comment]
I have verified this funcationality working fine. If user have set # instead of link then definitely shows blank popup model.

**Comment by krinaydhanani** [comment]
Even if user put # then in the popup can we show notification like Video URL not found something like that.

**Comment by hiteshmakvana** [comment]
We will not put so many restriction from our end it will be up to the user what he wants to show.
