### ISSUE TITLE
Cache helper not working as expected

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#336]
There is some glitch in cache helper when we update any event it should have clean the transient of events and show updated listing on the events shortcode.

Currently it is not working and keep showing expired events on listing page.

**Comment by hiteshmakvana** [comment]
![image](https://user-images.githubusercontent.com/42602299/90135770-cd713900-dd90-11ea-8cc2-57fa0bf907c8.png)

![image](https://user-images.githubusercontent.com/42602299/90135671-a581d580-dd90-11ea-9333-44ba40b9f2b3.png)

**Comment by krinaydhanani** [comment]
I can not face the issue regarding the expired listing. If I found any issue regarding listing expires event then I will open the bug in future with proper reproducing stapes.
