### ISSUE TITLE
ELEMENTOR : - Single organizers not working on elementor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#337]
Single organizers not working on elementor.

![image](https://user-images.githubusercontent.com/35419531/90140416-5ab78c00-dd97-11ea-9585-00c9a4f37c20.png)

**Comment by wpem-kishan** [comment]
I have verified, working fine.

![image](https://user-images.githubusercontent.com/61741365/90225443-05c75480-de2f-11ea-841d-9286a8fb35cf.png)

**Comment by krinaydhanani** [comment]
Yes it's working fine.
