### ISSUE TITLE
Invalid argument error in event listing shortcode

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#338]
If i use "selected_event_type/selected_ticket_price/selected_category" in event listing shortcode then i got below error,

![FireShot Capture 186 - Beta Test - localhost](https://user-images.githubusercontent.com/25837982/90215888-b70fbf80-de1a-11ea-9cec-ee9ca377ed57.png)

**Comment by ritakikani** [comment]
Tested and Verified.

**Comment by ritakikani** [comment]
"selected_event_type/selected_ticket_price/selected_category" not working in [events] shortcode.

**Comment by ritakikani** [comment]
When we multiple value(separated by comma) then this attribute not working.

**Comment by wpem-kishan** [comment]
I have fixed issue but you need to follow below step for multiple value:

[events selected_event_type="business-professional,charity-causes"]

![image](https://user-images.githubusercontent.com/61741365/90597254-57485880-e20e-11ea-9eb0-d9fcc3074359.png)

**Comment by ritakikani** [comment]
i had test this shortcode, now it is working fine for me!
