### ISSUE TITLE
Need to change or update image on event dashboard shortcode page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#339]
At frontside event dashboard, we don't have button for "Download Event csv file". It will be there only if there is WP Event Export addon is active. So need to remove that button from screenshot of event dashboard shortcode page and Frontend Event Dashboard for Organizer page.

https://wp-eventmanager.com/knowledge-base/the-event-dashboard/

https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

![image](https://user-images.githubusercontent.com/25837982/90216584-90528880-de1c-11ea-97a5-7f44829a4776.png)

**Comment by Priya-Goenka** [comment]
Siddharth Please make a screenshot:
![image](https://user-images.githubusercontent.com/65893994/90417770-d4ba7e80-e0d1-11ea-9c05-773ee1ce2656.png)

**Comment by ritakikani** [comment]
Hello @Priya-Goenka , changes not done on this page for image : https://wp-eventmanager.com/knowledge-base/the-event-dashboard/

![image](https://user-images.githubusercontent.com/25837982/90635645-13257a00-e247-11ea-8b8e-00465046e978.png)

**Comment by Priya-Goenka** [comment]
done
