### ISSUE TITLE
Event Category and type settings is used for both listing and submission form

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#341]
In doc, Categories & Types Settings page, As per header text one can think that this settings is only to enable category and types for submission form only but when you enable this settings also category and type is view in event listing so need to specify that this settings is use for both Form submission and for event listing also

https://wp-eventmanager.com/knowledge-base/settings/

On this page it shows this settings is used to enable event listing types and category.

https://wp-eventmanager.com/knowledge-base/event-submission-page-settings/#articleTOC_11

It may create confusion.

![image](https://user-images.githubusercontent.com/25837982/90217313-a8c3a280-de1e-11ea-90f6-95b99304f99c.png)

**Comment by ritakikani** [comment]
Still this need to change. on : 
https://wp-eventmanager.com/knowledge-base/settings/

![image](https://user-images.githubusercontent.com/25837982/90634537-757d7b00-e245-11ea-8a00-5df49785e3f4.png)

**Comment by ritakikani** [comment]
Also need to change on this : 
https://wp-eventmanager.com/knowledge-base/event-submission-page-settings/#articleTOC_11



![image](https://user-images.githubusercontent.com/25837982/90634722-c7be9c00-e245-11ea-8817-f20fec894e2b.png)

**Comment by ritakikani** [comment]
please change this also

![image](https://user-images.githubusercontent.com/25837982/90639263-0fe0bd00-e24c-11ea-9768-44615fdda099.png)

![image](https://user-images.githubusercontent.com/25837982/90639316-20913300-e24c-11ea-8ff1-8ef12c718718.png)

**Comment by Priya-Goenka** [comment]
done

**Comment by ritakikani** [comment]
changes done!
