### ISSUE TITLE
Contact Organizer feature missing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#342]
Contact organizer feature missing in organizer venue add-on.

![image](https://user-images.githubusercontent.com/35419531/90218102-9a768600-de20-11ea-87c1-1e7b661c09de.png)

**Comment by wpem-kishan** [comment]
This is not core plugin issue. Please put bug on corrent git reposetory. I have created below bug.
https://github.com/wpeventmanager/wp-event-manager-contact-organizer/issues/5

**Comment by krinaydhanani** [comment]
Yes bug move on correct repository.
