### ISSUE TITLE
New feature: Organizer venue

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#343]
Organizer can be added from the backend and frontend.

By default we will add organizer shortcode pages if user want to change those page settings they can change it.

Organizer dashboard will be capable of adding, deleting,duplicating his own organisers.

**Comment by krinaydhanani** [comment]
Organizer duplicating not working from backed side.

**Comment by Priya-Goenka** [comment]
I have not added that feature in the doc.
