### ISSUE TITLE
Deign not look good in other WordPress default themes.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#345]
![image](https://user-images.githubusercontent.com/35419531/90218789-4b315500-de22-11ea-9706-7b7aee7beee8.png)

**Comment by ritakikani** [comment]
i also get this bug

![image](https://user-images.githubusercontent.com/25837982/90309106-e13cac80-df02-11ea-9157-28212a04c88c.png)

**Comment by ritakikani** [comment]
on event dashboard page, get black underline on action icons.

![image](https://user-images.githubusercontent.com/25837982/90309132-2a8cfc00-df03-11ea-928a-c2c37ad061c0.png)

**Comment by ritakikani** [comment]
Organizer dashboard page design with Twenty seventy theme : 

![image](https://user-images.githubusercontent.com/25837982/90309178-86578500-df03-11ea-9eeb-4df1f3fc6986.png)

**Comment by siddharthgotawala** [comment]
a tag underline is coming from theme css so that is the theme design's issue

**Comment by krinaydhanani** [comment]
Now it's look good.
