### ISSUE TITLE
Need to change Upcoming event widget "order by" text

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#346]
In our Upcoming Event Widget, Their is "orader by" title 2times, 
1. Order by : Asc/Desc 
2. Order by : Title, ID, Name etc.

![image](https://user-images.githubusercontent.com/25837982/90219165-11ad1980-de23-11ea-851b-a7450c45cde5.png)

**Comment by wpem-kishan** [comment]
I have checked title one time comes.
https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters

![image](https://user-images.githubusercontent.com/61741365/90238244-3dd89280-de43-11ea-80d1-07aa83ce60b9.png)

**Comment by ritakikani** [comment]
I mean this title text : 

![FireShot Capture 193 - Widgets ‹ Latest Wordpress — WordPress - localhost](https://user-images.githubusercontent.com/25837982/90240670-5054cb00-de47-11ea-8194-e733f98efbf4.png)

**Comment by ritakikani** [comment]
Done!
