### ISSUE TITLE
ELEMENTOR : - Single event listing design not looking good in Elementor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#349]
Single event listing design not looking good in Elementor.

![image](https://user-images.githubusercontent.com/35419531/90220358-add82000-de25-11ea-852d-0549fa001f48.png)

**Comment by siddharthgotawala** [comment]
After publishing it's look good. At while we put on elementor they take there own height and width.

![image](https://user-images.githubusercontent.com/68212017/90306444-e5f56680-deea-11ea-90e4-45858248210d.png)

**Comment by krinaydhanani** [comment]
Yes after publishing it's look good.
