### ISSUE TITLE
Need to give link for addon in core doc

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#350]
Set link for addon on this page : https://wp-eventmanager.com/knowledge-base/enable-trace-debug-javascript-file-logs/

![image](https://user-images.githubusercontent.com/25837982/90220579-16bf9800-de26-11ea-82c8-2c1b061b7174.png)

**Comment by Priya-Goenka** [comment]
Log is added to the core plugin, The addon, do not exist now.

**Comment by dieppon** [comment]
Well, the information its incorrect, in the plugin settings there are no  mention of logging.
