### ISSUE TITLE
ELEMENTOR : - We need to provide filter section in Elementor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#351]
We need to provide filter section in Elementor so user can show filter easily.

![image](https://user-images.githubusercontent.com/35419531/90222818-728c2000-de2a-11ea-90d8-45fcffad8b9c.png)

**Comment by wpem-kishan** [comment]
We already created event list widget in elementor with all filters.

![image](https://user-images.githubusercontent.com/61741365/91432694-b72ea700-e87f-11ea-8016-bda5cef60893.png)

**Comment by krinaydhanani** [comment]
we have to provide a separate filter option. For example, If I want only Category filter then there is not an option for me to put only the category option. Right now I have to use all the filter because I do not have a separate filter option.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now we have  provide a separate filter option .

It is working properly.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now we have  provide a separate filter option .

It is working properly. Now I have closed the bug.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now we have provide a separate filter option .

It is working properly. Now I have closed the bug.
