### ISSUE TITLE
Need to change label of Recent Events.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#352]
We need to change the label because we are not listing only Recent Events.
We are also listing Future Events also. 

We can simply sow "Events"

![image](https://user-images.githubusercontent.com/35419531/90222959-b8e17f00-de2a-11ea-9f97-e15e630ab2fb.png)

**Comment by ritakikani** [comment]
Verify and Done!

**Comment by krinaydhanani** [comment]
Yes label changed.
