### ISSUE TITLE
ELEMENTOR : - We need to provide all the Event listing options to users in Elementor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#353]
We need to provide all the Event listing options to users in Elementor like " Recent Events , Past Events , Up Coming Events " so user can easily show all the events at one place with simple drag and drop.

**Comment by wpem-kishan** [comment]
I have added date option on event list widget.

![image](https://user-images.githubusercontent.com/61741365/91436058-fb707600-e884-11ea-85c3-dc6d8e3c0267.png)

**Comment by wpem-kishan** [comment]
I discuss with @hiteshmakvana we add only Upcoming widget only.

**Comment by krinaydhanani** [comment]
Upcoming event widget working fine.
