### ISSUE TITLE
ELEMENTOR : - Make the separate details section separate.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#355]
Make the separate details section separate so user can easily drag and drop.

![image](https://user-images.githubusercontent.com/35419531/90233163-547aeb80-de3b-11ea-98d0-0a13efa95751.png)

**Comment by wpem-kishan** [comment]
we have create widget for single event page so we do not seperate. Also we already created seperate widget for Zoom with Zoom category.

![image](https://user-images.githubusercontent.com/61741365/91438005-5788c980-e888-11ea-800a-19a2c20c6b9e.png)

**Comment by krinaydhanani** [comment]
We are providing Single Event Field widget so it's working fine.
