### ISSUE TITLE
Event Category and Event Types not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#356]
If I edit Event Category and Event Types from admin panel it's not update at fronted side.

**Comment by wpem-kishan** [comment]
I have verified this bug, working fine.

**Comment by ritakikani** [comment]
I had tested and working fine in my local!

**Comment by krinaydhanani** [comment]
Its not working fine. While I select child category and type.

**Comment by hiteshmakvana** [comment]
On post an event and filter page child category working fine. Can you please provide the exact page where we can see the issue?

**Comment by krinaydhanani** [comment]
It's working fine.
