### ISSUE TITLE
All Settings of events on one page in admin side

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#358]
In wordpress 5.5, i had first install latest version of Wp event manager with organizer feature, then i degrade with old version "master", And i open settings page, i got below all settings in one tab :

![FireShot Capture 190 - Settings ‹ Latest Wordpress — WordPress - localhost](https://user-images.githubusercontent.com/25837982/90237940-b7bc4c00-de42-11ea-89a6-4d7919b3bfc6.png)

**Comment by wpem-kishan** [comment]
Duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/326

**Comment by ritakikani** [comment]
Done!
