### ISSUE TITLE
ELEMENTOR : - We have to provide all the Event Listings Short code Attributes in elementor widget.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#359]
We need to provide all the Event Listings Shortcode Attributes in elementor with separate widget like : - 

Filters : - With the help of Filters widget user drag and drop the filter function anywhere.

Also we can provide seprate filter widgets like " event category , event type " so if user have options to which filter he want to use.

Featured Events : - With the help of Featured Events widget user drag and drop the Featured Events anywhere.

**Comment by wpem-kishan** [comment]
we give all option in event list widget so I don't think so we create separate widget.

**Comment by krinaydhanani** [comment]
Event listing features not working.
