### ISSUE TITLE
Organizer Detail Section not shown in field editor

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#360]
Organizer section not available in field editor of old version.

Tested with WP old version.

First i installed old version of Wp Event manager (with organizer feature)
then i save filed editor of event section.
then degrade Wp event manager version with (3.1.13)

![FireShot Capture 196 - Field Editor ‹ Beta Test — WordPress - localhost](https://user-images.githubusercontent.com/25837982/90243265-32d63000-de4c-11ea-9247-e2bc329bee30.png)

**Comment by wpem-kishan** [comment]
I have fresh install  wordpress and wp event manager plugin 3.1.13 I have see organizer all field so please again verify,

**Comment by ritakikani** [comment]
Please try to reproduce bug with the above step and fix issue.

**Comment by ritakikani** [comment]
We must need to enable "Enable organizer " from Event Listing Settings. And working perfect!
