### ISSUE TITLE
Organizer Description box different then our core add-on box.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#361]
Organizer Description box different then our core add-on box.
Make it same like our description box.

![image](https://user-images.githubusercontent.com/35419531/90248043-7ed9a280-de55-11ea-9a7d-d7e9a4671f5b.png)

**Comment by ritakikani** [comment]
Verify from my side and working now!

**Comment by krinaydhanani** [comment]
Now it's look good.
