### ISSUE TITLE
"Cancel" button on add/edit organizer form

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#363]
If try to edit organizer from dashboard then it will redirect me on edit organizer form, but then i think that no need to edit organizer then their is no button for "Cancel" edit and close the form and redirect me on previous page.
Also need to put "Cancel" button on Add organizer form.

![image](https://user-images.githubusercontent.com/25837982/90306775-096de080-deee-11ea-9667-db60b6c40032.png)

![image](https://user-images.githubusercontent.com/25837982/90306844-a466ba80-deee-11ea-8aa2-04c98fbfde3d.png)

**Comment by wpem-kishan** [comment]
I discussed with Hitesh and I think we do not add to cancel button.

**Comment by krinaydhanani** [comment]
It's working fine.
