### ISSUE TITLE
"Cancel" button on Event edit form

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#364]
Need to out "Cancel" button on edit event form/submit event form.

![image](https://user-images.githubusercontent.com/25837982/90306813-5fdb1f00-deee-11ea-9aa6-d3ae8d1cba18.png)

![image](https://user-images.githubusercontent.com/25837982/90306824-8305ce80-deee-11ea-9502-b2aaa1540152.png)

**Comment by hiteshmakvana** [comment]
We don't need as of now because user can set navigation menu instead of cancel.

**Comment by wpem-kishan** [comment]
I discussed with Hitesh and I think we do not add to cancel button.

**Comment by krinaydhanani** [comment]
It's working fine.
