### ISSUE TITLE
Event banner issue in event listing page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#365]
I had added event from admin and add banner but not add thumbnail image then at frontside event listing page not getting event banner, it is display in single event page and in widget.

![image](https://user-images.githubusercontent.com/25837982/90308498-a4ba8200-defd-11ea-8c77-e5dbbd63842d.png)

Event Listing :

![image](https://user-images.githubusercontent.com/25837982/90308507-abe19000-defd-11ea-8687-523dcab9a6e6.png)

Widget : 

![image](https://user-images.githubusercontent.com/25837982/90308515-b439cb00-defd-11ea-847d-e9d9011cabd8.png)

**Comment by ritakikani** [comment]
still face same problem!

**Comment by wpem-kishan** [comment]
when add new event from admin site we need compulsory set event thumbnail

**Comment by ritakikani** [comment]
Done!
