### ISSUE TITLE
Organizer dashboard page design issue in column

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#366]
On organizer dashboard, when I click on No. of events, the column text will move little bit left side as shown in both screenshot.
And also need to change mouse pointer for link (No. of events) column.
Also need to set design for Add Organizer button.

![image](https://user-images.githubusercontent.com/25837982/90309057-71c6bd00-df02-11ea-9ea9-b7ee68025840.png)

![image](https://user-images.githubusercontent.com/25837982/90309058-74c1ad80-df02-11ea-8aa9-5fa86036c115.png)

**Comment by siddharthgotawala** [comment]
We have updated the layout please recheck

**Comment by ritakikani** [comment]
Done!
