### ISSUE TITLE
Need to shortcodes document

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#369]
Need to shortcodes document

submit_event_form
event_dashboard

submit_organizer_form
organizer_dashboard

events
event
event_summary
past_events
event_register

event_organizers
event_organizer

**Comment by Priya-Goenka** [comment]
All the individual documents has details of the shortcode. do I need to make a a new one?

**Comment by sapnadudhat03** [comment]
@Priya-Goenka

Create a doc for "event_register" shortcode and "my_registration" too. Ask the development team for the purpose of these shortcodes.

**Comment by Priya-Goenka** [comment]
Rita/hitesh, let me know what is the shortcode, event_register used for?

**Comment by Priya-Goenka** [comment]
Doc for My Registrations= https://docs.google.com/document/d/13ww3IXNkSlAA9x1jFiKVcBeQhhhqxkvTNN8P1tfcwCg/edit

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Please update the doc.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/my-registrations/
