### ISSUE TITLE
Got the issue while installing wp event manager.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#371]
Fatal error: Uncaught Error: Cannot unset string offsets in F:\XAMPP\htdocs\WPEM\wp-content\plugins\wp-event-manager\core\wp-event-manager-install.php:57 Stack trace: #0 F:\XAMPP\htdocs\WPEM\wp-content\plugins\wp-event-manager\wp-event-manager.php(169): WP_Event_Manager_Install::install() #1 F:\XAMPP\htdocs\WPEM\wp-includes\class-wp-hook.php(287): WP_Event_Manager->updater('') #2 F:\XAMPP\htdocs\WPEM\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 F:\XAMPP\htdocs\WPEM\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #4 F:\XAMPP\htdocs\WPEM\wp-admin\admin.php(175): do_action('admin_init') #5 F:\XAMPP\htdocs\WPEM\wp-admin\about.php(10): require_once('F:\\XAMPP\\htdocs...') #6 {main} thrown in F:\XAMPP\htdocs\WPEM\wp-content\plugins\wp-event-manager\core\wp-event-manager-install.php on line 57

**Comment by wpem-kishan** [comment]
I have verified working fine. If you getting issue give me which you case getting error.

**Comment by krinaydhanani** [comment]
It's working fine.
