### ISSUE TITLE
Organizer dashboard layout change

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#375]
Organizer dashboard layout change

**Comment by krinaydhanani** [comment]
Please put the proper Screed for old layout and new layout so tester can understand all changes done or still not.

**Comment by wpem-kishan** [comment]
@krinaydhanani I have asign to sidharth this bug so please vefiry only your assign bugs only.

**Comment by krinaydhanani** [comment]
@wpem-kishan I test this issue because @hiteshmakvana told to check every issue which label is fix. There is no meaning to who open the issue and who you assign.
