### ISSUE TITLE
Add thumnail as event listing page banner

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#381]
If admin add events from admin panel, then he must need to add "event banner" + "event thumnail".
Event banner is used to display event banner on single event detail page.
Event thumbnail is used to display event thumbnail at event listing page and for widget also.

![image](https://user-images.githubusercontent.com/25837982/90392297-3d8f0000-e0ac-11ea-8d44-7143bab0b7d2.png)

**Comment by Priya-Goenka** [comment]
@Hitesh said not required.
