### ISSUE TITLE
Add actions at backend- Organizer Feature

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#384]
![image](https://user-images.githubusercontent.com/65893994/90408138-109b1700-e0c5-11ea-9970-b46fa6612637.png)
![image](https://user-images.githubusercontent.com/65893994/90408143-142e9e00-e0c5-11ea-9b71-7a52eef93319.png)

**Comment by wpem-kishan** [comment]
Wordpress already provided edit and delete action.

![image](https://user-images.githubusercontent.com/61741365/91530747-45ab3300-e929-11ea-9b2a-5807ce682252.png)

**Comment by krinaydhanani** [comment]
It's working fine. WordPress already provide this feature.
