### ISSUE TITLE
We should provide a button for enable or disable Sharing on social media in admin panel.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#385]
Right now we just provide a short code. If user want to disable the share button they need to put the code in function file after when they want to show the button thy need to remove it so it's a complicated process for users so for simplify : - 
We should provide a button for enable or disable Sharing on social media in admin panel so user can easily use the feature.

**Comment by wpem-kishan** [comment]
right now we don't have setting for that but we have alreay added filter so you can add filter on functions.php

add_filter( 'event_manager_event_friend_share', '__return_false' );

**Comment by krinaydhanani** [comment]
I think it's a improvement. We should provide it in future.
