### ISSUE TITLE
Automatic enabling and disabling of registration button. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#387]
We know the code exists, however it should be an inbuilt feature of showing or removing the registration button on the Single event listing page.

**Comment by wpem-kishan** [comment]
if you no need button than add code : https://github.com/wpeventmanager/wp-event-manager-registrations/issues/14
there is only one way.

**Comment by krinaydhanani** [comment]
It's working fine.
