### ISSUE TITLE
Event location feature not working fine.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#389]
When I click on online event in admin the event location not changed.

**Comment by hiteshmakvana** [comment]
Admin side we are not adding more restrictions but we will add this in milestone 3.1.15

**Comment by krinaydhanani** [comment]
This is not working fine. If I change the event location from the admin side it is not changing.

**Comment by krinaydhanani** [comment]
Now it's working fine.
