### ISSUE TITLE
Need to wright proper description for upgrade data base features.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#394]
Need to wright proper description for upgrade data base features so user can understand the process easily. Also we need to remove Lorem Ipsum text.

![Opera Snapshot_2020-08-19_120928_localhost](https://user-images.githubusercontent.com/35419531/90609225-5a990f80-e221-11ea-9091-d5dd5fd37acd.png)

**Comment by wpem-kishan** [comment]
duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/402

**Comment by krinaydhanani** [comment]
Text upgraded not it's working fine.
