### ISSUE TITLE
Need to change the text of organizer page setup.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#396]
Need to change the text of organizer page setup right now I can see the same text of post an event page text.

![Opera Snapshot_2020-08-19_131502_localhost](https://user-images.githubusercontent.com/35419531/90609932-60432500-e222-11ea-8aac-ee4b4fcfef1b.png)

**Comment by Priya-Goenka** [comment]
Submit Organizer Form: This page allows people to Submit the Organizers form the frontend.
In case if you do not want to allow your users to submit organizers from the frontend, you can uncheck this and skip creating this page. 

Organizer Dashboard: This page allows people to manage (edit, delete and duplicate)t the Organizers form the frontend.
In case if you do not want to allow your users to manage organizers from the frontend, you can uncheck this and skip creating this page.

**Comment by krinaydhanani** [comment]
Text replace now it's working fine.
