### ISSUE TITLE
Location Field is incorrectly showing online 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#397]
In case if the event is not online
and location is left empty, it shows online n location. 

![image](https://user-images.githubusercontent.com/65893994/90629120-6940f000-e23c-11ea-8687-6f06510efd03.png)
![image](https://user-images.githubusercontent.com/65893994/90629211-9b525200-e23c-11ea-95f3-6085628fae2f.png)

**Comment by hiteshmakvana** [comment]
By default we have added if there is no location on event it will be online by default. If user don't like that we can remove that.

**Comment by wpem-kishan** [comment]
for admin side we do not provide any validation so location field always show.
