### ISSUE TITLE
Need to change the Lorem Ipsum text from Upgrade yor database for new version of WP Event Manager

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#402]
Need to change the Lorem Ipsum text from Upgrade yor database for new version of WP Event Manager.

![image](https://user-images.githubusercontent.com/35419531/90726410-4ae00080-e2df-11ea-9abb-5caf48c3b9cd.png)

**Comment by Priya-Goenka** [comment]
3.1.14 has released!
We are constantly working to improve your event management experience, We have a new release focusing on a handle of fixes and updates & here is a summary of what has been improved...

1. Manage your Organizers directly at the frontend and backend.
2. Migration of Old Organizer data would be transferred to the list Automatically.

A prior update does no harm before updating the plugin!

**Comment by Priya-Goenka** [comment]
Hello friends! We have a new release focusing on a handle of fixes and updates that detect which e-commerce providers are active.

This is a minor release that should be smooth sailing when updating. That said, it’s always a good idea to backup your site and test changes in a development environment before installing this on your live site, as you would with any other WordPress update.

**Comment by krinaydhanani** [comment]
Text upgraded not it's working fine.
