### ISSUE TITLE
Some feature are not working in Field Editor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#404]
Time and Repeated features not working in field editor.

**Comment by hiteshmakvana** [comment]
This can be extended with custom code.

**Comment by mistry-jignesh** [comment]
Time field is working fine.

Face issue with repeated option .

When added the option then found below error.

![image](https://user-images.githubusercontent.com/75515088/159445530-6c7f5bad-1649-4bc3-98b8-651c5ced0309.png)

**Comment by ritakikani** [comment]
We gave repeated field for tickets only, if user want to change anything in repeated field then he can customize by override template file and using hook and filters.

**Comment by mistry-jignesh** [comment]
As discussed with the team client need to follow the above instruction then it can work as per your request.
So I closed the issue.
