### ISSUE TITLE
Event End Date must greater than the event start date

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#406]
Need to put validation for event end date, it must be greater than the event start date at front side post an event form.

![image](https://user-images.githubusercontent.com/25837982/90772719-919b1e00-e312-11ea-88bc-ef7df2f85ad1.png)

![image](https://user-images.githubusercontent.com/25837982/90772752-9a8bef80-e312-11ea-8034-bf267010c7bf.png)

**Comment by krinaydhanani** [comment]
It's working fine.
