### ISSUE TITLE
Elementor : Styling Options

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#409]
Make the Eementor elements fully Elementor compatible. Right now they have no styling options so there is really no use for them.  Each individual item requires its own CSS so it is a pain in the but to use and thus not used. I am talking about font choices, padding, margin, alignment, color, background options that are normally included in Elementor elements. 

Something we need it.

<img width="246" alt="Screenshot 2020-08-29 at 09 13 54" src="https://user-images.githubusercontent.com/15089059/91631348-2cfa5600-e9d9-11ea-924c-580a0a78b4cb.png">
<img width="249" alt="Screenshot 2020-08-29 at 09 17 33" src="https://user-images.githubusercontent.com/15089059/91631351-2ec41980-e9d9-11ea-9942-fa63afb64e55.png">
<img width="256" alt="Screenshot 2020-08-29 at 09 18 10" src="https://user-images.githubusercontent.com/15089059/91631352-2f5cb000-e9d9-11ea-909e-6f335818dde7.png">
<img width="257" alt="Screenshot 2020-08-29 at 09 19 30" src="https://user-images.githubusercontent.com/15089059/91631353-2ff54680-e9d9-11ea-8c4d-85399d2e7235.png">

**Comment by wpem-kishan** [comment]
We do not provide styling in list page if user need custom design than create custom template for single event.

duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/261

**Comment by hiteshmakvana** [comment]
Basic styling we are already providing 
![image](https://user-images.githubusercontent.com/42602299/93341491-ce8ffd00-f84b-11ea-96ff-a2afd81c8e71.png)
