### ISSUE TITLE
Organizer detail blank on organizer dashboard page

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#417]
I had submit oganizer with Description, but on organizer dashboard page it show me blank as seen in below screenshot.
so either we need to remove the column of "Detail" or we need to show detail of organizer.

![image](https://user-images.githubusercontent.com/25837982/91007895-b9cc9a80-e5fa-11ea-88d5-669ec19eb56f.png)

**Comment by wpem-kishan** [comment]
I have verified with 2 user website. All data perfectly moved.

**Comment by krinaydhanani** [comment]
I verify it. I got social media.
