### ISSUE TITLE
How to install WP Event Manager add ons

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#421]
we have recorded video: https://www.youtube.com/watch?v=uEH0i4JuAwg

**Comment by sapnadudhat03** [comment]
@Priya-Goenka Please write the doc for this as shown in video.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1vgFM591d2qGEJhLLIlyhxJbYk8J5CM36dRSFo6_q--8/edit

**Comment by sapnadudhat03** [comment]
@SwapnilBendale and @ashokdudhat The doc is ready and verified. Swapnil can add in live.

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Pls share live site link if it is added on site.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/install-wp-event-manager-addons/
