### ISSUE TITLE
Logical Bug in datepicket range selection

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#427]
I have one event start from 12-08-2020 to 18-08-2020, but if I select datepicker as seen below screenshot  then this event not display in result list.
It seems like that only check start date is within the given range, but we must need to check for end date also.

![image](https://user-images.githubusercontent.com/25837982/91287663-aada1980-e7ad-11ea-93e7-1ce2c3147277.png)

**Comment by krinaydhanani** [comment]
Now it's working fine.
