### ISSUE TITLE
Hide addintional information section

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#429]
Hide additional information section from single event page : 
to hide additional information section from single event page, need to add this code in functions.php file of child theme.

`
// Disable additional fields on frontend event detail page

add_filter( 'event_manager_show_additional_details', '__return_false' );
`

**Comment by ritakikani** [comment]
Testing done from my side so once @krinaydhanani  will test if this is working fine then we will prepare doc for this.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/14P4A-aIaLIlH45rH95jpibZ4zAOXN-OId23hKszYXvQ/edit

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Create a doc of this.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/hide-additional-info-section/
