### ISSUE TITLE
We should provide Event Search Bar feature.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#438]
We should provide the Event Search Bar feature because when there are multiple events that time users can fiend events easily.
We have to provide a setting of this feature like user can Endable or Disable Search bar from the backend.

Please take reference from me.

**Comment by wpem-kishan** [comment]
we have already giver this feature. In event search form "Search with Keyword" exaclty work as per your query.

**Comment by krinaydhanani** [comment]
Right now we are providing custom event search form but my concern is we need to provide the  Endable or Disable Search bar from the backend so users can easily use this feature.

**Comment by hiteshmakvana** [comment]
Use filter true or false to hide or show event filters and keyword search is already implemented with core plugin.

**Comment by krinaydhanani** [comment]
It's working fine.
