### ISSUE TITLE
Need to improve QUICK FEEDBACK feature while deactivating our add-on.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#441]
We need to improve QUICK FEEDBACK feature while deactivating our add-on so we easily understand why user deactivating our add-on and we improve it.

Please take reference from me.

- In WPEM Store we need to show below details.

**Plugin Feedbacks :**

Customer Email |  Website URL  |  Version  | Deactivate Reason | Date & Time

**Comment by krinaydhanani** [comment]
https://github.com/wpeventmanager/wp-event-manager/issues/1590

**Comment by ritakikani** [comment]
@mistry-jignesh , please also check here as it connected with this enhancement so https://github.com/wpeventmanager/wpemstore-licensing/issues/46

**Comment by mistry-jignesh** [comment]
I have checked the issue. A quick feedback feature is available.
When I deactivated the plugin, a popup is available.
It is working fine according to the requirements. There is one backslash issue available.
For that create a new issue in the WPEM store. Here I closed the issue.
