### ISSUE TITLE
User suggestion : need to improve daterange picker

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#442]
I have an event in which start date is 1-1-2020 and event end date is 31-12-2020.
So i filter event listing with daterange picker date with "1-8-2020 to 1-10-2020", then i am not getting above event, but as per the logic it must be there in result list cause in "1-8-2020 to 1-10-2020" range event already in running mode.

**Comment by hiteshmakvana** [comment]
Most of the case event will be for certain days not for months. I think better is to make it simple instead of more complex.

**Comment by hiteshmakvana** [comment]
Daterange picker works on event start date. This is not valid in case of start date.
