### ISSUE TITLE
Timezone- default to Wordpress timezone

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#444]
![image](https://user-images.githubusercontent.com/65893994/91698620-a12b2a00-eb90-11ea-85a5-f978ab476348.png)

**Comment by wpem-kishan** [comment]
We already give setting and It is working fine.
![image](https://user-images.githubusercontent.com/61741365/91701542-13057280-eb95-11ea-90e8-623d0aff1119.png)

**Comment by krinaydhanani** [comment]
We are providing the feature so it's working fine.
