### ISSUE TITLE
Need to update pot file

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#446]
Some missing string is in .pot file like,

"If it doesn't show organizer(s). Manage your organizer(s) from here"
![image](https://user-images.githubusercontent.com/25837982/91797584-8ca66a80-ec40-11ea-9611-09d60e0a7f02.png)

 "to"

![image](https://user-images.githubusercontent.com/25837982/91797544-726c8c80-ec40-11ea-97c4-284844bc5dc9.png)

**Comment by krinaydhanani** [comment]
File updated.
