### ISSUE TITLE
need to set design for notification 

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#447]
Here, "Rss Reset" looks like it is one word, we must need to separate it so user can understand that  "RSS" and "Reset" is separate word with its own functionality.

![image](https://user-images.githubusercontent.com/25837982/91800282-4fdd7200-ec46-11ea-80ae-84d17e82885a.png)

**Comment by krinaydhanani** [comment]
Now it's look batter.
