### ISSUE TITLE
Need to add RSS feed funstionality in doc

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#448]
Need to add topic, user can generate RSS Feed also for searched events and also mention that we are providing RSS Feed with html view, if they want RSS in XML then need to override template file "rss-event-feed.php" at child theme side.

![image](https://user-images.githubusercontent.com/25837982/91800675-0b9ea180-ec47-11ea-8859-c5e3110a620a.png)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1P7eyIKCGgReNMjoVyxM3LKIyBk0Kf_B4QswZOuvulAY/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Content is available in the "Event listing " section on the KB page.
So I closed the issue.
