### ISSUE TITLE
Customization Doc

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#449]
Is it possible to show my registrations on my account page as a new menu? Rita kindly give code of this so priya can make a doc pf this.

**Comment by ritakikani** [comment]
Hi @Priya-Goenka , you need to put this code in child theme or main theme functions.php file and then need to Save Permalink from admin panel, ypu will get "My Registrations" tab in my-account page at front side.

`// ------------------
// 1. Register new endpoint to use for My Account page
// Note: Resave Permalinks or it will give 404 error
  
function wpem_add_my_registrations_endpoint() {
    add_rewrite_endpoint( 'my-registrations', EP_ROOT | EP_PAGES );
}
  
add_action( 'init', 'wpem_add_my_registrations_endpoint' );
  
  
// ------------------
// 2. Add new query var
  
function wpem_my_registrations_query_vars( $vars ) {
    $vars[] = 'my-registrations';
    return $vars;
}
  
add_filter( 'query_vars', 'wpem_my_registrations_query_vars', 0 );
  
  
// ------------------
// 3. Insert the new endpoint into the My Account menu
  
function wpem_add_my_registrations_link_my_account( $items ) {
    $items['my-registrations'] = 'My Registrations';
    return $items;
}
  
add_filter( 'woocommerce_account_menu_items', 'wpem_add_my_registrations_link_my_account' );
  
  
// ------------------
// 4. Add content to the new endpoint
  
function wpem_my_registrations_content() {
	echo '<h3>My Registrations</p>';
	echo do_shortcode( '[my_registrations]' );
}
  
add_action( 'woocommerce_account_my-registrations_endpoint', 'wpem_my_registrations_content');`

**Comment by ritakikani** [comment]
@krinaydhanani , @Priya-Goenka , please check this above code.

**Comment by sapnadudhat03** [comment]
@Priya-Goenka **If the above code is working fine then create a new doc of this.**

**Comment by Priya-Goenka** [comment]
Didnot work for me.

**Comment by krinaydhanani** [comment]
@Priya-Goenka It's working fine. Please test again.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1GnJuFZtwgLPEs_P8koyjyPZsYYEs2ocYeH3-fI5OCIk/edit#

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Create a doc of this.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/add-my-registrations-my-account/
