### ISSUE TITLE
Need to add GDPR checbox in forms

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager#452]
We need to add GDPR checkbox in all our forms like submit event, submit organizer etc. as per client suggestion : 

I don't think, that every your EU citizen clients should develop the legally correct contact form one by one.I mean, you have to grant the correct, working contact form. The GDPR checbox is totally basic in the form, like the name field or the send button.I
 am really surpriced, that you didn't know, how GDPR works, however, you
 have to implement also this rules, if you sell for EU citizens... I
understand, that you cannot update the plugin immediately, but please,
let me know the exact, step-by-step solution for this failure asap.If you cannot, then please be so kind escalate the issue, because your form is wrong currently.

**Comment by krinaydhanani** [comment]
I dont think we need to i,mplement this feature because we are selling just Wordpress addon. We are not store any data on database. Our addon store data in client database but for that they can use third party GDPR addon.
