### ISSUE TITLE
Need to move 3 fields in Venue feature.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#454]
If we are making separate venue field then there is no meaning to show Venue Name, Zip Code, Event Location in the post an event page because the user is confused between 2 forms. Need to move 3 fields in Venue feature.

If we are providing separate venue feature then why we are taking the information from post an event page?

![image](https://user-images.githubusercontent.com/35419531/92081607-f1003000-ede0-11ea-9fc7-ff976505508b.png)

**Comment by wpem-kishan** [comment]
I discussed with Hitesh, he told me only one field "Venue Name" removed.

**Comment by krinaydhanani** [comment]
I think we should move all the venue related fields in venue form. If I am thinking from the user side there is no meaning to fillup some fills in venue fields and some in event form.

**Comment by hiteshmakvana** [comment]
No, we will not move event location and zip code we will move once we get more feedback from the user.

For now data will be stored in both the meta keys venue and event.
