### ISSUE TITLE
Need to change the text color in button.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#455]
Need to change the button colour.

![image](https://user-images.githubusercontent.com/35419531/92085537-97026900-ede6-11ea-838c-085e033ff041.png)

**Comment by siddharthgotawala** [comment]
This issue is not from core addon.

Please move this issue in proper addon and provide proper steps so i can find and solve this issue.

**Comment by siddharthgotawala** [comment]
c19185d

**Comment by krinaydhanani** [comment]
I close this issue to here.
