### ISSUE TITLE
ELEMENTOR : - Single event organizer not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#456]
Single event organizer not working.

![image](https://user-images.githubusercontent.com/35419531/92091173-fe6fe700-eded-11ea-8afb-35553c34eb20.png)

**Comment by wpem-kishan** [comment]
This is wight use while create single event page with elementor. I have verified this is working fine.

**Comment by krinaydhanani** [comment]
it's working fine for elementer pro.
