### ISSUE TITLE
ELEMENTOR : - Need to provide venue fields for elementor. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#457]
Because we are launching separate venue feature we must need to provide separate venue fields for elementor.  

We should provide widgets like: - 

Single Venue: - Hear we can show every single venue whatever user can choose from the dropdown.
Venue Dashboard: - Hear we can show the venue dashboard.
Single Event Venue: - Hear we can show every venue of every single event.

**Comment by krinaydhanani** [comment]
Still, one feature missing.

Single Event Venue: - Hear we can show every venue of every single event.

**Comment by wpem-kishan** [comment]
Single event page we can not show same as organizer section. we show only sidebar.

![image](https://user-images.githubusercontent.com/61741365/92200868-a2ae6800-ee98-11ea-8cb9-5b838dbf32d7.png)

**Comment by krinaydhanani** [comment]
It's working fine.
