### ISSUE TITLE
ELEMENTOR : - Single Event Field not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#459]
ELEMENTOR : - Single Event Field not working.

![image](https://user-images.githubusercontent.com/35419531/92094693-5ad50580-edf2-11ea-9e2e-9429717ddebb.png)

**Comment by wpem-kishan** [comment]
This is use while create single event page with elementor. I have verified this is working fine.

**Comment by krinaydhanani** [comment]
Some fields are not working.

In the event listing feature the following event field not working like.

1. Online Event
2. Zip Code - I can see venue Address in Zip code.
3. Video URL
4. Event timezone
5. Organization name
6. Registration Limit
7. Paid Tickets
8. Show Hide Registration Button
9. Free Tickets
10. Donation Tickets
11. Venues
12. Ticket Type

**Comment by krinaydhanani** [comment]
It's working fine but needs to remove 3 options from there.

1. Paid Tickets
2. Free Tickets
3. Donation Tickets

**Comment by krinaydhanani** [comment]
It's working fine.
