### ISSUE TITLE
Need to change the order of box.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#460]
Need to change the order of box. We need to show like.

1. Past Events
2. Current Events
3. Upcoming Events

![image](https://user-images.githubusercontent.com/35419531/92096142-2bbf9380-edf4-11ea-8fbd-7220eb5195b6.png)

**Comment by ashokdudhat** [comment]
COrrect order.

1. Current Event
2. Upcomming event
3. past event

**Comment by krinaydhanani** [comment]
Need to arrange this order.

1. Current Event
2. Upcoming event
3. past event

**Comment by krinaydhanani** [comment]
Now it's working fine.
