### ISSUE TITLE
Add new feature "fronted dashboard shorting".

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#462]
Add new feature "fronted dashboard shorting". So user can set order from here.

![image](https://user-images.githubusercontent.com/35419531/92205311-0b024700-eea3-11ea-8a72-7135f7c20bfc.png)

**Comment by Priya-Goenka** [comment]
Please add the image in the doc last https://docs.google.com/document/d/1rilB6G8Xf632ph-CN4bAGGGJn984w6U0K5LKLlIVxu8/edit

**Comment by siddharthgotawala** [comment]
screenshot is added in the doc.

**Comment by Priya-Goenka** [comment]
@Swapnil, pls add the last part: https://docs.google.com/document/d/1rilB6G8Xf632ph-CN4bAGGGJn984w6U0K5LKLlIVxu8/edit

Sorting Events on Frontend Dashboard with image here: https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

**Comment by SwapnilBendale** [comment]
Done - https://wp-eventmanager.com/knowledge-base/frontend-event-dashboard/

**Comment by krinaydhanani** [comment]
Shorting feature add-ed.
