### ISSUE TITLE
Need to add venue pages in page setup.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#463]
We have to add venue pages in Page Setup.

![image](https://user-images.githubusercontent.com/35419531/92233646-48c89500-eece-11ea-8b6f-916ed9f73240.png)

**Comment by wpem-kishan** [comment]
![image](https://user-images.githubusercontent.com/61741365/92349446-bacdf380-f0f3-11ea-810b-bec048ea1627.png)

**Comment by krinaydhanani** [comment]
It's working fine.
