### ISSUE TITLE
Venue Description box need to make like our other description box.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#465]
Venue Description box needs to make like our other description box.

![image](https://user-images.githubusercontent.com/35419531/92357511-99760300-f105-11ea-82bc-a888a05d1322.png)

**Comment by wpem-kishan** [comment]
when you test first you need to reset field editor then you will start testing.

**Comment by krinaydhanani** [comment]
It's working fine.
