### ISSUE TITLE
Event expiry Datepicker does not change. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#467]
Start and End Date are in one format added correctly. The expiry date is not added, though the place holder saying yyyy-mm-dd -- expiry date isn't added. I think the Expiry field takes dd-mm-yyyy and the placeholder is misleading

**Comment by wpem-kishan** [comment]
This is not date format issue. We need to change input box placeholder.

**Comment by krinaydhanani** [comment]
It's working fine.
