### ISSUE TITLE
The Thumbnails are not auto adjusting,

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#468]
Depending on the size of screen the thumbnails do not auto adjust to the events listing page. They cut. 

![image](https://user-images.githubusercontent.com/65893994/92471369-7c206200-f1f5-11ea-83b6-a1dccf0dd3e3.png)

**Comment by siddharthgotawala** [comment]
If we remove hard cropping it will look something like this if user use wide and square images together it will still not look good so right now our listing is fine

![image](https://user-images.githubusercontent.com/68212017/93090671-b76dd580-f6ba-11ea-82d0-5a599e18cdec.png)
