### ISSUE TITLE
Event banner is not equalk to event thumbnail.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#469]
When you set a new event from backends, if someone is not assigning event thumbnail, it should automatically;ly take event banner as the event thumbnail. this is not happening.

**Comment by krinaydhanani** [comment]
After removing event banner option I was not able to remove Event Thumbnail from admin.

**Comment by krinaydhanani** [comment]
If I add a banner from thumbnail then it will not upload.

**Comment by krinaydhanani** [comment]
It's working fine.

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by hiteshmakvana** [comment]
@Priya-Goenka Can you please confirm then we can close this issue?
