### ISSUE TITLE
Events if on same date- does not sort by Time

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#472]
Is there any shortcode for sorting events by time? 
When shortcode [events orderby="event_start_date"] is passed, the events if on the same day, say November 7 has 10 events, at 4pm, 5pm, 8am, 10pm,7pm....
These do not order by time, they are randomly displayed.

**Comment by krinaydhanani** [comment]
Still, one event shows me in last.

![image](https://user-images.githubusercontent.com/35419531/92739894-f1796780-f39a-11ea-81da-9060adcee18d.png)

**Comment by krinaydhanani** [comment]
Now it's working fine.
