### ISSUE TITLE
Place holder not showing perfectly in Venue folder.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#473]
Select some option place holder not showing perfectly before opening. 

![image](https://user-images.githubusercontent.com/35419531/92568003-25ba2e80-f29c-11ea-8c96-35f5c9c4da04.png)

**Comment by wpem-kishan** [comment]
I checked, all looks good.

![image](https://user-images.githubusercontent.com/61741365/92719006-317f2100-f380-11ea-8fd9-157b0d8db9d3.png)

**Comment by krinaydhanani** [comment]
It's working fine.
