### ISSUE TITLE
Widget not working on time.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#474]
If event expired on 02:00 PM then still show Up Comming widget at 04:00 PM.

**Comment by wpem-kishan** [comment]
While test you need to check your site timezone.

![image](https://user-images.githubusercontent.com/61741365/92718762-da794c00-f37f-11ea-9e6a-0fcb37e39817.png)

**Comment by krinaydhanani** [comment]
It's working fine.

**Comment by krinaydhanani** [comment]
It's working fine.
