### ISSUE TITLE
Datepicker format

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#477]
Please see, I have selected the date picker format as 1-15-2020, however in the search bar, it does not appear to be the same. 

![image](https://user-images.githubusercontent.com/65893994/92897981-410f7000-f43b-11ea-9663-28b294e4efa3.png)
![image](https://user-images.githubusercontent.com/65893994/92898042-4cfb3200-f43b-11ea-8f54-a0905fdd573f.png)

**Comment by krinaydhanani** [comment]
Now it's working fine.
