### ISSUE TITLE
Event banner is distorted- iphone 11- Responsiveness issue. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#488]
![image](https://user-images.githubusercontent.com/65893994/93053600-a9ea2880-f685-11ea-9702-356dad9a762d.png)
![image](https://user-images.githubusercontent.com/65893994/93053633-b8d0db00-f685-11ea-9139-3802881929d1.png)

**Comment by Priya-Goenka** [comment]
Online responsive when checked is fine, but actually, on phone it's not p[roper.

**Comment by siddharthgotawala** [comment]
If we remove hard cropping it will look something like this if user use wide and square images together so right now listing is fine

![image](https://user-images.githubusercontent.com/68212017/93090208-0e26df80-f6ba-11ea-8c93-be89106e3c0e.png)

**Comment by krinaydhanani** [comment]
It's working fine in my device. I am using the same device. Please ask him to clear browser cache or check-in private browsing.

**Comment by hiteshmakvana** [comment]
![Image from iOS](https://user-images.githubusercontent.com/42602299/93203950-df207480-f772-11ea-9c9a-ae8c254d1448.png)

There is no issue in iPhone 11 Please check the above screenshot.
