### ISSUE TITLE
Need to make the proper description.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#489]
Need to make the proper label and description for both fields.

![image](https://user-images.githubusercontent.com/35419531/93063777-5cc18300-f694-11ea-9d27-42946777ad13.png)

**Comment by Priya-Goenka** [comment]
Enable Organizer- Enabling this would allow you to display organizers for your events. 
Enable Venue- Enabling this would allow you to display Venue for your events.

**Comment by Priya-Goenka** [comment]
Enable Organizer- Disable this to remove the functionality of Organizers on Your Event Website.
Enable Venue- Disable this to remove the functionality of Venue on your Event Website.

**Comment by Priya-Goenka** [comment]
Enable Organizer-Disable this to delete the Organizer feature on Your Event Page.
Enable Venue- Disable this to delete the Venue feature on Your Event Page.

**Comment by krinaydhanani** [comment]
Now it's working fine.
