### ISSUE TITLE
Venue list shortcode

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#492]
List of Venue, just like the organizer list to any visitor is not available. 
Any non-logged in visitors cannot see the list of venues.

**Comment by wpem-kishan** [comment]
use below shortcode for venue lists
[event_venues]

**Comment by krinaydhanani** [comment]
It's not working fine I got an error.

D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\shortcodes\wp-event-manager-shortcodes.php ( Line Number 1713)

**Comment by krinaydhanani** [comment]
Still, some error needs to fix it.

**Comment by krinaydhanani** [comment]
Still, some errors needs to fix it.
