### ISSUE TITLE
Venue Doc

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#493]

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/15aYNhZ1BakP2G-OVBHL7DA7Iz49rfzKWne7oi1iIBzQ/edit

**Comment by Priya-Goenka** [comment]
Siddharth please attach images after the layout has been designed.

**Comment by sapnadudhat03** [comment]
@SwapnilBendale It's verified from my side. 

Please discuss with priya for the screenshots before publishing on live site.

**Comment by SwapnilBendale** [comment]
Doc Published - https://wp-eventmanager.com/knowledge-base/setting-up-venue/
