### ISSUE TITLE
Need to make venue section in single event listing page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#506]
Need to make venue section in single event listing page.

**Comment by wpem-kishan** [comment]
Duplicate bug : https://github.com/wpeventmanager/wp-event-manager/issues/457

**Comment by krinaydhanani** [comment]
@wpem-kishan Please check URL does not redirect me to the single venue page.

![image](https://user-images.githubusercontent.com/35419531/93320127-51a25a80-f82e-11ea-8c69-47083c9ce67f.png)

@siddharthgotawala Please shoe the venue logo in the section.

**Comment by krinaydhanani** [comment]
@siddharthgotawala Please shoe the venue logo in the section.

**Comment by krinaydhanani** [comment]
Now it's working fine.
