### ISSUE TITLE
Organizer and Venue Popup option not showing at admin side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#508]
Organizer and Venue Popup option not showing at admin side so admin was not able to submit organizer and venue from admin side.

**Comment by wpem-kishan** [comment]
I discuss with Hitesh, We do not add the admin side.

**Comment by krinaydhanani** [comment]
Then please remove this question mark from the admin side so the user will not confuse.


![image](https://user-images.githubusercontent.com/35419531/93303578-5577b200-f819-11ea-980f-824c1cdfdcd6.png)

**Comment by wpem-kishan** [comment]
we can not remove because this is tooltip for showing information.

**Comment by krinaydhanani** [comment]
If we are showing the information but the user can not use this information then what is the meaning to show it?

**Comment by hiteshmakvana** [comment]
This is the help tool tip to provide more information about the field.
