### ISSUE TITLE
LAyout is bad for event summary page

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#514]
Event summary shortcode involved a summary of an event id. 
The layout shows a box that is even smaller than the normal event listing page, box layout. 

It should be like a previous one. 

![image](https://user-images.githubusercontent.com/65893994/93301573-46dbcb80-f816-11ea-89a2-6e1871958c6d.png)
![image](https://user-images.githubusercontent.com/65893994/93301585-4b07e900-f816-11ea-9429-7b88ad515658.png)

**Comment by wpem-kishan** [comment]
If you want custom width then define width in shortcode parameter
[event_summary id="18" width="250px" align="left" featured="false" limit="1"]

**Comment by krinaydhanani** [comment]
@Priya-Goenka please put this shortcode and new image in the documentation.
