### ISSUE TITLE
Need code for fixing Event banner 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#520]
Many requests to fix the event banner size, please provide code for the same.

**Comment by siddharthgotawala** [comment]
Can you specify which event banner you want to fix in size? or can you share a screenshot?

**Comment by siddharthgotawala** [comment]
For single event listing page, We can not fix banner size user have to crop image themselves.

**Comment by krinaydhanani** [comment]
It's working fine.
