### ISSUE TITLE
Event images on additional info

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#523]
When in field editor, some one is adding a field as event images and adding images, it is displaying Array

![image](https://user-images.githubusercontent.com/65893994/93427449-76a0d700-f8db-11ea-83ed-a79850592dcb.png)
![image](https://user-images.githubusercontent.com/65893994/93427465-7bfe2180-f8db-11ea-88e3-606e1c6d7255.png)

**Comment by krinaydhanani** [comment]
Now it's working fine.
