### ISSUE TITLE
Event_type filter not working

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#531]
[events event_type="Attraction"] Not working

**Comment by wpem-kishan** [comment]
@Priya-Goenka you added the wrong shortcode parameter

follow these bugs: https://github.com/wpeventmanager/wp-event-manager/issues/224

**Comment by krinaydhanani** [comment]
[events show_filters="false" show_pagination="true" per_page="3" selected_event_type="attraction"]

It's working fine please put above shortcode.
