### ISSUE TITLE
String Translation

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#533]
Please check if all the strings are translated

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/93748180-75421800-fc15-11ea-84a0-89074dc4c648.png)
![image](https://user-images.githubusercontent.com/65893994/93748235-87bc5180-fc15-11ea-8bdc-57dc9a2f0409.png)
![image](https://user-images.githubusercontent.com/65893994/93748290-9efb3f00-fc15-11ea-82f6-c0f7353bc46a.png)
![image](https://user-images.githubusercontent.com/65893994/93749437-8db33200-fc17-11ea-808f-70caba90bc59.png)

**Comment by wpem-kishan** [comment]
I have verified all strings. There are not define hardcode strings. We will generate again pot file.

**Comment by shopdoc** [comment]
There are still some strings which changed to lowercase like "paid", "free" etc. and so lost their translation.

**Comment by Michele64** [comment]
still not translated, even if the strings are present in the .po files... 
![Köln-–-online-–-Pyar](https://user-images.githubusercontent.com/13287876/203856241-9ee402ff-1a83-489f-a797-460385c3e31b.png)

**Comment by mistry-jignesh** [comment]
I have verified the above issues. Facing issues mentioned in the screenshot.


1.![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/4eccec25-d9b8-4e68-bf4d-41cfce7fc32f)


2. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/8f81bcdf-d7c2-4bef-ab1c-9b6263b9e02a)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now String Translation issue is fixed.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/58e116af-9849-4a7f-9e88-7958f50e602d)

So I closed the issue
