### ISSUE TITLE
RSS feed for all the events

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#536]
Right now, RSS feed is only avaialable after searching, rather it should be available for all the events.

**Comment by live-aamir** [comment]
@mistry-jignesh @Priya-Goenka RSS feeds are for listing multiple posts, the RSS would include a link to the post itself. RSS feed for one post or page is not recommended. 

Other than searching, one can also subscribe to event listing post by using below format url for RSS.
**https://example.com/feed/?post_type=event_listing**

**Comment by mistry-jignesh** [comment]
As per @live-aamir : RSS feeds are for listing multiple posts, the RSS would include a link to the post itself. RSS feed for one post or page is not recommended.
So I closed the issue.
