### ISSUE TITLE
Need to set Validation for Event timezone.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#538]
Need to set Validation for Event timezone. If the user selects the **Use website timezone** option that time we need to remove **Event timezone** from add-event in admin side.

@Priya-Goenka Also need to make one separate doc on the Event timezone.

**Comment by wpem-kishan** [comment]
I have verified with an existing and fresh setup. It works fine.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/other-settings/
