### ISSUE TITLE
Multi select category is not working 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#544]

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/94105829-c2153100-fe57-11ea-93e7-337269c5eda7.png)
Please see i have selected multicategories, however it is not displaying on the frontend.

**Comment by Priya-Goenka** [comment]
![Uploading image.png…]()

**Comment by wpem-kishan** [comment]
It works fine, You need to enable the setting for that.

Setting -> Event Submission 

![image](https://user-images.githubusercontent.com/61741365/94107489-300f2780-fe5b-11ea-85b6-266f0a579a6a.png)

**Comment by krinaydhanani** [comment]
It's working fine. We have to select an option from setting.
