### ISSUE TITLE
Organizer name missing in event organizer page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#545]
Organizer name missing in event organizer page.

![image](https://user-images.githubusercontent.com/35419531/94105893-e8d36780-fe57-11ea-90f3-9357db2be43f.png)

**Comment by wpem-kishan** [comment]
Organizer name already come to I think we do not add above description

![image](https://user-images.githubusercontent.com/61741365/94110860-e75a6d00-fe60-11ea-906f-7eec1edf4735.png)

**Comment by krinaydhanani** [comment]
We need to change the design also for showing mail id and contact number. @siddharthgotawala please redesign it also.

**Comment by wpem-kishan** [comment]
@krinaydhanani as per our discussion I have added Organizer phone field but need some css for first test and assign to this bug @siddharthgotawala

**Comment by krinaydhanani** [comment]
Now it's working fine.

**Comment by wpem-kishan** [comment]
As per discuss with @hiteshmakvana we remove organizer phone field
