### ISSUE TITLE
There is an error with the registration/email url button. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#546]
After a link is added and when the event is edited, it fill a email id of someone by default. 

https://www.youtube.com/watch?v=e46IYMtSATo&feature=youtu.be

**Comment by Priya-Goenka** [comment]
https://www.youtube.com/watch?v=KDGvXAbXC50&feature=youtu.be

**Comment by wpem-kishan** [comment]
I have watch video and I have test with fresh setup and existing setup both site working fine.

**Comment by krinaydhanani** [comment]
It's working fine in my PC also.
