### ISSUE TITLE
When I change the event Thumb line that time the event banner not changing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#547]
When I change the event Thumb line that time the event banner not changing.

![image](https://user-images.githubusercontent.com/35419531/94112082-8e8bd400-fe62-11ea-901f-1d2c1f2e8cfc.png)

**Comment by wpem-kishan** [comment]
we can not change event banner when user upload thumbnail.

**Comment by krinaydhanani** [comment]
@Priya-Goenka Please take care of this thing from now Event Thumbline and Event Banner is different things. If the user uploads event banner then they can see there changes in banner and if the user can change the event thumbline then they chan see the change only in event listing thumbline.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/adding-your-first-event/

**Comment by sapnadudhat03** [comment]
@Priya-Goenka Pls add a link of the section which u added in all doc so I come to know. Otherwise, I am just searching in the whole doc.
