### ISSUE TITLE
Box missing in the pagination arrow.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#550]
Box missing in the pagination arrow.

![image](https://user-images.githubusercontent.com/35419531/94135826-a0c93a80-fe81-11ea-9ee1-c6a42d15d604.png)

**Comment by wpem-kishan** [comment]
I have verified it. It not missing any box.

![image](https://user-images.githubusercontent.com/61741365/94139060-a9703f80-fe86-11ea-8620-42202d72408c.png)
