### ISSUE TITLE
Uploading a PDf file in additional section doesnot downloads it - it shows array. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#558]
![image](https://user-images.githubusercontent.com/65893994/94263297-75fae700-ff52-11ea-9ec1-c64df437801c.png)
![image](https://user-images.githubusercontent.com/65893994/94263332-814e1280-ff52-11ea-9600-b52a479c74b1.png)
![image](https://user-images.githubusercontent.com/65893994/94263353-8b701100-ff52-11ea-8100-4d4b7c84dd00.png)

**Comment by krinaydhanani** [comment]
Now, this issue is fixed. Now user can download any file like (PDF, Word, Text) from the upload file.

**Comment by hiteshmakvana** [comment]
![image](https://user-images.githubusercontent.com/42602299/100592936-cc532000-331d-11eb-9a0b-f47358f97ef4.png)


If file type is pdf then it will show a download button and if the file is an image then it will directly output.
