### ISSUE TITLE
Field Editor : Type (Button option)

### ISSUE THREAD

**Issue by NirmalMistry123** [wpeventmanager/wp-event-manager#56]
The Button Option type is not working.

![button_option](https://user-images.githubusercontent.com/43330266/46069656-9b08c380-c199-11e8-90af-2bb8fc9ff063.png)

**Comment by hiteshmakvana** [comment]
Please use options array in your field.  There is no issue in button options type.

**Comment by hiteshmakvana** [comment]
When you are using field editor it will might show error or warning. New version 2.8 it is fixed.
