### ISSUE TITLE
Thumbnail images on widgets are cutThumbnail images on widgets are cut

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#560]
![image](https://user-images.githubusercontent.com/65893994/94263942-7c3d9300-ff53-11ea-91f5-e3341ce111e3.png)

**Comment by wpem-kishan** [comment]
duplocate bug : https://github.com/wpeventmanager/wp-event-manager/issues/563

**Comment by krinaydhanani** [comment]
I close this issue because of duplication.
