### ISSUE TITLE
Need to make separate google map and venue section.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#562]
Need to make separate google map and venue section.

![image](https://user-images.githubusercontent.com/35419531/94331631-cf632480-ffeb-11ea-97f2-81926ce1784d.png)

**Comment by wpem-kishan** [comment]
we already implemented on google map addon. Please test with latest google map code.

**Comment by krinaydhanani** [comment]
I close this issue here because of the duplication issue of Google Map.
