### ISSUE TITLE
Sort by time on event dashboard.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#564]
Sort by time on the event dashboard.

![image](https://user-images.githubusercontent.com/35419531/94398958-2bf94780-0184-11eb-852e-327ed395d467.png)

**Comment by hiteshmakvana** [comment]
Sorting filter already provided with new dashboard in 3.1.18

**Comment by krinaydhanani** [comment]
Yes, the date short issue was fixed in the new dashboard.
