### ISSUE TITLE
Need to show finger pointer on event category and type in the single event listing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#566]
Need to show finger pointer on event category and type in the single event listing.

![image](https://user-images.githubusercontent.com/35419531/94644688-9a1a4780-0307-11eb-954e-06bf6765e971.png)

**Comment by wpem-kishan** [comment]
@siddharthgotawala please check.

**Comment by krinaydhanani** [comment]
Now it's working fine.
