### ISSUE TITLE
Show Hide Registration Button still showing after removing code.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#567]
Show Hide Registration Button still showing after removing code and field from field editor.

![image](https://user-images.githubusercontent.com/35419531/94666841-9e585c00-032b-11eb-9793-b3d47de64590.png)

**Comment by wpem-kishan** [comment]
When you remove code then delete also field from field editor in admin side.

**Comment by krinaydhanani** [comment]
I already removed Show Hide Registration Button field from field editor and still, I face this issue.

**Comment by wpem-kishan** [comment]
If you add a field via code then remove the field using the below filter.

```
add_filter( 'event_manager_show_additional_details_fields', 'wpem_show_additional_details_fields', 10 );

function wpem_show_additional_details_fields($additional_fields)
{
	if( isset($additional_fields['attendee_information_fields']) )
        unset($additional_fields['attendee_information_fields']);

    return $additional_fields;
}
```

**Comment by krinaydhanani** [comment]
I face the same issue after removing the field from the field editor.

**Comment by krinaydhanani** [comment]
@Priya-Goenka Please make documentation for the below code. Which the help of the below code user will hide any fields in a single event listing.

```
add_filter( 'event_manager_show_additional_details_fields', 'wpem_show_additional_details_fields', 10 );

function wpem_show_additional_details_fields($additional_fields)
{
	if( isset($additional_fields['attendee_information_fields']) )
        unset($additional_fields['attendee_information_fields']);

    return $additional_fields;
}
```

**Comment by krinaydhanani** [comment]
Yes now, the issue is perfectly fixed. The documentation part still remains @Priya-Goenka Please make documentation on this code and move to the fix. I will close this issue after documentation.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1N-ysIR3-1Y4tsT-RZQAvcjtgbsmuXJEmUSrNO4YSvWI/edit
