### ISSUE TITLE
Events Selected Datetime not working with order by and order filter.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#568]
Events Selected Datetime not working with order by and order filter.

[events selected_datetime="today,28-12-2020" orderby="event_start_date" order="DESC"]

**Comment by wpem-kishan** [comment]
I have verified it. This is working fine.

**Comment by krinaydhanani** [comment]
This shortcode is not working fine in my Events listing.

[events selected_datetime="today,2-10-2020" orderby="event_start_date" order="ASC"]

**Comment by wpem-kishan** [comment]
Try with latest code.

**Comment by krinaydhanani** [comment]
After updating the add-on this shortcode is perfectly working fine.
