### ISSUE TITLE
After creating the pages it will not set automatically to the pages in setting page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#571]
After creating the pages it will not set automatically to the pages in setting page. We have to provide this to the user so they do not want to setup manually.

![image](https://user-images.githubusercontent.com/35419531/94991696-52631c80-05a2-11eb-9308-0bbb413586e0.png)

**Comment by wpem-kishan** [comment]
@krinaydhanani please check.

**Comment by krinaydhanani** [comment]
Yes now, the issue was fixed. All the page was automatically select in the page after finish setup.

**Comment by hiteshmakvana** [comment]
@krinaydhanani After the new dashboard, there is no need for an organizer and the venue dashboard must be removed.

If it is making conflict with the links and filter please provide details here.

**Comment by krinaydhanani** [comment]
@wpem-kishan Please remove the organizer and the venue dashboard from the page setup.

**Comment by wpem-kishan** [comment]
As discussed with @hiteshmakvana we do not delete organizer and venue dashboard pages.

**Comment by krinaydhanani** [comment]
As per the @hiteshmakvana, we are not removing the organizer and the venue dashboard pages from pagesetup.
