### ISSUE TITLE
Event banner

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#573]
Please provide code, if the event banner is not selected from the backend, it should select a automatic image like on our staging site it selected wp ecvent manager logo, same they ant to change then?

![image](https://user-images.githubusercontent.com/65893994/95057761-397a7880-0714-11eb-831f-a32038efce57.png)

**Comment by ritakikani** [comment]
@Priya-Goenka , to set default image for single event page, you need to write below filter in your parent/child theme functions.php file :

```
add_filter('event_manager_default_event_banner', 'set_event_manager_default_event_banner', 10, 2);
function set_event_manager_default_event_banner($event_banner, $post){
	return 'DEFAULT_EVENT_BANNER_PATH';
}
```

**Comment by mistry-jignesh** [comment]
As discussed with the team client need to follow the above instruction then it can work as per your request.
So I closed the issue.
