### ISSUE TITLE
Need to fix validation issue in submit event.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#574]
While post and event I got  (Event end date must be greater than the event start date. ) notification.

![image](https://user-images.githubusercontent.com/35419531/95072096-502aca80-0728-11eb-96b9-22ad39bb2222.png)

**Comment by wpem-kishan** [comment]
@krinaydhanani please check.

**Comment by krinaydhanani** [comment]
Yes, I got this issue because of the Date **.** ( Dot ) format now it's fixed.
