### ISSUE TITLE
Need to fix notification design issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#576]
Notification is not aligning properly.

![image](https://user-images.githubusercontent.com/35419531/95166072-d7c91580-07ca-11eb-8687-e3600c04eb52.png)

![image](https://user-images.githubusercontent.com/35419531/95166186-0a730e00-07cb-11eb-840b-6724b981ce58.png)

**Comment by siddharthgotawala** [comment]
We will improve this in 3.1.19

**Comment by kaushikpokal** [comment]
Fixed

![image](https://github.com/user-attachments/assets/f77cf04f-4397-4171-852d-a5613f0f9cbe)

![image](https://github.com/user-attachments/assets/08b56169-afb5-4c3d-b0bc-15dc50d7de10)

**Comment by mistry-jignesh** [comment]
Now this issue is fixed. So I closed the issue.

![image](https://github.com/user-attachments/assets/b031ee3e-19c2-4946-b266-847646bf4e9e)
