### ISSUE TITLE
Need to make all the filter boxes same.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#577]
Need to make all the filter boxes drop-down arrow same.

https://wpeventmanager.slack.com/files/U016YCBUUHY/F01C10B9YCA/image.png?origin_team=T9ZC8TJ2D&origin_channel=D017UJVMF8U

**Comment by siddharthgotawala** [comment]
Filter boxes dropdown arrow comes from browser and Datepicker dropdown arrow comes from datepicker library. We cannot change it globally. User can customise themselves.

**Comment by krinaydhanani** [comment]
If it arrow come from the browser side and one arrow is an image then we can not do anything.
