### ISSUE TITLE
Multiple event Type and Category not showing in the single event listing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#580]
Multiple event Type and Category not showing in the single event listing.

To reproduce this bug follow the below steps.

1. While publishing event select multiple types and category.
2. Approve this event from the admin side.
3. Open the event and check the sidebar how many category and type you can see.

![image](https://user-images.githubusercontent.com/35419531/95419853-0a544900-0958-11eb-89b4-67a097cdf0e2.png)

**Comment by wpem-kishan** [comment]
You need to enable the setting for that.

![image](https://user-images.githubusercontent.com/61741365/97871482-96307980-1d3a-11eb-9174-fd38849befc5.png)

**Comment by krinaydhanani** [comment]
Still, the Multi-select Event Category For Submission features not working.

![image](https://user-images.githubusercontent.com/35419531/97997047-66ff2400-1d9d-11eb-8146-9d19b4dff8e5.png)

**Comment by krinaydhanani** [comment]
After removing the above setting this feature not working.

**Comment by krinaydhanani** [comment]
Now the Term Multiselect is perfectly working fine but Term Select not working.

**Comment by krinaydhanani** [comment]
Yes, now the turn select and multi-select issues were perfectly fixed.
