### ISSUE TITLE
Need to fix the warning in the core plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#581]
Need to fix the warning in the core plugin.

![image (3)](https://user-images.githubusercontent.com/35419531/95421422-12fa4e80-095b-11eb-82c1-db4878b9363d.png)

**Comment by wpem-kishan** [comment]
give me case which case field editor data removed.

**Comment by krinaydhanani** [comment]
After fixing the field editor issue I never face the same issue. However, I will open the bug if I face the same issue in future.
