### ISSUE TITLE
Ticket prices option not working after activation sell ticket and registration add-on.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#585]
Ticket prices option not working after activation sell ticket and registration add-on.

![image](https://user-images.githubusercontent.com/35419531/95648132-8d110b80-0af2-11eb-9659-7f8feac0a1a3.png)

**Comment by wpem-kishan** [comment]
Yes, we removed ticket price option fields if sell ticket plugin active.

**Comment by krinaydhanani** [comment]
If we removed the Ticket prices option fields once the user active Sell ticket then please remove the setting as well so it will not make confusion for the user.

**Comment by wpem-kishan** [comment]
try with latest core and sell ticket addons.

**Comment by krinaydhanani** [comment]
With the latest code, this feature is perfectly working fine.
