### ISSUE TITLE
Need to rename the notification.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#588]
In the trash page after deleting the event I can see the notification like "1 post permanently deleted." We have to show event deleted. @Priya-Goenka Please provide suitable text for this notice.

![image](https://user-images.githubusercontent.com/35419531/95949550-86470900-0e10-11eb-83e9-5c3a2a7d5888.png)

**Comment by Priya-Goenka** [comment]
Your event is permanently deleted.

**Comment by krinaydhanani** [comment]
Still, this issue is not fixed, please show the above notice once the user deletes any event.

**Comment by wpem-kishan** [comment]
We follow woocommerce notification message and we need to show singular & multiple count with a message.

**Comment by krinaydhanani** [comment]
Then it's fine. I am closing this issue because we are following WooCommerce rule.
