### ISSUE TITLE
Improve the description box on frontend. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#589]
![image](https://user-images.githubusercontent.com/65893994/96086279-b7dad580-0edf-11eb-9df6-ce097455c4ff.png)

**Comment by wpem-kishan** [comment]
You need to add below code in functions.php and add give upload image capability to user role wise.

For ex.
$organizer = get_role('organizer');
$organizer->add_cap('upload_files');

```
add_filter( 'submit_event_form_wp_editor_args', 'wpem_submit_event_form_wp_editor_args', 10 );

function wpem_submit_event_form_wp_editor_args($args)
{
	$args['media_buttons'] = true;

    return $args;
}
```

**Comment by krinaydhanani** [comment]
@Priya-Goenka Please make a doc for this setting.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1Tkz0SqobqLLuoypFlsfplOvKEHDaKkbSaoJ5cs-b5b4/edit

**Comment by SwapnilBendale** [comment]
Published - https://wp-eventmanager.com/knowledge-base/add-images-in-description-box/
