### ISSUE TITLE
Load more button is not showing

### ISSUE THREAD

**Issue by siddharthgotawala** [wpeventmanager/wp-event-manager#591]
Load more button is not showing when we toggle list view.

**Comment by wpem-kishan** [comment]
This is an issue form calendar addon

duplicate issue: https://github.com/wpeventmanager/wp-event-manager-calendar/issues/32

**Comment by krinaydhanani** [comment]
I close this issue here because of duplication of https://github.com/wpeventmanager/wp-event-manager-calendar/issues/32
