### ISSUE TITLE
Core button focus issue

### ISSUE THREAD

**Issue by siddharthgotawala** [wpeventmanager/wp-event-manager#593]
Button hover color stays on the background until the user clicks somewhere else.
https://github.com/wpeventmanager/wp-event-manager-contact-organizer/issues/11

**Comment by wpem-kishan** [comment]
Commit link : https://github.com/wpeventmanager/wp-event-manager/commit/286136f7b64f4c9c98e42b847575fbd02399c779

**Comment by krinaydhanani** [comment]
Now, this button hover and the colour issue is fixed. Now it looks better than previous.
