### ISSUE TITLE
Require notice text for Event Time zone.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#600]
Require notice text for Event Time zone.

For example 
First user will publish the event with Use website time zone option and then they select the Select time zone on each event  then our addon will take WordPress by default time zone.

![image](https://user-images.githubusercontent.com/35419531/96578622-51143e00-128a-11eb-9aed-4b39de7bd445.png)

**Comment by Priya-Goenka** [comment]
given

**Comment by krinaydhanani** [comment]
I can not see any notice in the setting. @wpem-kishan Please put the notice whatever giver by priya.

**Comment by Priya-Goenka** [comment]
Use website timezone
Choose a time zone for each event.

**Comment by Priya-Goenka** [comment]
In case while submitting an event, if the timezone for each event is not selected, the event manager and other addons will take the default WordPress timezone.

**Comment by krinaydhanani** [comment]
I don't think the above notice is more suitable @hiteshmakvana please put your comment. If you think the above notice is perfectional then please ask @wpem-kishan to put in the code.

@wpem-kishan Please give the space between **Time** **Zone** because both are separate words.

**Comment by krinaydhanani** [comment]
Yes, the notice was updated now user will understand easily about both feature.
