### ISSUE TITLE
Override archive template

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#609]
Override archive template

**Comment by wpem-kishan** [comment]
copy file: wp-content/plugins/wp-event-manager/templates/content-event_listing_category.php
past file: wp-content/themes/YOUR-THEME/wp-event-manager/content-event_listing_category.php

```
add_filter( 'archive_template', 'wpem_event_archive', 20 );

function wpem_event_archive($template)
{
	if ( is_tax( 'event_listing_category' ) ) {

		$template = get_template_directory() . '/wp-event-manager/content-event_listing_category.php';
    }
    elseif ( is_tax( 'event_listing_type' ) ) {

		$template = get_template_directory() . '/wp-event-manager/content-event_listing_type.php';
    }

    return $template;
}
```

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1CyqVR3X0aaSN_xdh5dyyHL4uWewmt1WmpLj-1aBOeiU/edit

**Comment by sapnadudhat03** [comment]
@SwapnilBendale Pls upload on live site.

**Comment by SwapnilBendale** [comment]
Updated - https://wp-eventmanager.com/knowledge-base/how-override-archive-template/

**Comment by ritakikani** [comment]
I could not found this doc link in our knowledgeable. Please add this link as menu.

**Comment by krinaydhanani** [comment]
https://wp-eventmanager.com/knowledge-base/template-files-override/

**Comment by mistry-jignesh** [comment]
I have verified this issue. This doc is available under **Tutorials** section.

URL : https://wp-eventmanager.com/knowledge-base/template-files-override/

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/e87ed11a-0dc9-41b0-9890-df6fa04f6346)
