### ISSUE TITLE
Need to show the search filter while users on the Multi-select Categories and Event Types option.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#610]
Need to show the search filter while users on the Multi-select Categories and Event Types option.

![image](https://user-images.githubusercontent.com/35419531/97144783-4f32fa80-1722-11eb-80d9-efe7d240c383.png)

**Comment by wpem-kishan** [comment]
If select type is multiselect then chosen jquery do not show search box in dropdown list.

https://harvesthq.github.io/chosen/

**Comment by krinaydhanani** [comment]
If the issue from the library side then it's fine, We can not do anything from our side.
