### ISSUE TITLE
Plugin info box alignment issue

### ISSUE THREAD

**Issue by siddharthgotawala** [wpeventmanager/wp-event-manager#612]
![image](https://user-images.githubusercontent.com/68212017/97268056-4bea5c80-1851-11eb-9fa5-7c0b79bd2e2a.png)

https://github.com/wpeventmanager/wp-event-manager-registrations/issues/83

**Comment by krinaydhanani** [comment]
Still the border touch with setting information.

**If possible then please redesign the setting page.**


![image](https://user-images.githubusercontent.com/35419531/97990203-6a41e200-1d94-11eb-97b7-318419bf6f36.png)

**Comment by krinaydhanani** [comment]
Now the alignment issue was fixed and looks better than the previous.
