### ISSUE TITLE
Field editor issue, some fields is not working properly.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#616]
Field editor issue, some fields are not working properly.

1. I got an array in output while I select an option in the multi-select field.
2. Term Checklist, Term Multiselect, Term Select type are not working.

![image](https://user-images.githubusercontent.com/35419531/97434473-4d149b80-18dc-11eb-90cf-2368a81664b0.png)

**Comment by wpem-kishan** [comment]
Term Checklist, Term Multiselect, Term Select type are working only front side

**Comment by hiteshmakvana** [comment]
Can we regulate the backend with gutenburge?

**Comment by wpem-kishan** [comment]
Yes now compatible with Gutenberg editor.

**Comment by krinaydhanani** [comment]
Yes, now I can not face this issue with other editors as well.
