### ISSUE TITLE
Need to fix some notice in the core plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#618]
Need to fix some notice in the core plugin.

![image](https://user-images.githubusercontent.com/35419531/98437743-a8dbe300-2099-11eb-9fa2-90fff7ce6035.png)

The notice is like 

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 360

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 299

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 360

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 299

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 360

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 299

**Comment by wpem-kishan** [comment]
give me test case.

**Comment by krinaydhanani** [comment]
After updating the core plugin I never got this notice but in future, if I will get the same notice I will open the bug.
