### ISSUE TITLE
Event Category multi-select setting not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#619]
After selecting the Event Category multi-select setting I am not able to select multiple categories from the event submission form.

![image](https://user-images.githubusercontent.com/35419531/98437977-b1cdb400-209b-11eb-8791-0cad5a9c8a7f.png)

**Comment by wpem-kishan** [comment]
After setting save you need to change field type:
![image](https://user-images.githubusercontent.com/61741365/99358825-1545b600-28d4-11eb-9d33-7933dfd142f0.png)

**Comment by krinaydhanani** [comment]
Now this issue is solved because we remove both settings from the setting page

**Comment by hiteshmakvana** [comment]
@krinaydhanani Have you tested without those settings will effect on several places like single event page, listing page?

**Comment by krinaydhanani** [comment]
Yes, @hiteshmakvana  I check in all the cases like after selecting the **Term Multiselect**, **Term Select** because once the user will select the **Term Multiselect** they can see the multiple categories and once he will change the **Term Select** then they can see one category but the old user can see all the category and type before event update.

**Comment by hiteshmakvana** [comment]
If user changed from multiple to single then what will happen?

Inside the database multiple values stored and you are getting a single value at the frontend.

**Comment by krinaydhanani** [comment]
As per the below comment I mention the old user can see all the categories and type before event update.
