### ISSUE TITLE
Need to fix some notice which is I got on post event page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#620]
Need to fix some notice which is I got on the post-event page.

![image](https://user-images.githubusercontent.com/35419531/98438149-26edb900-209d-11eb-998b-52876d76ca11.png)

Notice is like 

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 360

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 299
Skip to content

**Comment by wpem-kishan** [comment]
give test case.

**Comment by krinaydhanani** [comment]
I close this issue here because of duplication issue #404
