### ISSUE TITLE
Need to fix Ticket Options notice on post event page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#621]
I got the Ticket Options is a required field notice even if I select the ticket option.

Also, the ( . ) is missing in the post an event page.

![image](https://user-images.githubusercontent.com/35419531/98438173-5c92a200-209d-11eb-8901-24bf1af887ee.png)

**Comment by krinaydhanani** [comment]
Still, this issue is not fixed because still I got the notice even I select the paid or free option.

**Comment by wpem-kishan** [comment]
@krinaydhanani please check

**Comment by krinaydhanani** [comment]
Yes now the dot **.** will be added at the end of the notice and the feature is also working fine.

I got the **Ticket Price** after the **Registration Deadline** we need to show after the **Ticket Options** because  **Ticket Options** and **Ticket Price** both are connected fields.

![image](https://user-images.githubusercontent.com/35419531/100598168-6027ea80-3324-11eb-8ac4-61d1d8203385.png)

**Comment by wpem-kishan** [comment]
I have verified it, both field priorities define properly. Maybe you changed priority from field editor.

![image](https://user-images.githubusercontent.com/61741365/100702840-67a0cf80-33c8-11eb-8a23-b7165334d73e.png)

**Comment by krinaydhanani** [comment]
Maybe I face this issue while testing another field in the field editor. If I face the same issue in the future then I will open the same bug.
