### ISSUE TITLE
Need to fix some field editor issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#622]
Need to fix some field editor issues.

1.  Type - Button 

Button not working with Button Option in field editor.

Also, the button name was removed after submitting an event.

![image](https://user-images.githubusercontent.com/35419531/98438259-e3e01580-209d-11eb-9b5d-470bba8c937c.png)

2. Type - Repeated

The repeated type is not working.

3. Type - Textarea

Textarea's colour was gray while clicking on the writing area.

![image](https://user-images.githubusercontent.com/35419531/98438304-299cde00-209e-11eb-9fe1-f14c997da2ca.png)

**Comment by wpem-kishan** [comment]
I have verified it. This is working file. Repeated field we will improve.

**Comment by krinaydhanani** [comment]
Still, all the issue was exiting.

**1.  Type - Button** 

Button not working with Button Option in field editor.

Also, the button name was removed after submitting an event.

![image](https://user-images.githubusercontent.com/35419531/98438259-e3e01580-209d-11eb-9b5d-470bba8c937c.png)


**2. Type - Repeated**

The repeated type is not working.

**3. Type - Textarea**

Textarea's colour was gray while clicking on the writing area.

![image](https://user-images.githubusercontent.com/35419531/98438304-299cde00-209e-11eb-9fe1-f14c997da2ca.png)

**Comment by wpem-kishan** [comment]
1 and 3 fixed

**Comment by krinaydhanani** [comment]
We remove the button option in the field editor.
