### ISSUE TITLE
Need to fix event date issue I get it while post an event.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#623]
I got the "Event end date must be greater than the event start date." notice when I select the end date different from the start date.

![image](https://user-images.githubusercontent.com/35419531/98439008-5d2e3700-20a3-11eb-9ded-ac8ca1cf1127.png)

**Comment by wpem-kishan** [comment]
Yes, we added rules. If you added end date less than start date then you will get this error.

**Comment by krinaydhanani** [comment]
After updating I can not face the same issue.
