### ISSUE TITLE
Need to fix attribute issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#624]
Need to fix some attribute issues in the core plugin because some attributes are not working and some are in conflict with each other.

Following attributes are not working with **show_filters="_"**.
1. show_categories and show_event_types.

show_more attributes not working perfectly.

2. If I apply filter show_more="false" then we need to show all events. 

For example, if I have 20 events and  I set only 6 events for Listings Per Page and I apply show_more="false" then I can see only 6 events and there is no other way to go to other events.

3. selected_ticket_price="paid" not working.

4. ticket_prices="free" not working.

5. event_online="false" not working.

**Comment by krinaydhanani** [comment]
Need to correct the attribute definition is the doc and need to mansion if they want to show all event then they need to pass **per_page** attribute.

![image](https://user-images.githubusercontent.com/35419531/99939831-fa21ed00-2d90-11eb-9815-0d9adf2daed8.png)



@wpem-kishan Still the following attribute not working.

1. selected_ticket_price="paid" not working.
2. 
3. ticket_prices="free" not working.
4. 
5. event_online="false" not working.

**Comment by wpem-kishan** [comment]
1. [events selected_ticket_price="paid"]

2. [events selected_ticket_price="ticket_price_free"]

3. [events event_online="false"]

**Comment by krinaydhanani** [comment]
Now all the parameters working fine. @Priya-Goenka Please mention in the doc as well.

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/the-event-listings/?kinsta-cache-cleared=true

**Comment by krinaydhanani** [comment]
Now all the shortcode mentioned in the doc.
