### ISSUE TITLE
Custom Field- Wp-editor not working properly

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#626]
![image](https://user-images.githubusercontent.com/65893994/98641480-d783e300-2351-11eb-8e4c-2d62a51bf9f0.png)

**Comment by wpem-kishan** [comment]
I have verified it. This is working fine.

**Comment by krinaydhanani** [comment]
@wpem-kishan This is not working fine please check the backend side.

**Comment by krinaydhanani** [comment]
Yes, now the Custom Field- Wp-editor working properly admin side as well as the frontend side.
