### ISSUE TITLE
How to enter past events

### ISSUE THREAD

**Issue by atulc77** [wpeventmanager/wp-event-manager#627]
I'm creating an events website using WP Event Manager and I'd like to showcase our portfolio of recent events held before we started using WPEM. When creating an event in WPEM, the start-date selector doesn't let you go to any date earlier than today. I can manually override it and hand enter a past date, but then the newly created event shows as cancelled.  I'm looking for a way to enter the past events into WPEM and be able to pull up a list using [past_events] shortcode. Please help.

**Comment by hiteshmakvana** [comment]
@atulc77 We have taken your feedback and our team will improve ASAP.

**Comment by wpem-kishan** [comment]
https://github.com/wpeventmanager/wp-event-manager/issues/671

**Comment by krinaydhanani** [comment]
@atulc77 You can use the below filter to publish the past events.

For Frontside
Enable : add_filter('event_manager_show_past_date_frontend', '__return_true', 10);

For admin
Enable : add_filter('event_manager_show_past_date', '__return_true', 10);
