### ISSUE TITLE
Need to fix HTML tag issue in core plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#629]
HTML tag not working in the Venue and Organiser description.

For Example, if I try to put some HTML tags in the Venue and Organiser description from the description box then it will not work in fronten.

**Comment by wpem-kishan** [comment]
if you add more features in editor check below link.

https://code.tutsplus.com/articles/quick-tip-using-wp_editor--wp-27136

**Comment by krinaydhanani** [comment]
Please check the Venue and Organiser description box if I put some HTML tags still not working.

**Comment by krinaydhanani** [comment]
Now the HTML issue was fixed in the core plugin.
