### ISSUE TITLE
Translation strings

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#631]
Date Range on form
Category
Event Type

**Comment by hiteshmakvana** [comment]
Those string are compatible with translation but it is not taking translated value with some plugins.

**Comment by christianfroehlichconsulting** [comment]
Hi, its not working at us too. Did you found a workaround or a solution? 

Thank you!

**Comment by mistry-jignesh** [comment]
Verified this issue .This issue is present.

**Comment by tamanna-ahuja** [comment]
Covering in Translation #874 , Request you to close this issue as its duplicate

**Comment by mistry-jignesh** [comment]
This issue is covered in the #874. So here I closed the issue.
