### ISSUE TITLE
Organizer and venu strings are not translated

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#634]
Organizer and venue strings are not translated:
![image](https://user-images.githubusercontent.com/65893994/99391398-26a4b780-2900-11eb-86fd-6c7230fafee7.png)
![image](https://user-images.githubusercontent.com/65893994/99391414-2b696b80-2900-11eb-9a88-83ec4848c3a9.png)

Please check other strings as well.

**Comment by krinaydhanani** [comment]
Yes now, all the organizer and venue related string was trancelated.
