### ISSUE TITLE
Add new event dashboard design

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#638]
Add new event dashboard design

**Comment by krinaydhanani** [comment]
Need to highlight Event name as well as event status and put status icon.

![image](https://user-images.githubusercontent.com/35419531/99932584-8676e480-2d7e-11eb-9943-c9c022c883dc.png)

**Comment by krinaydhanani** [comment]
Need to make drop down menu more attractive.

![image](https://user-images.githubusercontent.com/35419531/99932799-27fe3600-2d7f-11eb-8df5-d13b1c2854d2.png)

**Comment by krinaydhanani** [comment]
A new event dashboard design was added now it looks better than previous.

**Comment by hiteshmakvana** [comment]
@krinaydhanani If anyone overridden the template file then How this will affect the dashboard?

Can you please provide a screenshot?

**Comment by krinaydhanani** [comment]
Yes for that reason we need to think about it before release and for that, I already open the bug https://github.com/wpeventmanager/wp-event-manager/issues/643.

**Comment by hiteshmakvana** [comment]
This bug we can close because the new design is implemented and old compatibility bug refferences.
