### ISSUE TITLE
Add option to remove the Location at all events

### ISSUE THREAD

**Issue by Felix5566** [wpeventmanager/wp-event-manager#640]

**Comment by wpem-kishan** [comment]
Do you want to remove from existing database or event data then you might have to remove manually or using sql query from your database? If you just removed field event may not work correctly.

**Comment by krinaydhanani** [comment]
I am going to close this issue because this is not a demanding feature by other customers and we don't think this is a necessary thing to implement like removing the location from all events. We can not implement this feature for security reasons as well.
