### ISSUE TITLE
Need to redesign addon setup page in the core plugin.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#642]
Need to redesign addon setup page in the core plugin.

**Comment by wpem-kishan** [comment]
@siddharthgotawala please verify your changes

**Comment by krinaydhanani** [comment]
Yes, not the new setup will ready but the button has some grammatical mistake so @Priya-Goenka Please provide me the correct button sentence also please update new screen shots in the documentation.

![image](https://user-images.githubusercontent.com/35419531/100448080-bfdd8600-30d7-11eb-842b-c0180eff84e3.png)

**Comment by Priya-Goenka** [comment]
Skip, set up the plugin manually.

**Comment by krinaydhanani** [comment]
@wpem-kishan please put the above text to the button.

**Comment by krinaydhanani** [comment]
Yes, now a new design was added. The new design looks better than the previous one.
