### ISSUE TITLE
Need to provide a new design like it will not affect the old users. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#643]
Need to provide a new design like it will not affect the old users. 

For example, if some user had purchased our add-on before 2 years and not renew it then the design will look like the below image.

![image](https://user-images.githubusercontent.com/35419531/99934354-c7bdc300-2d83-11eb-9b84-2ca5732f2a34.png)

Need to give the below add-on updates with a core plugin.

**1. Registration 
2. Export 
3. Ical
4. Bookmark
5. Alert**

**Comment by hiteshmakvana** [comment]
With new updates of addons, it will start fixing the issue.

**Comment by mistry-jignesh** [comment]
I have verified issue . Now this issue is working properly.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
