### ISSUE TITLE
I can not see the organizer name in the organizer box.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#645]
I can not see the organizer name in the organizer box on the single event listing page.

![image](https://user-images.githubusercontent.com/35419531/99962630-898dc700-2db6-11eb-825e-a0e1b2060afd.png)

**Comment by krinaydhanani** [comment]
Now I can see the organizer name in the organizer section.

**Comment by hiteshmakvana** [comment]
Now, if current post typ of $post variable is not belong to organizer or event then it will return empty.

`['event_listing', 'event_organizer']`
