### ISSUE TITLE
Notice text issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#649]
@Priya-Goenka Please provide proper notice text for no event.

@wpem-kishan Please apply the same text in the upcoming event as well.

![image](https://user-images.githubusercontent.com/35419531/100316990-8de9f800-2fe1-11eb-9506-9370017cee16.png)

**Comment by Priya-Goenka** [comment]
No events at the moment.

**Comment by krinaydhanani** [comment]
@wpem-kishan Please apply the above notice in the code.

**Comment by hiteshmakvana** [comment]
The current text is better the new. Please take a look if there is any grammatical mistake then update and provide feedbac.

**Comment by Priya-Goenka** [comment]
No mistake then.

**Comment by krinaydhanani** [comment]
I think we should show a notice for the **Upcoming events**   like **There are no upcoming events at this time.** and for the **Resent event** we should show the **There are no recent events at this time.** because it looks better than the previous.
