### ISSUE TITLE
Need to show the organizer author-wise in the particular event at admin side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#653]
Need to show the organizer author-wise in the particular event at admin side.

**Comment by wpem-kishan** [comment]
As per dicussed with @hiteshmakvana we need to show all Organizer for admin user.

**Comment by krinaydhanani** [comment]
I do not agree with the decision but as par @hiteshmakvana we are showing all the organizers to the admin.

**Comment by hiteshmakvana** [comment]
@krinaydhanani As per the default WordPress functionality, you must have to set up user role and particular access. If you doesn' t allow organizer to manage all organizer then it will reflect into a situation where organizer doesn't want to change the details (it might happen some site owner doesn't allow specific information).

Admin can access and set up different organizer event to different author. This may be confusion but there is no way accept proving all the organizer access to admin.
