### ISSUE TITLE
Need to give the pagination for organizer listing.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#654]
Need to give the pagination for organizer listing at single event page listing because if any event there is more than 10 organizer then the single event listing page goes too long.

**Comment by wpem-kishan** [comment]
I don't think so we add pagination on single event page because user will add 2 or 3 Organizers.

**Comment by hiteshmakvana** [comment]
Need to take feedback from the user and team. Please provide your view then I can commit anything.

**Comment by ritakikani** [comment]
There is no need to add pagination for organizer in single event page.

**Comment by mistry-jignesh** [comment]
As per team, there is no need to add pagination for the organizer on a single event page.

So I closed the issue.
