### ISSUE TITLE
Please verify- Elementor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#655]
When you are adding a custom field say gallery from field editor, and using a file attribute. Does that works with elementor as well?

**Comment by Priya-Goenka** [comment]
Add a custom field in field editor- Gallery
use the attribute file type
Check if you are uploading an image- via elementor in this custom field it works?
Please add 2-3 images and try.

**Comment by krinaydhanani** [comment]
@Priya-Goenka Add a custom field in field editor- Gallery use the attribute file type was fixed. 
For the Check, if you are uploading an image- via element in this custom field it works?
Please add 2-3 images and try. please provide me with proper stapes so I can reproduce it.
