### ISSUE TITLE
Moving pages to dashboard should remove from frontend. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#657]
If certain pages are moved to the event dashboard pages, then the menus should be removed from main tab- however this is subjective.

**Comment by hiteshmakvana** [comment]
Do you mean that registration or other dashboard shortcodes and settings will be removed from the frontend? 

No, all the shortcodes and settings will be the same as it is just the UI of the dashboard is changed. This will allow user to handle all the operations easily.

Thank you
