### ISSUE TITLE
Need to correct all the label in professional at admin side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#659]
Need to correct all the label in professional at admin side.

![image](https://user-images.githubusercontent.com/35419531/100585835-35359a80-3314-11eb-9f05-9282eeca7287.png)

**Comment by Priya-Goenka** [comment]
reference needed.

**Comment by hiteshmakvana** [comment]
Check strings and settings text is correct and user friendly

**Comment by Priya-Goenka** [comment]
provided
