### ISSUE TITLE
Need to correct notice text.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#660]
This feature is working only when the user is login. @Priya-Goenka please provide the suitable text so the user will understand.

![image](https://user-images.githubusercontent.com/35419531/100594280-7bdcc200-331f-11eb-9df8-8c0f374284f8.png)

**Comment by Priya-Goenka** [comment]
If enabled, the registration form will hide, after the user registers for the event.

**Comment by krinaydhanani** [comment]
@Priya-Goenka You should mention like this feature is working when the user is login.

**Comment by Priya-Goenka** [comment]
If enabled, the registration form will hide, after the user Logged in user registers for the event.

**Comment by krinaydhanani** [comment]
@Priya-Goenka I think you still not get my point. I said whatever notice we are providing right now which is perfectly fine. You just need to say and add the setting is not worked if the user is login. It will not work if the user is not login.

**Comment by Priya-Goenka** [comment]
If enabled, the registration form will hide, after the Logged in user registers for the event.

Krinay this is perfect. Also mention, ki delete karna hai, add karna hai ya correct hai.

**Comment by krinaydhanani** [comment]
@Priya-Goenka I don't your notice is perfect and simple toounderstand. @hiteshmakvana please advise here if you think it's perfect then, let me know so I will close this issue.

**Comment by hiteshmakvana** [comment]
current text is correct.
