### ISSUE TITLE
Organizer template files must be inside organizer folder

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#662]
Currently, organizer template files are inside the templates directory which is making confusion for the user to decied which file is for which structure.

All the event-related files must be in the template directory. 
Organizer files must be inside templates/organizer/

**Comment by krinaydhanani** [comment]
Yes, not all the files will be organized in the organizer folder. If I override then it's perfectly working fine. 

If any older user has customized before then we need to inform them to create the organizer folder and move the file into the folder.
