### ISSUE TITLE
Venue template files must be inside venue folder 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#663]
Currently, venue template files are inside the templates directory which is making confusion for the user to decide which file is for which structure.

All the event-related files must be in the template directory.
Venue files must be inside templates/venue/

**Comment by krinaydhanani** [comment]
Need to remove **venue-event_listing** file from the template folder because we are not using this feature in the venue.

**Comment by krinaydhanani** [comment]
Now the **venue-event_listing** file was removed from the template file. 

Yes, now all the files will be organized in the venue folder. If I override then it's perfectly working fine.

If any older user has customized before then we need to inform them to create the venue folder and move the file into the folder.

**Comment by hiteshmakvana** [comment]
Override will be less amount of people but we can inform them. We need to make a proper structure for the future updates.
