### ISSUE TITLE
strings

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#665]
![image](https://user-images.githubusercontent.com/65893994/100611840-f9acc780-3337-11eb-900a-86c100336a9c.png)
![image](https://user-images.githubusercontent.com/65893994/100611908-15b06900-3338-11eb-8541-0499cdef60a7.png)

**Comment by Priya-Goenka** [comment]
![Uploading image.png…]()

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100612390-ec440d00-3338-11eb-80aa-894c6a2e7322.png)

**Comment by Priya-Goenka** [comment]
![Uploading image.png…]()

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100612458-054cbe00-3339-11eb-980d-e50382353278.png)

![image](https://user-images.githubusercontent.com/65893994/100612494-14337080-3339-11eb-8376-61d424390362.png)
![image](https://user-images.githubusercontent.com/65893994/100612536-28776d80-3339-11eb-9dc6-28c755d5aef6.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100612871-a63b7900-3339-11eb-9a03-16b48862481e.png)

**Comment by Priya-Goenka** [comment]
![Uploading image.png…]()

**Comment by Priya-Goenka** [comment]
![Uploading image.png…]()

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100613885-3f1ec400-333b-11eb-9592-40757b015a72.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100614173-bbb1a280-333b-11eb-9c52-df6583e145fc.png)
![image](https://user-images.githubusercontent.com/65893994/100614208-c9ffbe80-333b-11eb-8d09-410e06552db2.png)
![image](https://user-images.githubusercontent.com/65893994/100614269-e56ac980-333b-11eb-958e-4ace846af1d8.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100614337-fddae400-333b-11eb-957b-e1d58e2031b4.png)
![image](https://user-images.githubusercontent.com/65893994/100614400-1814c200-333c-11eb-86ec-6b2abd0482e1.png)
![image](https://user-images.githubusercontent.com/65893994/100614650-7477e180-333c-11eb-8ceb-d8604d6b10f8.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100715442-354d9d00-33dd-11eb-9648-16ebb4cf2600.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100718414-4ef0e380-33e1-11eb-8c75-043671293993.png)
same in venue

**Comment by krinaydhanani** [comment]
All the above string was translated in the latest version.
