### ISSUE TITLE
Need to fix the filter issue at the admin side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#666]
Need to fix the filter issue on the admin side. The event will not filter the start date and end date wist at admin side.

![image](https://user-images.githubusercontent.com/35419531/100620646-a7be6e80-3344-11eb-92ca-9c52c2b72367.png)

**Comment by krinaydhanani** [comment]
Yes, now the filter issue was fixed at the admin side. Not user can filter everything whatever he want.

**Comment by hiteshmakvana** [comment]
Admin side sortable table column working with ASC and DESC order.
