### ISSUE TITLE
[event-calendar] not showing for non-logged in users

### ISSUE THREAD

**Issue by Bobody** [wpeventmanager/wp-event-manager#667]
It's only showing the calendar for logged-in users and also I need to know where the PHP code for [event-calendar] is located.

Thanks

**Comment by hiteshmakvana** [comment]
@Bobody 

Event calendar is part of our paid plugin. Here we are listing only issue related to free plugin WP Event Manager. If you have purchased WP Event Manager Calendar please create support ticket [here](https://support.wp-eventmanager.com/)

**Comment by Bobody** [comment]
This is for the free version provided here https://demo.vaincode.com/mage-event/event-calender/

**Comment by Priya-Goenka** [comment]
@Bobody 
This is not our plugin. Please check which plugin you are using
