### ISSUE TITLE
Need to provide text for setup page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#670]
Need to provide text for setup page.

![step-1](https://user-images.githubusercontent.com/35419531/100722337-8615c380-33e6-11eb-9934-2473afcd2e9b.png)

![step-2](https://user-images.githubusercontent.com/35419531/100722359-8a41e100-33e6-11eb-9055-0330b5f99c84.png)

![Setup-welcome-page](https://user-images.githubusercontent.com/35419531/100722349-88781d80-33e6-11eb-8280-40b20c3f06d7.png)

**Comment by siddharthgotawala** [comment]
@Priya-Goenka Please find the text below for 3 setup pages

### Page-1

> Introduction
> 
> Setup Wizard Introduction
> Thanks for installing WP Event Manager!
> 
> This setup wizard will help you get started by creating the pages for event submission, event management, and listing your events.
> 
> If you want to skip the wizard and setup the pages and shortcodes yourself manually, the process is still relatively simple. Refer to the documentation for help.

 ### Page-2
 
> Page Setup
> 
> WP Event Manager includes shortcodes which can be used within your pages to output content. These can be created for you below. For more information on the event shortcodes view the shortcode documentation.
> 
> **Post an Event** - This page allows peoples to post events to your website from the front-end.
> 
> If you do not want to accept submissions from users in this way (for example you just want to post events from the admin dashboard) you can skip creating this page.
> 
> **Event Dashboard** - This page allows peoples to manage and edit their own events from the front-end.
> 
> If you plan on managing all listings from the admin dashboard you can skip creating this page.
> 
> **Events** - This page allows users to browse, search, and filter event listings on the front-end of your site.
> 
> **Submit Organizer Form** - This page allows people to Submit the organizers form the frontend.
> 
> In case if you do not want to allow your users to submit organizers from the frontend, you can uncheck this and skip creating this page.
> 
> 
> **Event Organizers** - This page allows peoples to show organizers from the front-end.
> 
> In case if you do not want to allow your users to show organizers from the frontend, you can uncheck this and skip creating this page.
> 
> **Submit Venue Form** - This page allows people to Submit the venues form the frontend.
> 
> In case if you do not want to allow your users to submit venues from the frontend, you can uncheck this and skip creating this page.
> 
> 
> **Event Venues** - This page allows peoples to show venues from the front-end.
> 
> In case if you do not want to allow your users to show venues from the frontend, you can uncheck this and skip creating this page.

*Venue Dashboard and Organizer Dashboard will be removed from the page setup

### Page - 3

> All Done!
> 
> Thanks for installing WP Event Manager! Here are some handy resources for getting started with our plugins.
> 
> Helpful Resources
> 
> Knowledge Base
> Solve your queries by browsing our documentation.
> Browse More »
> 
> FAQs
> Explore through the frequently asked questions.
> Get Answers »
> 
> Video Tutorials
> Learn different skills by examining attractive video tutorials.
> Watch all »
> 
> Add ons Support
> Get support for all the Add ons related queries with our experienced/ talented support team.
> Get Add ons Support »

**Comment by Priya-Goenka** [comment]
Page-1
Introduction

Setup Wizard Introduction
Thanks for installing WP Event Manager!

This setup wizard will help you get started by creating various pages for event submission, event management, and listing your events, along with setting up organizers and venues pages.

The process is still relatively simple if you want to skip the wizard and manually set up the pages and shortcodes yourself. Please refer to the documentation for support.

Page-2
Page Setup

The WP Event Manager includes shortcodes which can be used to output content within your pages. These can be generated directly as mentioned below. Check the shortcode documentation for more information on event shortcodes.

Post an Event - This page allows peoples to post events to your website from the front-end.

If you do not wish to accept submissions from users in this way (for example you just want to post events from the admin dashboard) you can skip creating this page.

Event Dashboard - This page allows peoples to manage and edit their own events from the front-end.

If you plan on managing all listings from the admin dashboard you can skip creating this page.

Events - This page allows users to browse, search, and filter event listings on the front-end of your site.

Submit Organizer Form - This page allows users to Submit the organizers form the frontend.

In case if you do not want to allow your users to submit organizers from the frontend, you can uncheck this and skip creating this page.

Event Organizers - This page allows peoples to show organizers from the front-end.

In case if you do not want to allow your users to show organizers from the frontend, you can uncheck this and skip creating this page.

Submit Venue Form - This page allows people to Submit the venues from the frontend.

In case if you do not want to allow your users to submit venues from the frontend, you can uncheck this and skip creating this page.

Event Venues - This page allows peoples to show venues from the front-end.

In case if you do not want to allow your users to show venues from the frontend, you can uncheck this and skip creating this page.

*Venue Dashboard and Organizer Dashboard are not included in the page setup process, please create it as per your need. 
Page - 3
All Done!

Thanks for installing WP Event Manager! Here are some valuable resources that will assist you in getting started with our plugins.

Helpful Resources

Knowledge Base
Solve your queries by browsing our documentation.
Browse More »

FAQs
Explore through the frequently asked questions.
Get Answers »

Video Tutorials
Learn different skills by examining attractive video tutorials.
Watch all »

Add ons Support
Get support for all the Add ons related queries with our experienced/ talented support team.
Get Add ons Support »

**Comment by krinaydhanani** [comment]
@wpem-kishan Please put all the text in responsible places.

**Comment by krinaydhanani** [comment]
Yes, now the setup page was improved.

**Comment by Priya-Goenka** [comment]
Link is incorrect
![image](https://user-images.githubusercontent.com/65893994/100841256-0ac31900-349d-11eb-9e87-d02d4b768dda.png)

**Comment by Priya-Goenka** [comment]
This plugin was made by
WP Event Manager

Owned and Managed by
WP Event Manager

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100844214-8f179b00-34a1-11eb-9ba5-feefc28fd6ff.png)
This is not needed because it does not work. Events are deleted after the expiry date.

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/100844771-4dd3bb00-34a2-11eb-9ec4-02c5ba79675d.png)
How are these two different?

**Comment by krinaydhanani** [comment]
Yes now, all the above issue was fixed.
