### ISSUE TITLE
Allow add past date while add/edit event

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#671]
Allow add past date while add/edit event

**Comment by wpem-kishan** [comment]
For frontside
enable : add_filter('event_manager_show_past_date_frontend', '__return_true', 10);
disable : add_filter('event_manager_show_past_date_frontend', '__return_false', 10);

For admin
enable : add_filter('event_manager_show_past_date', '__return_true', 10);
disable : add_filter('event_manager_show_past_date', '__return_false', 10);

**Comment by krinaydhanani** [comment]
Yes with help of the above filter user can post past events perfectly.

**Comment by hiteshmakvana** [comment]
Krinay test the code and assign to documentation team.

**Comment by krinaydhanani** [comment]
I already test this code @Priya-Goenka please make a document on the above code.

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1dLFvAOfwDuiq2GM2r7eydBMgJs_FlqIXJfL8we5GhZU/edit
