### ISSUE TITLE
Please verify, i have complaints. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#673]
The backend event end date filter doesnot works. Please verify with latest version. 

![image](https://user-images.githubusercontent.com/65893994/100841734-b4a2a580-349d-11eb-82b3-1a9f2f4cba3f.png)

**Comment by krinaydhanani** [comment]
I already fixed this issue before https://github.com/wpeventmanager/wp-event-manager/issues/666. Please pull the latest version and check. If you found anything please assign it back to me.
