### ISSUE TITLE
Scroll not working on the setting page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#674]
Scroll not working on the setting page.

To reproduce this bug please follow the steps.

Goto the event manager setting.
Click in general.

**Comment by siddharthgotawala** [comment]
This problem is from admin.min.js. 
@hiteshmakvana Please check from your end.

**Comment by mistry-jignesh** [comment]
Face this issue with above steps.

Please check it.

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is not reproduced and working fine.

Scroll is workin fine .

So I closed the issue.
