### ISSUE TITLE
Add a type -URL in custom fields

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#675]
Can we add a URL type in the field editor type?

![image](https://user-images.githubusercontent.com/65893994/100880153-6a87e700-34d2-11eb-8ef2-8503c3158b12.png)

**Comment by mistry-jignesh** [comment]
Now I am added URL type filed in the editor .

![image](https://user-images.githubusercontent.com/75515088/111291562-53c66400-866d-11eb-9080-743ffb0a3530.png)

But in the Add new event page(**Backend**) this field is missing . This should be available.

![image](https://user-images.githubusercontent.com/75515088/111291866-a1db6780-866d-11eb-8161-9055e674b4a6.png)


It is available at front end application. 

When I have add below URL then on the event page it is display URL text. 

URL link - https://www.youtube.com/watch?v=7LkKfCcYxCk

![image](https://user-images.githubusercontent.com/75515088/111293300-2084d480-866f-11eb-921d-4eab818b707d.png)

**Comment by mistry-jignesh** [comment]
**Still in the Backend URL field is missing .**  When try to create new event at backend.

**Front end it is working fine .**

![image](https://user-images.githubusercontent.com/75515088/111473647-484c6900-8751-11eb-8ede-4c602e80e8ec.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now this issue is resolved at backend .

This field is available at backend.

**Comment by mistry-jignesh** [comment]
I have verified issue . This issue is fixed and working properly.

So now I have closed the bug.
