### ISSUE TITLE
Event dashboard shortcode not showing correct UI 

### ISSUE THREAD

**Issue by wpem-ashish** [wpeventmanager/wp-event-manager#677]
Expected UI: 
![image](https://user-images.githubusercontent.com/75177623/100984065-36fb9a00-3570-11eb-9c71-d586c5765f56.png)

Actual UI:
![image](https://user-images.githubusercontent.com/75177623/100984132-4aa70080-3570-11eb-8ab6-0b6d149fd9f3.png)

**Comment by krinaydhanani** [comment]
@wpem-ashish  It's not a bug please clear your browsing cache-press CTRL+F5. Still, if you facing the same issue then please let me know.

**Comment by wpem-ashish** [comment]
Issues is fixed.
