### ISSUE TITLE
event_types attribute missing in doc.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#678]
Please mention event_types attribute with explanation in doc.

And please mention on both attribute is not working with show_filters="false".

![image](https://user-images.githubusercontent.com/35419531/100997455-48e53900-3580-11eb-938c-ac8fcc76c3e2.png)

**Comment by Priya-Goenka** [comment]
https://wp-eventmanager.com/knowledge-base/the-event-listings/

**Comment by krinaydhanani** [comment]
@Priya-Goenka Please mention on both attribute is not working with show_filters="false".

**Comment by Priya-Goenka** [comment]
Please read carefully!

**Comment by krinaydhanani** [comment]
This issue was fixed.
