### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WP_Event_Manager_Category_Walker'

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#681]
Fatal error: Uncaught Error: Class 'WP_Event_Manager_Category_Walker' not found in /media/data/kishan/site/wpem/wp-content/plugins/wp-event-manager/admin/wp-event-manager-cpt.php:339 Stack trace: #0 /media/data/kishan/site/wpem/wp-includes/class-wp-hook.php(289): WP_Event_Manager_CPT->events_by_event_type('event_listing') #1 /media/data/kishan/site/wpem/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /media/data/kishan/site/wpem/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /media/data/kishan/site/wpem/wp-admin/includes/class-wp-posts-list-table.php(559): do_action('restrict_manage...', 'event_listing', 'top') #4 /media/data/kishan/site/wpem/wp-admin/includes/class-wp-list-table.php(1297): WP_Posts_List_Table->extra_tablenav('top') #5 /media/data/kishan/site/wpem/wp-admin/includes/class-wp-list-table.php(1231): WP_List_Table->display_tablenav('top') #6 /media/data/kishan/site/wpem/wp-admin/edit.php(449): WP_List_Table->display() #7 {main} thrown in /media/data/kishan/site/wpem/wp-content/plugins/wp-event-manager/admin/wp-event-manager-cpt.php on line 339

**Comment by krinaydhanani** [comment]
Yes, the error was fixed but still if I disable the category feature that time type filter also removed.
