### ISSUE TITLE
Field editor reset issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#690]
If I reset only the venue or organizer that time all field editors will reset. We need to be separate all field editor functionality.

**Comment by krinaydhanani** [comment]
Now Field editor reset stop working.

**Comment by hiteshmakvana** [comment]
Reset is working fine please provide steps to reproduce.

**Comment by krinaydhanani** [comment]
Field editor reset function not working fine.

To reproduce the bug please follow the simple steps.

1. **Event form fields**

- Go to the dashboard on the admin side.
- Click on event manager
- Go to the field editor
- Add some fields in Event form fields.
- Then save it.

- Add some fields in Organizer form fields.
- Then save it.

- Add some fields in Venue form fields.
- Then save it.

- Now try to reset it you can see all ( **Organizer form fields**, **Venue form fields** ) field editor forms are reset.


2.  **Organizer form fields**

- Go to the dashboard on the admin side.
- Click on event manager
- Go to the field editor
- Add some fields in Organizer form fields.
- Then save it.

- Now try to reset it you can see nothing will happen because the **Reset to default** feature not working in the **Organizer form fields**.


3.  **Venue form fields**

- Go to the dashboard on the admin side.
- Click on event manager
- Go to the field editor
- Add some fields in Venue form fields.
- Then save it.

- Now try to reset it you can see nothing will happen because the **Reset to default** feature not working in the **Venue form fields**.

**Comment by pooja-pragda** [comment]
As I reviewed & verified this bug with the staging demo & there I can't reproduce this bug.

**Comment by krinaydhanani** [comment]
This issue was fixed. I am going to close this issue.
