### ISSUE TITLE
Event organizer and venue duplication not working.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#692]
Event organizer and venue duplication not working from a new event dashboard.

**Comment by hiteshmakvana** [comment]
Code is reviewed.

**Comment by pooja-pragda** [comment]
The event organizer and venue duplication are working fine now. But there is an issue with the delete action. It asks twice for the organizer.

**Comment by mistry-jignesh** [comment]
I have verified issue . Now this is duplicate #697.

So I closed the issue.
