### ISSUE TITLE
Core plugin datepicker conflict with boostrap.min.js

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#693]
Core plugin datepicker conflicts with boostrap.min.js

You can reproduce this bug with **eventpress** theme.

![image](https://user-images.githubusercontent.com/35419531/101317919-70404c80-3885-11eb-8986-49b7498584d2.png)

**Comment by siddharthgotawala** [comment]
Can we add below classes if theme has bootstrap.min.js?

`comiseo-daterangepicker-triggerbutton ui-button ui-widget ui-state-default ui-corner-all comiseo-daterangepicker-top comiseo-daterangepicker-vfit ui-button-text-icon-secondary`

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/108945484-b2a64800-7682-11eb-86f5-4d18db588945.png)

**Comment by mistry-jignesh** [comment]
I have verified this bug. I have activate EventPress theme but same issue is available.

![image](https://user-images.githubusercontent.com/75515088/109616709-821b4e00-7b5b-11eb-93e7-074af999faf1.png)

**Comment by tamanna-ahuja** [comment]
As discussed with @kaushikpokal , We might have to change our datepicker all over plugin will take care in later versions

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this fixed and working.

So I closed the issue.
