### ISSUE TITLE
Need to fix the design issue at admin side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#694]
Need to align label and pending event count at admin side. I face this issue in WordPress Version 5.6.

![image](https://user-images.githubusercontent.com/35419531/101591605-e58d5800-3a12-11eb-9c7a-7bb68629c797.png)

**Comment by siddharthgotawala** [comment]
there is no additional class to customise it so for now we can not do anything here.
