### ISSUE TITLE
Past event Widget

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#696]
Please create another widget of past events.

**Comment by Priya-Goenka** [comment]
In the widget section there is only upcoming event, featured event widget and calendar widget, but not for pst event

**Comment by mistry-jignesh** [comment]
![Widget](https://user-images.githubusercontent.com/75515088/109617911-f6a2bc80-7b5c-11eb-9fac-22e2557236d5.png)

Above image widget section past event widget is not present.

**Comment by mistry-jignesh** [comment]
I have verified bug. I have updated plugin .Now past event widget is present in widget section.

**Comment by krinaydhanani** [comment]
This issue is perfectly working fine.
