### ISSUE TITLE
Elementor select field will show key instead of value

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#699]
If you are trying to create a single event template with the custom field it will output the key stored inside the database instead of the value.

For example, country fields stored key-value pair like this IN: India, USA: United States of America

in this case, it will output IN and the USA which is key.

**Comment by krinaydhanani** [comment]
I am not able to test this case before fixing the field editor issue. Please fix the field editor first then I can test it well.

**Comment by mistry-jignesh** [comment]
Still it will display key value.

![image](https://user-images.githubusercontent.com/75515088/109958799-a4a09900-7d0c-11eb-9e1f-bd5dfc46aa6b.png)

**Comment by hiteshmakvana** [comment]
You need to create key-value pair in the field editor and then save your event data. Select single event template and assign field tags from the dynamic tag. have you followed this process?

**Comment by mistry-jignesh** [comment]
I have verified the bug. Now select value  is display on the page.

It working fine so I have closed the bug.
