### ISSUE TITLE
Event listing issue with WordPress 5.6.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#700]
After updating WordPress 5.6 in Mozilla Firefox, the event will not list for the first time. It will load on a hard refresh.

**Comment by krinaydhanani** [comment]
This issue is not fixed perfectly because still, I am facing the same issue while opening the event listing.

![image](https://user-images.githubusercontent.com/35419531/102971331-332fb780-451f-11eb-87c9-fc91320415d0.png)

**Comment by mistry-jignesh** [comment]
Still issue is present in  Mozilla Firefox. Event will not list for the first time. It will load on a hard refresh

**Comment by hiteshmakvana** [comment]
Can you try stagin or any live site which is not working on mozila?

**Comment by mistry-jignesh** [comment]
I have verified this bug. It is working properly.

Events are listing properly.

**Comment by mistry-jignesh** [comment]
I have verified this bug. It is working properly.

Events are listing properly. So I have closed the issue.
