### ISSUE TITLE
Group field not working perfectly in the field editor.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#703]
Group field not working perfectly in the field editor because if I delete the parent group field then the child field will not be deleted.

To reproduce this bug please follow the below steps.

Go to the dashboard on the admin side.
Click on event manager
Go to the field editor
Add the Group field ( Add all the field type as well)
Now delete the parent field.

Only the parent field will be deleted but the child field still remains as per below image.

![image](https://user-images.githubusercontent.com/35419531/102971862-252e6680-4520-11eb-8a45-c56deded1c91.png)

**Comment by ritakikani** [comment]
Now it is working fine

**Comment by mistry-jignesh** [comment]
I have verified this issue. Added a few field types for the testing.
Now deleted the parent field then the child field is not deleted.
It is working fine. So I closed the issue.
