### ISSUE TITLE
Need to fix date piker issue it will conflict with new WordPress version 5.6.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#704]
Need to fix date piker issue it will conflict with new WordPress version 5.6 because after updating WordPress version 5.6 admin can able to select the previous event start date.

![image](https://user-images.githubusercontent.com/35419531/102976380-7a21ab00-4527-11eb-8aba-4588b8da3fd4.png)

**Comment by hiteshmakvana** [comment]
Restriction on the datepicker removed due to conflcit of past event can not be added after date passed.

**Comment by krinaydhanani** [comment]
Yes, this issue was fixed. I am going to close this issue.
