### ISSUE TITLE
Need to fix the notice I got while filter event filter by category.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#705]
Need to fix the notice I got while filter the event filter by category.

To reproduce this bug please follow the steps.

After installing WP Event Manager.
Go to the Event Types or Category on the admin side.
Then check the count of any type or category 
Then click on the count.

Now you can see below notice and warning on your screen.

![image](https://user-images.githubusercontent.com/35419531/103074230-31352980-45ef-11eb-92bc-b762630b7fcd.png)

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 400

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 305

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 400

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 305

Notice: Undefined index: fields in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 400

Warning: array_keys() expects parameter 1 to be array, null given in D:\Xampp\htdocs\wpem\wp-content\plugins\wp-event-manager\forms\wp-event-manager-form-abstract.php on line 305

**Comment by pooja-pragda** [comment]
I can not see any error in Event Types or Category on the admin side as mentioned above.

**Comment by mistry-jignesh** [comment]
I have verified bug at backend. Now this error is disappear . 

Issue is working properly.

**Comment by krinaydhanani** [comment]
Now I am not getting any issue while filter events by category or type.
