### ISSUE TITLE
Need to fix corrupt image issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#707]
First I had removed all the corrupt images from my media.
Then I set the same image in 2 events.
Then left the site for 2 hours. 
Then I had check after 2 hours and I can see there are 3 corrupt images created in the media.

![image](https://user-images.githubusercontent.com/35419531/103395461-62b07680-4b54-11eb-9d00-6d30d3c94c75.png)

**Comment by pooja-pragda** [comment]
Exactly followed mentioned steps & wait for a day, if any corrupt image will generate or not.
But there is no corrupted image is generated.

![image](https://user-images.githubusercontent.com/76870773/108945873-69a2c380-7683-11eb-9a63-eff70621554c.png)

**Comment by krinaydhanani** [comment]
I am going to close this issue because this is not reproducible by the developer and this thing happen sometimes.
