### ISSUE TITLE
Elementor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#708]
Featured event is not displaying when using elementor for event display using widget!

**Comment by pooja-pragda** [comment]
For a featured event in the event display widget - the "Show Featured" option set true.  

![image](https://user-images.githubusercontent.com/76870773/107904234-32d8f900-6f71-11eb-8d7e-40b2d7fbb18c.png)

**Comment by krinaydhanani** [comment]
The option should be working like that. 

All Events: We need to show all events even featured or not.
Ture: We need to show only featured event
Falce: We need to show only those event which is not featured.

**Comment by hiteshmakvana** [comment]
This might be not working when you are importing events. It is working fine for me.

**Comment by hiteshmakvana** [comment]
![image](https://user-images.githubusercontent.com/42602299/111289669-62ac1700-866b-11eb-9c5d-94ba189c1953.png)

**Comment by hiteshmakvana** [comment]
![image](https://user-images.githubusercontent.com/42602299/111289728-7192c980-866b-11eb-8814-15adf08fcf5f.png)

**Comment by mistry-jignesh** [comment]
I have performed below setting  from elementor .

![image](https://user-images.githubusercontent.com/75515088/111318130-c4c84480-868a-11eb-9959-bc8d8a5aafab.png)

The  featured events should not display. Here in the page are showing all the featured event .


![image](https://user-images.githubusercontent.com/75515088/111317964-9fd3d180-868a-11eb-8387-89d5e51f5bcc.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue. I have checked other environment  .It is working properly.

**Comment by hiteshmakvana** [comment]
Import may not have proper data.

**Comment by mistry-jignesh** [comment]
I have verified this issue. If user import improper data then issue is reproduced otherwise It is working fine.

So now I have closed this issue.
