### ISSUE TITLE
Need to add venue field doc in Custom Fields documentation.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#709]
Need to add venue field doc in Custom Fields documentation.

![image](https://user-images.githubusercontent.com/35419531/103514511-c6a7a780-4e92-11eb-95be-17a9b96e989d.png)

**Comment by Priya-Goenka** [comment]
https://docs.google.com/document/d/1XAvmMYcwaZO-Y3x8wfVbxVOYjAXpvW3X8XwK-MTL9Ik/edit

**Comment by Priya-Goenka** [comment]
@siddharth, please make images and assign them to swapnil

**Comment by SwapnilBendale** [comment]
Published - https://wp-eventmanager.com/knowledge-base/venue-fields/

**Comment by krinaydhanani** [comment]
Yes now, this doc is published.
