### ISSUE TITLE
Sorting events on organizer details page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#711]
If the user wants to show events in descending or ascending order on the organizer details page then we need to provide a shortcode or widget for them.

**Comment by hiteshmakvana** [comment]
```
add_filter("wpem_upcoming_single_organizer_event_listing_query_args","YOUR_THEME_SLUG_change_organizer_listing_order");
function YOUR_THEME_SLUG_change_organizer_listing_order($args){
//$args['orderby'] = 'YOUR CUSTOM ORDER';
return $args;
}
```

**Comment by krinaydhanani** [comment]
I can see the below error when I put this code.

![image](https://user-images.githubusercontent.com/35419531/109967334-4927d880-7d17-11eb-9578-7dcaf3da46e8.png)


![image](https://user-images.githubusercontent.com/35419531/109967291-3dd4ad00-7d17-11eb-80ad-1d98b6fa2bda.png)

**Comment by hiteshmakvana** [comment]
You have added code two times.

**Comment by mistry-jignesh** [comment]
Still face same issue . Also I have put same code as you have provided .

![image](https://user-images.githubusercontent.com/75515088/111433143-ecb7b680-8723-11eb-8357-d7161d03fd39.png)

**Comment by krinaydhanani** [comment]
@Priya-Goenka After the test, this bug please make documentation on this code.

**Comment by hiteshmakvana** [comment]
```
//code for upcoming event tab
add_filter("wpem_single_organizer_upcoming_event_listing_query_args","YOUR_THEME_SLUG_change_organizer_listing_order_upcoming");
function YOUR_THEME_SLUG_change_organizer_listing_order_upcoming($args){
//$args['orderby'] = 'YOUR CUSTOM ORDER';
return $args;
}
//code for past event tab
add_filter("wpem_single_organizer_current_event_listing_query_args","YOUR_THEME_SLUG_change_organizer_listing_order_current");
function YOUR_THEME_SLUG_change_organizer_listing_order_current($args){
//$args['orderby'] = 'YOUR CUSTOM ORDER';
return $args;
}
//current tab 

add_filter("wpem_single_organizer_past_event_listing_query_args","YOUR_THEME_SLUG_change_organizer_listing_order_past");
function YOUR_THEME_SLUG_change_organizer_listing_order_past($args){
//$args['orderby'] = 'YOUR CUSTOM ORDER';
return $args;
}

```

**Comment by Priya-Goenka** [comment]
Jignesh please check and if confirmed, assigned me back.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed .

Now sorting is working properly.

So I closed the issue.

**Comment by mistry-jignesh** [comment]
Need to add code in the documentation and provide a small description of this issue. @Prachetshi1991

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1S8qmBXG45qi_60IHYMs2adDnWCdnT9SZTItEPXP4aUQ/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now code is available on the KB pages in the Organizer Shortcode section.
So I closed the issue.
