### ISSUE TITLE
Need to fix comment issue in single event listing. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#717]
If I want to hide old comments in a single event listing then there is no code for it. 

https://wp-eventmanager.com/knowledge-base/hide-comment-on-listing-page/

**Comment by pooja-pragda** [comment]
https://wp-eventmanager.com/knowledge-base/hide-comment-on-listing-page/

Add following with this.

Find single.php file in the parent theme directory & duplicate it in the child theme.
Find `comments_template()`  function in single.php.
there should be the following code :

```
if (comments_open() || get_comments_number()) :
      comments_template();
endif;
```

Replace with below code : 
```
if (comments_open() || get_comments_number()) :
     if ('event_listing' !== get_post_type()) :
         comments_template();
     endif;
endif;
```

**Comment by hiteshmakvana** [comment]
@krinaydhanani Can you please provide a reason to make it as bug?

**Comment by krinaydhanani** [comment]
@hiteshmakvana Yes according to @Priya-Goenka our customer needs to hide old comments so she asks me to open this bug.

**Comment by mistry-jignesh** [comment]
Please add code in the below page -

https://wp-eventmanager.com/knowledge-base/hide-comment-on-listing-page/

**Comment by mistry-jignesh** [comment]
@Prachetshi1991  - Please add code in the documentation.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1u-XryEK5fjAiKL6bpICkypQvasKA9HWbTB44d4xj2G8/edit

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now code is available on the KB page.
So I closed the issue.
