### ISSUE TITLE
Custom Field- incorrect file type. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#718]
![image](https://user-images.githubusercontent.com/65893994/106111573-2e8b9e00-6172-11eb-807a-dcf29789f8a8.png)

When a user upload a file in the custom field, he gets Download displayed, rather it should display the name of the file uploaded.

**Comment by pooja-pragda** [comment]
It will look like this.

![image](https://user-images.githubusercontent.com/76870773/107733228-7a1c7b00-6d20-11eb-9a53-ed463ca919c8.png)

**Comment by mistry-jignesh** [comment]
I have verified this bug. Now it is working properly.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
