### ISSUE TITLE
Need to fix Download custom field issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#719]
When a user uploads a file in the custom field, he gets Download displayed, rather it should display the name of the file uploaded.

![image (1)](https://user-images.githubusercontent.com/35419531/106112461-4d3e6480-6173-11eb-96a7-c41bd7de4deb.png)

**Comment by pooja-pragda** [comment]
It will look like this.

![image](https://user-images.githubusercontent.com/76870773/107733187-5eb17000-6d20-11eb-874d-0b25b8b2bd55.png)

**Comment by mistry-jignesh** [comment]
I have verified this bug . Now this is working fine.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
