### ISSUE TITLE
Need to fix debug log.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#720]
I got this error after deactivation WooCommerce. 

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/5885876/debug.log)

![image](https://user-images.githubusercontent.com/35419531/106113019-fe44ff00-6173-11eb-91c0-90fb412b3c02.png)

**Comment by hiteshmakvana** [comment]
This bug is part of sell ticket and already improved in next update.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now this error message is not display when deactivation WooCommerce the plugin.

Now I have closed the bug.
