### ISSUE TITLE
Extra Settings  when event delete not delete image

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#721]
we can put settings for checked/unchecked.. when event delete then not delete images.. by default it is checked.

for more info: https://wordpress.org/support/topic/event-banner-image-gets-deleted/

**Comment by mistry-jignesh** [comment]
In the setting option, there is one option is added. If enable option then the event is  deleted from the trash .
Here image is not deleted from the media library. It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7cc7a8a7-4569-42d5-9ed9-0f2d2dc9e8ab)

So I closed the issue.
