### ISSUE TITLE
Need to improve Event Dashboard at fronted side.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#722]
Need to improve the Event Dashboard on the front side. Need to make it more attractive and clear. 

![image](https://user-images.githubusercontent.com/35419531/107004382-340d6780-67b4-11eb-96f2-6a9b9bff9200.png)

**Comment by siddharthgotawala** [comment]
Option 1 
![image](https://user-images.githubusercontent.com/68212017/107357996-d309ca80-6af8-11eb-9a3f-3fd342206a0b.png)

Option 2 
![image](https://user-images.githubusercontent.com/68212017/107358146-08161d00-6af9-11eb-934a-3c1703b1c2fb.png)

**Comment by krinaydhanani** [comment]
@ashokdudhat Please select anyone layout so we can implement.

**Comment by hiteshmakvana** [comment]
Current one is better and also we can not switch to different version every time.

**Comment by krinaydhanani** [comment]
@hiteshmakvana This task is given by @ashokdudhat he needs to improve it that's why I have provided the above layout.
