### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#723]
Just to let you know, I was able to fix the issue of the displaying of my custom field variable by modifying the custom-single-event_listing.php file.

As it worked correctly for multiselect, I replace at the line 194 $field_value by $field['options'][$field_value] and it works.

**Comment by hiteshmakvana** [comment]
On which site?

**Comment by Priya-Goenka** [comment]
I dont know about the site now, Just it was reported, so i wanted it to be verified.

**Comment by krinaydhanani** [comment]
We need all the details to resolve the issue and this issue is very old so I am going to close this issue now.
