### ISSUE TITLE
Upcoming events

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#724]
Just like past event, please give shortcode for upcoming events

**Comment by hiteshmakvana** [comment]
[events] shortcode is used for upcoming events.

**Comment by Priya-Goenka** [comment]
No Hitesh, [events display all the events if I have not hidden the Past events. 
If you could introduce the shortcode that will only list the future events, just like a page of Past events.

**Comment by ritakikani** [comment]
We already implement this shortcode [upcoming_events].

**Comment by mistry-jignesh** [comment]
Verified shortcode : [upcoming_events]. It is working fine.
So I closed the issue.
