### ISSUE TITLE
elementor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#725]
![image](https://user-images.githubusercontent.com/65893994/107364338-53ccc480-6b01-11eb-9e72-3561233dc6ba.png)
Share with friends is wrongly displayed. please test

**Comment by hiteshmakvana** [comment]
I have troubleshot everything there is no issue I haven't found anything.

**Comment by mistry-jignesh** [comment]
I have verified issue . Here issue is unable to reproduced it.

So I have closed the issue.
