### ISSUE TITLE
Bug With Custom field type

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#726]
Issue: Array showing on frontend for file type- multi-select (images)

Even if i will add multiple galleries into it will only return the path of the files selected. We haven't added any restriction on file it can be pdf or image anything. If we show all the files as images it may break the process and another customer will complain again.

In this case, i need clear instruction on what should be stored inside the files and how we will output this.  

Solution: creating 2 file types- One for Document type(pdf/doc/excel/ppt,etc)
One for only Images same like banner.

**Comment by mistry-jignesh** [comment]
![image](https://user-images.githubusercontent.com/75515088/109923184-698a6f80-7ce4-11eb-81c5-18531dfa13a4.png)

**Comment by hiteshmakvana** [comment]
@mistry-jignesh This bug is related to multiple value showing at frontend. Please create a separate bug for pdf file issue.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now it is working fine.

Also I have created other issue for multiple value showing at frontend and issue id is  # 757.

Now I have closed the bug.
