### ISSUE TITLE
Sorting on archive page.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#727]
On the archieve post type page(event category and type)
the users are demanding sorting feature- by date

**Comment by ritakikani** [comment]
This is wordpress default functionality, so we can not customize it because it affects our other pages functionality like event listing page.So, user can customize by itself.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - This is WordPress default functionality, so we can not customize it because it affects our other pages functionality like event listing page. So, user can customize by itself.

So I closed the issue.
