### ISSUE TITLE
Need to fix issue - Theme 3 issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#729]
URL : https://staging-wpeventmanagerdemo.kinsta.cloud/

1 First Go to Event tab.
2. When I have clicked on the event organizer from organizer option then on the page user name is display 2 times.Also Image is display corrupted.

Please check image.

![image](https://user-images.githubusercontent.com/75515088/108183830-83e31b80-7130-11eb-9ec2-f1776a38f6de.png)

**Comment by hiteshmakvana** [comment]
![image](https://user-images.githubusercontent.com/42602299/111293939-ce907e80-866f-11eb-9cb5-8a3b14db6e06.png)

I haven't found any issue in the organizer listing.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is resolved.

So I have closed the issue.
