### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#731]
First of all, fields Start Date and End Date aren't required in the editor, even though if I look into Field Editor they set as required - this is confusing for my client and they tend to omit those fields.
Further on, if post is saved without end date, it somehow defaults to 1/1/1970, so any check in frontend templates like:
if (isset($start_date) && isset($end_date) && $start_date != $end_date)
will not work correctly.
There is also an issue with datepicker, if I select 15/1/2021 as a datepicker format in Event Manager settings, it goes crazy, it saves totally wrong dates.

**Comment by mistry-jignesh** [comment]
I have verified this issue but this issue is unable to reproduced it.

So I have closed issue.
