### ISSUE TITLE
[ Repeated Field ] Any addons are deactivated 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#732]
When any addon is deactivated and still fields are stored inside the field editor then it may product warning error.

For example, paid ticket repeated field stored but fields are not inside the paid tickte field then it will product warning.

It can also reproduce when you deactivate woo-commerce and keep the sell ticket.

**Comment by hiteshmakvana** [comment]
In most of the cases, addon will remove its fields.

**Comment by mistry-jignesh** [comment]
I have verified bug. Now it is working properly.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
