### ISSUE TITLE
[ Autofill ] Organizer form fields 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#733]

**Comment by Priya-Goenka** [comment]
In case if it's possible, the organizer created when they signup, submitting new event, , should be auto-assigned to this event.

**Comment by mistry-jignesh** [comment]
In  Submitting new event form  - 

Organizer field : 

When I have click on the  "Here" text button then open form is not filled up.

![image](https://user-images.githubusercontent.com/75515088/109922175-fcc2a580-7ce2-11eb-8cde-3911fffe8fa5.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now When I have click on the "Here"(Organizer) text button then open form is  filled up.

It is working properly.  So I have closed the issue.
