### ISSUE TITLE
Setting not working

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#735]
![image](https://user-images.githubusercontent.com/65893994/108665151-44cf1480-74fa-11eb-8c9d-375ecdf4ed13.png)

**Comment by mistry-jignesh** [comment]
I have verified this bug. Mail is received but password  link is missing in the mail. 

Please check image.

![image](https://user-images.githubusercontent.com/75515088/109649272-adb12f00-7b81-11eb-89cc-c6dd503752a8.png)

**Comment by mistry-jignesh** [comment]
I have verified bug. Now it is working properly.

**Comment by mistry-jignesh** [comment]
Now this functionality is working properly . So I have closed the bug.
