### ISSUE TITLE
wp-event-manager / update-banner

### ISSUE THREAD

**Issue by soda31** [wpeventmanager/wp-event-manager#738]
Hello,

First congrats for your excellent plugin !
It's powerfull and quite easy to use / customize

I have a question , perhaps it is a bug , I don't know
As you can see in this [video](https://youtu.be/-WGINTl4dbY)

I created an event and later I want to update banner
It's ok for thumbnail but not for widgets (event listing and incoming events)

Did I messed something ?

Regards

ED

**Comment by mistry-jignesh** [comment]
I have verified issue .Here issue is unable to reproduced it.

So I have closed the issue.

**Comment by mistry-jignesh** [comment]
I have verified issue .Here issue is unable to reproduced it.

So I have closed the issue.

**Comment by soda31** [comment]
Hello,
I do not understand how you can not reproduce the bug !

I tested that again
https://demo.wp-eventmanager.com/t3a6zsurong9qhc/events/#events

admin : I create an event
then I update banner using dashboard

Banner is not updated in events page
But in the dashboard thumbnail is ok

Did you saw my video ?

Thanks

Regards
