### ISSUE TITLE
[ Elementor ] Single event template

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#740]
The event organizer for the particular event is not showing due to template structure change.

**Comment by mistry-jignesh** [comment]
I have verified issue with elementor but organizer is not display in single event template.

![Org3](https://user-images.githubusercontent.com/75515088/109965389-e9c8c900-7d14-11eb-8c72-b4a7b26f3fd8.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now it is working properly.

Now I have closed the issue.
