### ISSUE TITLE
New Google Location Rule

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#741]
The User has reported this,  You need to provide location for the online events as well, according to google new policy. The error logs are filled ith error. 

"location": [{
"@type": "VirtualLocation",
"url": "https://mywebsite.com/event"
google mention to have it : https://developers.google.com/search/docs/data-types/event#structured-data-type-definitions

Online event: If the event is happening online, set the @type to VirtualLocation. Add the location.url property.
you need to update/fix your plugin to be compatble with google now... that ahs changed

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/109604272-4081a780-7b49-11eb-9a8c-64ab284b138a.png)

**Comment by mistry-jignesh** [comment]
**Online Event**  : When I have run below URL then following error is display in the result.

URL - 
https://staging-appwpeventmanager.temp927.kinsta.cloud/event/backyard-compost-basics-a-free-webinar/

![image](https://user-images.githubusercontent.com/75515088/109812197-cb4dc980-7c51-11eb-8c11-726f6b5df331.png)


**With Location Name**  : When I have run below URL then following warrning message is display


https://staging-appwpeventmanager.temp927.kinsta.cloud/event/meeting-or-networking-event-invention-con-2020/

![image](https://user-images.githubusercontent.com/75515088/109812906-a9087b80-7c52-11eb-85eb-49eea074edbf.png)

**Comment by hiteshmakvana** [comment]
I have tested here https://search.google.com/test/rich-results?

There is no issue and the offer is not used in our fields.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this is working properly.

So I have closed the issue.
