### ISSUE TITLE
selected_datetime not working in combination with show_filters="false" ?

### ISSUE THREAD

**Issue by karlienfabre** [wpeventmanager/wp-event-manager#744]
Hi, 

I'm trying to make a view of the first 4 upcomming events on my homepage by using this shortcode:
[events  per_page="4" orderby="event_start_date" show_filters="false" show_pagination="false" show_more="false" layout_type="box" selected_datetime="Today,31-12-2021" ]

But the selected_datetime doesn't seem to work as it's still showing past events. I do want to use a filter on the homepage, because on a different page I want to list all events, also past/expired events. So I don't want to use the general setting don't show expired events..

If I remove the show_filters="false" code, the selected_datetime does work in the view.. 

Any chance you guys can help me out here? 

Thanks!
Karlien
<img width="1607" alt="Screenshot 2021-03-04 at 12 02 30" src="https://user-images.githubusercontent.com/5577319/109957170-dd2c7c80-7ce4-11eb-8dd7-507aa78a2e52.png">

**Comment by krinaydhanani** [comment]
Now this is perfectly working fine.
