### ISSUE TITLE
Issue with duplicate button

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#745]
Issue no. 2
It is throwing wron event end date- taking back to 1970

Issue no. 3
Event banner gets deleted from the duplicated event, if the original event gets deleted from the Trash.

**Comment by hiteshmakvana** [comment]
- Event end date working fine with duplicate event.
- Banner is duplicating with event 
![image](https://user-images.githubusercontent.com/42602299/111452348-6f4a7100-8738-11eb-93e4-864e55dc66b0.png)

**Comment by krinaydhanani** [comment]
This is not an issue everything is perfectly working fine with the duplicate events.
