### ISSUE TITLE
Organizer ID

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#747]
lATEST VERSION DOESNOT DISPLAYS ORGAN IZER ID WHEN HOVERING TEH MOUSE ON ORGANIZER NAME IN THE aDMIN>> EVENT MNAAGER>> ORGANIZER SECTION

**Comment by hiteshmakvana** [comment]
If we show the organizer id then we need to override the core wp table list functionality for edit, delete etc.

**Comment by ritakikani** [comment]
@krinaydhanani  this may break wordpress functionality and also this may take time because of complexity.

**Comment by live-aamir** [comment]
@mistry-jignesh added the ID column as discussed with @krinaydhanani.
![Screenshot_3](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/2bf33c58-60f9-4b39-aa19-e97226bc9342)

**Comment by mistry-jignesh** [comment]
I have verified this issue.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/aad741ce-e479-422a-aa24-2dce45a1d3db)

So I closed the issue.
