### ISSUE TITLE
Need to fix  - Organizer section - paragraph issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#748]
Organizer section content are showing only one paragraph .

Here paragraph should be show as per I have enter details in organizer. 

![image](https://user-images.githubusercontent.com/75515088/110452982-ba86d300-80eb-11eb-99cd-7407cf879db5.png)

![image](https://user-images.githubusercontent.com/75515088/110453496-38e37500-80ec-11eb-99f0-afc5009c5d97.png)

**Comment by hiteshmakvana** [comment]
If you just apply empty space it will not automatically add paragraph and also it is in text mode. This depends on several theme filters like auto apply p tag. Which we don't need to apply from our end.

**Comment by mistry-jignesh** [comment]
When I have create normal page then in the view page paragraph is working properly.

But in the organizer section is not working . 

As per @hiteshmakvana  Sir said that If you just apply empty space it will not automatically add paragraph and also it is in text  mode.

**Comment by mistry-jignesh** [comment]
So now I have closed the issue.

**Comment by mistry-jignesh** [comment]
Client is facing issue. So I have reopen the issue.

**Comment by mistry-jignesh** [comment]
Verified issue . Now Heading formating issue and image issue is fixed.

For paragraph need to add <br>tag. 

So I closed the issue.
