### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#75]
Hello,

On the event page, there is a category name under event listing. It is clickable. There is no category page for the events so better to make it non-clickable.

https://screenshots.firefox.com/NaNVbzO8jsaKKVdT/localhost

**Comment by hiteshmakvana** [comment]
Category template should be supported the same as event tag.

**Comment by krinaydhanani** [comment]
We should make a layout of these pages.

![image](https://user-images.githubusercontent.com/35419531/92232294-f4bcb100-eecb-11ea-9b1f-553c2131a635.png)

**Comment by hiteshmakvana** [comment]
@sapnadudhat03 Template hierarchy added with theme template support.
