### ISSUE TITLE
Searech Issue Bug reported by cutomer

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#756]
I spent hours trying to figure out why the event search wouldn't work on my site. Thought I'd share the solution in case it's something you'd like to add to the core plugin to increase compatibility or at least document for others. More information on what this code does can be found here.

add_filter('get_event_listings_result_args', function($result) {
	relevanssi_do_query($result);

	return $result;

**Comment by hiteshmakvana** [comment]
This is result not query you can apply argument and it will give your result.

**Comment by Priya-Goenka** [comment]
ok, i just reported for you to have look at it.

**Comment by mistry-jignesh** [comment]
This is not an issue . So now I have closed the issue.
