### ISSUE TITLE
Need fix issue - Custom field type

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#757]
**Custom field type** issue

When I have added PDF file then proper icon should be display.

![image](https://user-images.githubusercontent.com/75515088/111312046-eb837c80-8684-11eb-8751-f6bcf76e3a9b.png)

**Comment by hiteshmakvana** [comment]
If you have stored correct value it should display correctly. 

![image](https://user-images.githubusercontent.com/42602299/111462581-9b6bef00-8744-11eb-899e-ccd3d3da66d9.png)

**Comment by mistry-jignesh** [comment]
As per @hiteshmakvana comment If you have stored correct value. It should display correctly.

So now I have closed the issue.
