### ISSUE TITLE
undefined array key "post_type" after log in

### ISSUE THREAD

**Issue by Ganoash** [wpeventmanager/wp-event-manager#758]
Error message: Undefined array key "post_type" in ./wp-content/plugins/events-manager/em-events.php on line 323, referer: url/path/
plugin version:  5.9.11.3
frequency: some of the time

Hi, I'm using the event-manager wordpress plugin to manage events for an organization. Lately some specific users have been unable to acces any page on the website because of this error. Any help or a fix would be appreciated

**Comment by hiteshmakvana** [comment]
Hi @Ganoash 

Our plugin name is WP Event Manager and this error is not related to our plugin. Please contact your plugin author.

Thank you

**Comment by mistry-jignesh** [comment]
As per @hiteshmakvana  above comment this error is not related to our plugin. So Now I have closed the bug.

**Comment by mistry-jignesh** [comment]
As per @hiteshmakvana above comment this error is not related to our plugin. So Now I have closed the bug.
