### ISSUE TITLE
Need to fix  - Event duplication issue at event dashboard

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#759]
When I have click on the duplication icon for duplicating event then on the page is display below message.

![image](https://user-images.githubusercontent.com/75515088/111476747-74b5b480-8754-11eb-821a-e1aacdfc46d9.png)

![image](https://user-images.githubusercontent.com/75515088/111476606-5354c880-8754-11eb-9c75-b64a495028e7.png)

**Comment by hiteshmakvana** [comment]
If you haven't set u the submission page then it should show you an error.

**Comment by mistry-jignesh** [comment]
I have verified this issue. This is not an issue.  I have just set backend setting.

Now it is working properly . So I have closed the issue .
