### ISSUE TITLE
Upcoming Event Widgets

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#76]
Hello,

Upcoming Event Widget seems not working properly. It is showing current event and past events both. It should display only UPCOMING EVENTS...........

https://screenshots.firefox.com/v4kFcF2P0xFXWUow/localhost
https://screenshots.firefox.com/UkOLBsXgne5hT1jN/localhost

**Comment by ritakikani** [comment]
Now, upcoming event widget is working fine
