### ISSUE TITLE
Need to fix - Reset button is required 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#760]
Event Dashboard  - When I have type location as "Surat" and click on the filter button then search result is display on the screen.

Now I have to remove this search result then here required "Reset" . So user can easily remove this search result.

![image](https://user-images.githubusercontent.com/75515088/111612354-65da0b00-8803-11eb-9faf-8bb8114dcd32.png)

**Comment by jenniferhad** [comment]
Has this been looked at yet? It's causing a lot of my users to complain. 

If not, does anyone have a workaround? I'm having trouble hacking a button to work myself

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.

A reset button is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/949e716f-b86e-40d0-9abd-1b20a7b1fdac)

So I closed the issue
