### ISSUE TITLE
wp-event-manager / update-banner does not work !

### ISSUE THREAD

**Issue by soda31** [wpeventmanager/wp-event-manager#763]
Hello,

#738 has been close but bug is always here

I tested that again
https://demo.wp-eventmanager.com/t3a6zsurong9qhc/events/#events

admin : I create an event
then I update banner using dashboard

Banner is not updated in events page
But in the dashboard thumbnail is ok

Did you saw my video ?

If it works on your side could you post a video showing what you are doing ?

Thanks

Regards

**Comment by hiteshmakvana** [comment]
When you set up event banner first time it must have synchronized with the event thumbnail. After updating that several user requesting that it must have to be separate because they want to use event banner images and thumbnail images separately. 


As per the user feedback, we have improved this. If we got more queries on this then we can synchronize both. Also synchronizing to good for more users. In case you want to synchronize it from your end you can do it by customizing it.

**Comment by soda31** [comment]
Hi hiteshmakvana,
Thanks for your answer.

I find that it is a strange behaviour, at least it could be a checkbox somewhere to let user choose.

I tryed this, update
zzzz\wp-content\plugins\wp-event-manager\templates\content-event_listing.php

At beginning of file
comment 
//$thumbnail  = get_event_thumbnail($post,'full');
and put this instead
$thumbnail  = get_event_banner($post);

Seems working but is it the good way ?

Could you confirm or help me ?

Thanks,
Regards

**Comment by hiteshmakvana** [comment]
Hi @soda31 

We need solid reason to implement this. If we do this then some customers will complain it is better if you can override the template and use the functions accordingly?

I have to talk with our team before implementing anything on this. This can be more trouble in the future if we change without checking the possiblity.

**Comment by soda31** [comment]
Hi hiteshmakvana,

I do not understand why **full** CRUD is not applied for events
create, read, update, delete

Update is not working fully for events
Updating image event means that thumbnail and banner need to be updated simultaneously

Could you proove me that nobody id complaining about this strange behaviour ?

I agree to update template but could you confirm that I want to do is correct ?


I tryed this, update
zzzz\wp-content\plugins\wp-event-manager\templates\content-event_listing.php

At beginning of file
comment
//$thumbnail = get_event_thumbnail($post,'full');
and put this instead
$thumbnail = get_event_banner($post);

Seems working but is it the good way ?


Thanks,
Regards

**Comment by ritakikani** [comment]
User can upload multiple banner for same event so if we will show banner at event listing page, then that will cause the issue some times. so thumbnail will be better to show on event listing page.

In case if any customer want to show banner on listing page, then he just need to override template file called "content-event_listing.php".

In that file just need to replace below code 

`$thumbnail  = get_event_thumbnail($post, 'full');` with

`$thumbnail  = get_event_banner($post);
if(is_array($thumbnail)):
    $thumbnail = $thumbnail[0];
endif;`

**Comment by mistry-jignesh** [comment]
Verified this  issue . Just need to override template file. Using below code.
In case if any customer want to show banner on listing page, then he just need to override template file called "content-event_listing.php".

In that file just need to replace below code

$thumbnail = get_event_thumbnail($post, 'full'); with

$thumbnail = get_event_banner($post); if(is_array($thumbnail)): $thumbnail = $thumbnail[0]; endif;
