### ISSUE TITLE
Please check Pagination for upcoming event. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#765]

**Comment by Priya-Goenka** [comment]
When you use upcoming event widget in the ellementor, Pagi9nation works?

**Comment by Priya-Goenka** [comment]
Okay i faced this issue on user site, When in elementor, I use the Upcoming event widget on the listing page, and then I say true to Pagination. On frontend, the pagination does not change pages only. The buttons say page 2 doesn't works only.

Also when using load more, it repeats the same events. Please test once,

**Comment by hiteshmakvana** [comment]
8fb8008a38ea2a19ab73c5ad9ffce2a17d3b1702

**Comment by mistry-jignesh** [comment]
I have verified issue. Now the issue is fixed .

It is working fine . So now I have closed the bug.
