### ISSUE TITLE
URL field type- Multiple files.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#767]
Please allow permission to add multiple URLs on the same field.

**Comment by hiteshmakvana** [comment]
For now we don't have multiple URL feature.

**Comment by ritakikani** [comment]
I think we do not need to add this feature.

**Comment by mistry-jignesh** [comment]
As per @ritakikani :  We do not need to add this feature.
So I closed the issue.
