### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#768]
I've noticed that after setting dates for events (only the start date as they are single day events and with no specific start or end time), the dates revert to 01/01/1970, I have d-m-Y as the chosen date format.

**Comment by mistry-jignesh** [comment]
I have checked this issue .This issue is unable to reproduced.

**Comment by mistry-jignesh** [comment]
Verified issue . Now this issue fixed & working properly.

Date is save properly.

So I closed the issue.
