### ISSUE TITLE
Organizer and Venue disappeared from Submit-Event-Form

### ISSUE THREAD

**Issue by shopdoc** [wpeventmanager/wp-event-manager#769]
When adding an event in a new installed website there are no fields to choose organizer or venue. Both are activated in the settings.

(In an older installation of wp-event-manager this is working fine.)

**Comment by hiteshmakvana** [comment]
Hi @shopdoc 
Create the organizer submission page and assign the venue submission page. Once the page is assigned it will show you the selection. User must be logged in to select or add venue or organizer.

Thank you

**Comment by shopdoc** [comment]
Hi @hiteshmakvana,
thank you! It's working now but shouldn't it depend on the existence of venues and organizers rather than assignment of submission pages?

Best regards
