### ISSUE TITLE
Filters not working for Calendar-View

### ISSUE THREAD

**Issue by shopdoc** [wpeventmanager/wp-event-manager#770]
When having the calendar-addon installed an using [events] you get a third view option. The filters above only have an impact on list- and box-view results. The calendar-view ist showing all events. Everytime.

**Comment by mistry-jignesh** [comment]
This issue is related to calendar addon. So
 
I closed the issue. Filter related issue open in the calendar addon.

Issue #63.

So I closed the issue.
