### ISSUE TITLE
Underscore in Select type field editor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#771]
1 create custom fielt
2 type: Select
3. Use two-word placement- Chicken salad. 
4. It will store- Chicken_salad
5. display chicken_salad
6. Also the Capital letter are not capitaled. 
![image](https://user-images.githubusercontent.com/65893994/113267294-d00aa980-92f3-11eb-9f48-558cdc0f7c99.png)

**Comment by hiteshmakvana** [comment]
With latest version you won't face this issue.
