### ISSUE TITLE
Need to fix issue - Time is display wrong

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#772]
I have created new field from field editor . Type as select = Date. 

Now perform below setting .

![image](https://user-images.githubusercontent.com/75515088/113689575-1c852900-96e8-11eb-9809-00c18b0c78a6.png) 

![image](https://user-images.githubusercontent.com/75515088/113690592-38d59580-96e9-11eb-85ca-641dd3f55770.png)

When I have view event then it is display wrong time on the page.

![image](https://user-images.githubusercontent.com/75515088/113690679-4be86580-96e9-11eb-9cbd-b631f6d0e1a4.png)

**Comment by hiteshmakvana** [comment]
If there is only date stored in field then there is no way to show time so it will automatically take 12AM by default. 
This makes sense and also if you want to use the date and time then you can see start date and end date both working fine.

**Comment by mistry-jignesh** [comment]
As per this comment there is only date stored in field then there is no way to show time so it will automatically take 12AM by default .So there is no issue.

Now I have closed the issue.
