### ISSUE TITLE
Multiple attendee information get lost after order is submitted

### ISSUE THREAD

**Issue by panilo** [wpeventmanager/wp-event-manager#778]
Hello,
I tried the following

1. From your demo website https://demo.wp-eventmanager.com
2. Go to Events
3. Select Event with sell ticket https://demo.wp-eventmanager.com/event/meeting-or-networking-event-tech-jobs-fair-berlin-2021/
4. Select Tech Jobs Fair Berlin - 2021 VIP quantity 2
5. Remove paid tickets in the cart, leave only free tickets
6. Fill in all the information on the checkout page
7. Complete the registration
8. Go in the backend panel > Event Registrations > All Event Registrations
9. Your order will appear with only one ticket and only one attendee information

Expected
9. Your order should display the selected number of tickets and display the correct attendees information

**Comment by mistry-jignesh** [comment]
Now this issue fixed with latest version sellticket ,Registration  addon.

So I closed the issue.
