### ISSUE TITLE
Need to fix - After the refresh page message is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#779]
Click on the Event Dashboard .

Event listing page is load .

From the any event click on the "Mark cancelled" icon.

On the screen is display message. Now refresh the page.

Observed that Message is display on the screen. This message should remove from the page.

![image](https://user-images.githubusercontent.com/75515088/113814145-d636d500-978e-11eb-8305-8aa34156bf55.png)

**Also put dot ( . ) at the end of the sentence.**

**Comment by pooja-pragda** [comment]
This message is to identify that event is already cancelled, it will not vanish on page refresh/reload.

**Comment by mistry-jignesh** [comment]
I have verfied issue dot ( . ) issue is fixed. 

As per@pooja madm this message is to identify that event is already cancelled, it will not vanish on page refresh/reload.

**Comment by yukta05** [comment]
this issue is solved so i close this issue.
