### ISSUE TITLE
Need to fix - Upcoming events tabs - Message display - There are currently no events.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#780]
From Event Dashboard . Click on the one event.

Now in the event from organization section click on the "More info " button.

Open organization page . 

Go to Current events tabs.

In the current event tabs -Display the current events

Using the pagination option move to the second page.

Change the tab from current events tabs to upcoming event tabs.

Here on the page directly display message " There are currently no events".

In the upcoming events tabs there are many event but it is display message **There are currently no events.**

![image](https://user-images.githubusercontent.com/75515088/113817903-abe81600-9794-11eb-89f0-a323f7f6ff9b.png)

![image](https://user-images.githubusercontent.com/75515088/113817998-c621f400-9794-11eb-8ceb-ce3071afabff.png)

**Comment by tamanna-ahuja** [comment]
@mistry-jignesh  - This is working in the core setup. Request you to find the exact scenario when this is happening and drop STR(Steps to Reproduce) again.
