### ISSUE TITLE
"orderby" not working for calendar view

### ISSUE THREAD

**Issue by shopdoc** [wpeventmanager/wp-event-manager#783]
The sorting option for event listings [events orderby="event_start_date"] has no impact on calendar view. (I would expect a sorting by time within a single day.)

**Comment by mistry-jignesh** [comment]
This shortcode [events orderby="event_start_date"]  not working calendar view.

**Comment by mistry-jignesh** [comment]
Now this issue open in the calendar plugin. 

Issue is - https://github.com/wpeventmanager/wp-event-manager-calendar/issues/79

So I closed the issue.
