### ISSUE TITLE
Echoes out bool(true) on event submit page

### ISSUE THREAD

**Issue by jonsisk** [wpeventmanager/wp-event-manager#784]
https://github.com/wpeventmanager/wp-event-manager/blob/984e086ccf6ec9895e8d07f561af69cb6315b0fe/wp-event-manager-template.php#L393

**Comment by hiteshmakvana** [comment]
Removed in new updates.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now bool(true) on event submit page issue is resolved .

So I am closed the issue.
