### ISSUE TITLE
Dates displaying on List view has problem.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#787]
![image](https://user-images.githubusercontent.com/65893994/116042985-b78c7580-a68c-11eb-9ffa-32b7547f0d6f.png)

If you see, the date 35 is in horizontal view, however, 04,09, is in vertical view.

**Comment by ritakikani** [comment]
this issue is already resolve in previous version.

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is working fine.

03,05,06 date events are in the horizontal view.

It is working fine.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/ad6d4eae-ff93-4a29-9f4a-1a810b822724)

So I closed the issue.
