### ISSUE TITLE
BackEnd Post Event Page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#79]
Default Wordpress Icons are getting missed on Edit Post an Event Page. Only Event Manager add-on is activated.

![postevent](https://user-images.githubusercontent.com/49863477/56880882-0f7f4a00-6a7c-11e9-9a04-44131e9f6ff2.png)

**Comment by hiteshmakvana** [comment]
It might be some theme of any other plugin conflict.
