### ISSUE TITLE
Need to fix - font style is not apply

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#790]
When I have apply Bold+Italic style then Italic effect unable to show event page.

![image](https://user-images.githubusercontent.com/75515088/117103022-2b1e3900-ad97-11eb-9316-e112fc40e851.png)

![image](https://user-images.githubusercontent.com/75515088/117102851-c82ca200-ad96-11eb-833e-a476abda04df.png)  
 
Same issue with only bold effect is not apply.  

![image](https://user-images.githubusercontent.com/75515088/117132576-a34d2480-adc0-11eb-8b5a-da1818bfe3c9.png)

![image](https://user-images.githubusercontent.com/75515088/117132495-89abdd00-adc0-11eb-8fee-9fb2affb3800.png)

**Comment by tamanna-ahuja** [comment]
Covering in Custom Field- Wp editor not reflecting Formating. #806

**Comment by mistry-jignesh** [comment]
This issue is covering in the #806 .

 So I closed the issue.
