### ISSUE TITLE
Date filter in range. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#792]
I set up a start and end date, but in the event page, when i choose a date/dates between start and end dates, the event doesn’t show up.
However if I choose the specific start date, or the specific end date, or a range that includes the start or the end date, the event is shown as it should.

Example:
Start date: 1/5/2021
End date: 5/5/2021
If I choose 1/5/2021 or 5/5/2021 in the callendar, the event displays.
If I choose 4/5/2021, or (2/5/2021 to 4/5/2021) the event is not being displayed.

**Comment by r0manenk0** [comment]
Hi. Is there any fix for this bug

**Comment by mistry-jignesh** [comment]
Here I select the start date -  1/5/2021 - Here event is not display.

If select end date - 5/5/2021- Here only 2 events are display.

4/5/2021, or (2/5/2021 to 4/5/2021) the event is not being displayed.

**Comment by mistry-jignesh** [comment]
I have verified issue . Now this issue is fixed & working fine.

Here  range that includes the start or the end date, the events are shown .

So I closed the issue .

**Comment by Priya-Goenka** [comment]
not resolved. or maybe arising again

**Comment by Priya-Goenka** [comment]
https://wordpress.org/support/topic/date-filter-for-several-days-event-not-working-as-expected/

**Comment by from-schenefeld** [comment]
Hello everybody,

is there any update/solution on this issue?

**Comment by ritakikani** [comment]
As per our plugin current feature, we are providing date filter as on event start date only, not between start-end date. 
For urgent resolve, we are already providing hooks and filters to customize anything to customers, so for this you can customize with below hook/filter.

$query_args = apply_filters( 'get_event_listings_query_args', $query_args, $args );
do_action( 'before_get_event_listings', $query_args, $args );


But regarding this new feature we need to discuss this topic with our senior.

**Comment by from-schenefeld** [comment]
Hi @Priya-Goenka 

do you think someone could support me for above described issue? An answer on this would not be only beneficial for me but also for others using WP Event Manager as I saw this request also on wordpress.org-Support page.

It would be very helpful and I think it should not be that hard to summarize the steps to shortly.

Thanks so far and best wishes
Andreas

**Comment by ritakikani** [comment]
Hi @from-schenefeld , 

As above, a mention that we are providing hooks and filters to customize many more in our plugin.so, if you want to customize filter as per your requirement, you can use below hook/filter.

$query_args = apply_filters( 'get_event_listings_query_args', $query_args, $args );
do_action( 'before_get_event_listings', $query_args, $args );

You need to use this filter/hook to customize code.you can not add this above code in your theme functions.php file but you need to use this hook/filter and in that you need to write code to customize filter.

And yes, we will provide this feature in future if will approved from our senior team.

**Comment by krinaydhanani** [comment]
This issue is fixed so I am going to close this issue.
