### ISSUE TITLE
Need to fix - WPML - Select language as Hindi - Event listing page- Events are not display 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#795]
Enable WPML plugin .

Translated events page to Hindi Language.

Select language as Hindi.

Front End : Click on the Event link button.

Event listing page events are not display.

Here on the screen throbber is display infinite time.

While I am selecting language as "English" then Events are display.

![image](https://user-images.githubusercontent.com/75515088/117609248-41543c80-b17d-11eb-8da0-6519d0677a52.png)

Also similar issue found : Events box view, Events list view and Calendar view.

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine. Below is the screenshot. Please check.
![Screenshot 2024-03-15 123351](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/2b89bfda-ea52-4756-a60a-766945a7d0da)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine as per Aamir steps.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/72b83694-d14c-4123-bf09-4489229034c0)

So I closed the issue.
