### ISSUE TITLE
Need to fix - WPML - Select language as German- Organizers icon and details are not display 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#796]
Enable WPML plugin .

Translated Organizer dashboard page and One organizer to German language. 
 
Select language as German .

Front End : Go to organizer option  > Organizer Dashboard .

Here organizer details and organizer icon are not display.

Organizer name is display in English language.

![image](https://user-images.githubusercontent.com/75515088/124265219-0c4be100-db53-11eb-9127-277ac5727c21.png)

**Comment by live-aamir** [comment]
@mistry-jignesh The german language translate some words as english. Here rest are working fine. Below is the screenshot. Please check.
![Screenshot 2024-03-18 141715](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/ea2b5aa3-e663-48e2-be5c-7cd6950d43c5)

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is working as per the provided steps.
![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7b9b6d4f-4e90-4b5e-b97b-d3d9b7fef38a)
So I closed the issue.
