### ISSUE TITLE
Need to fix - WPML - Select language as Hindi - Content display in English language

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#797]
Enable WPML plugin .

Translated event organizer and one organizer page to Hindi language.

Select language as Hindi.

Front End : Go to organizer option >Event organizer .

Event organizer page  text are display in English language.

![image](https://user-images.githubusercontent.com/75515088/124267324-b9275d80-db55-11eb-85be-192561f44fd1.png)

**Comment by live-aamir** [comment]
@mistry-jignesh The content of the organizer needs to be translated when creating organizer for other language. I have created it.
Below is the screenshot. Please check.
![Screenshot_18](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/aafecf8f-6101-44fd-9745-31821fd3039b)

**Comment by mistry-jignesh** [comment]
I have verified this issue with the steps provided.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/e50b09e2-76c8-460b-9898-a23490ef9bd2)

This issue is working fine. So I closed the issue.
