### ISSUE TITLE
Need to fix - WPML - Select language as "Hindi" - Venue Details is not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#798]
Enable WPML plugin .

Translate Event venue form Hindi language.

Select language as Hindi.

Front End : Go to venue option >Venue list .

If there is no venues then this message should be display Hindi.

![image](https://user-images.githubusercontent.com/75515088/124258784-6a74c600-db4b-11eb-851b-2e55a6766b36.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working properly. For this WPML needs properly configured. Below is the screenshot.
Please check.
![Uploading Screenshot_3.png…]()

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is working fine as per the provided steps.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/60368bf5-c88c-443a-a0e3-91bf1d1a2119)

So I closed the issue.
