### ISSUE TITLE
Need to fix - WPML - Select language as "Hindi" -Venue Dashboard venue details not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#799]
Enable WPML plugin .

Translate venue dashboard and one venue page in Hindi Language.

Select language as Hindi.

Front End : Go to Venue option >Venue Dashboard .

Here venue name , venue icon and Details are not display Hindi.

While I am selecting language as "English" then Events are display.

![image](https://user-images.githubusercontent.com/75515088/124260195-081cc500-db4d-11eb-94df-ba689f351d9a.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine. Below is the screenshot. Please check.
![Screenshot_14](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/dbd3c29b-f0cb-4c2c-8bea-eb7c3b469db1)
