### ISSUE TITLE
Custom Field- Wp editor not reflecting Formating. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#806]
Wp editor not reflecting any formatting.

**Comment by mistry-jignesh** [comment]
During testing I have found following issue : 

1.Backend  -Wp Editor - When I have apply bold effect then Event view page register form and even category and event type all things are missing.
 
![image](https://user-images.githubusercontent.com/75515088/118088744-27b52e00-b3e5-11eb-9922-db1fde85794a.png) 

2. Backend - Wp Editor - When I have apply bold effect then Event view page bold effect is not shown. 

![image](https://user-images.githubusercontent.com/75515088/118089147-ae6a0b00-b3e5-11eb-8239-8c7429c3a125.png) 

3.Backend - Wp Editor - When I try to add image url.It  is added successfully but on the event page image URL is not display.

![image](https://user-images.githubusercontent.com/75515088/118092833-41a53f80-b3ea-11eb-9d3f-aa604f6114e5.png)  

4.

**Comment by tamanna-ahuja** [comment]
Latest status ?

**Comment by mistry-jignesh** [comment]
Verified issue with latest plugin. Above issues are present related to formating.

**Comment by tamanna-ahuja** [comment]
Checked format is getting applied, So this issue is not wp editor instead css issue . Request you to open new bug for plugin ui improvements and add this in next version

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja -  This issue is not wp editor instead css issue .

Now this issue is plugin ui improvements and add this in next version.

So this issue is assigned for enhancement

**Comment by mistry-jignesh** [comment]
Verified this issue. Facing issue in the formating.

Please check it.


![image](https://user-images.githubusercontent.com/75515088/177936414-d317d58f-9ccf-4539-8899-c1a88774a28b.png)

**Comment by kinjal6810** [comment]
<p>,<BR> tag is not allowing in Wordpress database.

Same issues I found below forum

https://blog.templatetoaster.com/wordpress-line-break-not-working/

https://stackoverflow.com/questions/39616885/p-and-br-tag-is-not-displayed-in-wordpress-database

https://wordpress.stackexchange.com/questions/130075/stop-wordpress-automatically-adding-br-tags-to-post-content

solution:- Client used other editor like TinyMCE ,WP Quick front-end editor.

**Comment by live-aamir** [comment]
@mistry-jignesh I have tested it, the formatting is working fine in both gutenberg and classic editor. Please check.

**Comment by mistry-jignesh** [comment]
I have checked the issue with Aamir.
This issue is with the WP Editor custom field. It is fine on the event details page.
So I closed the issue.
