### ISSUE TITLE
Need to fix [Backend] - Event Start as display 01.01.1970

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#809]
Datepicker Date format as select as : 01.15.2021

Create a new event and select start date as Today .

Click on the save button.

Now edit event and observed that event start as display 01.01.1970

https://prnt.sc/12vjz33

**Comment by DanWin** [comment]
We could reproduce this issue:
In a multisite the selected date format is German: dd.mm.yyyy. The date picker still uses mm.dd.yyyy.
When saving a date with day > 12, the month is invalid, so date is reset to 01.01.1970.
When a day <= 12 is selected, day and month are switched, and with every saving, they change position each time.
This happens only in a multi-site, a single site works as expected.

**Comment by tamanna-ahuja** [comment]
@DanWin ,

Please take the latest update, and In case, you are still able to reproduce this issue than let us know with proper steps to reproduce.

**Comment by mistry-jignesh** [comment]
Thanks for now we have reproduced issue & would be covering in  #768.

https://github.com/wpeventmanager/wp-event-manager/issues/768
