### ISSUE TITLE
Bug : Invalid enum value in field "eventAttendanceMode" (optional)

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#811]
![image](https://user-images.githubusercontent.com/65893994/118810193-35792080-b8c9-11eb-842f-e1446f4de582.png)
![image](https://user-images.githubusercontent.com/65893994/118810206-3ad66b00-b8c9-11eb-945f-265a905ca2cc.png)

**Comment by tamanna-ahuja** [comment]
[Find Url ](https://search.google.com/test/rich-results) for testing

**Comment by mistry-jignesh** [comment]
As per above issue is fixed and working fine. 

So I closed the issue.

Here new issue is face for Google  Structured Data.

For this created new issue.
