### ISSUE TITLE
Datepicker date range doesn't work properly

### ISSUE THREAD

**Issue by Thiggel** [wpeventmanager/wp-event-manager#812]
Hey there,

On my own site, I installed your plugin and included the event listing page, but the date picker doesn't seem to work. 
If I select a date that is in between the starting and end date of an event, but doesn't strictly include any of them, then the event doesn't get shown.

The same error occurs on your demo page: There's an event that takes place from April 25 until September 7, but if I put May 5 into the date picker, it doesn't get shown in the list.

I'd really appreciate some help with this as it is super important for the launch of my website.

Kind regards

**Comment by mistry-jignesh** [comment]
This issue with duplicated with issue - https://github.com/wpeventmanager/wp-event-manager/issues/792

So I closed the issue & status is assigned duplicated.
