### ISSUE TITLE
Need to fix issue - Custom field is not available at front end post form 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#813]
Custom field is not available at front end post form .

I have created one field in registration form. This field is available at backend  but at front end post form this is not avialbel.

![image](https://user-images.githubusercontent.com/75515088/118965808-b518f500-b986-11eb-892a-5ea8f95d26e7.png).

 
![image](https://user-images.githubusercontent.com/75515088/118966749-851e2180-b987-11eb-88fa-d924c7f16cc7.png)

**Comment by pooja-pragda** [comment]
At first, the issue is not related to the core plugin, is related to the registration addon & the second thing is it works perfectly, unable to reproduce.

**Comment by mistry-jignesh** [comment]
Now this issue is not related core plugin.

Issue is working fine.

So I closed the issue.
