### ISSUE TITLE
Need to fix - WPML - Event Dashboard - Page is not translated in Hindi

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#816]
When I have selected language as "Hindi"  then below page is display on the screen.

![image](https://user-images.githubusercontent.com/75515088/119328972-53b49700-bca2-11eb-94c0-5a7d3ad58e51.png)

When I have selected language as "english" then below page is display on the screen.

![image](https://user-images.githubusercontent.com/75515088/119329829-39c78400-bca3-11eb-81d3-4b5f2304d87c.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This is working fine. For this WPML needs to be configured properly with pages and events both needs to be created for translation. Below is the screenshot. Please check.
![Uploading Screenshot_1.png…]()

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is working fine as per the provided steps.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/7057e523-772e-45be-b21d-0c80fa4166cc)

so I closed the issue.
