### ISSUE TITLE
Need to fix -Venue form - Change text label

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#817]
Venue form - Change text label.

Please check below url.

![image](https://user-images.githubusercontent.com/75515088/119334185-6df17380-bca8-11eb-92db-632ba5d9852e.png)

**Comment by mistry-jignesh** [comment]
I have verfied issue . Now the text label is change on venue form.

So this issue is fixed.

**Comment by yukta05** [comment]
![image](https://user-images.githubusercontent.com/86232676/141930862-ae8e9504-f64a-45f2-b6e1-7fb3bffb4d4b.png)
I have verified issue , this issue is solved , so i closed this issue.
