### ISSUE TITLE
Ticket Price field

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#82]
Ticket Price field should be numeric only.
![Price](https://user-images.githubusercontent.com/49863477/56884941-dac5bf80-6a88-11e9-93e4-b43c4fb14a9f.png)

Validate it on front end and back end form both.

**Comment by ritakikani** [comment]
Ticket price field is a normal field which will show whatever information is added by end-user which will show  at single event page. We will not provide any validation or currency options.
