### ISSUE TITLE
DAtepicker not compatible with wpml

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#823]
On listing page, the apply, clear, months, and weeks are non translatabl.

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine. Below is the screenshot. Please check.
![Screenshot_2](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/22433b26-95d5-475d-bb01-2f15387d0e8e)
