### ISSUE TITLE
[ WPML ] settings or wp_options table translation 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#824]
WPML support options table or settings translation which is stored in database but we can translate this as per the language defined.

**Comment by live-aamir** [comment]
@mistry-jignesh Some of the translation not showing in backend needs fresh updated .pot file as some of the text internationalization done recently in backend.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine with new .pot file.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/3108f28c-aba2-4107-8189-c96458448690)

So I closed the issue.
