### ISSUE TITLE
Upcoming events on Organizers page should be sorted by date. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#825]
![image](https://user-images.githubusercontent.com/65893994/119810453-ad67cc00-bf03-11eb-8dbf-7c449af60c2d.png)

**Comment by mistry-jignesh** [comment]
Yes this issue is present. Upcoming events on Organizers page should be sorted by date.

**Comment by tamanna-ahuja** [comment]
As this issue is not of core, Request you to move this issue to the contact organizer plugin

**Comment by mistry-jignesh** [comment]
This issue is re not core plugin . I have created this in the contact organizer plugin .

https://github.com/wpeventmanager/wp-event-manager-contact-organizer/issues/25

So now I closed the issue.
