### ISSUE TITLE
Custom information collected in field editor for organizers must display on Organizer details page. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#827]
If i am creating custom field n Organizer Field editor, It should display these data on organizer details page atleast.

**Comment by mistry-jignesh** [comment]
Yes this issue is present.

If i am creating custom field n Organizer Field editor, It should display these data on organizer details page atleast.

**Comment by tamanna-ahuja** [comment]
As written shown organizer field , but as fields doesn't display as their type would request you to open enhancement for same because it would need a small structure to be taken care which couldn't be achieved in this version

**Comment by mistry-jignesh** [comment]
I have verified issue. Now I have created custom field in the Organizer Field editor, It is display these data on organizer details .

So I closed the issue.
