### ISSUE TITLE
Banner duplicating in Media folder

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#831]
When I upload an event banner via post an event in the front end, it uploads the image twice?

![image](https://user-images.githubusercontent.com/65893994/120169935-1316c980-c21e-11eb-9c73-e83fe61d09c8.png)

**Comment by mistry-jignesh** [comment]
This issue verified  but it is workig fine and image banner is not duplicating in the media folder.

So this issue is fixed . So I closed the issue.
