### ISSUE TITLE
Need to fix -Single event detail  page is not added in elementor Pro 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#832]
Single event detail page is not added in elementor Pro .

**Comment by pooja-pragda** [comment]
In the new version of elementor pro, you have to set conditions at the time of template creation of a single page for events.

**Comment by mistry-jignesh** [comment]
I have verified issue. Set conditions at the time of template creation of a single page for events .

Now added signle event details page using elementor pro.
