### ISSUE TITLE
Event dashboard- delete button not working in elementor

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#833]

**Comment by mistry-jignesh** [comment]
Same issue with organizer dashboard and venue Dashboard.

**Comment by mistry-jignesh** [comment]
Yes this issue is present.

Delete button not working in elementor.

**Comment by mistry-jignesh** [comment]
I have verified issue in elementor. Now this issue is fixed & working.

Delete button not working in elementor.

So I closed the issue.
