### ISSUE TITLE
Ordering events by date does not work

### ISSUE THREAD

**Issue by dhalucario** [wpeventmanager/wp-event-manager#836]
![image](https://user-images.githubusercontent.com/10533763/121179852-74fbb280-c860-11eb-89c0-e2c6691af631.png)

What happens:

The events are being outputted in this order:
10th June 2021
9th June 2021
2nd June 2021
17th June 2021

The events should be output in this order:
2nd June 2021
9th June 2021
10th June 2021
17th June 2021

**Comment by christianfroehlichconsulting** [comment]
Hi, we experience the same difficulties.

**Comment by mistry-jignesh** [comment]
Yes this issue is present. Here events are not being order.

**Comment by tamanna-ahuja** [comment]
Data issue @mistry-jignesh  clear all events and try sorting it will work
