### ISSUE TITLE
Need to fix - Elementor -Event organizer issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#840]
When I have selected order as "ASC" and Order by select as "name".
When I  have selected order as "DESC" and Order by select as "name".

Here organizer name is not display as per order select.

![image](https://user-images.githubusercontent.com/75515088/121509432-428aba80-ca04-11eb-9b45-94fe3dee624a.png)

**Comment by tamanna-ahuja** [comment]
Hadn't fixed anything other than testing it working , May be covered with filtered issue request you to test again.

**Comment by mistry-jignesh** [comment]
I have verified issue with latest version. I have select option as mention in the steps.

Here organizer name is not display as per order select.


![image](https://user-images.githubusercontent.com/75515088/161194877-b06bec66-a57e-41ca-827e-23f86999a5cb.png)

![image](https://user-images.githubusercontent.com/75515088/161194950-8c16eeff-9004-47cc-9613-2a157019d27a.png)

**Comment by tamanna-ahuja** [comment]
This is working with CORE may be data redundancy is the issue

**Comment by mistry-jignesh** [comment]
I have verified issue with latest version in the new setup . 

This issue my be created data redundancy.

Now this issue is working fine. 

Organizer name is display as per order select.

So I closed the issue.
