### ISSUE TITLE
Need to fix - Elementor - Past event listing -Order issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#841]
When I have select order as "ASC" and order by select as "Title".
When I have select order as "DESC" and order by select as "Title" .

Here event are not display as per order.

![image](https://user-images.githubusercontent.com/75515088/121512915-e0cc4f80-ca07-11eb-9a35-1b7e176deffb.png)

**Comment by mistry-jignesh** [comment]
I have verified issue.

Here  Past event are not display as per order.

![image](https://user-images.githubusercontent.com/75515088/132857113-99f97af9-ba9e-46e7-a782-68e52af0337d.png)

![image](https://user-images.githubusercontent.com/75515088/132857060-d0aca27b-e800-47bb-ada5-05a55f4beb6e.png)

**Comment by tamanna-ahuja** [comment]
Please test in core

**Comment by mistry-jignesh** [comment]
This issue is coverd into #854. 

So I closed this issue.

**Comment by mistry-jignesh** [comment]
I have verified issue .Now this issue is fixed and working .

Here event are display as per order (ASC/DESC).

So I closed the issue.
