### ISSUE TITLE
Need to fix -Elementor - Single Event - Register for event button is missing on event page.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#842]
Single Event - Register for event button is missing on event page.

![image](https://user-images.githubusercontent.com/75515088/121516197-964cd200-ca0b-11eb-8143-8e44784cf5a1.png)

![image](https://user-images.githubusercontent.com/75515088/121516113-7c12f400-ca0b-11eb-9e7a-419d26297c29.png)

**Comment by pooja-pragda** [comment]
There should be a notice/message that - "You already registered for the event". this is related/duplicate of #849 Elementor - In registration form not getting warning/success notice.

**Comment by mistry-jignesh** [comment]
This issue is related to # 849 issue. 

So now I have closed the issue.
