### ISSUE TITLE
Need to fix -Elementor - Event details page is not showing properly 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#844]
When I have activate Elementor and Elementor pro. 

Go to Event Dashboard page and open any events.

Observed that below view page is open.

![image](https://user-images.githubusercontent.com/75515088/122380232-4b8c0680-cf85-11eb-947c-4d662fb084cf.png)

**Comment by hiteshmakvana** [comment]
You have to add some content in template.
