### ISSUE TITLE
List Venues and Organizers Shortcodes

### ISSUE THREAD

**Issue by gorfreed** [wpeventmanager/wp-event-manager#847]
This is regarding issue #243 which has been marked as fixed but is indeed not. 

The original author @ashokdudhat requests a feature for listing venues and organizers by shortcode like it is possible with TheEventsCalendar (https://theeventscalendar.com/extensions/list-venues-and-organizers-shortcodes). I cannot find any similar shortcode for the functionality described by the link in the documentation. I am looking for exactly the same feature!

**Comment by gorfreed** [comment]
Shortcodes exist.

**Comment by live-aamir** [comment]
@gorfreed For Venue Shortcode - https://wp-eventmanager.com/knowledge-base/venue-shortcodes/
  For Organizer Shortcode - https://wp-eventmanager.com/knowledge-base/organizer-shortcode/

**Comment by mistry-jignesh** [comment]
The dev team has provided a doc reference for this issue. So There is no reply from the client side.
So I am closing the issue.
