### ISSUE TITLE
date format on past events on single event organizer page. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#850]
![image](https://user-images.githubusercontent.com/65893994/123380818-89a0b000-d5ad-11eb-9cd7-49c4da27e10e.png)
![image](https://user-images.githubusercontent.com/65893994/123380917-a806ab80-d5ad-11eb-81dc-612a69e9119d.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is working fine. Date is display properly.

So I closed the issue.
