### ISSUE TITLE
Need to fix - Last Name field is missing at frontend form

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#851]
Backend :  Attendee information to collect 

![image](https://user-images.githubusercontent.com/75515088/123428374-5da02180-d5e3-11eb-9821-f7bf8da99331.png)

Front end  form : Post an event - Attendee information to collect 

![image](https://user-images.githubusercontent.com/75515088/123428623-a1932680-d5e3-11eb-814c-28579f751363.png)

**Comment by pooja-pragda** [comment]
this issue is from attendee information addon please create there.

**Comment by mistry-jignesh** [comment]
This issue is related to attendee information addon. This issue is created in attendee information addon.

So I have closed the issue.
