### ISSUE TITLE
Orderby parameter isn't working in shortcode.

### ISSUE THREAD

**Issue by msufiannasir** [wpeventmanager/wp-event-manager#853]
[events orderby="event_start_date"]

It simply doesn't work. Orderby parameter isn't working anymore. We need to fix this. Can you please help me out so I can fix the plugin and contribute in it if you don't have time to manage it?

Seems like we have same issue reported before https://github.com/wpeventmanager/wp-event-manager/issues/783 

Can you guys please take a look into ti?
Plugin Version 3.1.21
Wordpress Version 5.7.2

**Comment by pooja-pragda** [comment]
The correct shortcode will be: [events order="ASC/DESC" orderby="event_start_date"]

**Comment by mistry-jignesh** [comment]
I have verfied issue .Use - [events order="ASC/DESC" orderby="event_start_date"] shortcode.

This is working fine.
