### ISSUE TITLE
Need to fix -Shortcode Issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#854]
events event_online="false"

events selected_ticket_price="paid"
events selected_ticket_price="free"

events ticket_prices="ticket_price_paid"
events ticket_prices="ticket_price_free"

events per_page="5" orderby="event_start_date"
events per_page="15" orderby="name"
events per_page="15" orderby="parent"
events per_page="15" orderby="modified"

events show_pagination="True"
events per_page="5" show_more="false/true"

events show_more="true"

past_events per_page="5" orderby="title"

past_events per_page="5" keyword="Ticket book17Ticket book17"

Also  below shortcode not working in Elementor .

past_events orderby="title"
past_events order="DESC"
past_events keyword="Event for Testing -102 -DR"

events event_online="false"
events keyword="Take hiking"
events order="ASC" and "DESC

When I have used above shortcode then this shorcode is not working.

**Comment by pooja-pragda** [comment]
checked almost all of them & works fine. please reproduce properly if not working.

**Comment by mistry-jignesh** [comment]
I have verified shortcode. I am facing issue with shortcode.

events event_online="false"

events selected_ticket_price="paid"
events selected_ticket_price="free"

events per_page="10" order="DESC"
events per_page="10" order="ASC"

events per_page="10" show_ticket_prices="false"
events per_page="10" show_ticket_prices="true"

past_events per_page="5" orderby="title"

past_events per_page="5" keyword="Ticket book17Ticket book17"

Also below shortcode not working in Elementor .

past_events orderby="title"
past_events order="DESC"
past_events keyword="Event for Testing -102 -DR"

events event_online="false"
events keyword="Take hiking"
events order="ASC" and "DESC

When I have used above shortcode then this shorcode is not working.

**Comment by mistry-jignesh** [comment]
After few shortcode issues fixed . I have verified issue.  Facing issue in the below shrotcode.


[events event_online="false"]
[past_events per_page="5" orderby="title"]
[past_events per_page="5" keyword="Event for fair"]

**Elementor**

[past_events orderby="title"]
[past_events order="DESC"]
[past_events keyword="Decipher Decipher Decipher Decipher"]
[events event_online="false"]
[events keyword="Speed Reading"]
[events order="ASC" and "DESC]

**Comment by mistry-jignesh** [comment]
I have verified issue . Below shortcode is not working fine.

[past_events per_page="5" keyword="Event for fair"]

**Elementor**

[past_events order="ASC"]
[past_events order="DESC"]
[past_events keyword="CAL- Month "]
[events keyword="TestCAL- Month"]
[events order="ASC" and "DESC]

**Comment by mistry-jignesh** [comment]
I have verified issue with issue . Now this issue is working fine.

So I closed the issue.
