### ISSUE TITLE
Need to fix - Backend - Bulk action - Expire Events

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#858]
When I have select expire events from bulk action then filter option is not working .

Here unable to display expire event list.

Please check image.

![image](https://user-images.githubusercontent.com/75515088/124113532-2c16d280-da89-11eb-861a-c0d979caa2ea.png)

**Comment by pooja-pragda** [comment]
The option is to stand for the action not filter,
01. the select event then select the option- "Expire events" 
02.  Apply this to events.
Notice there selected events are expired.

**Comment by mistry-jignesh** [comment]
As per @pooja-pragda comment. The option is to stand for the action not filter.

So this is not an issue. So I have closed the issue.
