### ISSUE TITLE
Need to fix - Backend - Add Organizer and Add Venues issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#859]
When I have not added details for organizer and venues then click on the Publish button.

Here on the page display the message "Post Published " . View Post

When I have click on the View post then Post not found message is display.

Please Add proper validation message .

![image](https://user-images.githubusercontent.com/75515088/124125018-c3365700-da96-11eb-935d-0dd17f207337.png)

**Comment by pooja-pragda** [comment]
[Backend] - Won't fix. Even Wordpress default allows publishing blank posts.

**Comment by ritakikani** [comment]
@mistry-jignesh , we can't manage backend wordpress functionality.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - We can't manage the backend WordPress functionality.
So I closed the issue.
