### ISSUE TITLE
Need to fix - Backend - If there is no event then event name should be from dropbox

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#860]
If there is no event then event name should be remove from dropbox .

![image](https://user-images.githubusercontent.com/75515088/124127159-07c2f200-da99-11eb-9ff3-f8ffb301144e.png)

**Comment by pooja-pragda** [comment]
The Issue is in the recurring events addon. please create there.

**Comment by mistry-jignesh** [comment]
I have created new issue in the recurring events addon.

So I have closed the issue.
