### ISSUE TITLE
[ WPML ] Organizer and venue need to be compatible

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#864]
Organizer and venue listing not showing translated data on perticular language with WPML.

**Comment by tamanna-ahuja** [comment]
![Early test for PHP8 - WPML causing fatal error - WPML](https://user-images.githubusercontent.com/16346531/160985775-2ddb4972-6b0c-4648-afed-90f23ac333c4.png)


![Capture](https://user-images.githubusercontent.com/16346531/160985831-16e7f1f1-4101-44a3-bdbe-36528108adc1.PNG)



WPML is not compatible with the latest PHP VERSION 8 one they release an update we will look into issues raised as needed.

**Comment by live-aamir** [comment]
@mistry-jignesh Both dashboard are working fine. Below are the screenshot. Please check.
![Screenshot_20](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/9a5cded3-dd79-4925-b083-0b287f35def0)
![Screenshot_19](https://github.com/wpeventmanager/wp-event-manager/assets/49248762/9b5273f5-69ff-491b-9201-cf73229ed7ee)

**Comment by mistry-jignesh** [comment]
I have verified this issue. 

Organizer and venue dashboard is translation is working fine . Other pages also translated properly.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/8a8f6081-31a8-49e5-b11e-85b23ef55bfe)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/642923cc-a1eb-4126-87b5-905083da8eb7)

![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/07dbf72f-5313-4bd6-bfc2-1e55ac6b098f)


So I closed the issue
