### ISSUE TITLE
Backend - Event Registration section - Donation ticket details is missing

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#869]
Event Registration section - Ticket details option

Donation ticket details is missing. Here only display Paid and free ticket details.

![image](https://user-images.githubusercontent.com/75515088/125587384-ac45a9fa-dc37-48ca-832d-14d4b207116e.png)

**Comment by pooja-pragda** [comment]
this is an issue from the sell ticket addon please create there.

**Comment by mistry-jignesh** [comment]
This issue is not related to core plugin. So this issue is created in the sell ticket addon.

So I have closed the issue .
