### ISSUE TITLE
Events ordering issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#871]
.I have select orderby as "featured "option.

If there is not featured date events then events are not display in order.
https://prnt.sc/1bqa1aw

2.I have select orderby as "featured "option.

If there is featured date events then events are not display in order.

https://prnt.sc/1bqhqgb

3.I have select orderby as "Event start date "option.

There are 3 events .All events start on same date and time(07/7/2021) and 2 events are finished on same date(31/8/2021).
one event finished on (31/7/2021)

Here one event finished on 31/7/2021 and this event is display second position. 

This event should be display first. 

https://prnt.sc/1bpm0ae

**Comment by mistry-jignesh** [comment]
Verified issue. This issue is present.

**Comment by tamanna-ahuja** [comment]
will cover in Event should be sorting time wise also #999

**Comment by mistry-jignesh** [comment]
As per above comment issue will cover #999 .

So I closed the issue.
