### ISSUE TITLE
Single event listing issue with elementor pro.

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#872]
single event listing issue with elementor pro.

Registration button is not display on the event details page.

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/139634093-87fb5dd9-d7a9-40a9-83db-5ae5883197b3.png)

**Comment by mistry-jignesh** [comment]
This issue is not reproduced & working fine .

So I closed the issue.
