### ISSUE TITLE
Fatal error on all Post Category pages, caused by rewrite rules

### ISSUE THREAD

**Issue by jonmarccurtis** [wpeventmanager/wp-event-manager#873]
I have traced the issue down to EM's rewrite rules.  Somehow, in my PROD server (only), the following entries have ended up in the DB Options table -> rewrite_rules: 
11:"event/(.+)$";s:56:"index.php?pagename=&em_redirect=1&event_slug=$matches[1]";s:14:"location/(.+)$";s:59:"index.php?pagename=&em_redirect=1&location_slug=$matches[1]";s:14:"category/(.+)$";s:59:"index.php?pagename=&em_redirect=1&category_slug=$matches[1]";

These rules do not show up in my STAGING server, and I do not know how they got into PROD.  But the "category" rule conflicts with WP Post's Categories.  Any WP post category pages' querys match that rule.  Then EMPermalink:redirection() has this code:
```
           if( is_object($wp_query) && $wp_query->get('em_redirect') ){
…
                }elseif( $wp_query->get('category_slug') ){
                    $url = get_term_link($wp_query->get('category_slug'), EM_TAXONOMY_CATEGORY);
                }
                if(!empty($url)){
                    wp_safe_redirect($url,301);
                    exit();
                }
```

Because I luckily used different category slugs for posts and events, get_term_link() returns a WP_Error instead of a string/link, and wp_safe_redirect() triggers a fatal error.

It appears that the rules originated from a conditional section of rewrite_rules_array() with the comment: //add redirection for backwards compatability

So, can you tell me what I might have done on PROD to cause these rules to be written in the DB?  And how do I get rid of them, make sure they don't get written again?

**Comment by jonmarccurtis** [comment]
After a little more checking, I found that all I have to do to correct it, is to go to Settings -> Permalinks, and hit "Save".  It clears and rebuilds the rewrite_rules() cache.

But I'd still appreciate any hints as to how the rules got there in the first place, so I can avoid it in the future.

**Comment by hiteshmakvana** [comment]
@jonmarccurtis After installation process we are doing` flush_rewrite_rules();` I think this might be due to any other plugin or your custom code.

**Comment by jonmarccurtis** [comment]
Interesting theory, but why would any other plugin be writing rewrite rules for "em_redirect"?  A quick search through my source code doesn't find that string anywhere outside of your plugin.

**Comment by tamanna-ahuja** [comment]
@jonmarccurtis - We could not find "em_redirect" in our code, It seems to be conflicting due to any other Plugin.

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja - We could not find "em_redirect" in our code. 

It seems to be conflicting due to any other Plugin.

So here I closed the issue.
