### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#874]
Date picker not getting translated. 
Please check for- Days( Mon-Sunday)
Please check for Months
Please check

![image](https://user-images.githubusercontent.com/65893994/126969619-3cd92eec-bcd8-4be1-bfc1-b9ec3f08d96a.png)

**Comment by Priya-Goenka** [comment]
![image](https://user-images.githubusercontent.com/65893994/127625628-a57ab7e2-d94c-4780-a6c5-f13db609e4b0.png)

**Comment by christianfroehlichconsulting** [comment]
Looks like it got bugfixed ("denglish") a bit, but still there are some open.
<img width="717" alt="Bildschirmfoto 2021-08-25 um 16 02 04" src="https://user-images.githubusercontent.com/15247333/130805234-1a70e016-c281-4284-b9c3-000e3edef3d0.png">

**Comment by mistry-jignesh** [comment]
Ticket label should transalte in selected language .

![image](https://user-images.githubusercontent.com/75515088/134112582-a723c346-9a4b-4b52-bcab-eeee6eeb2af9.png)

**Comment by mistry-jignesh** [comment]
This issue are verified and this issue are present.

**Comment by mistry-jignesh** [comment]
I have translated wp event manager plugin into few language . Please verify it.

**Comment by mistry-jignesh** [comment]
I have verified issue .Now above all translation issue are fixed and working fine.

Translation is working properly,

So I closed the issue.
