### ISSUE TITLE
[ Admin ] Event listing table css 

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#875]
There is some issue with SEO and other plugin injecting the column inside event listing which causing the css issue on listing page at admin side.

**Comment by kaushikpokal** [comment]
table.wp-list-table th {
    width: 30%;
}
Add above css and issue resolved

**Comment by mistry-jignesh** [comment]
Please add below code in the css for resolved issue.

table.wp-list-table th {
width: 30%;
}

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed .

Now backend all events page is display proper.

So I closed the issue.
