### ISSUE TITLE
Using show_pagination and selected_datetime in shortcode lists previous events

### ISSUE THREAD

**Issue by stschiggerl** [wpeventmanager/wp-event-manager#876]
I am using the folloging shortcode to show the 3 next upcoming events per page:

[events show_filters="false" orderby="event_start_date" order="ASC" show_pagination="true" per_page="3" selected_datetime="today,2099-12-31"]

At the beginning all events are listed correctly. But when moving to a page >1, and then back to page 1, events before "today" are listed on page 1.

**Comment by mistry-jignesh** [comment]
Verified above shortode but this code is not working.

**Comment by tamanna-ahuja** [comment]
This is working and for load time you have generated new issue Event Listing - Filter option- Throbber is availabel more time on the screen #1001 . So request you to close this issue

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed.  

Shortcode is working properly.

So I closed the issue.
