### ISSUE TITLE
Ordering Events By Event Start Date

### ISSUE THREAD

**Issue by dschibbb** [wpeventmanager/wp-event-manager#877]
I have this in my functions.php...

 //ORDER BY DATE
function theme_name_custom_orderby( $query_args ) {
	$query_args[ 'orderby' ] = 'meta_value'; 
	$query_args[ 'order' ] = 'ASC';
	return $query_args;
}
 
add_filter( 'event_manager_get_listings_args', 'theme_name_custom_orderby', 99 );
 
function theme_name_custom_orderby_query_args( $query_args ) {
	$query_args[ 'meta_key' ] = '_event_start_date';
	return $query_args;
}
 
add_filter( 'get_event_listings_query_args', 'theme_name_custom_orderby_query_args', 99 );

and this is my shortcode:

[events show_filters="false" order="DESC" orderby="_event_start_date"]

But the events are still not sorted correctly.

Sorting is like:

21.10.2021
11.09.2021
26.08.2021
18.11.2021
10.10.2021

Any hints?

**Comment by micker** [comment]
confirm on my site any news ?
i use a widget i use this shortcode [events per_page="9" order_by="event_start_date" order="DESC" show_filters="false"]

**Comment by pooja-pragda** [comment]
correct shortcode is: 
```
01. [events show_filters="false" order="DESC" orderby="event_start_date"]
02. [events per_page="9" orderby="event_start_date" order="DESC" show_filters="false"]
```

**Comment by dschibbb** [comment]
@pooja-pragda No offence... but please read the issue properly.... both my shortcode and @micker's is correct when I compare it to what you posted... I have just updated the plugin and the bug is still there.

**Comment by mistry-jignesh** [comment]
I have verified both shortcode. Both short code is working fine.

Past event are display becuase in the backend "Event listing " tab not enable "Hide Expired Listings" option.

If enable this option then past event are not display in the list.

![image](https://user-images.githubusercontent.com/75515088/140866492-6b8b3016-3083-4986-b74a-cc419fb7eb14.png)

![image](https://user-images.githubusercontent.com/75515088/140866708-4e9188e9-2038-4b4d-9c1d-f70e70be4aba.png)
