### ISSUE TITLE
"Choose a Category" and "Choose an Event Type" not translated

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [wpeventmanager/wp-event-manager#878]
On the Event Listing Page the Dropdowns "Choose a Category" and "Choose an Event Type" are not translatable.

<img width="530" alt="Bildschirmfoto 2021-08-08 um 09 18 43" src="https://user-images.githubusercontent.com/15247333/128624238-093fa46f-634c-4be5-b602-0c201eef6549.png">

**Comment by mistry-jignesh** [comment]
Verified issue. This issue is represent.

**Comment by mistry-jignesh** [comment]
I have verified issue . Now this issue is fixed & working fine.

"Choose a Category" and "Choose an Event Type" are  translatable.

![image](https://user-images.githubusercontent.com/75515088/160993448-80d9b141-0639-44cc-b998-cda4d43db04b.png)

So now I closed the issue.
