### ISSUE TITLE
only show paid events

### ISSUE THREAD

**Issue by Merlindi** [wpeventmanager/wp-event-manager#880]
I would like to display only the paid events on one page, and only the free events on another - unfortunately the additions 

[events selected_ticket_price="paid"]
[events selected_ticket_price="free"]
[events ticket_prices="ticket_price_paid"]
[events ticket_prices="ticket_price_free"]

do not change the display!

Similarly, I would like to display on the home page only 6 events *without* show more! i ask support for help and they saw my workaround and thougt ervything is fine now! No!

**Comment by Priya-Goenka** [comment]
@Merlindi 

The Shortcodes are not working at the moemnt, we will provide an update in the next release. 
Regarding the only displaying the 6 events on home page, You need to hide the show more button with custom CSS, Or customize it with help of developer at your end.

**Comment by mistry-jignesh** [comment]
I have verified shortcode. Shortcode are not working.

Please check it.

[events selected_ticket_price="paid"]
[events selected_ticket_price="free"]
[events ticket_prices="ticket_price_paid"]
[events ticket_prices="ticket_price_free"]

**Comment by tamanna-ahuja** [comment]
You have to enable the settings  "Enable Ticket prices for listing and submission form"  in the Event Submission tab  than only shortcode filter will work

**Comment by mistry-jignesh** [comment]
I have verified issue with shortcode .

 Enable the settings "Enable Ticket prices for listing and submission form" in the Event Submission tab than only shortcode filter will work.

This issue is fixed and working . So I closed the issue.
