### ISSUE TITLE
ical - Download with 403 Error

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [wpeventmanager/wp-event-manager#881]
If i click on Download ical

<img width="266" alt="Bildschirmfoto 2021-08-25 um 16 07 10" src="https://user-images.githubusercontent.com/15247333/130805871-c27cec95-971d-4096-8ca5-0b02c2060985.png">

i get a 403 Error - on all Events.

<img width="1067" alt="Bildschirmfoto 2021-08-25 um 16 06 06" src="https://user-images.githubusercontent.com/15247333/130805927-8fc5f3ab-648d-450b-b71c-44b7be5bd0a2.png">

**Comment by christianfroehlichconsulting** [comment]
I found the reason. I needed to deactivate the Plugin "Disable Comments".

**Comment by hiteshmakvana** [comment]
iCal is just adding arguments to the URL for downloading file. Due to any other plugin which is changing the rewrite rules may effect on the site.

**Comment by mistry-jignesh** [comment]
I have verified issue. I have downloaded ical file & open it but there is no 403 error message is display.

So I have closed the issue.
