### ISSUE TITLE
Loco transalte - Organizer and Venue should be comptiable 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#889]
Loco transalte - Organizer and Venue should comptiable .

**Comment by ritakikani** [comment]
already compitible.

**Comment by mistry-jignesh** [comment]
I have verified this issue but facing an issue with the organizer & Venue.

1. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/5c68deba-0555-4b84-b9b3-f2146732361c)
---------------------------------------------------------------------------------------------------------------------------------

2. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/6a9b51db-31d1-4db8-ab34-885d58667dd2)

---------------------------------------------------------------------------------------------------------------------------------

3. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/8954f258-a455-4ab7-9fa9-ea2b70e8a05f)

---------------------------------------------------------------------------------------------------------------------------------

4.  ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/844ecf4a-21f4-4401-86e1-c28090d4d500)  

---------------------------------------------------------------------------------------------------------------------------------

5. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/837f41d1-28d2-4084-aacc-61713188adf8)  

---------------------------------------------------------------------------------------------------------------------------------

6. ![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/72fa1185-8f92-4096-bffd-7addfdc88dfb)

---------------------------------------------------------------------------------------------------------------------------------
7.![image](https://github.com/wpeventmanager/wp-event-manager/assets/75515088/60d43058-d2cd-40e3-a45d-601c87b207ae)


---------------------------------------------------------------------------------------------------------------------------------

**Comment by mistry-jignesh** [comment]
As per @ritakikani  : It is already compatible. 
So I closed the issue.
