### ISSUE TITLE
Backend - Online Event radio field not working after publishing page

### ISSUE THREAD

**Issue by monika-12** [wpeventmanager/wp-event-manager#9]
Online Event radio button field not working after publishing page on backend.
Steps:
1. Backend dashboard
2. Create New Event
3. Select any filed value yes/no on Online Event option
4. Publish page
Actual Result - Radio select filed works before publishing page but it will not show select field after publishing page.
Expected Result - It should display same before and after publishing page. 
![before-publishing-page](https://user-images.githubusercontent.com/17018981/42564888-9a091aa4-851f-11e8-9705-771ec7d9072a.png)
![after-publishing-page](https://user-images.githubusercontent.com/17018981/42564892-9ca96a66-851f-11e8-81b0-bc9576811ce9.png)

**Comment by hiteshmakvana** [comment]
As per my testing from the backend side it is working fine.
