### ISSUE TITLE
Making URL type clickable

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#900]
Add this after line 360 in \plugins\wp-event-manager\templates\content-single-event_listing.php

<?php elseif( $field['type'] == 'url' ) : ?>
                                                                                <div class="wpem-col-12 wpem-additional-info-block-textarea">
                                                                                    <div class="wpem-additional-info-block-details-content-items">
                                                                                        <p class="wpem-additional-info-block-textarea-text"><a target="_blank" href="<?php if(isset($field_value)) echo esc_url($field_value); ?>"><?php printf( __( '%s', 'wp-event-manager' ),  $field['label']); ?></a></p>
                                                                                    </div>
                                                                                </div>

**Comment by mistry-jignesh** [comment]
I have verified issue .Added code in the "content-single-event_listing.php" page.

Now this issue is fixed and working properly. 

URL type is clickabel .
