### ISSUE TITLE
Search box by date is an issue.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#903]
The event  is from 15-nov to 28-nov
But if I search events between 22-nov and 25-nov
no events appear

**Comment by mistry-jignesh** [comment]
I have verified issue . Search functionality is not working. 

Date wise filter not working .


![image](https://user-images.githubusercontent.com/75515088/140879979-34fbeea3-b2cf-4f92-a17f-4828b6505154.png)

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed.

Filter functionality is working properly.

So I closed the issue.
