### ISSUE TITLE
Responsive issue on the mobile for date range

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#904]
Responsive issue on the mobile for date range .

https://www.loom.com/share/e58e7193198a4a94938fb6dd5b70eb7f

**Comment by mistry-jignesh** [comment]
Verified issue and this issue is present.

So I closed the issue.

**Comment by tamanna-ahuja** [comment]
No need to take care as the scroll is satisfying the requirement and isn't generating any issue with entering the date. We are anyways planning to work on a responsive issue this too will be covered at that time if needed. Request you to close this issue

**Comment by mistry-jignesh** [comment]
As per above comment. We are anyways planning to work on a responsive issue this too will be covered at that time if needed. 

So I closed the issue.
