### ISSUE TITLE
Event Dashboard - Delete venue/Organizer - Message is not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#905]
Event Dashboard - Delete venue .

When delete any venue from event dashboard then delete message is not display.

https://www.awesomescreenshot.com/video/5928291?key=b475dd969c9e27893bf8669d16e765fb

 **Event Dashboard - Delete Organizer** 

When delete any organizer from event dashboard then delete message is not display.

**Comment by mistry-jignesh** [comment]
1.This issue is fixed but **Should change text in the message**.

Currently below message is display .

"Are you sure you want to delete this event?

Here instead of "Event" word should display the message - **Venue/Organizer.**

Message :  

"Are you sure you want to delete this venue?
"Are you sure you want to delete this organizer?  


2. In the organizer - When click on the delete button then below message is display.

"Are you sure you want to delete this event"?

Here two button is display.  OK and Cancel.

If I click on the "Ok /Cancel" 2 times then message box is closed.

**Comment by tamanna-ahuja** [comment]
Request you to check all related issues and close as there are few duplicates of this and try not to add task in done task , you always can check and open new task related to new issues if needed.

**Comment by mistry-jignesh** [comment]
I have verified issue . Now message is display when delete organizer/Venue. 

This issue is fixed and working properly. There is one issue found .Now this issue is related to logo image is not deleted.
 
So I closed the issue
