### ISSUE TITLE
New event listing theme - Event listing page -  Reset button should availabel for the clear the textbox

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#906]
Event listing page : 

Reset button should availabel for the clear the textbox.

Currently there is no any option .

![image](https://user-images.githubusercontent.com/75515088/140738802-79061d16-bfc6-48d0-a4cd-a92cc53dc1e0.png)

**Comment by krinaydhanani** [comment]
We are already providing this feature so I am going to close this bug.
