### ISSUE TITLE
Shortcode pagination is not working

### ISSUE THREAD

**Issue by tekkx2k13** [wpeventmanager/wp-event-manager#912]
The pagination option of the events shortcode is not working when dates are selected.
Shortcode used:
[events show_filters="false" per_page="3" selected_datetime="today,today" layout_type="list" show_pagination="true" orderby="event_start_date"] 

Problem: on page load event-list is loaded fine, if you switch to another page it doesn't use the values of "selected_datetime" instead it shows all events

Solution:
File: event-ajax-filters.min.js / event-ajax-filters.js Line 211 
var datetimes = target.data('datetimes'); --> var datetimes = JSON.stringify(target.data('datetimes'));

So the js-object gets translated into a real json string, which then can be decoded by the php file.

would be awesome if you could implement the fix

**Comment by mistry-jignesh** [comment]
Verified issue . Below shortcode is not working .

[events show_filters="false" per_page="3" selected_datetime="today,today" layout_type="list" show_pagination="true" orderby="event_start_date"]


Also event listing page when I have selecte "Today" then this option is not working.

Message is display - "There are no events matching your search."

![image](https://user-images.githubusercontent.com/75515088/159631972-ad001278-e57a-45a9-95bf-d745d5b2ee7b.png)

**Comment by mistry-jignesh** [comment]
I have verified issue . Now run below shortcode.

[events show_filters="false" per_page="3" selected_datetime="today,today" layout_type="list" show_pagination="true" orderby="event_start_date"]

Here below error messge is display on the page.

![image](https://user-images.githubusercontent.com/75515088/159893274-4cd70a16-10ec-4aed-88ce-221fa7d15124.png)


When click on the next page using pagination option then loading icon is display.

![image](https://user-images.githubusercontent.com/75515088/159893463-e51268ee-6482-49bf-9ab6-82639a51578e.png)

**Comment by mistry-jignesh** [comment]
I have verified shortcode & working fine. Today event are display on the page.

Infinite throbber time display throbber issue is fixed.

So I closed the issue.
