### ISSUE TITLE
Cannot Hide Registration Button for specific events

### ISSUE THREAD

**Issue by windycitymoon** [wpeventmanager/wp-event-manager#913]
The method for hiding the event registration button for specific events per your documentation doesn't work

https://wp-eventmanager.com/knowledge-base/hide-show-registration-button/

Can anyone update this documentation or provide a working snippet.

**Comment by Priya-Goenka** [comment]
Hi @windycitymoon 

The document has been updated, please test now, else, open a support ticket.
