### ISSUE TITLE
 event related all details not showing, use shortcut  [event id="37"] 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#914]
https://app.wp-eventmanager.com/wp-admin/edit.php?post_type=event_listing
 [event id="37"]

not displaying  registration , organizer, venue , date and time and location related information. 
![image](https://user-images.githubusercontent.com/86232676/143535470-e61349bb-1d5c-4fbf-b293-be6a3f036676.png)

also need to change the doc's video  https://wp-eventmanager.com/knowledge-base/the-single-event-listing/ for this short code.

**Comment by tamanna-ahuja** [comment]
@yukta05  Covering this in bug shortcode is incompatible with Avada builder. #988

**Comment by yukta05** [comment]
as per @tamanna-ahuja , this issue is covered in #988, so i close this issue.
