### ISSUE TITLE
 In backend/Frontnend Organizer  field not available

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#915]
Pages tab - When page is not set for organizer in the backend .

Here in the backend & front end -  organizer  field not availabel.

This field should be availabel.

**Comment by live-aamir** [comment]
@mistry-jignesh Please explain a bit more with screenshot or screencast and description.

**Comment by mistry-jignesh** [comment]
In the backend - Go to settings > Pages

![image](https://user-images.githubusercontent.com/75515088/159211624-c53e750d-5aae-42dc-aa20-9e4fa8a53f75.png)

If below 2 pages are not set then Post an Event page at backend & frontend side both field are missing .

![image](https://user-images.githubusercontent.com/75515088/159211839-26fc6777-ffd0-41cc-ac0d-eb77d191ba59.png)

So here unable to add or select organizer or venue.

This field should be availabel.

**Comment by mistry-jignesh** [comment]
Please check issue with above steps.

**Comment by tamanna-ahuja** [comment]
@mistry-jignesh As discussed with @krinaydhanani , We can by default select setting pages for users at the time of activating our plugin

**Comment by ashokdudhat** [comment]
We can by default select setting pages for users at the time of activating our plugin ... > that should not be limitiation... after ativation user can able to set page at any time same like woocommerce page settings.
