### ISSUE TITLE
Expiry date won't be set as end date automatically

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#917]
Expiry date won't be set as end date automatically.

![image](https://user-images.githubusercontent.com/75515088/144597196-c4aa39c7-4655-4014-8aa3-d6706e7f1faf.png)

**Comment by mistry-jignesh** [comment]
Verified issue and this issue is present.

**Comment by Priya-Goenka** [comment]
The issue is not present, 
When someone add a end date from frontend, after approval the end date is set to expiry date.
