### ISSUE TITLE
Feature requested by client 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#919]
Feature requested by client .

Mention feature request in image.

![image](https://user-images.githubusercontent.com/75515088/144598715-7a6ff7a9-22c8-476f-b58e-3fd326a6d014.png)

**Comment by ritakikani** [comment]
These all features we already have currently.

**Comment by mistry-jignesh** [comment]
As discussed with the team client need to follow the above instruction then it can work as per your request.
So I closed the issue.
