### ISSUE TITLE
Event is repeating on the next page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#921]
Same event is display next page.

I have created one page & use below shortcode.

Now view the page . Here 1st & 2nd page similar event is display.

**Event Name - P6 - Artificial Intelligence Startup**

[past_events per_page="5" orderby="parent"]

https://user-images.githubusercontent.com/75515088/145214458-53cba51c-e436-4c93-96ec-2971e504bd4a.mp4

**Comment by live-aamir** [comment]
https://user-images.githubusercontent.com/49248762/148223250-6a26e5dc-2afe-41d2-a7dd-24e94cffe814.mp4

Not find described issue.

**Comment by mistry-jignesh** [comment]
I have verifid issue with below branch . I have face over there.

![image](https://user-images.githubusercontent.com/75515088/148341224-4a3f034f-2c2e-4735-a107-f9f5966a4624.png)

Please check it.

**Comment by live-aamir** [comment]
Still I need to test on 3_1_23 as the issue is with duplication of post from frontend discussed with @mistry-jignesh

**Comment by live-aamir** [comment]
Again tested with the way @mistry-jignesh asked to check . I have not found the issue again below is screen cast

https://user-images.githubusercontent.com/49248762/152140679-69ce6944-299c-4fdc-a197-6f0bb221b325.MP4

**Comment by mistry-jignesh** [comment]
I have verified issue with aamir and in there enviroment this issue is working fine.

Not able to reproduced issue again .

So I closed the issue.
