### ISSUE TITLE
Event category and type base is not working. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#924]
![image](https://user-images.githubusercontent.com/65893994/145961142-520fe805-431c-4235-9e13-26d2548bcd80.png)
![image](https://user-images.githubusercontent.com/65893994/145961372-24f92e3f-4458-4e45-8fa0-c587446891a1.png)

**Comment by hiteshmakvana** [comment]
https://wp-eventmanager.com/knowledge-base/enabling-full-template-support/
This is the solution.
