### ISSUE TITLE
[frontend side] post an event page :- can not clear the form

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#934]
post an event form not clear after reload the page.
if user do not want to submit event then there should be having clear form option. 
steps :- fill-up the form
            click on preview
            now click on edit listing
           reload the page.

**Comment by live-aamir** [comment]
I have not found such issue with branch  3_1_23

https://user-images.githubusercontent.com/49248762/149148240-f324cd07-ab92-4736-9742-87f89b92e51f.mp4

**Comment by mistry-jignesh** [comment]
I have verified issue. This issue is not invalid.

When I have reload the page then data should clear from post an event form.

Here kindly check it.


https://user-images.githubusercontent.com/75515088/152730994-b56bf19b-0e06-4ac7-9546-94ff9e07d62e.mp4

**Comment by yukta05** [comment]
this issue is related to #937

**Comment by tamanna-ahuja** [comment]
Cant reproduce now

**Comment by mistry-jignesh** [comment]
This is not an issue . After the preview page & reload the page then content  is availabel with form.

So I closed the issue.
