### ISSUE TITLE
backend side:-can save the changes using any save button in form field 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#947]
https://user-images.githubusercontent.com/86232676/152290363-01069eee-8b2c-4d78-ad9c-8877c1bcf4c2.mp4

steps 
1. select multiple path option for the event form field and save the changes by using venue form field's save button.

**Comment by ritakikani** [comment]
This is not any issue, so we can close this.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - This is not an issue, 
So I close this issue.
