### ISSUE TITLE
- (dash ) required , if not any information 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#948]
![Screenshot_10](https://user-images.githubusercontent.com/86232676/152295985-a6ad875f-5945-407b-b20d-120a8a1d5ada.png)
in organizer and venue form not used any social media regarding link. here is the deash symbol required.

**Comment by mistry-jignesh** [comment]
I have verified issue .This issue is fixed.

If there is no any information then - Dash is display.

So I closed the issue.
