### ISSUE TITLE
backend side :- reset the field by default

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#949]
https://www.awesomescreenshot.com/video/7183470?key=78e955fcd06b8111f16ad29eef5a0eda

steps:- delete some field in organizer and venue form field and click on save changes button , 
change the tab and again open form field tab 
here all deleted fields are also available.

**Comment by mistry-jignesh** [comment]
I have verified issue. Organizer & Venues field reset issue is fixed.

Now delete many fields and change the tabs many times .

Again open form field tab  and try to reporudced issue but this it is working fine.

So I closed the issue.
