### ISSUE TITLE
Elementor - Event Listing Page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#95]
[Issue - 1] On preview page, events are not displaying. Events are showing only on original page after updating the page.

[Issue - 2] By default (without changing any option), Event listing page is not displaying featured events. And if I change "Show Featured" to "True", then only featured events are displaying. It should display featured and non-featured both types of events with "All Events" option.

![Event-Listing](https://user-images.githubusercontent.com/49863477/58242105-da5cd380-7d6b-11e9-8e69-86db9e2ab86e.png)

**Comment by sapnadudhat03** [comment]
[Issue - 3] If I add categories and types into boxes, then category and types fields are getting removed from filter box.

![caaaa1](https://user-images.githubusercontent.com/49863477/58242689-e301d980-7d6c-11e9-8054-d0922b094b28.png)

![caaaaaaaaa2](https://user-images.githubusercontent.com/49863477/58242706-eb5a1480-7d6c-11e9-83f6-eab5e009929c.png)

**Comment by ritakikani** [comment]
Issue 2- working properly now.

Issue 3 - When you enter specific Categories/types then Category/type filter will be override. Please read this for information : https://www.wp-eventmanager.com/documentation/the-event-listings/

**Comment by sapnadudhat03** [comment]
Hello Rita,

Issues are still there on my end.

**Comment by ritakikani** [comment]
Hi,

We face this issue because elementor free version not provide us ajax handler and for this we need to use pro version of elementor.

**Comment by mistry-jignesh** [comment]
I have verified above bug . Now these bug are working properly.

**Comment by mistry-jignesh** [comment]
This functionality is working fine. So I have closed the bug.
