### ISSUE TITLE
White screen when trying to edit event

### ISSUE THREAD

**Issue by grandeljay** [wpeventmanager/wp-event-manager#951]
I just ran the WordPress importer to import events form one site to another. After successfully importing the events I can not edit them, the page is just white. Here are the errors that are generated then.

```
PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  allowed_block_types is <strong>deprecated</strong> since version 5.8.0! Use allowed_block_types_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  block_editor_settings is <strong>deprecated</strong> since version 5.8.0! Use block_editor_settings_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
```

**Comment by tamanna-ahuja** [comment]
Hi @grandeljay ,

Could you please let me know, which PHP version and WP Event Manager plugin version you are using?

**Comment by grandeljay** [comment]
I think WP Event Manager was on Version 3.1.23 and PHP was likely 8 (not yet 8.1)

**Comment by tamanna-ahuja** [comment]
@grandeljay - Would request you to take the latest update and let us know if you still face the issue.

**Comment by mistry-jignesh** [comment]
When try to import event from one site to othersite  then after adding the XML file .

Here below error message is display.

![image](https://user-images.githubusercontent.com/75515088/159848618-89354087-8eb4-404b-9703-eebc09ae34c1.png)

**Comment by tamanna-ahuja** [comment]
This error is not of our plugin instead this is of WordPress importer plugin so we won't be taking care of this

**Comment by mistry-jignesh** [comment]
This error message is coming from WordPress importer plugin .

Reset other error message is not present.

So now I closed the issue.
