### ISSUE TITLE
Start and end date translation of datepicker 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#954]
Also Translate Select some option in organizr Field

**Comment by mistry-jignesh** [comment]
I have verified issue.

In the date picker - Week name are still display in the english.

Month name are display properly.

![image](https://user-images.githubusercontent.com/75515088/153817699-dc8025c1-85cd-4297-a9d3-a7e4942a9484.png)

**Comment by mistry-jignesh** [comment]
I hav verified issue. Now this is fixed .

Translation of datepicker issue is fixed .

So I closed the issue.
