### ISSUE TITLE
need to use coma in the message 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#955]
![Screenshot_17](https://user-images.githubusercontent.com/86232676/153209450-8a38b30c-e7e1-46f9-9b2c-d44773fa9e16.png)

**Comment by hiteshmakvana** [comment]
It's already separated by pipe sign

**Comment by yukta05** [comment]
in message box required space in between word and pipe sign

**Comment by tamanna-ahuja** [comment]
I missed a file @mistry-jignesh  , Had checked and pushed again

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed.

Added space & comma in the message.

So I closed the issue.
