### ISSUE TITLE
Elementor- Cancelled events are not showing up on listing page 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#960]
Cancelled events are not showing up on listing page .

**Comment by yukta05** [comment]
Also Featured events

**Comment by mistry-jignesh** [comment]
I have verified  both option Cancelled & Featured Events.

Here expired date are display with  Cancelled & Featured Events.

Which is wrong  .Only Live Cancelled & Featured Events should display .
