### ISSUE TITLE
Org security fixes

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager#964]

**Comment by mistry-jignesh** [comment]
1. In the backend -  Start/end & Listing expiry date text box . Date is display middle in the box.
  
![image](https://user-images.githubusercontent.com/75515088/156156087-a66faf38-af9b-4a67-9c6f-f0fc0f5cf1a8.png)

**Comment by mistry-jignesh** [comment]
2. Debug file - PHP warning error message is present.

![image](https://user-images.githubusercontent.com/75515088/156157511-70fa9a6c-7c26-41f8-a85a-0c877b72af99.png)

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/8161032/debug.log)

**Comment by mistry-jignesh** [comment]
3.  Post an event page display the code.

![image](https://user-images.githubusercontent.com/75515088/156157944-8f5dadc9-b687-4fbd-8661-7101b3a61968.png)

**Comment by mistry-jignesh** [comment]
4. After update the event from backend then below code is display on the page.

![image](https://user-images.githubusercontent.com/75515088/156158259-c9996cd7-7153-40f9-8f4f-86006dcaeef9.png)

**Comment by mistry-jignesh** [comment]
5.Backend - Setting - General setting - Google ApI key

![image](https://user-images.githubusercontent.com/75515088/156158775-eaacf035-711e-4cb5-829a-c023c8eacd76.png)

**Comment by mistry-jignesh** [comment]
6..Backend - Setting - Date & Time format - Date Format.

![image](https://user-images.githubusercontent.com/75515088/156159262-3155b75e-0955-4233-a3b5-a5bc20749d0b.png)

**Comment by mistry-jignesh** [comment]
7.Backend - Setting- Google Map general settings 

![image](https://user-images.githubusercontent.com/75515088/156159683-f839c245-c137-4694-abe3-c1fe6cbc8cd3.png)

**Comment by mistry-jignesh** [comment]
8.

**Comment by mistry-jignesh** [comment]
9.Dashboard page - Display URL 

![image](https://user-images.githubusercontent.com/75515088/156160536-a5815fba-2c7d-4c90-a881-6ffda1cb09b6.png)

**Comment by mistry-jignesh** [comment]
10. Save change in the event frontend side & click on the "Save changs" button.
11. Click on the view button. Here Parse error message is display .

![image](https://user-images.githubusercontent.com/75515088/156161287-1fe297c8-d14c-436b-9288-f72e495a7455.png)

**Comment by mistry-jignesh** [comment]
12 . Backend - Setting - Google Analytics.
      
![image](https://user-images.githubusercontent.com/75515088/156165415-d22a3ac1-e42c-41e8-870c-8d89f25f69fd.png)

![image](https://user-images.githubusercontent.com/75515088/156165626-2aee659b-6f06-405a-885c-36d30f626f2c.png)

**Comment by mistry-jignesh** [comment]
13. Dashbaord > Upgrade your database.

![image](https://user-images.githubusercontent.com/75515088/156165941-3384e235-ca8e-460d-bb9f-64be2d6c8884.png)

**Comment by mistry-jignesh** [comment]
14.  When created new event then display the parse error message on the page.

![image](https://user-images.githubusercontent.com/75515088/156167802-25950434-d1f0-4ac6-bd39-a8bbe0775a5e.png)

**Comment by mistry-jignesh** [comment]
16. Event dashboard > Click on the Event title name then Display the **parse error message** on the page.

![image](https://user-images.githubusercontent.com/75515088/156294609-f1439493-931c-4cd5-91fc-c476689423af.png)

**Comment by mistry-jignesh** [comment]
20. Debug file - PHP Deprecated error message is present.

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/8167132/debug.log)

**Comment by mistry-jignesh** [comment]
21. Event is expired at 31-03-2022 but in the backend all events are marked as expired .

![image](https://user-images.githubusercontent.com/75515088/156308402-e029e04d-3696-4bbe-986a-15942558aafc.png)

**Comment by mistry-jignesh** [comment]
22. Created event using visual composer then placeholder postion is change.

![image](https://user-images.githubusercontent.com/75515088/156310197-85c0800a-9bea-4b87-8709-f744b0cf4d4f.png)

**Comment by mistry-jignesh** [comment]
24.  Single event registration  with visual composer.

![image](https://user-images.githubusercontent.com/75515088/156314249-e562f296-fee3-4dc5-a1a6-53f73b61b535.png)

Click on the view page but page is display the blank.

![image](https://user-images.githubusercontent.com/75515088/156314403-19790467-a006-4769-9800-36dc0652c777.png)

**Comment by mistry-jignesh** [comment]
25. Single event Listing option is not working with visual composer.
![image](https://user-images.githubusercontent.com/75515088/156318830-25eeb579-fe45-4987-9ce3-53cb075f9ebb.png)

**Comment by yukta05** [comment]
28. placeholder text moves at the right side in Submit Venue Form
change field setting(remove or add some field ) of Venue form fields at backend side and save.
Now Click on Reset to default option in the field editor at the backend side of event manager.
At frontend side open  Submit Venue Form option, here in the form placeholder text moves at the right side

29. placeholder text moves at the right side in Submit Organizer Form
change field setting(remove or add some field ) of organizer form fields at backend side and save.
Now Click on Reset to default option in the field editor at the backend side of event manager.
At frontend side open  Submit organizer Form option, here in the form placeholder text moves at the right side.


https://user-images.githubusercontent.com/86232676/156335741-2b8a8f62-9df9-46e8-8b44-98828511f3ca.mp4

**Comment by mistry-jignesh** [comment]
31. Try to activated - WPML Multilingual CMS plugin but it is display fatal error message.
    Here plugin is not enable.

![image](https://user-images.githubusercontent.com/75515088/156352805-8523ad57-83dd-47fc-9570-1cd0d3497710.png)

**Comment by yukta05** [comment]
loco translator:- placeholder  sentences are not translate 
![Screenshot_46](https://user-images.githubusercontent.com/86232676/156357247-f28f5da7-116a-44cf-aa6b-2900f10d59ee.png)
![Screenshot_45](https://user-images.githubusercontent.com/86232676/156357238-1ae0c0ba-f800-4ce1-acff-82861ad11f82.png)
