### ISSUE TITLE
When categopry and type are set to term multiselect. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#966]
![image](https://user-images.githubusercontent.com/65893994/156306620-d6f0d6fd-d721-4664-b80c-558fe45c7eb3.png)
Its says select some options as common, rather than choose categories or Types.

**Comment by Priya-Goenka** [comment]
Also when categories are set to term multiselet, the default categories donot appear

**Comment by mistry-jignesh** [comment]
I have verified issue . This issue fixed.

Now text as display -  choose categories or Types.

So I closed the issue.
