### ISSUE TITLE
Elementor - Event Dashboard

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#97]
Posts per page seems not working.

![ddddddd](https://user-images.githubusercontent.com/49863477/58246428-acc85800-7d74-11e9-8249-9f45c0eb4b1b.png)

**Comment by sapnadudhat03** [comment]
Hello Rita,

I tested on my end and issue is still there. now, it is showing shortcode instead of result when i drag and drop event dashboard widget into area.

![eeeeeeeeeeee](https://user-images.githubusercontent.com/49863477/58619478-9f661d00-82e2-11e9-905f-a362324d322c.png)

**Comment by hiteshmakvana** [comment]
Hi @sapnadudhat03 
Can you pull latest version again ?

**Comment by ritakikani** [comment]
tested and working perfect now.
