### ISSUE TITLE
Event registration is display closed

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#970]
Event registration is display closed.

Event end date and Registration deadline date is selected as below.

![image](https://user-images.githubusercontent.com/75515088/156716369-a1467f79-985f-4f2e-8b6f-5cc20722f4f4.png)

![image](https://user-images.githubusercontent.com/75515088/156716264-d5ef8e6b-8166-44d9-8203-e4e4b8ff8769.png)

**Comment by tamanna-ahuja** [comment]
Pushed to #964

**Comment by mistry-jignesh** [comment]
I have verified issue . Now this issue is fixed .

Working fine & So closed the issue.
