### ISSUE TITLE
selected multiple files option at backend side, but only one logo display in the form

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#972]
selected multiple files option at backend side,
![Screenshot_51](https://user-images.githubusercontent.com/86232676/156745302-042f4399-07e0-40cc-aa8e-174bda83b7a1.png)

if you fill up organizer and venue form from the  backend side here not given any multiple file uploading option, 
and at the frontend side you can upload multiple logo but after submission only one logo display. 

https://user-images.githubusercontent.com/86232676/156745899-740fbe69-d3be-4908-b944-70e7ef26319b.mp4

**Comment by tamanna-ahuja** [comment]
Very rare cases would be there that organizers have multiple logos. Usually logo cant be multiple and as it is by default field editor option for selecting multiple files thats why it is not restricted to select multiple .  As discussed , This cant be counted as bug or needed to be improved.

**Comment by yukta05** [comment]
If logo can not be multiple, then i think we have to remove that option from the back end.

**Comment by ritakikani** [comment]
we can't remove this "multiple files" for particualr organizer form because this is common for all fields.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - We can't remove this "multiple files" for a particular organizer form because this is common for all fields.
So I closed the issue.
