### ISSUE TITLE
Update needed for Multisite

### ISSUE THREAD

**Issue by ashokdudhat** [wpeventmanager/wp-event-manager#976]
Please check this

https://wordpress.org/support/topic/update-needed-for-multisite/

**Comment by mistry-jignesh** [comment]
I have verified issue . After update start & date date .

Here in the text box date with time also display.

![image](https://user-images.githubusercontent.com/75515088/159893858-fd1be2d7-68a7-4a39-8d30-fca6ce8db321.png)

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed & working fine.

Now date & time save correctly.

So I closed the issue.
