### ISSUE TITLE
The event category permalink is not updating in URL

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#978]
![image](https://user-images.githubusercontent.com/65893994/157630680-c6aaf483-3f0b-401a-92f4-329b28e2acff.png)
![image](https://user-images.githubusercontent.com/65893994/157630801-12b0f9fa-96a1-4090-9425-5d980e71e8c0.png)

**Comment by tamanna-ahuja** [comment]
We have to add below code to get this work.

add_theme_support('event-manager-templates');

**Comment by Priya-Goenka** [comment]
Verified.
