### ISSUE TITLE
Elementor -  Upcoming event listing - Today event is  display in the list

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#981]
In the upcoming event listing - Today event is  display in the list.

![image](https://user-images.githubusercontent.com/75515088/158117235-b2816211-2664-48d2-8f03-52e7bd136ec9.png)

**Comment by tamanna-ahuja** [comment]
As the event has an ending date of 31st March, it will show it in upcoming events. because of a continuing event.

**Comment by mistry-jignesh** [comment]
As per @tamanna-ahuja -  Event has an ending date of 31st March, It will show it in upcoming events because of a continuing events.

So I closed the issue.
