### ISSUE TITLE
Taxonomy change not applied randomly

### ISSUE THREAD

**Issue by ajussak** [wpeventmanager/wp-event-manager#986]
When i change category or type in an event, the changes are randomly not saved after click on Update button

And i noticed another issue with "Most used" tab :+1: 
![Capture d’écran de 2022-03-15 18-44-46](https://user-images.githubusercontent.com/12643734/158439651-32852cf4-ae6b-4eb0-815c-b27116310454.png)

**Comment by mistry-jignesh** [comment]
I have verified issue. 

In the Event categories - Most Used tab - Selecting mutiple option.

![image](https://user-images.githubusercontent.com/75515088/159627950-b8c71387-d8bb-487f-9039-6d9d5e1aab32.png)

Please check Screenshot.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed & working properly.

Taxonomy save properly. So I closed the issue.
