### ISSUE TITLE
option for organizers to make events private or public.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#989]
option for organizers to make events private or public.

**Comment by Priya-Goenka** [comment]
There is a request that Organizers want to keep their events as drafts as well, so is that possible to incorporate

**Comment by ritakikani** [comment]
We already given fieldeditor, so user can add new field for event private or public with checkbox type, then he has to use filter to check if the field value is true then hide else show vice-verse.

**Comment by mistry-jignesh** [comment]
As discussed with the team client need to follow the above instruction then it can work as per your request.
So I closed the issue.
