### ISSUE TITLE
Elementor - Featured event widget

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#99]
Issue with Elementor - Getting notice messages with the featured event widget.

![ffffffffffff](https://user-images.githubusercontent.com/49863477/58249461-97572c00-7d7c-11e9-8118-3c5212123e2d.png)

**Comment by sapnadudhat03** [comment]
With the upcoming events widget also having the same issue.

![uuuuuu](https://user-images.githubusercontent.com/49863477/58249548-cff70580-7d7c-11e9-80df-1c1a1933470b.png)

**Comment by ritakikani** [comment]
working with without issue now.
