### ISSUE TITLE
when i click  on the clear button , box should be open.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#990]
https://user-images.githubusercontent.com/86232676/159215668-4631e72c-17ae-494c-8ce5-32b2c9bf1784.mp4

**Comment by mistry-jignesh** [comment]
I have verified issue. When click on the clear button,Right now box is closed.

So this issue is face. Please check it.

**Comment by tamanna-ahuja** [comment]
Somehow file got replaced pushing again

**Comment by mistry-jignesh** [comment]
I have verified issue. When click on the clear button , Right now box is open.

This issue is fixed & working fine.

So I closed the issue.
