### ISSUE TITLE
Backend - New delete fields are availabel 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#993]
First add few new fields in the Event form field .

Now click on the save changes buttton.

New added fields are save .

Delete all new added fields & Click on the save changs button.

Observed that deleted field are agian availabel in the field editor.

Second times delete all new field & click on the save changes button.

Here delete fields are remove from the list.

So field here remove second times I have deleted.

**Same issue is present Venue/Organizer**

https://user-images.githubusercontent.com/75515088/159673141-3a44afad-089b-44f6-b688-661b8b1db3f4.mp4

**Comment by ritakikani** [comment]
This issue is resolved in https://github.com/wpeventmanager/wp-event-manager/issues/1427.

**Comment by mistry-jignesh** [comment]
This issue is fixed in #1427.
I have verified this issue. It is working fine.
So I closed the issue.
