### ISSUE TITLE
Event status is display "Active"

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#994]
**Front End :**

I have manually updated event start /end date with past date.

Like Start date as select "15-03-2022"

End date as select as  "20-03-2022" 

Registration Deadline -"20-03-2022" 

Expiry date -"20-03-2022" 

Save the event. After that event status is display Active.

Event should be display expired.

**Comment by tamanna-ahuja** [comment]
@mistry-jignesh  - Until it is not approved it will display as active

**Comment by mistry-jignesh** [comment]
@tamanna-ahuja  - At backend - Need to update the event then it will show expired event.

I have verified this follow & event is display expired.

So I closed the issue.
