### ISSUE TITLE
Event should be sorting time wise also

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#999]
When I have use below short code then events are display with start date .

 Events should be order like start date & time.

[events per_page="10" orderby="event_start_date"]

Like today there are 3 events.

Event A - start time - 10:00 AM [25-03-2022]
Event B - start time - 12:00 PM  [25-03-2022]
Event C  -Start time - 2:00 PM  [25-03-2022]

Right now events are not showing time wise also.

Event A - start time - 10:00 AM [25-03-2022]
Event C  -Start time - 2:00 PM  [25-03-2022]
Event B - start time - 12:00 PM  [25-03-2022]

**Comment by ritakikani** [comment]
we add new value for orderby attribute "event_start_date_time" for event listing sorting as per date and time both.
`
[events orderby="event_start_date_time" per_page="25" order="ASC"]`

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is working fine and time wise sorting working fine.
So I closed the issue.
